### ISSUE TITLE
Items with invalid graduation_year fields causing facet to break.

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1014]
Commencement Year facet breaks due to invalid values for graduation_year, these need to be fixed as well as validation on `graduation_year` to be allow for 4 digit year values only.

- [x] fix bad values 
```
        "has_model_ssim":["GraduateThesisOrDissertation"],
        "id":"vh53x113r",
        "graduation_year_tesim":["2005. For master (tiff) digital images of maps contained in this document contact scholarsarchive@library.oregonstate.edu. TIFF files stored on permanent server in Hennessey, Jennifer T. 2005 Folder."]},
      {
        "has_model_ssim":["GraduateThesisOrDissertation"],
        "id":"08612t602",
        "graduation_year_tesim":["June 17, 2017"]},
      {
        "has_model_ssim":["GraduateThesisOrDissertation"],
        "id":"bv73c506s",
        "graduation_year_tesim":["June 12, 2017"]},
      {
        "has_model_ssim":["GraduateThesisOrDissertation"],
        "id":"6m311t974",
        "graduation_year_tesim":["June 2018"]},
      {
        "has_model_ssim":["GraduateThesisOrDissertation"],
        "id":"vq27zt36n",
        "graduation_year_tesim":["June 2018"]},
      {
        "has_model_ssim":["GraduateThesisOrDissertation"],
        "id":"dr26z308m",
        "graduation_year_tesim":["September 18, 2017"]},
      {
        "has_model_ssim":["GraduateThesisOrDissertation"],
        "id":"b5644x161",
        "graduation_year_tesim":["0904"]}]
```

- [ ] model validation for `graduation_year` to allow only 4 digit values

**Comment by straleyb** [comment]
What should these digit values reflect? We can check the "type" of the information and verify that it is of length 4. I'll pull this ticket off, but id like to know a little bit more context behind the whole 4 digit number limitation.

**Comment by vantuyls** [comment]
graduation year is meant to be a year value. that said, DSpace didn't restrict the type of data that could be entered in that field, so we see people putting all kinds of junk (though related junk) in this field. 

The only real exception to this is the final entry in the above example with a graduation year that is clearly (?) a typo - 0908. I bet if we opened that doc we'd find that it was published in 1908.

**Comment by straleyb** [comment]
Sounds good. Thanks for the info. I'll be working on this ticket now and probably a bit in the morning. But I understand what im looking for now. 👍

**Comment by wickr** [comment]
@simholt and @vantuyls In addition to checking for 4 digits for the year, does it make sense to do additional validation, such as not allow anything more than 5 (or whatever) years in the future? And/or not allow anything too far in the past (last 5 years, or not before the university existed)

**Comment by wickr** [comment]
Talked with Steve and Sarah, won't worry about checking graduation date for typos for dates too far in the past or future.

**Comment by straleyb** [comment]
1862 and current + 5

**Comment by straleyb** [comment]
name changes
