### ISSUE TITLE
Update all purchased e-resources to set visibility to match visibility from DSpace

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1026]
some purchased e-resources (all of them?) should only be avilable to OSU Community, but are listed in SA@OSU as Public. These need to be reverted to OSU Community visibility.

**Comment by luisgreg99** [comment]
We created a script and a rake task to fix the visibility of these works (changed the visibility from `open` to `authenticated`). We have a log below as a reference to the list of works that have been updated:
```
log/fix-visibility-11-18-2017-16-45-PM.log-20171120
```
The script updated a total of 978 items (including child members or filesets attached)

**Comment by zhang4952** [comment]
Done
