### ISSUE TITLE
Remove Keyword from all metadata forms

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1033]
We have all users adding Subject at this point. Having Subject and Keyword metadata elements on the form is confusing to users and clutters the form.

**Comment by vantuyls** [comment]
@luisgreg99 do we have content in keyword right now?

**Comment by luisgreg99** [comment]
@vantuyls I did the following search in solr and found a total of `28810` works with content in `keyword`. Should we consolidate these existing values in `keyword` and move them to `subject` as part of metadata cleanup? We could create a task to re-assign or merge these existing values with `subject`.
```
"responseHeader":{
    "status":0,
    "QTime":149,
    "params":{
      "q":"keyword_tesim:[* TO *]",
      "indent":"on",
      "fl":"id,keyword_tesim,subject_tesim,has_model_ssim",
      "rows":"1",
      "wt":"json"}},
  "response":{"numFound":28810,"start":0,"docs":[
      {
        "has_model_ssim":["GraduateThesisOrDissertation"],
        "id":"9g54xn971",
        "keyword_tesim":["Ascites syndrome",
          "Chicken antioxidant status",
          "Eicosanoid",
          "Egg quality",
          "n-3 fatty acid"],
        "subject_tesim":["Broilers (Poultry) -- Metabolism",
          "Omega-3 fatty acids",
          "Broilers (Poultry) -- Feeding and feeds",
          "Oils and fats in animal nutrition"]}]
```
