### ISSUE TITLE
Update visibilty_during_embargo to authenticated

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#1037]
Some embargo items ingested into SA are set to 'restricted' for visibility_during_embargo, correct them to 'authenticated' that means having ONID.

**Comment by luisgreg99** [comment]
We created a script and a rake task to fix the visibility of these works. We have the logs below as a reference to the list of works that have been updated:
```
log/fix-embargo-11-17-2017-12-28-PM.log-20171119  
log/fix-embargo-11-20-2017-16-28-PM.log
```
The script updated a total of 228 works including the filesets attached.
