### ISSUE TITLE
Degree grantor on ingest form is showing as a URI not a label

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1040]
<img width="426" alt="screen shot 2017-11-20 at 4 52 15 pm" src="https://user-images.githubusercontent.com/9534576/33049085-3fe6c51c-ce13-11e7-8d79-f35f1e3dde80.png">

**Comment by luisgreg99** [comment]
@vantuyls can we make the `degree_grantors` field a select dropdown in the form (local based authority) so that we can display the label and also allow the user to select "Other" in the list?

**Comment by vantuyls** [comment]
we don't, at this point, have enough information about what other degree grantors should be in that list. maybe we can see what is in that field now and start there?

**Comment by vantuyls** [comment]
BUT that would be a separate issue to submit...
