### ISSUE TITLE
migrated works with FileSet attached but downloading the file fails

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1047]
Need to identify all of the works that failed during ingestion and reattach files.

Example: https://ir.library.oregonstate.edu/concern/parent/cr56n576w/file_sets/3t945w616

Fedora is missing actual hasFile metadata, ingestion job seems to have failed.

**Comment by simholt** [comment]
PDF doesn't exist:

http://ir.library.oregonstate.edu/concern/graduate_projects/0z7092093

**Comment by simholt** [comment]
http://ir.library.oregonstate.edu/concern/graduate_projects/gh93h4211

**Comment by simholt** [comment]
http://ir.library.oregonstate.edu/concern/graduate_projects/6969z526p

**Comment by simholt** [comment]
http://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/41687p08g

**Comment by revgum** [comment]
migration data fixes covered these
