### ISSUE TITLE
Moving over DSpace collection & community metadata - input?

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1050]
Regarding metadata associated with many collections and communities in DSpace:

The contextual information and links that appeared on collection and community landing pages -- I assume we will be able to transfer that information from DSpace and enable landing pages? If so, when? Is this some of the work that is happening in the wider community over the next couple months?

- From Mike Boock

**Comment by vantuyls** [comment]
landing pages will be enabled with Collection Extensions - due to release and update on SA@OSU by mid-April.
