### ISSUE TITLE
Fix redirects for collection & community pages

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1052]
Collection and community redirects--when will this be working? Need to account for xmlui and jspui directories: e.g. https://ir.library.oregonstate.edu/xmlui/handle/1957/89 and https://ir.library.oregonstate.edu/jspui/handle/1957/89

- From Mike Boock

**Comment by zhang4952** [comment]
There is no JSPUI for dspace-ir, only XMLUI. A little background: XML and JSP are two kinds of UI DSpace offered and OSU picks XMLUI, so all the URIs to dspace-ir will be xmlui/.... And the collection and community redirect has been deployed to production, like: https://ir.library.oregonstate.edu/xmlui/handle/1957/89.
