### ISSUE TITLE
RSS feed for new SA?

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1053]
Is there an RSS feed for the new IR? Can it be set up for different collections or presence of metadata?

- from Mike Boock

**Comment by wickr** [comment]
There is for search results.

RSS: https://ir.library.oregonstate.edu/catalog.rss?locale=en&q=&search_field=all_fields&utf8=%E2%9C%93
Atom: https://ir.library.oregonstate.edu/catalog.atom?locale=en&q=&search_field=all_fields&utf8=%E2%9C%93

Atom Feed for 'Master's Thesis' Resource Type: https://ir.library.oregonstate.edu/catalog.atom?f%5Bresource_type_sim%5D%5B%5D=Masters+Thesis&locale=en&q=&search_field=all_fields

RSS doesn't look very useful as it is right now. The Atom feed has more metadata and updated dates.

To get a different specific results feed, on a Results page, right click, select 'View page source' or equivalent, then search/look for RSS or Atom to get the exact feed URL.

**Comment by vantuyls** [comment]
@simholt did someone ask for a feed or was this just curiosity?

**Comment by simholt** [comment]
@vantuyls 

This was from Mike Boock notes -- all I have is what's already on the ticket.

**Comment by boockm** [comment]
I think this can be closed. There are at least a couple communities that auto-populate web pages with SA content/results. Here's an example of one that uses an old feed URL: http://www.forestry.oregonstate.edu/now-scholarsarchive

I'll look for others and let them all know that they need to change their URLs.

**Comment by simholt** [comment]
Closing as per above comment.
