### ISSUE TITLE
Add conference field metadata

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1055]
- From Mike Boock

Need to retrospectively add conference field metadata for all conference proceedings added to SA prior to migration including: conference name, conference location. Is there a way to batch edit metadata yet? If so, can I do that work until we have a metadata librarian?

**Comment by wickr** [comment]
Related to https://github.com/osulp/sa-content/issues/51

**Comment by vantuyls** [comment]
@simholt this might be something to revisit wiht your new superpowers.

**Comment by simholt** [comment]
@vantuyls 

It's on my list.

**Comment by simholt** [comment]
Closing -- is on list of batch edits.
