### ISSUE TITLE
Redirect DSpace JSPUI 

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#1057]
It sounds like someone may bookmark DSpace jspui in the past, we can redirect 

- [ ] jspui/handle to xmlui/handle

- [ ] index.jsp to SA homepage

**Comment by revgum** [comment]
for `jspui/....` we should add the route update to the handles controller like here: https://github.com/osulp/Scholars-Archive/blob/master/config/routes.rb#L38-L41

**Comment by revgum** [comment]
Traffic examples that we need routing fixed for:
```
/jspui/handle/1957/7951
/dspace/bitstream/1957/259/2/ACRLhandout.pub (the /2/ is likely the sequence_id which we don't care about anymore)
/xmlui/handle/1957/9318/stats
/xmlui/handle/1957/14728/browse
/xmlui/handle/1957/955/discover
```
