### ISSUE TITLE
[FIXED IN HYRAX] HTML code for 'Select type of work' modal appears in all pages when logged in

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1081]
When logged in, the HTML code that powers the 'Share your work' modal popup appears to be inserted into every page's code. Saw it on an item page, item stats page, and an admin page.

It's hidden, so it's not directly affecting anything, but it's 200 lines of code that's not needed. Unless we want to add a 'Share your work' to the navbar or some other place on every page.

Possible this is coming from Hyrax and should be fixed there, but with our tweaks to this modal I wasn't sure.

view-source:https://ir.library.oregonstate.edu/concern/technical_reports/br86b491h?locale=en
```
  <body>
    <a href="#skip_to_content" class="sr-only">Skip to Content</a>
    <div class="modal worktypes fade" id="worktypes-to-create" tabindex="-1" role="dialog" aria-labelledby="select-worktype-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title" id="select-worktype-label">Select type of work</h2>
      </div>
      <form class="new-work-select">
        <div class="modal-body">
          <div class="row match-my-cols">
            <div class="col-md-12">
                  <div class="row">
                    <div class="col-md-6 select-worktype">
                      <label>
                        <input type="radio" name="payload_concern" value="Article"
                               data-single="/concern/articles/new?locale=en"
                               data-batch="/batch_uploads/new?locale=en&amp;payload_concern=Article">
                        <div class="select-work-icon">
                          <span class="fa fa-file-text-o"></span>
                        </div>
                        <div class="select-work-description">
                          <h3 class="work-type-title">Article</h3>
                          <p>Scholarly research articles</p>
                        </div>
                      </label>
                    </div>
```

**Comment by vantuyls** [comment]
@wickr @luisgreg99 can you see if this is coming from Hyrax and if so open an issue there?

**Comment by luisgreg99** [comment]
@wickr @vantuyls This was fixed in hyrax master a few weeks ago with this PR https://github.com/samvera/hyrax/issues/2238 However, it looks like the update hasn't been released yet. Once it gets released, we would just need to update our hyrax gem and remove this line in our views: https://github.com/osulp/Scholars-Archive/blob/master/app/views/_masthead.html.erb#L1

**Comment by vantuyls** [comment]
looks like we'll see this in hyrax 2.1

**Comment by wickr** [comment]
Confirmed the extra code for the Share Your Work modal is not showing on all pages, just the homepage, due to integrating past Hyrax updates.
