### ISSUE TITLE
Rich (?) text in Review and Approval area

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1091]
the Review and Approval window allows for text to be added that can be used to communicate along a workflow. Currently, however, the field the text is entered in does not allow for any kind of formatting, line breaks, paragraphs, etc., making long comments and review notes difficult to use. 

Could there be a better text editor here?

**Comment by straleyb** [comment]
we might be able to swap it for tinyMCE but that may need extra config depending on how that data is stored.

**Comment by simholt** [comment]
If this isn't reflected in the corressponding email that's sent to depositors, I don't know how useful it is.

**Comment by vantuyls** [comment]
rich text works in workflow actions comment box. qa complete.
