### ISSUE TITLE
Strange metadata in GTD

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1095]
https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/0v838474z

Commencement year - 2011
Copyright year - 1977
doesn't have a Replace field

@zhang4952 any idea what's going on here?

**Comment by zhang4952** [comment]
It is strange indeed, here is the DSpace record: http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/16149?show=full. 
I need to search the ingestion logs to check what happened. Solve it in SA is simple though. @vantuyls

**Comment by vantuyls** [comment]
@simholt probably a quick (?) fix

**Comment by simholt** [comment]
That first link goes to an error page.

I looked at the SA record of the one Hui linked:
https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/9019s695d

... and it was fine (I tweaked a few things). Maybe it was fixed before? I'm closing this.
