### ISSUE TITLE
Change 'Thesis' Resource Type to valid one (undergrad, master's, honors) 

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1097]
wickr commented 21 days ago

There are about 2500 works with 'Thesis' as a Resource Type, but it's not on the authority list. You can't make any other edits or updates to these works until that is resolved (Save button is disabled).

Will likely need to check Degree Level, Degree Name, or some other fields to figure out what best determines what to change a given Resource Type to.
@wickr wickr added Post-Migration Work bug labels 21 days ago
@vantuyls
Member
vantuyls commented 18 days ago

@zhang4952 can you extract degree level, degree name, and degree field, and ID for these items and place them in a spreadsheet?

**Comment by zhang4952** [comment]
Correct 1,076 items according to the spreadsheet.

**Comment by simholt** [comment]
We got as many as we could; I'll pick up the rest.
