### ISSUE TITLE
 Evaluate Collection Extensions

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1098]
Evaluate collection extensions for functionality we want to take advantage of in SA@OSU including:

    - [ ] what types of collections will we want?
    - [ ] what content will be in those collections and how will we get it there?

**Comment by boockm** [comment]
Use case: "Pacific Northwest Insect Management Conference" proceedings. Stakeholders would like a launch page to browse and search for all of their proceedings from 1963-present. The conference name has changed at least a few times over this time period. "Collection/landing page" should include proceedings from all the conference names and ability to easily browse by conference year.

**Comment by vantuyls** [comment]
closing. duplicate of #966
