### ISSUE TITLE
Build ONS updating system for fields that allow "other" 

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1099]
metadata fields with controlled vocabularies in opaquenamespace need to have a system in place for updating the controlled vocab when "Other" is selected, followed by the user entering a string.

**Comment by vantuyls** [comment]
so, currently an email notification goes out to scholarsarchive@oregonstate dot edu - a human then has to check the information in the Other field and update ONS required. do we feel like this is sufficient, or is there more work to be done on this at a future date? @zhang4952 @revgum @wickr @luisgreg99

**Comment by shieldsb** [comment]
Current functionality is acceptable.
