### ISSUE TITLE
[Notification] When an item is completely uploaded and characterized and "The Job" is finished the uploader (depositor) should receive an email.

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#110]
User should get email notification when their item is live (after it has gone through whatever mediation process is relevant for that item type)

**Comment by revgum** [comment]
"Depositor" needs to know when the file was successfully uploaded and submitted. "Author" needs to know when the file was submitted (and eventually once it was approved through mediation)

Requires the ability to get the authors email during deposit (if the author isn't also the current depositor)

**Comment by revgum** [comment]
Closed upon review of issues
