### ISSUE TITLE
Clean up isPartOf content

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1100]
Member
vantuyls commented on May 22

Some content that moved from DSpace to Hydra used the mythical predicate isPartOfSeries and was, largely, a combination of Journal Title, Volume, and Number. We forewent cleaning this up pre-migration (because there wasn't a place to put the Volume and Number values in DSpace) in favor of cleaning these up post-migration.

SO: in the spreadsheet linked below, please clean up the metadata by separating Journal Title, Volume, Number and any additional information into appropriate form fields.
@vantuyls vantuyls added the Post-Migration Work label on May 22
@vantuyls vantuyls referenced this issue on May 22
Closed
Create spreadsheet of dspace items wiht ispartofseries #37
0 of 2 tasks complete
@mlv611
mlv611 commented on May 22

@vantuyls Where is the spreadsheet?
@vantuyls
Member
vantuyls commented on May 23

it hasn't been created yet. @zhang4952 is going to generate it soon.
@zhang4952
Member
zhang4952 commented on May 25 •

The spreadsheet is in the Google drive: https://docs.google.com/spreadsheets/d/10KnwYNVvJmHohJNFDv1mh_h6wAJ6fj2Cfgl3C1jm2Go/edit?usp=sharing, there are ~21,000 items with legitimate values. It will take 'significant' effort to clean it because they are in wide spreading formats.
@vantuyls @mlv611

**Comment by vantuyls** [comment]
@simholt project!

**Comment by simholt** [comment]
Sarah continues to work on this.

**Comment by simholt** [comment]
UPDATE:
This is the large in_series spreadsheet I've worked at off and on. The majority is resolved; I will run one more Solr search on this field to wrap up any remainders.
