### ISSUE TITLE
create readme and FAQ for Rights and License

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1101]
vantuyls commented on Apr 20

A basic FAQ that helps users understand what rightstatements and licenses mean.
@vantuyls vantuyls added the SA Migration label on Apr 20
@vantuyls vantuyls assigned mwillihooper on Apr 20
@mwillihooper
mwillihooper commented on May 8

Started here: https://docs.google.com/a/oregonstate.edu/document/d/15u9v-NcK2dDMiriTDon-MfVk3b_PuLbGneJiPsi9SVo/edit?usp=sharing

What else do we need? Are we going to have a separate module for copyright for authors/depositors?

**Comment by vantuyls** [comment]
- [ ] need to link to the copyright libguide
- [ ] part of #529

**Comment by vantuyls** [comment]
@simholt project?!

**Comment by simholt** [comment]
@vantuyls  

Er, there's this right now:

https://guides.library.oregonstate.edu/Scholars-Archive/Copyright

**Comment by simholt** [comment]
Links to Rights & License FAQs added.
