### ISSUE TITLE
Nursery Research Collection Ingest

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1103]
Hi Steve – I forgot to mention that we do have a developer, and I can get the  info to you in whatever way is easiest to be imported. (a feed, ???) No pressing timeline, though, the summer is fine. Thanks, Erin 

From: "Van Tuyl, Steven" Steve.VanTuyl@oregonstate.edu 
Date: Thursday, March 23, 2017 at 2:43 PM 
To: "Martin, Erin" Erin.Martin@oregonstate.edu 
Subject: Re: Nursery research deposited into SA 

Hi Erin, This is definitely a project we could take on. That said, we are  currently down quite a few staff and don’t have much bandwidth for large  projects of this sort. That said, we are in the process of hiring and I  hope that by Summer we would be ready to take this on. What is your  timeline? Also – over the summer, we will be cutting over to our new system,  which might make upload of this content easier, allowing you (if you  care to) to load these files. Thoughts on whether that is something you  would be able to take on? Either way is fine from my perspective, I just  know that some of our stakeholders prefer a little more independence  with respect to the upload process. Thanks. steve 

<><><><><><><><><><><><><><><><><><><><><><> 
Steve Van Tuyl 
Digital Repository Librarian 
Oregon State University Libraries & Press 
web \| http://osulibrary.oregonstate.edu/staff/vantuyls 
orcid \| http://orcid.org/0000-0002-8752-272X 
email \| steve.vantuyl@oregonstate.edu 
phone \| 541.737.3492 

From: "Martin, Erin" Erin.Martin@oregonstate.edu 
Date: Monday, March 20, 2017 at 2:09 PM 
To: Steve Van Tuyl steve.vantuyl@oregonstate.edu 
Subject: Nursery research deposited into SA 

Hi Steve – I’m looking to make a large deposit of research material into Scholar’s  Archive. It’s nursery plant research materials from about 1960 to 2010.  At this point it’s about 545 research reports and articles. You can see the pdfs listed at the bottom of this page: http://horticulture.oregonstate.edu/content/nursery-and-greenhouse-resources-oregon-state-university. It goes on for something like 30-odd pages. We are migrating this site from Drupal 6 to 7 and the new nursery  extension specialist wants to move the site in a different direction.  I’d like to have this research material entered into SA before that – I  believe most (if not all of it) is not in SA. What would you need from me to start this process? Thank you so much! Erin Erin Martin Web Content Strategist College of Agricultural Sciences 200 Strand Agriculture Hall 541-737-9134 Erin.Martin@oregonstate.edu
--

**Comment by vantuyls** [comment]
@simholt project!

**Comment by simholt** [comment]
Emailed Erin to see if still interested in this project.

**Comment by simholt** [comment]
I have not heard back from the dept so I am closing this issue.
