### ISSUE TITLE
change workflow for Conference Proceedings etc.

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1105]
this should be the one step workflow - stakeholder

**Comment by luisgreg99** [comment]
@vantuyls it looks like we can change the workflow in the admin set settings, but that will affect only items ingested in the future after setting the new workflow. 

Works already ingested would still be linked to the previous workflow: `No Review Workflow (self deposit)`. 

Do we want to reset all of the works already deposited to be linked to the new workflow as well? We can setup a script to reset the workflows on the existing items (deposited).

**Comment by vantuyls** [comment]
changed in the admin dashboard
