### ISSUE TITLE
some migrated content is missing Abstract

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1110]
example: http://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/3f462b468

the item has an abstract in DSpace but not in Hyrax.

**Comment by zhang4952** [comment]
I will run a query looking for GTD works that do not have abstract.

**Comment by vantuyls** [comment]
@zhang4952 can you give an update on this?

**Comment by zhang4952** [comment]
SA has been updated for all affected items, the full list and code are in the PR#https://github.com/osulp/Scholars-Archive/pull/1216.
