### ISSUE TITLE
Non-Academic Affiliation "Other" entry notification

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1124]
FYI:

santilis has entered one or more Non-Academic Affiliation 'Other' entries: OSU Superfund Research Program. These entries should be reviewed and added to the controlled vocabulary or rejected/corrected. Work: Identification, Quantification, and Risk Assessment of Polycyclic Aromatic Hydrocarbons and their Derivatives in Soil after Steam Enhanced Extraction (vm40xx46c)

https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/vm40xx46c

**Comment by luisgreg99** [comment]
@wickr is there an existing URI for `OSU Superfund Research Program`? If there is one, I can add it here https://github.com/osulp/Scholars-Archive/blob/master/config/authorities/other_affiliation.yml for this ticket. Or should we create a new term in opaquenamespace? I noticed that most of the terms in this local authority `other_affiliation` (URI based field) belong to the `subject` vocabulary: http://opaquenamespace.org/ns/subject

**Comment by wickr** [comment]
@luisgreg99 No, I found a wikidata/wikipedia entry for the larger Superfund Research Program, but that was it.

I created a new term for the OSU program, and Sarah reviewed it so it's ready: http://opaquenamespace.org/ns/subject/OregonStateUniversitySuperfundResearchProgram
