### ISSUE TITLE
using Back button on browser causes duplication/stacking of page elements

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1136]
when looking at an item, then using the Back button to get back to the review submissions page, the drop down and search boxes duplicate and stack on the page (see image)

To replicate:
1) go to review submissions page
2) select a work
3) look, the work showpage is there!
4) use the browser Back button
5) see more drop downs and search boxes

![screen shot 2017-12-20 at 1 49 10 pm](https://user-images.githubusercontent.com/9534576/34230336-98fee75c-e58c-11e7-9348-eac00d1cc715.png)

**Comment by straleyb** [comment]
Being caused by jquery datetimepicker
