### ISSUE TITLE
Change DOIs so they do not search internally when clicked

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1152]
DOI links should be external, not internal - ie submitting a search query, which is not helpful.

**Comment by simholt** [comment]
If you put a complete address (such as https://doi.org/10.1186/s12864-018-4519-y) in the field and click the external link button, it resolves to the site. But clicking on the address itself does an internal search.

Example:
https://ir.library.oregonstate.edu/concern/articles/vh53x1868

**Comment by simholt** [comment]
FYI: All of the DOIs now have the https prefix and external link pop-out buttons.

**Comment by straleyb** [comment]
https://github.com/osulp/Scholars-Archive/pull/1959

**Comment by simholt** [comment]
QA passed: 
![Article___Krakatoa___ID__cr56n115b___ScholarsArchive_OSU](https://user-images.githubusercontent.com/33705514/68798063-95bf4000-060a-11ea-8540-33a0b02c36b4.png)
