### ISSUE TITLE
Improve SA sorting by facet --> more

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1153]
SA sorting by Facet-->More is A-Z or Numerical. That’s fine but having only the "Previous/Next" buttons is sooo slow, defeats purpose of sorting unless have few results.

Need other options: End, list page numbers, skip between pages, etc. 

![screen shot 2018-01-04 at 12 59 53 pm](https://user-images.githubusercontent.com/33705514/34584108-45553894-f14f-11e7-845c-8f785e5060c3.png)

**Comment by straleyb** [comment]
We were talking about this issue yesterday. This is going to be a difficult problem to solve. The issue is that its finding a whole bunch of works but not displaying them because of visibility issues. So "There are works you just cant see them"

**Comment by straleyb** [comment]
@simholt Im going to close this ticket and make a new one describing this bug.

**Comment by revgum** [comment]
see #1349

**Comment by vantuyls** [comment]
qa complete. pagination works.

**Comment by straleyb** [comment]
qa done and deployed to production
