### ISSUE TITLE
Active Handles mismatch between DSpace and Hyrax

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1167]
Checked export of active Handles from DSpace vs. active Handles in Hyrax, as of December 29th, 2017.

Items may be migrated but missing Handles.

### Handles not redirecting/matching

- [x] 1639 - Instruments for rapidly measuring slope of grain in lumber [U.S. Forest Service Research Legacy]
1957/1639 and 1957/1640 point to the same item: https://ir.library.oregonstate.edu/concern/defaults/8c97kv14c
- [x] 1873 - Bark-peeling machines and methods [U.S. Forest Service Research Legacy]
1957/1873 and 1874 point to the same item: https://ir.library.oregonstate.edu/concern/defaults/cv43p1512
- [x] 1961 - Effect of piling methods on air circulation in a lumber dry kiln [U.S. Forest Service Research Legacy]
1957/1961 and 1962 points to the same item: https://ir.library.oregonstate.edu/concern/defaults/ft848v49g
- [x] 1966 - Construction and use of graphs in kiln drying lumber [U.S. Forest Service Research Legacy]
- [x] 1967 - Construction and use of graphs in kiln drying lumber [U.S. Forest Service Research Legacy]
1957/1966, 1967, 1968 point to the same item: https://ir.library.oregonstate.edu/concern/defaults/h989r762f
- [x] 1971 - Types of steam-heating systems... [U.S. Forest Service Research Legacy]
1957/1971 and 1972 point to the same item: https://ir.library.oregonstate.edu/concern/defaults/kp78gm768
- [x] 2067 - Relation of several formation variables to properties of phenolic-resin-bonded wood-waste hardboards [U.S. Forest Service Research Legacy]
1957/2067 and 2068 point to the same item: https://ir.library.oregonstate.edu/concern/defaults/3j333637b
- [x] 2130 - Effect of moisture absorption on flexural properties of a glass-fabric-polyester laminate [U.S. Forest Service Research Legacy]
1957/2130 and 2131 point to the same item: https://ir.library.oregonstate.edu/concern/defaults/k0698c445
- [x] 2683 - Interaction of moisture and wood [U.S. Forest Service Research Legacy]
1957/2683 and 2684 point to the same item: https://ir.library.oregonstate.edu/concern/defaults/4b29b969s
- [x] 2796 - Stress-strain distribution in Douglas-fir beams within the plastic range [U.S. Forest Service Research Legacy]
1957/2796 and 2797 point to the same item: https://ir.library.oregonstate.edu/concern/defaults/sf268874j
- [x] 2837 - Effect of temperature and restraint during drying on the tensile properties of handsheets [U.S. Forest Service Research Legacy]
1957/2837 and 2838 point to the same item: https://ir.library.oregonstate.edu/concern/defaults/wh246w95n
- [x] 3941 - Messenger ; Vol.5 No.1 (Winter 1990)
- [x] 5831 - Malheur County crop research 1990
- [x] 8424 - USDA report on water and related land resources, Middle Willamette River Basin, Oregon [Oregon Explorer]
add replace uri to https://ir.library.oregonstate.edu/concern/defaults/br86b870k
- [x] 10444 - Oregon Tidal Wetland Reference Sites Pilot Project : Soils Data [Datasets]
  - Found in Hyrax, Handle missing from replaces field
  - add 1957/10444 to replace uri to: https://ir.library.oregonstate.edu/concern/datasets/ks65hj656
- [x] 14878 - Corn drying [Agricultural Experiment Station -- Bulletins / Station Bulletins]
- [x] 16350 - Setup and swash on a natural beach [Faculty Research Publications (College of Earth, Ocean, and Atmospheric Sciences)]
- [x] 17278 - Cost-weight table [Extension Service -- Bulletins / Extension Bulletins]
1957/17278 and 17279 point to the same item: https://ir.library.oregonstate.edu/concern/administrative_report_or_publications/kk91fq11x
- [x] 18696 - Soil sampling for home gardens and small acreages [Extension Service -- Circulars / Extension Circulars]
already ingested: https://ir.library.oregonstate.edu/concern/administrative_report_or_publications/w66348583
  - DSpace Handle has version
  - canonical handle identifies the latest version
- [x] 22825 - Pheromone mechanisms and behavioral strategies for maximizing courtship success in a terrestrial salamander, Plethodon shermani [ETDs]
  - DSpace Handle has version
  - canonical handle identifies the latest version
- [x] 25763 - New Tools for Tidal Wetland Restoration: Development of a Reference Conditions Database... [Datasets]
add 1957/25763 to replace uri: https://ir.library.oregonstate.edu/concern/datasets/s1784r68k
- [x] 29314 - Baseline Characterization of Benthic Habitats and Organisms-Newport [Oregon Wave Energy Trust]
  - DSpace Handle has version
  - canonical handle identifies the latest version
- [x] 36232 - Glacier change in a basin of the Peruvian Andes and implications for water resources [ETDs, Water Resources Graduate Program Theses and Dissertations]
- [x] 38288 - Pararaucaria delfueyoi sp nov from the late jurassic canadon calcareo formation, chubut, argentina... [Faculty Research Publications (Botany and Plant P
  - DSpace Handle has version
  - canonical handle identifies the latest version
- [x] 43596 - Embargo test using embargo in file description tab, set to lift Oct. 31 [ETDs]
Not migrate.
- [x] 44860 - Characterization of Neurospora crassa “Fatty Acid Regulator” transcription factors, FAR-1 and FAR-2, by ChIP- and RNA-sequencing [Dataset]
add http://hdl.handle.net/1957/44860 to replace uri: https://ir.library.oregonstate.edu/concern/datasets/sf268993z
- [x] 48776 - Alternative splicing in the obligate biotrophic oomycete pathogen, Pseudoperonospora cubensis [Dataset]
add http://hdl.handle.net/1957/48776 to replace uri: https://ir.library.oregonstate.edu/concern/datasets/c534fv018
- [x] 54908 - The Northwest Archivists Mentoring Program: A Case Study [Faculty Research Publications (Libraries)]
  - DSpace Handle has version
  - canonical handle identifies the latest version
- [x] 55477 - Genomic sequencing and transposon mutagenesis of a biocontrol strain of Burkholderia seminalis... [Dataset]
add replace uri to: https://ir.library.oregonstate.edu/concern/datasets/nv9357931
- [x] 55540 - GLiMR toolset (ArcGIS geoprocessing tools), instruction manual, and 3D data used in support of the manuscript... [Dataset]
add http://hdl.handle.net/1957/55540 to replace uri: https://ir.library.oregonstate.edu/concern/datasets/tx31qq10b
- [x] 57742 - Collaborations between Tribal and Nontribal Organizations: Suggested Best Practices for Sharing Expertise, Cultural Resources, and Knowledge [Open Acces
  - DSpace Handle has version
  - canonical handle identifies the latest version
- [x] 58901 - Involving the users remotely: an exploratory study using asynchronous usability testing [Faculty Research Publications (Libraries), Open Access Articles
1957/58901 and 55683 point to the same item: https://ir.library.oregonstate.edu/concern/articles/kp78gj22j
- [x] 59988 - Wax Transfer Printing Characterization: Expanding Wax Printing to Various Paper-Types [Honors College Theses]

### DSpace Errors
- [x] 9742 - DSpace Error (not usual Resource Not Found)
Not migrate, item purged in DSpace.
- [x] 20194 - Image-seeking preferences &amp; behavior  of undergraduates:   a study to understand what they want, how they do it, &amp; how we can help
  - Not migrated
  - DSpace not showing item
- [x] 35861 - Asymmetric effects of trade costs on entry modes: Firm level evidence [Faculty Research Publications (Economics)]
  - Not migrated
  - DSpace not showing item

### Recent DSpace Submissions

- [x] 61956 
- [x] 61957
- [x] 61958
- [x] 61959
- [x] 61960
- [x] 61961
- [x] 61962
- [x] 61963
- [x] 61964
- [x] 61965
- [x] 61966
- [x] 61967
- [x] 61968
- [x] 61969
- [x] 61970
- [x] 61971
- [x] 61972
- [x] 61973
- [x] 61974
- [x] 61975
- [x] 61976
- [x] 61977
- [x] 61978

**Comment by vantuyls** [comment]
Check for each of these:
- [ ] was it exported from dspace - if so, re-migrate it

**Comment by zhang4952** [comment]
New ingestion in DSpace
- [ ] 61929

**Comment by zhang4952** [comment]
Done
