### ISSUE TITLE
New behavior for external and internal links

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1170]
the following spreadsheet should be used to re-define how internal and external links behave from the work showpage:

https://docs.google.com/spreadsheets/d/1rDBHRrKqsIuVZuSrjWNTO-CVeBvJURC924M_4pipKqU/edit#gid=0

**Comment by simholt** [comment]
Current and preferred link behavior listed here:
https://docs.google.com/spreadsheets/d/1rDBHRrKqsIuVZuSrjWNTO-CVeBvJURC924M_4pipKqU/edit?usp=sharing
