### ISSUE TITLE
create a footer for SA@OSU

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1171]
footer currently doesn't have as much information as would be useful. 

still need to create content for footer.

**Comment by revgum** [comment]
Would like to see the repo short hash code for the most recent commit to the master branch for the SA repo. This would potentially have an integration in the deployment script grabbing the commit hash code and updating a symlinked file on the server?

**Comment by simholt** [comment]
In addition to what's already on the footer, add elements similar to [Valley Lib](https://library.oregonstate.edu/), including:

![footer](https://user-images.githubusercontent.com/33705514/38635729-1848d266-3d7b-11e8-8226-99c4abf65279.png)

- **Contact Info** with physical address:
121 The Valley Library
Corvallis, OR 97331-4501
- **Contact Us** that links to SA Contact form: https://ir.library.oregonstate.edu/contact
- Link to Services for Persons with Disabilities: https://library.oregonstate.edu/accessibility-services
- Link to Valley Lib home page: **"Scholar's Archive is a service of [Oregon State University Libraries & Press](https://library.oregonstate.edu/)."** https://library.oregonstate.edu/
- Yes to @revgum's idea above.

**Comment by simholt** [comment]
Great! Looking forward to the link text getting fixed.
