### ISSUE TITLE
Are embargoes lifting automatically?

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1173]
are they?

**Comment by straleyb** [comment]
From what I can see, they don't expire automatically. 
As of 1/22/2018: Test being done for an embargo expiriing on the 23rd of January and will update on that day. In the mean time, there is a /embargo url that you can route to which is an embargo manager. This functionality isnt surfaced in the application as a link, but the route still exists. You can deactivate an embargo from this page as well as edit it and delete it.

**Comment by vantuyls** [comment]
okay, will create a new ticket to auto-release embargoes.
