### ISSUE TITLE
Customize worktypes w/defaults

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1174]
Resource Type: Honors College Thesis
NA Affiliation: Honors College

**Comment by simholt** [comment]
PART ONE: For the following worktypes, set default value of :peerreviewed to **no**
- [ ] GTD

- [ ] Grad Proj

- [ ] Honors Coll Thesis

- [ ] Undergrad Thesis

- [ ] Technical Report

- [ ] Admin Report

- [ ] Conference Procs

**Comment by simholt** [comment]
PART TWO: For the Honors College Thesis worktype:

- [ ] Set default :resource_type to **Honors College Thesis**
- [ ] Set default :degree_level to **Bachelor's**
- [ ] Set default :other_affiliation to **Honors College**
- [ ] Set default :peerreviewed to **no**

**Comment by simholt** [comment]
Looks great!
