### ISSUE TITLE
Community / Collection handle mapping

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1177]
see #1165 

After the ticket mentioned above is addressed, the yml mapping files for handles => community or handles => collection could be evaluated and simplified. Ticket #1165 will index all communities (even parent communities) for all items.. so communities like https://github.com/osulp/Scholars-Archive/blob/master/config/handles_ir_communities_collections.yml#L119 could be simplified to just finding the community "Department of Geosciences"

**Comment by shieldsb** [comment]
No longer needed.
