### ISSUE TITLE
[Analytics] When someone clicks a shared download link it should register as a download in Google Analytics

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#118]

**Comment by zhang4952** [comment]
The code can be executed as a filter before rending the pdf or actual document:
- the code understand it is a 'direct' link from search engine, such as by pattens like .pdf
- parse the pdf filename or link uri
- trigger GA and send download+1 for the pdf/uri

**Comment by zhang4952** [comment]
Another solution:
all directly linked pdf/document requests will be redirected to a special page, where Google Analytics is triggered as download

**Comment by vantuyls** [comment]
The Google Scholar guy at Open Repositories indicated that GA should be able to count these thing natively. I think we need to look at how GA deals with this type of thing before homebrewing our own solution, right?

**Comment by zhang4952** [comment]
GA should be able to track download if pdf link is clicked inside a page, but not a "direct link" of pdf sent by a search engine. The problem is that direct link does not create a page view and Google Analytics cannot track it natively because of javascript
