### ISSUE TITLE
Item Analytics: CSV export of item analytics

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#121]
For monthly (one link by the table) and daily (one link by the time series)

**Comment by vantuyls** [comment]
Exported file should include all analytics data for the item including:
Month
Year
Pageviews
Downloads

The file should start with the Month, Year the file was uploaded up to the last complete month.

**Comment by vantuyls** [comment]
Do we want a header in the file indicating when it was generated

**Comment by vantuyls** [comment]
File should include a line of text at the first row indicating the date-time of creation and the URI from which the file was created:
"This file was generated on <%Y%m%d%hh:mm:ss> and represents statistics for the item at <URI of Item>"

**Comment by vantuyls** [comment]
Header modification!
This file was generated on <%Y%m%d%hh:mm:ss> and represents  statistics for the item at <URI> Title: "<first 25 characters of title>"

**Comment by vantuyls** [comment]
NOTE: we currently only have a link for Daily Stats, we still need Monthly Stats

**Comment by straleyb** [comment]
Monthly by monthly graph. daily by time series.
