### ISSUE TITLE
graduation_year validation error doesn't render proper

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1228]
![screen shot 2018-02-08 at 1 51 35 pm](https://user-images.githubusercontent.com/32885/36000270-3e8a3de0-0cd7-11e8-9072-0695d7455435.png)

**Comment by simholt** [comment]
Lookin good.

![screen shot 2018-04-20 at 1 53 09 pm](https://user-images.githubusercontent.com/33705514/39073298-2ffe1a32-44a2-11e8-890d-0d45a73729dd.png)
