### ISSUE TITLE
Missing attached files for some works

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1233]
a handful of works that migrated from dspace are missing files. These are the ones i've found so far. 

http://ir.library.oregonstate.edu/xmlui/handle/1957/30294 - Appendix A.7z
--
http://ir.library.oregonstate.edu/xmlui/handle/1957/33356 - Archive disc.zip

http://ir.library.oregonstate.edu/xmlui/handle/1957/52380 - CurtisJennaR2014_Supplement.zip

**Comment by simholt** [comment]
These are also missing files:

https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/2b88qh992
https://ir.library.oregonstate.edu/concern/datasets/3484zm97d

**Comment by revgum** [comment]
Done!
