### ISSUE TITLE
Migrated items with funked up embargoes

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1235]
The following item shows an OSU embargo and has the following problem:
- [ ] the item should have an OSU embargo releasing to Public on the given release date, but was migrated with an OSU embargo releasing to OSU embargo

This is one example, but i'm concerned that there may be more out there...

https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/d217qr942

**Comment by simholt** [comment]
Here's another one (with an embargo that did not expire in December when it should have):
https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/jw827h15c

**Comment by vantuyls** [comment]
@luisgreg99 @zhang4952 can you confirm or deny that this is resolved?

**Comment by zhang4952** [comment]
@vantuyls @simholt : This issue is resolved. The activities are recorded in the PR: https://github.com/osulp/Scholars-Archive/pull/1250. I will close the issue.
