### ISSUE TITLE
Item should be visible to OSU users but is not

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1236]
this item:
https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/d217qr942

is unavailable to authenticated OSU users bbut it should bbe available.

**Comment by revgum** [comment]
Greg and I paired.. we found `visibility` was left as `restricted` in a previous cleanup rake task. We've got a list of all of the id's that need to be checked after having fixed this one.
