### ISSUE TITLE
Confirm embargo visibilities are set correctly for migrated DSpace items 

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#1248]
- [x] Create a list of embargoed DSpace items: handle, dc.description.embargo, dc.description.embargopolicy

- [ ] Run a script to publish embargo setup DSpace items

**Comment by vantuyls** [comment]
add:
- [ ] for the list of embargoed dspace items, also include the current embargo state in Hyrax

**Comment by luisgreg99** [comment]
I will get the current embargo state values in Hyrax from the given list, then we can compare the current vs expected visibility.
