### ISSUE TITLE
Direct pdf link should be considered as download

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#125]
A lot of traffics to SA are redirected pdf links from search engines such as Google Scholar, which Google Analytics can not. The new hydra IR should be able to:
1. identify the incoming pdf links and 
2. find the corresponding object/file
3. add 1 to its download count (just like user has pressed the "download" button)

**Comment by wickr** [comment]
the Download button on an item page in Hyrax currently does capture File Downloaded events, but if it's a direct link to a file with no javascript loaded, that won't be captured

**Comment by revgum** [comment]
For instance, visiting this url directly doesn't show up in analytics: http://lib-saapp1.library.oregonstate.edu/downloads/sj139571z?locale=en

**Comment by revgum** [comment]
see #309
