### ISSUE TITLE
smart validation based on required field and value being included

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1251]

**Comment by vantuyls** [comment]
more descriptive info? @straleyb

**Comment by straleyb** [comment]
This ticket may actually be done. https://github.com/osulp/Scholars-Archive/pull/1257

**Comment by straleyb** [comment]
We can now choose what we want to validate based on an object that describes specific validation requirements.

**Comment by vantuyls** [comment]
@straleyb should this be closed?

**Comment by straleyb** [comment]
Should be closed.
