### ISSUE TITLE
Some PDFs not opening in Acrobat

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1263]
PDFs on these records get "Insufficient data for an image" when opening in some versions of Acrobat but open in Preview (and other viewers) just fine. It is not related to migration; the same files in dspace also fail to open. This is not an uncommon issue with Acrobat, but if it is a file issue that we can fix, that is ideal. It has already impacted at least one SA user. 

I couldn't open these files last week but the problem disappeared after I ran the latest High Sierra Supplemental Update. Here is a partial list:

https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/b2773x70z
https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/tq57nt14b
https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/j098zd368
https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/br86b6306
https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/qn59q702d

Also, they all have blue doc thumbnails instead of proper file images.

![blue doc](https://user-images.githubusercontent.com/33705514/36857074-76b99980-1d2c-11e8-99d3-3f8ee60250f6.png)

**Comment by simholt** [comment]
Got another complaint about this yesterday - fac member and ref desk not able to open. Had to switch computers.

**Comment by vantuyls** [comment]
@simholt any update on this situation?

**Comment by simholt** [comment]
@vantuyls 

Yes -- I find more every day and the ref desk contacted me about the problem yesterday, 3/13.

They all open for me now, though.
