### ISSUE TITLE
Find Works without Files Attached

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#1264]
Run a Solr query to find out:
- parent works without child
- work without fileset

**Comment by mellinma** [comment]
@zhang4952  will you take a look at this ticket?  Have you had a chance to run this SOLR query?  and if not, can you schedule when you will have this done?

**Comment by zhang4952** [comment]
I find around 50 works without file attached in four work types. Here is the list of work ids:
`Article,45
id
np193g632
td96k7853
tt44ps62n
76537630r
m900p118b
h702qc90b
0g354m745
tm70n225b
1c18dm896
db78tj75f
0r9679523
70795f56m
q811kr24k
k0698f01s
70795f80p
bc386r089
vd66w535r
pr76f853p
2v23w071v
xw42nd714
pv63g519m
sb397d97t
nk322k48f
vx021m172
7d278z93d
xs55mj357
5m60qx652
2b88qj44p
rx913w21b
x920g288q
wd3762152
nz806495t
9c67wt160
st74cw68n
6395wd56v
3f462b72w
0p096c86h
7d278z89t
cz30q0228
cf95jh852
44558k617
cr56n619g
n009w7081
r207tv49m
qn59q863b

Dataset,2
id
p5547x09c
1j92gd02s

GraduateThesisOrDissertation,4
id
08612r83z
4b29bb27g
c247dx62j
7d278z283

TechnicalReport,1
id
08612p24c`

**Comment by simholt** [comment]
NOTE: Many of these are Oregon Sea Grant items where we purposely made a record for items we did not have permission to deposit articles for as an access point (the record includes information on how the item can be requested).
