### ISSUE TITLE
allow user to add parent work on edit work form.

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1267]

**Comment by vantuyls** [comment]
i don't understand this issue. @straleyb can you add more information?

**Comment by straleyb** [comment]
I think this was just said during a meeting that it would be useful to be able to add a parent work to a work that is currently being edited. Just like how you would add a child work, have a second form to add a parent work. @vantuyls @simholt

**Comment by vantuyls** [comment]
ah, right. title edited slightly. 

related to: 
https://github.com/osulp/Scholars-Archive/issues/887
(sorta)
