### ISSUE TITLE
On FileSet Analytics page, "downloads since..." dates are incorrect

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1269]
![screenshot from 2018-03-09 12-01-54](https://user-images.githubusercontent.com/2293544/37227327-cb9650a4-2391-11e8-968c-470a31317531.png)

https://ir.library.oregonstate.edu/files/d791sh21s/stats

Date Available for that Work is 2009

Problems:
- [ ] "0 views and 23747 downloads since July 14, 2017" - Date Available is on the item, why isn't that being used? Steve's comment below to use the first date of stats data makes the most sense though.
- [ ] 0 views even after migration (this is a popular article)
- [ ] missing stats from May 27, 2016 - December 2017 (possibly being addressed by Hui's reprocessing of stats)

Similar to #1169

**Comment by vantuyls** [comment]
set the downloads since date to match the analytics table's first date

**Comment by revgum** [comment]
see #1314

**Comment by simholt** [comment]
Yay it works!
