### ISSUE TITLE
Fix odd date sort on notifications page

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1273]
Date sort follows unknown and mysterious order that is not helpful to users.

![moar notifd](https://user-images.githubusercontent.com/33705514/37232642-c36552c8-23a4-11e8-9bfb-a4b07b08c01e.png)
![notifs](https://user-images.githubusercontent.com/33705514/37232643-c380ffb4-23a4-11e8-8546-2c3f15295559.png)

**Comment by vantuyls** [comment]
i believe this will be fixed in the hyrax 2.1 release.

**Comment by simholt** [comment]
All good.
