### ISSUE TITLE
Enable Blacklight Advanced Search

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1280]
some sorting and searching may be more functional with Blacklight advanced search enabled. This issue is to ask the question: is this a good idea, and, if yes, to initiate the investigation of what it would mean to implement this on SA@OSU. 

related: nothing

**Comment by wickr** [comment]
Original ticket referencing Advanced Search: https://github.com/osulp/Scholars-Archive/issues/888

**Comment by straleyb** [comment]
Looks like there is something going on with the solr query that is making it not work properly.

Below is the normal search
```
![image](https://user-images.githubusercontent.com/6424683/42242404-97f8864a-7ec2-11e8-8d89-6d61b50f3a19.png)
```

this is the advanced search
```
![image](https://user-images.githubusercontent.com/6424683/42242416-a6ab691e-7ec2-11e8-9ac3-0f8c7c047d8f.png)

```
