### ISSUE TITLE
Hyrax Bags Export Rake for MetaArchive Preservation

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#1285]
MetaArchive requires exported Bags similar to this for its crawler: http://metaarchive-staging.lib.calpoly.edu/bd-ms190_bag001_split/bd-ms190_bag001_1/. The Bag export rake will:
- Not use fedora-import-export-util anymore
- One parent work as one Bag
- Each Bag includes all fileset of the parent work
- add key metadata fields (title and etc) of parent work to bag-infor.txt, download all filesets
- use bagit Gem to create Bag from the download directory with a manifest of links to filesets

**Comment by wickr** [comment]
Can the crawler not handle deep folders under `/data` even with a manifest file? Or are we not generating a manifest file right now?  The sample you linked has this manifest: http://metaarchive-staging.lib.calpoly.edu/bd-ms190_bag001_split/bd-ms190_bag001_1/manifest-md5.txt

With the folder tree `/data/OralHistories/{file}`  so they don't need it completely flat.

fedora-import-export can export as BagIt, and there are config files to set options in bag-info.txt. Are you sure this isn't going to work at all?

The bagit gem will work, it's used in csv2bag, but you're going to have to write more of the Fedora querying code to get the right items out.
