### ISSUE TITLE
Unwanted variant labels showing up for non-aca other

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1288]
@wickr said this happened before and was fixed.

Created a new non-aca other:

> 
> - id: "http://id.loc.gov/authorities/names/n79100852"
> term: "Oregon Sea Grant"

When assigned, it lists **ALL** the variants from LC:

![not all the variants](https://user-images.githubusercontent.com/33705514/37686297-0f42b66a-2c54-11e8-8683-0c3c05570249.png)

See here:
https://ir.library.oregonstate.edu/concern/defaults/1g05fh80z

**Comment by wickr** [comment]
Prior changes: https://github.com/osulp/Scholars-Archive/issues/704

**Comment by wickr** [comment]
It might be this: https://github.com/osulp/Scholars-Archive/blob/master/app/indexers/default_work_indexer.rb#L21

Fields set to multiple: true are fetching all labels, of which the variant labels under altLabel are included.

**Comment by wickr** [comment]
@simholt sorry if the other discussion was confusing, but the 'Oregon Sea Grant' term label from the YAML file is only going to show up in the forms. The view pages (and solr) are going to use the fetched prefLabel for the term, in this case 'Oregon State University. Sea Grant College Program.'

**Comment by simholt** [comment]
Gotcha.

![fixed it](https://user-images.githubusercontent.com/33705514/37688412-3c7f9004-2c5d-11e8-82b3-1c8310430133.png)

**Comment by straleyb** [comment]
Take out if statement and just pull top label for all types. More work to be done on alt label indexing per #1423

**Comment by vantuyls** [comment]
qa done

**Comment by simholt** [comment]
Not sure what's going on here -- is functioning on some but not all? Or just items ingested since the fix?

Looks good: 
 http://ir.library.oregonstate.edu/concern/defaults/cv43p275v 

Not working:
http://ir.library.oregonstate.edu/concern/defaults/w6634875r
http://ir.library.oregonstate.edu/concern/articles/zp38wj63t

**Comment by vantuyls** [comment]
does a reindex or something of the like need to happen for this to apply to all items in the repo?

**Comment by wickr** [comment]
Yeah, #1467 is related. I should be able to get a fix in soon and then a full reindex will fix the above issues.

**Comment by simholt** [comment]
@wickr Has the system been reindexed? Still seeing multis on older items:

http://ir.library.oregonstate.edu/concern/administrative_report_or_publications/5q47rp03r

**Comment by wickr** [comment]
@simholt @vantuyls These should now all be resolved with the reindex last week. I double checked the links in this ticket and they look good.

**Comment by simholt** [comment]
Alles gute!
