### ISSUE TITLE
Build an OER Collection

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1292]
Stefanie Buck asked if we could build a collection specifically for OERs. The requirements for this are somewhat unclear at this point, but we should:
- [x] Build a collection for the OER Work Type
- [x] Consult with Stefanie about other needs for this collection

note: requires implementation of Collection Extensions on Hyrax 2.1

**Comment by simholt** [comment]
This collection is made and has been shared with Stefanie. I am waiting for feedback from her.

**Comment by shieldsb** [comment]
Completed.
