### ISSUE TITLE
restrict drop-down list contents by work type

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1295]
need an update on what exactly this entails @simholt

**Comment by simholt** [comment]
Starting thoughts:

https://docs.google.com/document/d/1tblRKWWIJSMCOagyUSITlQYJ1_OnBwUn3-q_NSivmI8/edit?usp=sharing

**Comment by simholt** [comment]
Same as #606?

**Comment by simholt** [comment]
Partially addressed in these tickets:
#1496: Restrict Resource Type for HCT deposits
#1492: Restrict Resource Type for GTD deposits
