### ISSUE TITLE
NoMethodError: undefined method `include?' for nil:NilClass in edtf_date_compare_service

### ISSUE THREAD

**Issue by luisgreg99** [osulp/Scholars-Archive#1297]
We can reproduce the error with:
```
bundle exec rails c
irb(main):005:0> ScholarsArchive::EdtfDateCompareService.includes_last_five_years?("invalid option here")
NoMethodError: undefined method `include?' for nil:NilClass
        from /Users/username/Scholars-Archive/app/services/scholars_archive/edtf_date_compare_service.rb:38:in `block in date_in_past_five_years?'
        ...
```

**Comment by luisgreg99** [comment]
Debugging notes: 

Screenshot from @simholt
![image](https://user-images.githubusercontent.com/3486120/38101480-3f568b14-3335-11e8-9bca-15bd35837cfc.png)

I looked more into this error, and it turns out that the degree field "Risk and Uncertainty Quantification in Marine Science" http://opaquenamespace.org/ns/osuDegreeFields/5TrS7vqq was throwing the broken page because it is missing a date in the degree field metadata.

For non-admin users, SA only lists degree fields with dates within the last five years to reduce the number of options under the "Degree field" dropdown. 

Is the option "Risk and Uncertainty Quantification in Marine Science" expected to be listed under "Degree Field" for current submissions? @simholt @wickr

**Comment by simholt** [comment]
Yes, it is new and should be current. (@wickr Am I supposed to add dates?)
