### ISSUE TITLE
Add fields to Other worktype

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1301]
Need to have the following non-required fields added to Other/Default worktype:

Degree Level
Degree Name
Degree Field

**Comment by simholt** [comment]
Looks good --

**Comment by simholt** [comment]
@straleyb 

Hmmm --- the degree field shows up in Edit but not on the record page (although it saves the entry).

See: https://ir.library.oregonstate.edu/concern/defaults/r494vr22d
-
![degree field in edit](https://user-images.githubusercontent.com/33705514/38886608-4be51878-422b-11e8-9e35-887948d59ec4.png)

![no degree field](https://user-images.githubusercontent.com/33705514/38886622-4e750d64-422b-11e8-9594-918e72f809c6.png)

**Comment by simholt** [comment]
@straleyb Tested on staging, still not working.
http://ir-staging.library.oregonstate.edu/concern/defaults/1831ck063

Deg field appears on edit page but not on show page:

![screen shot 2018-04-20 at 8 07 57 am](https://user-images.githubusercontent.com/33705514/39058928-092b73b2-4472-11e8-8a9c-80415411b4ea.png)
![screen shot 2018-04-20 at 8 08 07 am](https://user-images.githubusercontent.com/33705514/39058931-0b485408-4472-11e8-82a7-56b41dd1426a.png)

**Comment by straleyb** [comment]
Ahh not on show page. Ok thanks!

**Comment by revgum** [comment]
Degree Field in the presenter looks wrong

![screen shot 2018-04-20 at 4 31 42 pm](https://user-images.githubusercontent.com/32885/39077678-92b25e0c-44b8-11e8-8c2d-b162395ed8fc.png)

**Comment by straleyb** [comment]
deployed to production
