### ISSUE TITLE
Locate & ingest missing analytics

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1302]
This issue has been noted on Extension Service documents but may be more widespread (?).

Example:
https://ir.library.oregonstate.edu/concern/administrative_report_or_publications/rn301159f

Item says it's been available since 2011 but the statistics only go back to July 2017.

**Comment by zhang4952** [comment]
- [ ] Create a list of bitstream_id and filename from DSpace

- [ ] Update process_legacy_stats.rake to use the list when filename is missing from elasticsearch dump

- [ ] run process_legacy_stats.rake

**Comment by simholt** [comment]
Yaaaay!
