### ISSUE TITLE
link text color

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1311]
Link text color is black, which makes it unclear what links are on the system. This might make sense when looking at the values of metadata on the `show` page for a work, but definitely doesn't make sense everywhere on the application.

**Comment by vantuyls** [comment]
need to look for an OSU web color that would work for link text.

**Comment by vantuyls** [comment]
http://communications.oregonstate.edu/brand-guide/visual-identity/colors

Looking at Stratosphere, not sure i love this color for link text. @revgum @simholt @wickr @straleyb @KennaW @zhang4952 @luisgreg99 thoughts?

**Comment by revgum** [comment]
HighTide looks awesome

**Comment by revgum** [comment]
https://ir.library.oregonstate.edu/admin/appearance

I set the link and footer link color to high tide, give it a spin and lets talk about if this is good or if we need to reconsider.

@vantuyls

**Comment by vantuyls** [comment]
looks good. thank!

**Comment by simholt** [comment]
@revgum Isn't this already running on production?

**Comment by revgum** [comment]
@simholt indeed, this isn't really a code change, just an update on the appearance settings
