### ISSUE TITLE
Make all degree grantors visible to admins

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1313]
Right now, edit options in drop-down menu for Degree Grantor are Oregon State University and Other. Would like admins to see all versions of OSU, such as Oregon Agricultural College, Oregon State College, etc.

**Comment by wickr** [comment]
Need to add the older forms to the degree grantors local authority: 
Oregon Agricultural College | http://id.loc.gov/authorities/names/n95078079
Oregon State Agricultural College | http://id.loc.gov/authorities/names/n87850581
Oregon State College | http://id.loc.gov/authorities/names/n82022628

**Comment by simholt** [comment]
Good stuff --
