### ISSUE TITLE
Enable use of multiple controlled vocabularies for some fields

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1328]
Would be useful if could drop a LC URI, etc. into the :other_affiliation field instead of current multi-step process.

What about other fields?

**Comment by vantuyls** [comment]
@wickr thoughts on this?

**Comment by wickr** [comment]
I agree that it's useful, and it something we talked about early on, but it's not really compatible with our current setup.

**Comment by vantuyls** [comment]
okay. probably something to look forward to for OD2 that SA can then leverage?

**Comment by simholt** [comment]
This needs a reassessment - closing for now.
