### ISSUE TITLE
Nested attributes for author metadata

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#134]
Need to establish a relationship between author and identifier (e.g. ORCID, ResearcherID) in the metadata. Can this be accomplished by linking the author and identifier?

**Comment by terrellt** [comment]
Working on this a little and what I was worried about turned out to be true - nested attributes for blank nodes in the graph don't seem to work. Pushed up https://github.com/osulp/Scholars-Archive/tree/nested_authors to show the test that needs to pass.
