### ISSUE TITLE
Catalog view, facet pagination 

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1349]
It appears that `numDocs` returns the full count of works having the facet being viewed.. but the visibility of the works aren't reflected in that number. Private, or otherwise hidden works, can cause the pagination to render multiple "pages" to select which have no facet information to display.

TODO: Can the paginator (or solr query) be extended to account for the number of unique facet values instead of `numDocs`?

**Comment by revgum** [comment]
Consider querying SOLR for multiple pages worth of documents and evaluating how many are visible to the user on the `current_page` and the following 2-3 (whatever the configuration suggests) pages.. This data could be used on the front-end to make the determination of how many additional page buttons to render on pagination.

**Comment by vantuyls** [comment]
@revgum @straleyb any idea what a qa test for this would look like?
