### ISSUE TITLE
Ingest Form - labels and descriptions

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#135]
Apply agreed upon text for Final Label and Description to ingest form

**Comment by vantuyls** [comment]
See the shared GSheet - https://docs.google.com/a/oregonstate.edu/spreadsheets/d/1lVOgVtW8_foYj4gdsPOx-xBtF1GACLy4UGPPLKTbjiU/edit?usp=sharing

**Comment by straleyb** [comment]
Both on ingest form and on item record page.
