### ISSUE TITLE
Nonfunctioning degree grantor field 

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1351]
Found a bunch of items in the grad project worktype where you can't do anything with the degree grantor field.

![no degree grantor](https://user-images.githubusercontent.com/33705514/39022684-889b103a-43eb-11e8-8d66-4f69c85401bc.png)

Samples:
https://ir.library.oregonstate.edu/concern/graduate_projects/r494vm821
https://ir.library.oregonstate.edu/concern/graduate_projects/rf55zc858

**Comment by straleyb** [comment]
This looks like it has to do with how it was migrated over. Since you can't choose a blank degree grantor, this wouldn't be allowed. I think its non functioning because it was migrated over without a degree grantor and therefore not pulling the data properly.

**Comment by luisgreg99** [comment]
We were actually missing this line in the production environment: https://github.com/osulp/Scholars-Archive/blob/master/config/initializers/hyrax.rb#L240

**Comment by luisgreg99** [comment]
@simholt I just restarted the server with the small update. The options should now be showing up in the `Degree Grantor` dropdown.
