### ISSUE TITLE
thumbnails on catalog browse are super tiny

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1360]
![screen shot 2018-04-23 at 2 37 07 pm](https://user-images.githubusercontent.com/32885/39154657-e3c451ae-4703-11e8-8ca1-1feecc363ecc.png)

**Comment by simholt** [comment]
All set here.

![screen shot 2018-05-15 at 2 48 29 pm](https://user-images.githubusercontent.com/33705514/40085377-10efb3d8-584f-11e8-91e2-5eb5e6623d1d.png)
