### ISSUE TITLE
language changes don't stick

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1369]
Changing the language from english to spanish reverts to english on navigation to help/about/etc. pages.

Replicate:
1) go to homepage
2) change language from english to spanish
3) navigate to About
4) see language change back to english

**Comment by revgum** [comment]
I also noticed this, and it has an impact on a Hyrax bug that I identified https://github.com/samvera/hyrax/issues/2927

**Comment by simholt** [comment]
Wunderbar!

![screen shot 2018-05-15 at 2 46 10 pm](https://user-images.githubusercontent.com/33705514/40085274-c1001c5a-584e-11e8-85a5-64f8dbef95a0.png)

**Comment by wickr** [comment]
Tested again just now and language changes stick.
