### ISSUE TITLE
very long lines of bad metadata make the show page look bad

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1372]
![screen shot 2018-04-27 at 12 53 09 pm](https://user-images.githubusercontent.com/32885/39383931-eba8375e-4a1f-11e8-9d52-57ba4f186bd9.png)

**Comment by simholt** [comment]
Looks like breaks are now happening in the middle of words:

![screen shot 2018-05-15 at 2 29 32 pm](https://user-images.githubusercontent.com/33705514/40084600-7d9067f6-584c-11e8-8397-09416eb70de9.png)

**Comment by revgum** [comment]
Fixed in hyrax210 branch.

**Comment by simholt** [comment]
All better!
