### ISSUE TITLE
Change meta tag og:description mapping

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1374]
The default meta tag for og:description  
```
<meta property="og:description" content="TEST DESCRIPTION"/>
```
is mapped to `:description` and would probably be better as `:abstract`, or possibly both.

The current line at is https://github.com/osulp/Scholars-Archive/blob/master/app/views/shared/_citations.html.erb#L9
`<meta property="og:description" content="<%= @presenter.description.first.truncate(200) rescue @presenter.title.first %>"/>`

I don't think falling back to title makes sense since that's in the field right before og:description.

**Comment by straleyb** [comment]
@simholt How do we want to approach this ticket? Should we default to abstract? Or check description then check abstract? How do we want to go about it if both are empty?

**Comment by simholt** [comment]
@straleyb 
Please default to abstract. Description is old dspace stuff that I'm slowly moving to the appropriate field or deleting.
No idea if both are empty.

**Comment by CGillen** [comment]
QA Pass:
https://ir-staging.library.oregonstate.edu/concern/articles/8336h2114?locale=en#?c=0&m=0&s=0&cv=0&xywh=-204%2C-1%2C1046%2C360

```
og:description
The Mars Perseverance rover mission is part of NASA's Mars Exploration Program, a long-term effort of robotic exploration of the Red Planet. The Mars Perseverance mission addresses high-priority sc...
```

```
abstract
The Mars Perseverance rover mission is part of NASA's Mars Exploration Program, a long-term effort of robotic exploration of the Red Planet. The Mars Perseverance mission addresses high-priority science goals for Mars exploration, including key questions about the potential for life on Mars. The mission takes the next step by not only seeking signs of habitable conditions on Mars in the ancient past, but also searching for signs of past microbial life itself. The Mars Perseverance rover introduces a drill that can collect core samples of the most promising rocks and soils and set them aside in a "cache" on the surface of Mars.
```
