### ISSUE TITLE
Ingesting legacy statistics

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#1379]
Legacy statistics from DSpace has been exported into CSV from elasticsearch, each CSV corresponds to one handle (e.g., 1957-50669.csv) and it contains all the visits to that item in history. Each visit to DSpace SA@OSU should include these information in the CSV:
- visit type (view/download)
- item handle and item id for 'view'
- bitstream id and bitstream name for 'download'
- IP and time of the visit
- agent and other information

The process_legacy_stats.rake in sa_scripts will ingest the legacy view and download stats to WorkViewStat and FileDownloadStat in Hyrax for the correct objects accordingly:
- for view statistics: the rake task will find work in Hyrax by handle, then group the statistics by date, and update the WorkViewStat
- for download statistics: the program will find the fileset using both handle (to get work) and bitstream_name (to match filename), then group the download by date, and update FileDownloadStat

First round of processing finished in January 2018 but we had several user complains about missing file download statistics that earlier than the migration cut-off date. We identify the root cause as bitstream_name (i.e., filename) is missing from many of the CSV exports. The solution is to fetch the bitstream_name by bitstream_id if missing and we re-processed all the CSVs in April 2018.

Most of the fileset statistics should be corrected after the second round of processing. I can identify 3,250 errors of failed updates from the processing logs of April run, which is about 3% of total filesets in Hyrax. The errors are all related with problem of finding the correct fileset in Hyrax. I will attach github issues in below with details.

**Comment by zhang4952** [comment]
related #1380 , #1381

**Comment by shieldsb** [comment]
Done.
