### ISSUE TITLE
Date fields on the ingest form with a drop-down list of date types

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#138]
Add Other Date field to form - allow dropdown list of date types (from DataCite)

**Comment by vantuyls** [comment]
https://schema.datacite.org/meta/kernel-3/doc/DataCite-MetadataKernel_v3.1.pdf

**Comment by vantuyls** [comment]
Steve will inquire with DataCite re: RDF support

**Comment by vantuyls** [comment]
We will use opaquenamespace URIs for these predicates in the mean time (and possibly forever)

**Comment by zhang4952** [comment]
use e.g., opaqueness.org/date/modifiedDate

**Comment by wickr** [comment]
Huh? Why wouldn't we use this for modified? http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-modified

**Comment by vantuyls** [comment]
Modified is currently minted by Sufia, right. 

Also, modified isn't in the DataCite vocab for dates:
Accepted
Available
Copyrighted
Collected
Created
Issued
Submitted
Updated
Valid

**Comment by vantuyls** [comment]
So, when it comes to Date Modified - shouldn't these be coming from the Fedora PREMIS Event Service and our discussion about being able to add PREMIS events manually? I can't think of another case where we would need a modified date that isn't a PREMIS event.

**Comment by vantuyls** [comment]
Check out the Datacite2RDF crosswalk here: 
file:///Users/vantuyls/Downloads/DataCite2RDF.pdf

**Comment by luisgreg99** [comment]
@vantuyIs: this the same pdf: http://purl.org/spar/datacite/DataCite2RDF?

**Comment by vantuyls** [comment]
heh, yea. super useful link there, right?

**Comment by straleyb** [comment]
Awww and I thought I was gonna get access to your users folder!

**Comment by vantuyls** [comment]
Sorry, not this time. It would be too interesting for any of you to comprehend. You would descend into a fit of hysterical madness at the sheer magnitude of brilliance in my users folder.

**Comment by vantuyls** [comment]
Need: Find dateCollected
