### ISSUE TITLE
Psychology not showing in Degree Field drop-down menu

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1382]
I kept getting notifications to add Psychology as a new other. It shows up fine for me as an admin so I can edit them, but I tested it on a student account and it is not listed.

**Comment by luisgreg99** [comment]
It looks like `Psychology` at http://opaquenamespace.org/ns/osuDegreeFields/VlQXe2qK  in CVM doesn't have the current year listed in the `date` field. Right now it says `{1929,1931,1937,1947}` under `date`. I think if we include the current year (or any year during the last five years) in this date list, it should display the degree for regular users as well.

**Comment by simholt** [comment]
I learned how to alter the dates and we are up and rolling.
