### ISSUE TITLE
Enable edit access to additional info in datasets

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1391]
Cannot access the additional information that displays under the title on the show page. Many imported datasets have info here that belongs in a dedicated field but it cannot be moved.

Example: 
https://ir.library.oregonstate.edu/concern/datasets/zp38wh66f

Ryan says it may have something to do with datasets not having "description" enabled, instead showing all dataset fields on one edit page. 

dce:description not showing up.

**Comment by wickr** [comment]
Related: https://github.com/osulp/Scholars-Archive/issues/899

**Comment by vantuyls** [comment]
qa done

**Comment by straleyb** [comment]
qa done and deployed to production
