### ISSUE TITLE
Limbo submission cannot be deleted

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1393]
When logged in as admin, this upload does not resolve and therefore cannot be deleted. It does not show up on the student's Works page.

https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/sf268b14h

FYI: This upload was a problem earlier #1383.

**Comment by luisgreg99** [comment]
The work with id `sf268b14h` should now render the show page as expected.

Command line/console instructions used to resolve the request load on the show page:
```
w = ActiveFedora::Base.find("sf268b14h")
w.representative_id = ""
w.thumbnail_id = ""
w.save
```
