### ISSUE TITLE
Make Geonames field on show page an external link to the geonames uri

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1399]
Not sure if the URI is being saved, but we need to change the link type to an external link and make it respond to a method '#geonames_uri` which will get called when the show page renders that displays the external link box linking to the geonames uri.

```
<%= presenter.attribute_to_html(:replaces, render_as: :external_link) %>
```
Something like this. Possibly using a helper method too like this
```
config.add_index_field solr_name("abstract", :stored_searchable), label: "Abstract", itemprop: 'abstract', helper_method: :truncated_summary
```

**Comment by straleyb** [comment]
References #1277

**Comment by straleyb** [comment]
Fixed by #1403

**Comment by straleyb** [comment]
Why was this moved back?

**Comment by simholt** [comment]
Perfect!
