### ISSUE TITLE
Geoname label should include place, county, state, country

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1400]
Or place, country.

This usually comes in the form of Place << county << state << country. Or something similar. 

Portland >> Multnomah County >> Oregon >> United States 
Multnomah County >> Oregon >> United States 
Oregon >> United States 
United States

https://www.oregondigital.org/catalog/oregondigital:df67rb97v

**Comment by straleyb** [comment]
References #1277

**Comment by simholt** [comment]
Would prefer just top line:
Portland >> Multnomah County >> Oregon >> United States

**Comment by straleyb** [comment]
Portland, Multnomah County, Oregon, United States it is.

**Comment by straleyb** [comment]
This is going to be more difficult than we think. We need to configure the Location model to be able to override the rdf_label method and when it is picking a label, that it fetches parent objects until it hits a specific top level rdf subject. After it hits that it recursively backs out and builds the label. Having trouble with the interfaces between the #fetch method in SA and wherever its called in Hyrax.

**Comment by straleyb** [comment]
https://github.com/OregonDigital/oregondigital/blob/3ac62d8c3ca2d21a79dd37110e4885c9c76744fe/lib/oregon_digital/rdf/controlled.rb

**Comment by straleyb** [comment]
https://github.com/OregonDigital/oregondigital/blob/3ac62d8c3ca2d21a79dd37110e4885c9c76744fe/lib/oregon_digital/controlled_vocabularies/geographic.rb

**Comment by straleyb** [comment]
qa done and deployed to production
