### ISSUE TITLE
Add Geonames Feature Class into the label in SA

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1401]
Per https://github.com/osulp/Scholars-Archive/issues/1277

Having the feature class from Geonames in the label would help with disambiguation of locations that share names with each other. 

Depot Bay the bay 
Depot Bay the city.

**Comment by straleyb** [comment]
Ok so just display it in the typeahead, but not on the record itself.

**Comment by vantuyls** [comment]
qa done.

**Comment by straleyb** [comment]
on production and ready to be closed
