### ISSUE TITLE
Record with missing file, not in dspace

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1409]
Faculty looking for file attached to this record:
https://ir.library.oregonstate.edu/concern/open_educational_resources/9w032351z

Record in dspace does not have file, either, but there is reference to a PDF being uploaded: EMNO8531.pdf

**Comment by luisgreg99** [comment]
@zhang4952 is there a way to query and retrieve a bitstream from dspace given its name like `EMNO8531.pdf`?

**Comment by wickr** [comment]
Found it on archival storage, lun11, EESC Extension Miscellaneous folder. Sent the file to Sarah.

**Comment by simholt** [comment]
We need to do some queries and make sure this isn't a larger issue. I'll write up a ticket.
