### ISSUE TITLE
Assess quantity of records that should have files but do not

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1410]
Need to see if the problem in #1409 is wide-spread, limited to EESC pubs, or other. 

Files for these items were uploaded but, for whatever reason, did not attach properly in dspace and therefore did not make the migration. The filename for #1409 was listed under description.provenance in Additional Information. 

After these are identified, the files need to located and attached.

**Comment by zhang4952** [comment]
- [ ] Get a spreadsheet of all handles in DSpace with associated bitstreams

- [ ] sort handles by number of associated bitstreams and find those only have one bitstream that indicates they probably only associate license.txt
1957/23947
1957/24266
1957/24335
1957/24721
1957/24956
1957/38470

Background:
The bitstream EMNO8531.pdf is not attached to the item 1957/24956 successfully. The provenance shows that the pdf was uploaded but somehow not attached to the item in the approval step. The psql query shows the only bitstream attached is 'license.txt' and we can find 'EMNO8531.pdf' in Solr in probably it appears in the provenance field several times.

**Comment by simholt** [comment]
@wickr Located and sent me four of the files and I attached them. 

Checked ones are taken care of:
- [ ] 1957/23947
- [ ] 1957/24266
- [ ] 1957/24335
- [ ] 1957/24721
- [ ] 1957/24956
- [ ] 1957/38470

**Comment by zhang4952** [comment]
1957/56061 is the only handle that has 'placeholder.txt'. BTW, that handle has two bitstreams, the other one is 'license.txt'.

**Comment by zhang4952** [comment]
DONE!
