### ISSUE TITLE
Getting notifications for changes in Purchased e-Resources items

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1417]
Looks like same situation we had with #1386. I uploaded five items to the Purchased e-Resource worktype and got double notifications on four of them.

![screen shot 2018-05-22 at 11 30 54 am](https://user-images.githubusercontent.com/33705514/40382651-c1260798-5db3-11e8-9a7c-de5c702378e2.png)

https://ir.library.oregonstate.edu/concern/purchased_e_resources/zc77sw16n
https://ir.library.oregonstate.edu/concern/purchased_e_resources/m900p0825
https://ir.library.oregonstate.edu/concern/purchased_e_resources/rf55zf11w
https://ir.library.oregonstate.edu/concern/purchased_e_resources/f1881r99t

**Comment by luisgreg99** [comment]
It looks like there was a sidekiq process still running on old code (May 9 01:07pm). I have restarted sidekiq to pick up the update.
