### ISSUE TITLE
Ingest Form - Related Resources

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#142]
Input field for Related Resources should have a drop down to select relation type and a field for entering the URI for the related resource

**Comment by wickr** [comment]
Predicates used in Oregon Digital: https://github.com/OregonDigital/oregondigital/blob/master/app/models/datastream/oregon_rdf.rb#L357

**Comment by vantuyls** [comment]
Wait until Sufia 7 (PCDM) to see what we need to do here.

**Comment by zhang4952** [comment]
Closed upon review of issues
