### ISSUE TITLE
directory API for user type, until persons API is ready

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1428]
see #1426 
see #1427 

Establish an approved API application at:
https://developer.oregonstate.edu/user/me/apps

API call to the public directory can return a `primaryAffiliation` which has values (Employee, Other, Retiree, Student, or Unknown). __Caveat__ Users who choose to be confidential in Banner will not have this information. 
https://api.oregonstate.edu/v1/directory?q={username}

Currently I am registered as an owner of an API application that could be used for this integration.

**Comment by vantuyls** [comment]
@revgum can  you recommend a qa test?

**Comment by revgum** [comment]
I can't really think of one, we aren't surfacing the effect of this code aside from if you were a student (in which case you'd only see the ETD, Undergrad, and Other Scholarly Content worktypes.

**Comment by simholt** [comment]
Done
