### ISSUE TITLE
Selecting Other does not require an actual other anymore

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1434]
![others](https://user-images.githubusercontent.com/33705514/40750825-74071fd6-641d-11e8-895c-88a257565d60.png)

Depositors can select Other for Degree Level, Degree Name, and Degree Field and the system no longer forces completion of the new/other field. People can just save without typing the information in.

(Noticed on this upload: https://ir.library.oregonstate.edu/concern/undergraduate_thesis_or_projects/jm214v06n)

**Comment by vantuyls** [comment]
qa complete.

**Comment by vantuyls** [comment]
something odd is happening with this implementation: 
these steps:
1) create new work
2) add an Other to one of the metadata fields (in my case, to Degree Grantor)
3) add a degree grantor that already exists (in my case Oregon State College)
4) submit
5) message shows that says Oregon State College already exists
6) when i go to change the contents of the other field to something else, the checkmark for Describe Your Work (on the right) won't check and so i can't submit the item

**Comment by vantuyls** [comment]
qa complete

**Comment by straleyb** [comment]
is this ready to be closed?
