### ISSUE TITLE
Add OSU Distinguished Professors to Featured Researcher area 

### ISSUE THREAD

**Issue by mellinma** [osulp/Scholars-Archive#1436]
this requires emailing/asking the 3 professors if they would be willing to be featured.  - Sarah - do you want me to do this?  

Ed Brook  
Phone: 541-737-8197 
Fax: 541-737-1200
Email: brooke@geo.oregonstate.edu

Janet Tate
1 541 737 1700
tate@physics.oregonstate.edu

Joey Spatafora
1 541 737 5304
spatafoj@science.oregonstate.edu

http://oregonstate.edu/dept/ncs/lifeatosu/2018/oregon-state-names-three-distinguished-professors/

**Comment by simholt** [comment]
Brook, Edward J.
https://ir.library.oregonstate.edu/catalog?f%5Bcreator_sim%5D%5B%5D=Brook%2C+Edward+J.

Tate, Janet
https://ir.library.oregonstate.edu/catalog?f%5Bcreator_sim%5D%5B%5D=Tate%2C+Janet

Spatafora, Joseph W.
https://ir.library.oregonstate.edu/catalog?f%5Bcreator_sim%5D%5B%5D=Spatafora%2C+Joseph+W.

**Comment by vantuyls** [comment]
one issue at hand is that  we don't have a way to cycle through these in the system - once you set the featured researcher, you have to stick with that one until you manually set another one. We ought to discuss how to manage these outside of the system, and a schedule for setting them. @simholt @boockm

**Comment by simholt** [comment]
I posted Ed Brook's info last week.

**Comment by simholt** [comment]
This is from 2018 and not relevant now - closing.
