### ISSUE TITLE
Migrated item w/o files

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1438]
Supposed to have a thesis and presentation.

https://ir.library.oregonstate.edu/concern/undergraduate_thesis_or_projects/dn39x633q

http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/61697?show=full

**Comment by simholt** [comment]
Okay, that one is fixed but I found another:

https://ir.library.oregonstate.edu/concern/undergraduate_thesis_or_projects/fq977w72m
dspace: http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/13490

**Comment by vantuyls** [comment]
@zhang4952 do we need to revisit this entire issue of works migrated without files? 

what additionally can be done to check for these? because we're finding them at a somewhat alarming frequency.

**Comment by zhang4952** [comment]
- [ ] use query like `-member_ids_ssim:[* TO *] AND has_model_ssim:"GraduateThesisOrDissertation"` to find out works without any file attached by model
- [ ] locate files for the corresponding works
- [ ] attach files to works

**Comment by simholt** [comment]
Second file on this record not resolving:

http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/54878

**Comment by simholt** [comment]
- Almost all the default model ones were duplicate records without the files. A bunch of files didn’t make the transition because the file format in dspace was unknown.
- [This dataset](https://ir.library.oregonstate.edu/concern/datasets/47429f155) directs the user to download files from Box. I will figure out what to do do about it.
- Created separate issue to locate five items on dspace without files: #1464

**Comment by simholt** [comment]
All files located and attached.
