### ISSUE TITLE
[Geo] Nested attributes for geographic point

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#144]
Relates to #301 and #300. Some items will have geographic information that is not in Geonames (nor should it be?) - example: a latitude and longitude pair, or the bounding coordinates for an area

**Comment by vantuyls** [comment]
Need to identify whether there is a standard for coordinate use in metadata

**Comment by vantuyls** [comment]
May want to nest geographic stuff under Spatial - geoname, point, box, etc.

**Comment by zhang4952** [comment]
use methods similar to nested/paired author solution

**Comment by vantuyls** [comment]
using bbox in geoJSON

**Comment by vantuyls** [comment]
Flavor Text:

Point - A label and coordinate pair (latitude and longitude) for this geographic coordinate
Bounding Box - A label and set of coordinate pairs representing the upper left and lower right corners of the bounding box
GeoName - A geographic place name related to the digital object.

**Comment by wickr** [comment]
It might be good to give examples of the coordinate format after the text, if it's not too long. Or at least be super-specific about the format.

One of the issues we had in Oregon Digital was the latitude and longitude were set up as decimal/floating point, and some tried to put in coordinates with degrees, which broke indexing.

This one is kind of picky, but GeoName looks weird on it's own, I've only ever seen it 'GeoNames' and that looks like the official name. Again I would add a note that it needs to be a URI and give an example of the format:  http://sws.geonames.org/5710924/

**Comment by vantuyls** [comment]
Thanks @wickr - @luisgreg99 i've edited the comment above to incorporate these issues.

**Comment by luisgreg99** [comment]
Thanks @wickr and @vantuyls, I will add these examples in the form

**Comment by vantuyls** [comment]
http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#coverage
