### ISSUE TITLE
Allow direct input of Geonames URI in field, bypass typeahead search

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1443]
When you plug in a URI, it should hit that URI instead of the geonames authority uri. Basically if it detects a uri, hit that and parse the response, otherwise, hit the normal one and parse the response. This would enhance the select2 search to work in a much more user friendly way. #1277 Described this.

**Comment by straleyb** [comment]
We only allow typeahead currently, but this is can be done. Is this something we would like to do still?

**Comment by simholt** [comment]
Yes.

**Comment by lamtu1** [comment]
@simholt @carakey For this ticket, would you like the `location` field to hit the `geoname id` -> `5725428` or the full `uri` like -> `http://www.geonames.org/5725428/elk-river.html` for the result to pull up?

**Comment by simholt** [comment]
@lamtu1 Do you mean I could input the `geoname id` into the field and that would pull the correct info from Geonames? If so, yes, that's what would work best.

**Comment by simholt** [comment]
@lamtu1  Entering IDs does not appear to bring any results up. The typeahead works fine with words, but the ID does not. (5721419 is the id for Crater Lake)

<img width="218" alt="Screenshot 2023-09-20 at 3 02 43 PM" src="https://github.com/osulp/Scholars-Archive/assets/33705514/c678ed45-6dac-4932-9fde-153b93d2457b">

**Comment by lamtu1** [comment]
@simholt this PR was not merge in yesterday due to some other feedbacks I got to clean some stuff up. But will get it merge for QA today.

**Comment by simholt** [comment]
This is so much easier than navigating the names in the drop-down!
QA pass--
