### ISSUE TITLE
Non-Academic affiliation other not carrying over after failed save

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1444]

**Comment by straleyb** [comment]
This is an "other" choice and needs to be checked to see if this is still a bug. On failed save, the form should carry over the "other" choice with the data.

**Comment by lamtu1** [comment]
Hi @straleyb, I'm currently double checking just to make sure the PR is correct, when the form should carry over the 'Other' choice with data, does it mean when the `save failed`, when the user go to edit the form or go back to the form the data should be fill in those spot if the `'other' choice is chosen` correct?

**Comment by straleyb** [comment]
@lamtu1 Yep. If the save fails and they get redirected back to the edit/new page to update the data, the value should get pushed back into the form.

**Comment by lamtu1** [comment]
Would the `'other'` choice also need to display the `other choice value` as well? Meaning that the `'other' choice` will display what value was type in rather than just displaying `other` was selected?

**Comment by straleyb** [comment]
Yep. Everything should be retained. The "Other" choice and the value associated with it.

**Comment by carakey** [comment]
Not sure how to QA without an instance of a failed save. We're reasonably comfortable pushing this to production.
