### ISSUE TITLE
Item with odd embargo behaviour 

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1449]
This item has an embargo that was supposed to expire this month, but it is in Hyrax as Private. It expired in dspace. Would like to know if this is a one-time rarity or not.

https://ir.library.oregonstate.edu/concern/honors_college_theses/2n49t591n
http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/61182

**Comment by zhang4952** [comment]
The D2H processed json for this item is: /usr/local/deploy-rails/dspace2hydra/cache/processed_items/ITEM@1957-61182 on saapp1. Its visibility_after_embargo set as `open access`, which I believe should be 'open' in the latest Hyrax.

**Comment by zhang4952** [comment]
1. I query Solr with `visibility_after_embargo_ssim:"open access"` and it returns zero result ("open" or "authenticated" will return a few hundreds results)
2. The `embargo_history` of 2n49t591n shows the intended visibility after embargo is 'authenticated' but is actually 'restricted' after embargo release
3. To verify where is the actual problem, we can observe https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/9z903427x with:
embargo release date as June 21, 2018
visibility_during_embargo: "authenticated"
visibility_after_embargo: "authenticated"
if its visibility also becomes 'restricted' after embargo release, then we can narrow the issue to items with `visibility_after_embargo` set as 'authenticated'

**Comment by zhang4952** [comment]
- [ ] find all migrated item with `visibility_after_embargo` as 'open access': find ITEM\@1957-2*/*.json | xargs grep 'open access' >> ~/result

- [ ] check current `visibility` of these items in Hyrax: they should be `open` or `embargo`; if `embargo` then change `visibility_after_embargo` as 'open'

- [ ] make sure this item: http://ir-staging.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/pv63g047r?locale=en has the correct visibility after embargo after Jun 21, 2018

**Comment by simholt** [comment]
Another one that didn't expire:
http://ir.library.oregonstate.edu/concern/honors_college_theses/fb494b287

**Comment by revgum** [comment]
Can we confirm that this was handled by the most recent embargo inspection/cleanup and close this ticket if so? @zhang4952 @simholt

**Comment by simholt** [comment]
@revgum All good, closing.
