### ISSUE TITLE
Search Results index metadata 'box' is too narrow, Abstract wraps way too soon

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1450]
With Hyrax 2.1.0, in the Search Results, the area displaying an item's metadata is too narrow, and forces Abstract to wrap way too soon.

![image](https://user-images.githubusercontent.com/2293544/68504522-fa008f00-0219-11ea-9ced-146d858463ef.png)

The 'metadata' div is under a 'col-md-6' div, which may be the culprit.

Can see on our staging results, or on Nurax, about halfway down this page: https://nurax.curationexperts.com/catalog?locale=en&page=16&q=&search_field=all_fields

May want to submit this fix to Hyrax too.

**Comment by wickr** [comment]
This was part of the change to include User Collections in search results, and if one is present, there's a new column with info boxes for Collections and Works (see screenshot).
https://github.com/samvera/hyrax/blob/master/app/views/catalog/_index_list_default.html.erb

![screenshot from 2018-07-06 17-40-59](https://user-images.githubusercontent.com/2293544/42405006-76c84af8-8144-11e8-9949-20bd2fdf9a81.png)

There's a conditional to check if the Collections are present already, could extend that to the 'col-md-6' div, changing that to 'col-md-10' or something if it's not present.

**Comment by simholt** [comment]
Looks good, although items with early line breaks will still look off. 

QA passed.
![Screen Shot 2019-11-20 at 1 42 02 PM](https://user-images.githubusercontent.com/33705514/69280630-a5ef9600-0b9b-11ea-9870-7836233c5dc7.png)
