### ISSUE TITLE
Locate files not in dspace so they can be attached

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1464]
In completing #1438, found following records without files in dspace -- are they in scanned doc files? @zhang4952 looked up the name of the missing files.

http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/14855
em8646.pdf

http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/18233
171InteriorPainting.pdf

http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/18245
184Alfalfa.pdf

http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/18924
ec1297.pdf

http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/18364
fs234.pdf

**Comment by wickr** [comment]
Found 4 of the 5, sent to Sarah. Still looking for ec1297.pdf

**Comment by simholt** [comment]
Four files attached.

**Comment by wickr** [comment]
I've been unable to locate a file for: 
http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/18924
ec1297.pdf

I did a filename search for ec1297 and lots of other variants of keywords from the record.
Also asked Ryan O. and Brian. 
I'm confident in saying it's not on Parthenon where all of the others were.

**Comment by simholt** [comment]
Update - @mellinma located the hardcopy of the missing file and is working with Brian to get it scanned.

**Comment by simholt** [comment]
Uploaded! All files now located and attached.
