### ISSUE TITLE
Triple powered properties with multiple values/URIs only indexing 1 label

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1467]
http://ir.library.oregonstate.edu/concern/honors_college_theses/4f16c5058

"International Studies" displays as selected on the edit page but not the show page.

**Comment by wickr** [comment]
For triple powered properties: `academic_affiliation, other_affiliation, degree_field, degree_grantors`

Data is saved by the form ok, but when multiple values are present, only 1 label is indexed in Solr. `fetch_top_label` is called with all URIs as a group, with 1 label returned.

Replicated this issue on staging: http://ir-staging.library.oregonstate.edu/concern/honors_college_theses/8c97kq626?locale=en
Degree Field has 2 values, Academic Affiliation has 3 values, Other Affiliation has 3 values but all show only 1 label.
