### ISSUE TITLE
dspace subscriptions still operational

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1468]
Bailey received an email notification from dspace that "New items are available in the collections you have subscribed to" for an item with an embargo that was supposed to expire. 

I don't think these notifications should still be functioning. Can we turn them off?

**Comment by vantuyls** [comment]
@zhang4952 can you remove all but DSpace Admin rights to all communities and collections on DSpace?

**Comment by zhang4952** [comment]
Delete all groups that associated with DSpace collections in dspace-ir.

**Comment by zhang4952** [comment]
It is done
