### ISSUE TITLE
Discuss advanced search layout and assess expected functionality

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1473]

**Comment by vantuyls** [comment]
Two initial thoughts - probably for a future sprint:
1) Implement multiple facet selection on the main results page, not just on the Advanced Search page
2) Reconfigure the advanced search page to function more like Web of Science basic search. This will clean up the UI significantly.

**Comment by straleyb** [comment]
Advanced search is in. Maybe a new discussion about what we would like out of it. Closing.

**Comment by CGillen** [comment]
@simholt 
How do we feel about making facets work with a type-ahead? Example on OD2: https://staging.oregondigital.org/advanced
It allows for multi-select and unlimited facet values (not just the 6 displayed from expanded accordion), though it's not implemented correctly on OD2 yet.

**Comment by simholt** [comment]
@CGillen I like that.
