### ISSUE TITLE
Advanced search field order?

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1474]

**Comment by wickr** [comment]
Sarah and I did an initial review of these for what to keep. Didn't focus on the order.

Search Fields:

### Current
                                                                                                                 
* All Fields                                                                                                          
* Contributor                                                                                                         
* Academic Affiliation                                                                                                
* Related Items                                                                                                       
* Non-Academic Affiliation                                                                                            
* Dspace Collection                                                                                                   
* Dspace Community                                                                                                    
* Creator                                                                                                             
* Degree Field                                                                                                        
* Title                                                                                                               
* Abstract or Summary                                                                                                 
* Publisher                                                                                                           
* Date Accepted                                                                                                       
* Date Available                                                                                                      
* Date Collected                                                                                                      
* Date Copyright                                                                                                      
* Date Created                                                                                                        
* Date Issued                                                                                                         
* Date Reviewed                                                                                                       
* Date Valid                                                                                                          
* Subject                                                                                                             
* Hydrologic Unit Code                                                                                                
* File Format                                                                                                         
* Identifier                                                                                                          
* Keyword                                                                                                             
* Location                                                                                                            
                                                                                                                    
                                                                                                                    
### Removed                                                                                                           
* Language                                                                                                            
* Language Label                                                                                                      
* Rights                                                                                                              
* Rights Statement Label                                                                                              
* License Label                                                                                                       
* Peer Reviewed Label                                                                                                 
* Resource Type                                                                                                       
* Geographic Coordinates                                                                                              
* Location (based_near only)                                                                                          
* Identifier                                                                                                          
* Keyword

**Comment by simholt** [comment]
Can we add Committee Member and Advisor to the list?

**Comment by wickr** [comment]
@simholt sure.

**Comment by simholt** [comment]
Also, I think listing these in alphabetical order makes the most sense. @vantuyls ?

**Comment by vantuyls** [comment]
Final decision - reorder these into alpha

**Comment by straleyb** [comment]
Closing for new ticket. https://github.com/osulp/Scholars-Archive/issues/1981
