### ISSUE TITLE
Ingest Form - enter key field problem

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#148]
When you enter information in a field in the ingest form and hit enter a new field appears (a repeatable field), but the cursor does not move to the new field. 

When the enter key is hit again, the new field is deleted and the contents of the current field are removed.

Ideally it could work this way:
1) enter information in a repeatable field
2) hit the enter key, resulting in a new field being created and the cursor being moved to that new field

**Comment by revgum** [comment]
Closed upon review of issues
