### ISSUE TITLE
Remove Private and Oregon State Univ. Visibilty for GTD work type

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1491]
Depositors should not see Private or OSU visibility options when depositing GTDs - though administrative users should see all visibility options.

**Comment by luisgreg99** [comment]
@vantuyls Should these visibility options be removed from all other ETDs as well like GPs? or is it just for the GTD work type?

**Comment by simholt** [comment]
@luisgreg99 Just the GTD worktype.

**Comment by simholt** [comment]
Hey now:

![Screen Shot 2019-04-24 at 3 18 17 PM](https://user-images.githubusercontent.com/33705514/56697789-8d220f00-66a4-11e9-9454-215c81725985.png)
