### ISSUE TITLE
Restrict Resource Type for HCT deposits

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1496]
Honors College Work Type deposits should only offer the option of "Honors College Thesis" for Resource Type

**Comment by simholt** [comment]
Lovely:

![Screen Shot 2019-04-24 at 9 27 57 AM](https://user-images.githubusercontent.com/33705514/56676495-45cf5a80-6673-11e9-8bd7-a8a4b75fff46.png)
