### ISSUE TITLE
Add more granular time stamp information to Review Submissions table

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1497]
The Review Submissions table currently shows Submission Date in YYYY-MM-DD. More granular information is useful in this area. So extend that date to: YYYY-MM-DD-HH:MM:SS or similar

**Comment by simholt** [comment]
Looks good!
![Screen Shot 2019-04-29 at 3 07 41 PM](https://user-images.githubusercontent.com/33705514/56930136-96d6b880-6a90-11e9-8ed5-0c74cfd237df.png)
