### ISSUE TITLE
[Advanced Search] Add search button at top of page

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1502]
Currently, the search button on the advanced search page is at the bottom, requiring one to scroll to the bottom of the page to enact the search. 

Do: Add the search button to the top of the page, next to the Start Over button.

**Comment by simholt** [comment]
![Screen Shot 2019-11-20 at 1 45 20 PM](https://user-images.githubusercontent.com/33705514/69280840-05e63c80-0b9c-11ea-8b3a-3ded0ce8829e.png)

Nice -- QA passed.
