### ISSUE TITLE
Metadata fields should always be editable for Administrators

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1504]
Currently, some metadata fields are not editable (when values exist, they're locked as readonly):
- [ ] Location
- [ ] Related Items

Example:
https://ir.library.oregonstate.edu/concern/technical_reports/5q47rt93r/edit?locale=en

**Comment by vantuyls** [comment]
these are just examples. we want to be able to edit any metadata field that exists for an item.

**Comment by wickr** [comment]
#1530 reverted

**Comment by wickr** [comment]
The root of this issue appears to be that when values exist in Location and Related Items, when you Edit an item, they are readonly and not editable by anyone. They are on the form though.
![image](https://user-images.githubusercontent.com/2293544/43492539-497f947c-94de-11e8-82d1-c5f92111f861.png)

**Comment by wickr** [comment]
@luisgreg99 confirmed the form fields for existing values are set to 'readonly' due to ActiveFedora not supporting updating nested resources at the item level. To edit values, they must be deleted and re-added. It would help somewhat to explain this in the form fields' help text.
