### ISSUE TITLE
Surface Hyrax 2.1 UI changes on Work Showpages

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1505]
UI changes in Hyrax 2.1 are (presumably) being overwritten by our local work. We would like to take advantage of Hyrax 2.1 UI changes in SA@OSU.

**Comment by revgum** [comment]
Consider, now, Hyrax 2.2 as well (as seen on Nurax site)

**Comment by simholt** [comment]
Status? We're now running 2.5.1.
