### ISSUE TITLE
TypeError causes Production Console not to load

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1532]
`$ RAILS_ENV=production bundle exec rails c`

`...config/application.rb:34:in '[]=': no implicit conversion of Integer into String (TypeError)`

I think the new cache timeout value needs to be a string: https://github.com/osulp/Scholars-Archive/pull/1526/commits/545de0587c1dcb732474d0c30107c02426a9c8c5#diff-0c81412db819a0dbfb6a0a376ba0763dR68

**Comment by straleyb** [comment]
<img width="1066" alt="Screen Shot 2019-04-30 at 1 41 34 PM" src="https://user-images.githubusercontent.com/6424683/56991918-b97ad700-6b4d-11e9-956f-f5251dbbaf74.png">

This is working. Could have been fixed overtime. Closing and we can reopen if something pops up
