### ISSUE TITLE
add logging for failed saves in embargo expiring rake task

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1537]

**Comment by revgum** [comment]
Add logging for all activity on the embargo expiration rake task.. a line stating which work it is expiring, and a line that it was successful (or a line when it catches an exception along with the exception backtrace and message)

**Comment by straleyb** [comment]
These have been added and are logging. 
https://github.com/osulp/Scholars-Archive/commit/aa8e291e98ae41f37115b15883104d05ba9532ec#diff-5e6b78a6ac54286f56eb922b90aa57fd
