### ISSUE TITLE
Create UI for Reordering Creator on Form

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1542]
### Summary

Need to implement the UI for the ingest/edit forms for reordering creator. The UI used, currently, to reorder the Featured Works on the homepage. Specifics:
* UI should be no bigger than what we see on the Creator field currently
* Include up and down arrows
* Reindexing based on what is on the form after a change - drop, button click, and on form submit
* Use an ordered list element for creator

### Related work

#1500

**Comment by luisgreg99** [comment]
fixed by #1576
