### ISSUE TITLE
Add form help text explaining read-only lock for existing values on nested resources

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1555]
### Descriptive summary

When editing an item that has existing values for nested fields, like Related Items and Location (nested_geo), the form fields are set to readonly due to ActiveFedora not being able to do updates to the nested resources. Updates to existing values have to be done by deleting and re-adding the nested values. Adding a note to the form field's help text could help explain this.

First draft: "Due to current system limitations, existing values in this field cannot be edited. To make changes, add a new entry (label and/or URL) and remove the old one."

### Related work

Original issue #1504

**Comment by straleyb** [comment]
<img width="1214" alt="Screen Shot 2019-11-18 at 9 25 45 AM" src="https://user-images.githubusercontent.com/6424683/69075024-7008b100-09e5-11ea-8b72-ee0f3b85519a.png">

**Comment by simholt** [comment]
This currently shows up on ordered fields. It only needs to be on Related Items and Location (not any other Geographic Coordinate types).

![Screen Shot 2019-11-20 at 1 55 38 PM](https://user-images.githubusercontent.com/33705514/69281625-75106080-0b9d-11ea-9916-ca5a3898ac70.png)

**Comment by simholt** [comment]
Looks good!
