### ISSUE TITLE
Configure multiple tooltips depending on the context of the link. 

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1557]
### Descriptive summary

On the show page, we need to parse out the specific links that exist in the metadata of a work. If the link contains an @ then append a specific class so the JavaScript can enable the proper tool tip. Otherwise, check the parent field, if it is a description, then it should say "visit external link", finally, the rest should say "search SA@OSU"

### Expected behavior

Popup helper text should say "Visit external link" or something to that effect.

### Actual behavior

Popup helper text says "Search for this term in SA@OSU"

### Steps to reproduce the behavior

1. Visit https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/kd17ct94m?locale=en
2. Look at Additional Information section, hover over email address link

### Screenshot
![image](https://user-images.githubusercontent.com/2293544/43551451-e7331d7a-959b-11e8-8b46-62ac7f74b211.png)

**Comment by wickr** [comment]
When #1556 is merged, this will be a bigger issue, as over a hundred Funding Statements have external URLs in them.

**Comment by simholt** [comment]
Allllright -- QA good & done!
![Screen Shot 2019-09-10 at 2 59 19 PM](https://user-images.githubusercontent.com/33705514/64653586-9e618300-d3db-11e9-8197-9f6a848cc4f1.png)

![Screen Shot 2019-09-10 at 2 59 26 PM](https://user-images.githubusercontent.com/33705514/64653589-a02b4680-d3db-11e9-900c-6ec63a5cea7a.png)
