### ISSUE TITLE
Discuss functionality of updating ordered metadata.

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1563]
Currently, it is a limitation in active fedora that you cannot update the data in a nested resource, like the nested_order_creator. A user can bypass this limitation by deleting the field they wish to update and filling out a new field on the form and dragging it to its proper place. 

Ticket here https://github.com/samvera/active_fedora/issues/874

Another way we can do this on the backend is mark all elements for destroy and add new objects while copying all the info from each object to a newly generated object and save.

**Comment by luisgreg99** [comment]
fixed by PR https://github.com/osulp/Scholars-Archive/pull/1565
