### ISSUE TITLE
Service to parse index from nested_order_creator_label and sort based on index

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1568]
We need some way to use the index of a nested_order_creator to order the data before it is presented to the user on the show page. This can be done in a similar way we are doing it with uris. Using the structure of label$index we can parse out the index and order based on that. When we pass the ordered array back from the solr document it should display in the correct order.

**Comment by luisgreg99** [comment]
related to #1500

**Comment by luisgreg99** [comment]
fixed by #1579
