### ISSUE TITLE
SA bulk edit for isPartOf series

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1574]
Bulk edit test to separate out conglomeration of "series" terms from migration -- insert hasJournal, hasVolume, & hasNumber; clear out in_series field.

https://docs.google.com/spreadsheets/d/16Y0tuXXEd_vUwRvnuk-ty9YTUR0WHupqesSX8OUGb9Q/edit?usp=sharing

**Comment by revgum** [comment]
completed
