### ISSUE TITLE
Collection showpage Results Per Page dropdown breaks

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1575]
### Descriptive summary

On the Collection showpage (see link below) the Results Per Page dropdown throws an error when the number of results selected exceeds the number of works in the collection. 

https://ir.library.oregonstate.edu/collections/cc08hm78f?utf8=%E2%9C%93&sort=score+desc%2C+date_uploaded_dtsi+desc&per_page=50&locale=en&page=2

### Expected behavior
Results will display, and if the number of results selected is more than the number of results in the collection, the contents of the entire collection will display.

### Actual behavior
Page throws an error (see attached)

<img width="1192" alt="screen shot 2018-08-08 at 10 29 02" src="https://user-images.githubusercontent.com/9534576/43853777-e94a8b16-9af5-11e8-9839-24b18e8f6fe5.png">

**Comment by vantuyls** [comment]
checked this on Nurax and it is not an issue there.

**Comment by shieldsb** [comment]
No longer a problem- could not reproduce issue.
