### ISSUE TITLE
Logging for discrepancies between DSpace creator list and SA@OSU creator list

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1583]
### Descriptive summary

We need to know which works have creator discrepancies between DSpace and SA@OSU. Miss-spellings, amount. Literally anything.

References #1559

**Comment by straleyb** [comment]
Fixed by #1588

**Comment by revgum** [comment]
This is being covered in #1640

**Comment by revgum** [comment]
fixed in #1640
