### ISSUE TITLE
Establish ordering on related items field

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1596]
### Descriptive summary

The related items field sometimes includes sequential objects; ordering would increase functionality. It would also be effective for ranking items according to importance, specific to general.

### Expected behavior
Allow desired order to be preserved in related items field. 

### Actual behavior

For example, it would be best if part two was listed first so the user doesn't have to go hunting. Also good for Oregon Sea Grant link to be last since it is least important.

![screen shot 2018-08-21 at 11 05 36 am](https://user-images.githubusercontent.com/33705514/44420202-2c996b80-a532-11e8-8f52-5076f34411b7.png)

**Comment by straleyb** [comment]
Fixed by #1613
