### ISSUE TITLE
Extend CSV rake task to work on titles as well. 

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1609]
### Descriptive summary

Since we want ordered titles, and there are about 53 works in dspace with multiple titles, we need to operate on a second csv to order the titles as well. All others without multiple titles will be handled per usual. Just move the title over to the nested ordered title and assign it the index of 0.

**Comment by revgum** [comment]
If the rake task just treats titles in the usual way (just migrating over with indexes starting at 0), then we can go back through and manually fix the 53 works and not have to worry about making the rake task intelligent enough to handle ordered titles.

**Comment by straleyb** [comment]
So we will need a list of all possible works in dspace that dont have multiple titles and use that. @zhang4952 Can you drop that list here?

**Comment by revgum** [comment]
I don't think that's necessary, as every work is being operated on with regard to the ordered creators, just order the titles and the related items at the same time (but in the 0 starting index) fashion.

**Comment by straleyb** [comment]
You think the creator list is comprehensive enough to contain all the handles of works with titles? There isnt the possibility that one could be missed?

**Comment by revgum** [comment]
I expect that the CSV for ordered creators includes every migrated work (even if it has 1 creator), so that the creators are migrated to the new data structure regardless.

So the CSV covers all migrated works, and the other rake tasks covers all works that weren't migrated.

**Comment by straleyb** [comment]
Ok I just wanted to make sure.

**Comment by revgum** [comment]
This functionality is being covered in the #1640

**Comment by revgum** [comment]
fixed in #1640
