### ISSUE TITLE
Migrate Works with multiple titles to the new ordered titles

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1611]
### Descriptive summary

We are going to skip over all the works with multiple titles and do these by hand. 
https://docs.google.com/spreadsheets/d/1j-g2ec8OzZgAU5obun1NDKyvJv1KaENHvPG_AhIJr_E/edit?usp=sharing
Here is the list for future reference.

**Comment by revgum** [comment]
This is going to be covered in #1640

**Comment by revgum** [comment]
fixed in #1640
