### ISSUE TITLE
Ordered aesthetic feedback

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1616]
### Descriptive summary

This ticket provides a medium for feedback for the ordered stuff. We can take this ticket and break the suggestions into other tickets.

**Comment by simholt** [comment]
The click & drag buttons are really wide in Firefox - would rather they were same size as Chrome.

Firefox:
![screen shot 2018-08-24 at 11 48 10 am](https://user-images.githubusercontent.com/33705514/44602717-44245e80-a795-11e8-8ed3-4eb537988e3e.png)

Chrome:
![screen shot 2018-08-24 at 12 07 08 pm](https://user-images.githubusercontent.com/33705514/44603035-46d38380-a796-11e8-8575-5994ac0e91d8.png)

**Comment by luisgreg99** [comment]
@simholt The fix for the cross-browser compatibility issue in Firefox has been applied on staging.

**Comment by wickr** [comment]
'Label' doesn't need to be in the form fields

![image](https://user-images.githubusercontent.com/2293544/44880343-09bd3480-ac61-11e8-8e4b-df77e42ebc90.png)

**Comment by wickr** [comment]
![image](https://user-images.githubusercontent.com/2293544/44880631-e5158c80-ac61-11e8-9bd3-c46d350025b8.png)

For related items, the up and down arrows should display on the same line. The click-and-drag button should be the same single line height. Add approx. 10px vertical spacing to separate each Label/URL pairing.

**Comment by wickr** [comment]
![image](https://user-images.githubusercontent.com/2293544/44881228-ba2c3800-ac63-11e8-8fd1-d8f8fa4d0bcf.png)
When clicking the click-and-drag-button, it disappears while active, and moves the rest of the buttons and form fields to the left. This also uncovers the 'X Remove' text if it was previously hidden.

**Comment by straleyb** [comment]
Fixed by multiple PRs
