### ISSUE TITLE
Ordered works migrate in-place?

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1624]
### Descriptive summary

During migration for ordered metadata, if a work is accessed that hadn't already been migrated, migrate it in-place?

### Problem Statement

The data structures for several fields for each work has been changed in SA. While running the massive data migration, it is expected that users should be able to access/view/update works. In the event that a work is accessed, without having been migrated by the rake task, the SA code could have a service that performs the migration prior to rendering the edit page.

**Comment by wickr** [comment]
I don't think you should attempt to migrate something in-place if the migration task is already running, unless you're sure that the task would detect that and skip past it. This might make tracking final progress more difficult as well.

**Comment by revgum** [comment]
@wickr Agreed, the rake task would need to evaluate that the work it is operating on had already been migrated.

**Comment by revgum** [comment]
What if;

- the presenters (`#show`) were able to show the regular property as they have been, or the ordered property if the work was already migrated
- the forms (`#edit`) could detect if the work had been migrated, and migrate it if it hadn't already, finding the data in a CSV on the server to perform the migration for that one work
- the rake task migrates works, but detects first if the work had been migrated and logs details if it is skipped because it had already been migrated
