### ISSUE TITLE
Implement ordered items for additional fields

### ISSUE THREAD

**Issue by luisgreg99** [osulp/Scholars-Archive#1626]
### Descriptive summary
Implement ordering behavior on fields below:
- [x] creator
- [x] title
- [x] additional information
- [x] contributor
- [x] abstract
- [x] nested_related_items

~~alt_title~~
~~editor~~
~~tableofcontents~~
~~typical_age_range~~

### Expected behavior

Ability to order items in the `#show`, `#edit`, and `#new` forms.

### Related work

#1500

**Comment by simholt** [comment]
Removed some fields after discussion.

**Comment by straleyb** [comment]
Fixed by #1627
