### ISSUE TITLE
QA on ordered metadata fields

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1630]
### Descriptive summary

We need to do some pretty heavy duty QA on ordered fields. The following are suggested tests:
QA on ordering:
- [x] 1) create new work and check showpage

- [x] 2) edit work and check showpage

- [x] 3) remove contents of a creator field and save - then check ordering

- [x] 4) test migrated item

- [x] 5) add new creator to migrated item

- [x] 6) delete creator from migrated item

- [x] 7) reorder creator on migrated item

- [ ] :sunglasses: 1 billion creators

- [x] 9) batch upload with ordered creator

- [x] 10) test across a few (all?) work types

- [x] 11) intentionally trigger an error and then see if things are fine - trigger by leaving an Other field blank elsewhere on the form

- [x] 12) check saved content of the record, not just the showpage

- [x] 13) How does ordering work with the citation function?

**Comment by revgum** [comment]
I tested creating a batch work and got 
`ActionView::Template::Error: undefined method 'abstract' for #<Hyrax::Forms::BatchUploadForm:0x00005618ff0ae1c8>`
https://app.datadoghq.com/apm/resource/scholars-archive-staging/rack.request/25638a7e9b66d31a?start=1537377829333&end=1537378729333&paused=false&env=none&traceID=8052850497766222959&spanID=4793468107643811937

**Comment by luisgreg99** [comment]
@revgum I'm currently looking into ticket #1689 I think we missed the update for `batch_upload_form.rb`.

**Comment by luisgreg99** [comment]
@revgum batch uploads is now working as expected. It got fixed by https://github.com/osulp/Scholars-Archive/pull/1690 and https://github.com/osulp/Scholars-Archive/pull/1692
