### ISSUE TITLE
Figure out predicates for top level metadata (i.e. nested_ordered_*) and index

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1637]
### Descriptive summary

Right now we have predicates in place for the nested_ordered_* nested fields, but the actual predicates used for the top level object need to be figured out. No easy way that describes that a field is ordered.

https://github.com/osulp/Scholars-Archive/blob/master/app/models/concerns/scholars_archive/default_metadata.rb#L209

Need to figure out predicates for these fields.

**Comment by luisgreg99** [comment]
@wickr for the current `:creator`, could we change it to `::RDF::Vocab::DC.creator`? and use the DC11 version in `:nested_ordered_creator` like you suggested?
