### ISSUE TITLE
Update citation output for ordered fields

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1638]
### Descriptive summary

Ordered metadata fields require modification of our citation output. Need to ensure that order is preserved. 

### Related work

#1631 
#1632

**Comment by luisgreg99** [comment]
Addressed by https://github.com/osulp/Scholars-Archive/blob/master/app/models/concerns/scholars_archive/has_nested_ordered_properties.rb

Old methods in models still work (used for citation), but now return entries based on the order specified by the index of the corresponding nested field.
