### ISSUE TITLE
Enable virus scan

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#1653]
via guideline: https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#fixity-checking

**Comment by straleyb** [comment]
Im not sure how we can QA this, but the fact that it installed the gem on staging shows that its setup on the server proper. @revgum @decimalator Any ideas on how we can test virus scan is working?

**Comment by revgum** [comment]
I don't think this feature really lends itself to QA aside from the verification that the gem is running, the app boots (which depends on installed and functional clamav). I suppose we could find a file, with a virus, and run clamav on it on the server.. @decimalator?

**Comment by revgum** [comment]
Deploying to staging works fine, but we're having problems getting ClamAV working on production. @decimalator can you add context?

**Comment by revgum** [comment]
@decimalator suggests we rollback clamav for production until he can get it working (compilation fails)

**Comment by decimalator** [comment]
there is a known issue with the clamav 0.101.2 and the clamav gem. I can't find binary 0.100.2 clamav packages anywhere so I'm going to have to build it from source. Is there anything that Hyrax requires besides just the binary for scanning? Does Hyrax use the `clamd` daemon interface? Or just direct command-line scanning?

**Comment by decimalator** [comment]
Assuming that Hyrax just uses `clamscan`, you can try re-deploying with clamav enabled on production. I've built and installed 0.100.2 in `/usr/local/clamav`. I've already added it to the PATH.

**Comment by straleyb** [comment]
On production and running.
