### ISSUE TITLE
Investigate visibility of expired embargoes 

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#1667]
Investigate whether SA will set visibility for expired embargo items based on `visibility_after_embargo`:
- Whether this PR is merged in Hyrax and installed to SA: https://github.com/curationexperts/laevigata/pull/1123
- Whether SA has embargo service like: https://github.com/curationexperts/laevigata/blob/master/app/services/embargo_expiration_service.rb

**Comment by vantuyls** [comment]
what is the status of this work, @zhang4952 ?

**Comment by zhang4952** [comment]
The PR#1757 of "bugfix for embargo release logging" could be the solution of this issue, will wait for a week or so before close the issue.

**Comment by straleyb** [comment]
Closing this until we run into errors again.
