### ISSUE TITLE
Facets for the new nested elements.

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1679]
### Descriptive summary

If they are going to be searchable via a quick link from the show page, I believe facet configuration needs to be set up. https://github.com/projectblacklight/blacklight/blob/8b9041544553ce0dd0d979f9f39f78d94b30b46d/app/helpers/blacklight/render_constraints_helper_behavior.rb#L83

Suggests that its based off of facet configuration which is done in the catalog controller. 

The show page links work like a faceted search, and therefore need to be configured as facetable fields.

**Comment by luisgreg99** [comment]
fixed by https://github.com/osulp/Scholars-Archive/pull/1682
