### ISSUE TITLE
Find appropriate predicates for the various date types

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#168]

**Comment by vantuyls** [comment]
references #138

**Comment by vantuyls** [comment]
I think this is done. Any additional comments?

**Comment by straleyb** [comment]
We need to know what to use for date collected.

**Comment by vantuyls** [comment]
measurementDeterminedDate from the Darwin Core Schema? - http://rs.tdwg.org/dwc/terms/#measurementDeterminedDate

**Comment by wickr** [comment]
Here's what OD is using: http://opaquenamespace.org/ns/collectedDate

**Comment by wickr** [comment]
@vantuyls Can you pick something for dateCollected, either the DarwinCore measurementDeterminedDate or the ONS one that Oregon Digital is using?

**Comment by vantuyls** [comment]
DarwinCore looks appropriate.
