### ISSUE TITLE
Items moved between worktypes - cannot upload additional files

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1685]
### Descriptive summary
Moving items to a different worktype than what they were originally assigned removes them from a workflow. A side effect of this is the inability to upload additional files.

### Expected behavior
Can add new files to a record.

### Actual behavior
Can go through the actions of adding a new file but they never show up.

### Steps to reproduce the behavior
https://ir.library.oregonstate.edu/concern/graduate_projects/6m311p99v

Go into edit and add any type of file. It will not load on the show page.

**Comment by wickr** [comment]
Josh found the fix:
```ruby
irb(main):013:0> Sipity::Entity.where(proxy_for_global_id: 'gid://scholars-archive/GraduateThesisOrDissertation/1c18dk66p')
  Sipity::Entity Load (0.8ms)  SELECT `sipity_entities`.* FROM `sipity_entities` WHERE `sipity_entities`.`proxy_for_global_id` = 'gid://scholars-archive/GraduateThesisOrDissertation/1c18dk66p'
=> #<ActiveRecord::Relation [#<Sipity::Entity id: 186802, proxy_for_global_id: "gid://scholars-archive/GraduateThesisOrDissertatio...", workflow_id: 290, workflow_state_id: 869, created_at: "2017-10-19 23:59:36", updated_at: "2017-10-19 23:59:41">]>
irb(main):014:0> se = Sipity::Entity.find(186802)
  Sipity::Entity Load (0.5ms)  SELECT  `sipity_entities`.* FROM `sipity_entities` WHERE `sipity_entities`.`id` = 186802 LIMIT 1
=> #<Sipity::Entity id: 186802, proxy_for_global_id: "gid://scholars-archive/GraduateThesisOrDissertatio...", workflow_id: 290, workflow_state_id: 869, created_at: "2017-10-19 23:59:36", updated_at: "2017-10-19 23:59:41">
irb(main):015:0> se.update(proxy_for_global_id: 'gid://scholars-archive/GraduateProject/1c18dk66p')
   (0.4ms)  BEGIN
  SQL (0.7ms)  UPDATE `sipity_entities` SET `proxy_for_global_id` = 'gid://scholars-archive/GraduateProject/1c18dk66p', `updated_at` = '2018-09-14 22:13:03' WHERE `sipity_entities`.`id` = 186802
   (1.0ms)  COMMIT
=> true
```
I'll run that on all changed items and also add it to the script that does `.update_index` on future changes.

**Comment by wickr** [comment]
This is complete on the 12 Honors College Theses that had been moved, marked on the 'SA Wrong worktypes' doc.

**Comment by wickr** [comment]
All of the rest of items that had been moved are now fixed, and have been marked as such on the spreadsheet.
