### ISSUE TITLE
Need to identify whether there is a standard for coordinate use in metadata

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#169]

**Comment by vantuyls** [comment]
Refers to #148

**Comment by wickr** [comment]
Do you mean like geoLocationPoint and geoLocationBox in the DataCite schema? Or something to use but map to those?

**Comment by vantuyls** [comment]
Yes! At least someone around here is paying attention. Thanks Ryan. 

As to implementation - use of these DataCite terms is dependent on the RDF implementation of DataCite, correct?

**Comment by wickr** [comment]
Yes. If they're doing the mapping/implementing that's great, presumably to W3C Geo or http://schema.org/GeoCoordinates, or similar. If they don't have immediate plans for that, we can use one of those.

**Comment by vantuyls** [comment]
Need to sort out how to deal with bounding boxes. @wickr, thoughts?

**Comment by vantuyls** [comment]
http://schema.org/GeoShape? this has been declared "not great" so maybe we can find something better?

**Comment by wickr** [comment]
This W3C Incubator Report recommends adding GeoRSS to W3C's 2003 Geo:  http://www.w3.org/2005/Incubator/geo/XGR-geo-20071023/

GeoRSS: http://www.georss.org/

There's also GeoJSON: http://geojson.org/geojson-spec.html

Those seem to be more comprehensive. Not seeing much in the way of namespaces or predicates yet but we can probably figure one out.

**Comment by vantuyls** [comment]
geojson seems more flexible, lets go with that.

**Comment by vantuyls** [comment]
Trey says this is fine use geoRSS but he has a smug look on his face because its the last day.

**Comment by vantuyls** [comment]
OKAY! Looks like we should use the GeoJSON spec for bounding boxes "bbox" - http://geojson.org/geojson-spec.html
