### ISSUE TITLE
Location service returning too much info for some locations

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1694]
### Descriptive summary

This is a bug that @simholt found which deals with the location portion of the form. Some locations are returning way too much location information, broader terms all the way out to "Earth" which is so unnecessary. We need to find out why these terms are returning so much information. 

https://ir.library.oregonstate.edu/concern/technical_reports/qv33s275m

### Expected behavior

When a location is put into the auto complete part of the location field and the form is saved, it should return only a few broader terms up to the country of origin. 

### Actual behavior

Some terms are returning all the way up to earth.

### Steps to reproduce the behavior

Create a new work
add all required info
go to geonames portion of form
input portland oregon
save the work
view the show page.

**Comment by simholt** [comment]
Can we do same fix as for OD2?

https://github.com/OregonDigital/OD2/issues/1124

May solve #1972 and #1970

**Comment by simholt** [comment]
I can't test how these resolve on the show page (that function is suppressed) but the versions listed on the edit page look good:

![Screen Shot 2020-07-21 at 1 26 52 PM](https://user-images.githubusercontent.com/33705514/88103533-ffa6c680-cb55-11ea-8824-069a79578428.png)

Actually, that's how they show up on the edit page on prod right now, so ... @luisgreg99 ? I couldn't find the ticket where we turned this off.

**Comment by luisgreg99** [comment]
@simholt Oh you might be referring to this ticket https://github.com/osulp/Scholars-Archive/issues/2018? This one made it to production at the beginning of the work cycle in our first deploy on Tuesday (July 7). I believe it's about sending Location field to the background for later processing (a minute later to be precise according to [scholars_archive_callbacks.rb#L2](https://github.com/osulp/Scholars-Archive/blob/77cf85d19d1559fbaa87d70debf5397120e87548/config/initializers/scholars_archive_callbacks.rb#L2)). 

To test this one, we start a new or existing work, enter Location values (including required fields), submit, then wait one minute once submission/update succeeds to start seeing the labels on the work page for Location:
![image](https://user-images.githubusercontent.com/3486120/88109632-b8bdce80-cb5f-11ea-9f1a-597ebb981015.png)

I think we could reduce the wait time for `FetchGraphWorker` job. @straleyb was there a reason for setting it to 1 minute?

**Comment by simholt** [comment]
@luisgreg99 Geonames locations are not showing on **any** items on production.

OKay wait -- Location under the limiters shows [one item](https://ir.library.oregonstate.edu/concern/graduate_projects/kp78gp53c) that was uploaded in June:

![Screen Shot 2020-07-21 at 2 59 39 PM](https://user-images.githubusercontent.com/33705514/88111488-d8a2c180-cb62-11ea-97e2-22a01e75439d.png)

I went to a [map item](https://ir.library.oregonstate.edu/concern/defaults/fq978111w) that I knew had Geonames info but nothing was listed for Location on the show page. I went to the edit page, saved it, and now the location shows up as a URL:
![Screen Shot 2020-07-21 at 3 06 58 PM](https://user-images.githubusercontent.com/33705514/88112016-ddb44080-cb63-11ea-9edd-ea0399584f0b.png)

- - -
_Back to staging_

GOOD: Locations showed up properly for me with a new item:
![Screen Shot 2020-07-21 at 3 00 49 PM](https://user-images.githubusercontent.com/33705514/88111594-10aa0480-cb63-11ea-823f-ee4b606d46d7.png)

NOT GOOD: I tried to add a second location to an item on staging (cr56n115b). The original location showed up fine after I went in and saved it but the one I added today is a URL:
![Screen Shot 2020-07-21 at 2 57 12 PM](https://user-images.githubusercontent.com/33705514/88111272-7ba70b80-cb62-11ea-8bb0-ac4d17f42725.png)

Maybe this is related to the issue on production with the Geonames URL showing up? Is this an indexing thing?

**Comment by luisgreg99** [comment]
@simholt Oh I see, that's a good catch! For cr56n115b it turns out the work has geoname URIs with both `http` and `https` schemas. The map item [fq978111w](https://ir.library.oregonstate.edu/concern/defaults/fq978111w) has a location with `http` schema in the URI. 

Only `https` schema works for geonames service as of last year if I remember correctly. This is a known issue we had in OD2: https://github.com/OregonDigital/OD2/issues/943 and https://github.com/OregonDigital/OD2/issues/963 in previous work cycles. I'll run a script to update location values on staging (instead of reindexing which would only work for works with locations already using `https`).

**Comment by luisgreg99** [comment]
@simholt this one is ready for testing on staging. The script just finished and updated locations like in [cr56n115b](https://ir-staging.library.oregonstate.edu/concern/articles/cr56n115b), replacing "http" with "https" to get the short labels for all values. Search and facets also got updated to support the new location labels.

**Comment by simholt** [comment]
QA pass!
