### ISSUE TITLE
Changing work from Default model to Article model causes error at old URL

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1696]
### Descriptive summary

One of the worktypes changes needed for some works is changing from the Default model to the Article model. This has been completed for over 3400 works, and seemed to be ok. However, the 'old' Default model access URL:
https://ir.library.oregonstate.edu/concern/defaults/qv33rx600

throws an error: ```ActionView::Template::Error (undefined method `has_journal' for #<DefaultPresenter:0x00007f0200337648>):```

because the Default presenter doesn't know about `has_journal` now that the work is an Article. 

So anyone with the old link (which we used to say was the Citeable URL) or coming from search engines will now get the 'Ack SA is temporarily broken' error instead of any type of work show page.

This is another downside of having the work's model/type in the URL, and Hyrax allowing any valid presenter to try and display a work. ( https://ir.library.oregonstate.edu/concern/purchased_e_resources/qv33rx600 works ok because it includes article metadata and presenter, while https://ir.library.oregonstate.edu/concern/undergraduate_thesis_or_projects/qv33rx600  does not and also errors). 

Possible solutions are adding the Article-specific properties to the Default model so the error goes away and the work is viewable, or putting in another redirect system that will redirect the old, Default model URL to the new Article URL for any work changed. (That solution could also potentially work for #1378)

### Expected behavior
The Default model URL should still present the work and not error: https://ir.library.oregonstate.edu/concern/defaults/qv33rx600

### Actual behavior
When visiting the Default model URL after worktype change, get error "Ack! Looks like ScholarsArchive@OSU is temporarily broken."

**Comment by luisgreg99** [comment]
@wickr I think adding the article-specific properties to the Default model would be a quick fix for this case, but I agree that it would be nice to have a redirect system so that it can take care of duplicates as well. 
For the first possible solution, were you thinking on only adding and this include https://github.com/osulp/Scholars-Archive/blob/master/app/models/article.rb#L5 in https://github.com/osulp/Scholars-Archive/blob/master/app/models/default.rb?

**Comment by wickr** [comment]
@luisgreg99 yeah, I think that would do it along with the presenter. The downside being that this is only a fix for this specific change and wouldn't cover other model changes. And this also diminishes why we made separate models in the first place, if we basically merge them when needed.

**Comment by revgum** [comment]
@wickr What if a before_action filter was added to ScholarsArchive::WorksControllerBehavior which checks, only on #show, that the curation_concern model type is matching the appropriate controller and redirects to the appropriate route if it isn't matching properly?

**Comment by vantuyls** [comment]
I'm not sure what the best approach here is, but @wickr's comment about merging these properties in to the generic model is a good one. Why have different models if we just merge them all in the end? Is a redirect possible? Or @revgum's approach?

**Comment by vantuyls** [comment]
we also ought to consider tombstoning. UNC built out some tombstone functionality on hyrax that we maybe could look at.
