### ISSUE TITLE
Alternative Title appears to be non-searchable

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1698]
### Descriptive summary

Searches on known contents in Alternative Title appear not to work. The MAP shows Alt Title as searchable. Can someone check to ensure that this field is searchable and, if not, rectify?

### Expected behavior
Searches for known content in searchable field should return search results. 

1. Search for "4-H 1009"  
2. See no results

**Comment by simholt** [comment]
Example item with alt title 4-H 130R:
http://ir.library.oregonstate.edu/concern/administrative_report_or_publications/5712mc53f

**Comment by wickr** [comment]
It looks like it's not included in the 'All Fields' search: https://github.com/osulp/Scholars-Archive/blob/master/app/controllers/catalog_controller.rb#L200

I can get that added shortly.
