### ISSUE TITLE
Bulk populating of collections - Batch One

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1717]
Collections are created and ready to be populated. 

- [x] [Bioresource Research](https://docs.google.com/spreadsheets/d/1aploCeJUcTK_xC3wU1X9u1ix9l2KVkYQFEMXoNDGhpg/edit#gid=0)
- [x] [Celebration of Undergrad Excellence](https://docs.google.com/spreadsheets/d/1L9i6c4TwgIuq1WBgnEcFimGdu5zJHwHSeuW0iBFmRME/edit#gid=0)
- [x] [Engineering Experiment Station](https://docs.google.com/spreadsheets/d/1ZxaDWEbL7ihbZe_IzmMQElKATQ3tBl1A5IBo1UE75fE/edit#gid=0)
- [x] [Graduate Theses & Dissertations](https://docs.google.com/spreadsheets/d/116FSG6IY0PflRsRIuks96sYlOPqv6IkDdj_vfnPjqpM/edit#gid=597517396)
- [x] [Hatfield Marine Science Center](https://docs.google.com/spreadsheets/d/1zlTfgRSAgZkofnE8vpeqD1QEbxS68e5mi_YF_H8sT-4/edit#gid=0)
- [x] [Honors College Theses](https://docs.google.com/spreadsheets/d/16r4a2vl0QthZsded8Y5qekMGvokY2l-0_5zBkzuM2iw/edit#gid=268100634)
- [x] [Institute for Natural Resources](https://docs.google.com/spreadsheets/d/16GESd2hI8koQqmcSRjOfqhoWKzqar6Gmj66SFBkZYEA/edit#gid=0)
- [x] [Oregon Dept of Fish & Wildlife](https://docs.google.com/spreadsheets/d/1MA5Q-6jDSP_Z6CrAsxnRqk-2m9iVJv94rryctSGnBvI/edit#gid=0)
- [x] [Oregon Explorer](https://docs.google.com/spreadsheets/d/1NxXbZeOHvazcxB09LIQHoU2N3LWBtEN3-ocNOaAphxo/edit#gid=0)
- [x] [Oregon Sea Grant](https://docs.google.com/spreadsheets/d/1FVOsDHTpVoCjJjk9p7wu3EgcWvuSLyU3u3nbF5376wI/edit#gid=0)
- [x] [Oregon Wine Research Institute](https://docs.google.com/spreadsheets/d/1B_ivyfE5cNptya96zHZ72Lhi25k4VS148cK40vvFK1Y/edit#gid=0)
- [x] [President's Office](https://docs.google.com/spreadsheets/d/1ftrUMymCoAgPBvLblqAboionwQX0drlSBcyr5rtsFMw/edit#gid=0)
- [x] [Registrar's Office](https://docs.google.com/spreadsheets/d/1G1zuKszo2hrJYYs8gyiUWOYl4CgHqACp7optW3C-hRM/edit#gid=0)
- [x] [Rural Studies Program](https://docs.google.com/spreadsheets/d/1BwuKqruRCkbN-tslkRBgptk3uAyFquFzP6M5Yh2jsFw/edit#gid=0)
- [x] [Undergrad Research Scholarship etc](https://docs.google.com/spreadsheets/d/1jkUKGt92mcgy9Ng2ouUvHutV3oEJg0daiR1HHCMmRuc/edit#gid=0)
- [x] [University Libraries](https://docs.google.com/spreadsheets/d/1AvMF6DIQT2nhxB2Zk3uKuIUQeR9EfizmXJJ61OdlkEk/edit#gid=0)
- [x] [Writing Intensive Curriculum](https://docs.google.com/spreadsheets/d/1ZiErn8vsNiI88KzOic0K_skBDD2qiyNzHROZSvauP2U/edit#gid=0)

**Comment by revgum** [comment]
completed!
