### ISSUE TITLE
Verify migrated works

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1721]
### Descriptive summary

Query SOLR to see if there are any works that do not have ordered creator (to verify that the migration has occurred). Address any outliers if we find them.

**Comment by luisgreg99** [comment]
Solr queries for ordered fields migration:

	1. Solr query to find existing works with handles that have pending ordered fields migration:

```
"params":{ 
  "q":"-nested_ordered_creator_tesim:[* TO *] AND -has_model_ssim:FileSet AND creator_tesim:[* TO *] AND replaces_tesim:[* TO *]",
  "fl":"id, creator_tesim, has_model_ssim, replaces_tesim, date_uploaded_dtsi"
} 
```
Solr Response:
```
"response":{"numFound":19,"start":0,"docs":[…
```

These are my findings for the 19 handles:

Handles not found in the given `dspace_creator_ordered.csv` (15 handles):
```
1957/33606
1957/19625
1957/19730
1957/19752
1957/8067
1957/60857
1957/61113
1957/61447
1957/61413
1957/60870
1957/5131
1957/3034
1957/5066
1957/23313
1957/51636
```

@zhang4952  can we get the order info for the handles above? The last one `1957/23313` might be a version of `1957/23313.1`, which we have in `dspace_creator_ordered.csv`: 

```
46179:"27,603",9,Oregon State University. Extension Service,1,1957/23313.1
```

@zhang4952 can you confirm that this is the matching entry?

Missed or failed to process 3 handles (will investigate more, but we can start by trying in-place migration if possible):

```
1957/49896
1957/26066
1957/26184
```

Invalid or unknown handle:

```
UMI Number: 3395263
```

This one comes from the following work, which looks like it was not migrated from dspace, but it has a value in `replaces_tesim`:

```
"has_model_ssim":["PurchasedEResource"], "id":"8c97kw49p", "date_uploaded_dtsi":"2018-09-17T21:55:44Z", "creator_tesim":["Rich, Wesley Dowless"], "replaces_tesim":["UMI Number: 3395263"]},
```

Will investigate more about this work.

	2. Solr query to find existing works with no handles and have pending ordered fields migration:

```
"params":{ 
  "q":"-nested_ordered_creator_tesim:[* TO *] AND -has_model_ssim:FileSet AND creator_tesim:[* TO *] AND -replaces_tesim:[* TO *]",
  "fl":"id, creator_tesim, has_model_ssim, replaces_tesim, date_uploaded_dtsi"
} 
```

Solr response:
```
"response":{"numFound":539,"start":0,"docs":[…
```

For these works, I think we can just run the rake task again to finish migrating the remaining 539 works @gumj

**Comment by zhang4952** [comment]
@luisgreg99 Verify the 15 items in your list, all of them do not have `creator` in DSpace. It looks like `creator` is not a required filed in DSpace.
1957/33606
1957/19625
1957/19730
1957/19752
1957/8067
1957/60857
1957/61113
1957/61447
1957/61413
1957/60870
1957/5131
1957/3034
1957/5066
1957/51636
1957/23313

**Comment by luisgreg99** [comment]
@zhang4952 Sounds good, I retrieved what we have in `creator_tesim` for those works and created a `creator_missing_order_from_dspace.csv` that we can use to migrate ordered fields for those works: https://docs.google.com/spreadsheets/d/13KT0IpDcjzqJu_IC3kLO_smaFpqzN2csRp_21i4Gz0c/edit?usp=sharing

Most of the works have only one creator, so I set the `place` to be `1`.

The only one with multiple creators was `1957/60857`, but I looked at the bitstream and defaulted to the order as listed in the pdf for that one: http://dspace-ir.library.oregonstate.edu/xmlui/bitstream/handle/1957/60857/Flight%20capabilities%20of%20Drosophila%20suzukii.pdf?sequence=1 What do you think about this one?

**Comment by luisgreg99** [comment]
Update: It looks like the in-place-migration worked well to resolve/migrate most of the pending works with handles, so we are now down to 6 works instead of 19:

http://hdl.handle.net/1957/49896
http://hdl.handle.net/1957/19752
http://hdl.handle.net/1957/26066  
http://hdl.handle.net/1957/19730
http://hdl.handle.net/1957/26184
UMI Number: 3395263

**Comment by luisgreg99** [comment]
http://hdl.handle.net/1957/26184 has been fixed and migrated successfully. It also failed due to invalid URI in `degree_grantors`: `Oregon State Agricultural College` instead of http://id.loc.gov/authorities/names/n87850581

**Comment by luisgreg99** [comment]
http://hdl.handle.net/1957/19752, http://hdl.handle.net/1957/19730, and `UMI Number: 3395263` have been fixed. It turns out that in-place migration didn't work for these because `migrate_work_in_place` was missing in `purchase_e_resource_works_controller_behavior.rb`. They got fixed by running `Migrator.has_migrated?(work: p)` in the command line.

**Comment by luisgreg99** [comment]
http://hdl.handle.net/1957/49896 has been migrated successfully. @wickr suggested that we use http://id.loc.gov/authorities/names/n82022628 (Oregon State College) for `degree_grantors` (previously we had `Oregon State College in Electrical Engineering`) in `1957/49896`.

**Comment by luisgreg99** [comment]
While debugging, I came across a small list of works that were partially migrated (title and abstract were migrated but not additional_information, contributor, and creator):
```
-nested_ordered_creator_tesim:http* AND nested_ordered_creator_tesim:[* TO *] AND -nested_ordered_additional_information_tesim:http* AND nested_ordered_additional_information_tesim:[* TO *] AND -has_model_ssim:FileSet AND replaces_tesim:[* TO *]
```

- [ ] TechnicalReport `id:7s75dh53f`
- [ ] AdministrativeReportOrPublication `id: 5d86p135d`
- [ ] Default `id: rn301529j`
- [ ] TechnicalReport `id: hq37vt243`
- [ ] AdministrativeReportOrPublication `id: 37720d800`
- [ ] Default `id: gm80j0280`

**Comment by luisgreg99** [comment]
Just finished running `bundle exec rails scholars_archive:migrate_ordered_metadata`. It successfully migrated 536 out of 539 works remaining. Only 3 works (with no handles) failed to migrate:

- [ ] `hm50tx574`
- [ ] `rr1723298`
- [ ] `pk02cg40w`

I tried in-place migration, but it didn't work for these. I will try doing the migration via the rails console.

**Comment by luisgreg99** [comment]
Works `rr1723298 `, `hm50tx574` and `pk02cg40w` have been migrated successfully. 

`hm50tx574` and `pk02cg40w` were failing due to invalid format in graduation year: 
```
ActiveFedora::RecordInvalid (Validation failed: Graduation year Invalid value. Please ensure a year is used in this field (e.g 1908))
```
Both have a trailing space in the year.

`rr1723298` was failing due to missing the label in an existing related item:
```
ActiveFedora::RecordInvalid (Validation failed: Related items One or more items are missing label/related url values. Please provide both label and url values for each related item entered.)
``` 
I fixed it by setting the label as the url to resolve the validation error. This can be updated with a proper label in the edit form.

**Comment by luisgreg99** [comment]
fixed by https://github.com/osulp/Scholars-Archive/pull/1729
