### ISSUE TITLE
Ask Google to crawl the site

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1722]
### Descriptive summary

Here's a link to make the request: https://support.google.com/webmasters/answer/6065812?hl=en

**Comment by wickr** [comment]
I logged in to Google Search Console and resubmitted our Sitemap file.

The date under the 'Coverage' section says 10/12/18 right now.

**Comment by luisgreg99** [comment]
@wickr is there a way to check the progress in Google Search Console?

I checked out this dataset https://ir.library.oregonstate.edu/concern/datasets/n009w621c in Google Scholars: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C38&q=Remarkable+solar+panels+Influence+on+soil+moisture%2C+micrometeorology+and+water-use+efficiency+-+database.+&btnG= 
![image](https://user-images.githubusercontent.com/3486120/47309620-c2f91480-d5e9-11e8-88f1-29e1eb76ebb0.png)

and it looks like the metadata for the first entry is based on the `Cached` version from Hyrax 2.0.0, which still lists the old order for the `Creator` field:
https://scholar.googleusercontent.com/scholar?q=cache:RQ8gzCWf_vMJ:scholar.google.com/+Remarkable+solar+panels+Influence+on+soil+moisture,+micrometeorology+and+water-use+efficiency+-+database.+&hl=en&as_sdt=0,38

**Comment by wickr** [comment]
Sort of. The URLs in the Sitemap are found, and I checked ("URL Inspection") on this one, it was indexed, but I requested it to be indexed again. No guarantee when Google Scholar would pick up the changes.

**Comment by wickr** [comment]
https://scholar.google.com/intl/en/scholar/inclusion.html#troubleshooting  says:
"Keep in mind that, since these papers are already included in Google Scholar, updating their bibliographic data will usually take 6-9 months from the time you provide it on your website."

**Comment by wickr** [comment]
Related to #1916 

Closing due to recent discussions with Google Scholar and related changes.
