### ISSUE TITLE
Collection description metadata not appearing on the Collection landing page

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1735]
### Descriptive summary

When one adds metadata in the Collection Description field for a Collection, the description doesn't appear on the showpage for the collection. This works on Nurax, so it seems to be something we did. 

### Expected behavior
metadata added to a collection shoudl appear on the collection showpage (unless we say not to show it in config somewhere)

### Actual behavior
metadata does not appear on collection showpage

**Comment by simholt** [comment]
Looks good!

![screen shot 2018-11-02 at 12 15 54 pm](https://user-images.githubusercontent.com/33705514/47935870-19433e80-de99-11e8-8d3c-d535d8edb815.png)
