### ISSUE TITLE
Cannot add items to collection manually/individually

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1739]
### Expected behavior
Using the button on an item's show page OR the Relationships tab in an item's edit page, should be able to add an item to a collection by typing the name of the collection in the search box. This worked two weeks ago.

### Actual behavior
No matter what I type, no collections are returned in the search.

![screen shot 2018-10-30 at 2 54 37 pm](https://user-images.githubusercontent.com/33705514/47753132-c0cf2f80-dc53-11e8-87a5-b0e445c1cd79.png)

### Steps to reproduce the behavior
Choose any item and attempt to add it to a collection, such as Pacific Northwest Insect Management Conference.

**Comment by simholt** [comment]
(Is not working on staging, either.)

**Comment by straleyb** [comment]
Similarly, going to a Collections "Show page" and clicking "deposit new work through this collection" and creating a valid work, still does not save the work to the collection.

**Comment by simholt** [comment]
Can now add an item to a collection in these ways:
- from the edit page using the relationships tab, when making new works and editing existing ones
- add existing item from collection's admin page
- add existing item using the button on the item's show page

If you select "Deposit new work through this collection" on a collections admin page, it does not get automatically added to the collection; you have to select it in the relationships tab. QA cleared for my original issues --- I will write up a separate ticket for this.
