### ISSUE TITLE
sorting and views for search results are busted in collection views

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1742]
### Descriptive summary
when viewing a collection, the following issues emerge:
- [ ] sorting by title or dates is not sorting anything (always returns the same result) Sorting by date uploaded works
- [ ] mosaic and tile view do not properly label the collection (the collection ID is listed, not the title)
- [ ] video/slideshow view should be suppressed

### Expected behavior
- [ ] sorting should sort as expected
- [ ] views should have Title for the collection label if no other information shows (as in mosaic and tile views)

**Comment by CGillen** [comment]
@simholt Sorting doesn't seem to be an issue anymore, can you confirm? I suspect we still want to suppress the slideshow view. If I do that can we call this ticket done?

**Comment by CGillen** [comment]
Slideshow also doesn't work on regular search I'm going to suppress that too
