### ISSUE TITLE
Banner images for collections not persisting

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1744]
### Descriptive summary
Banner images I save to the edit pages of collections disappear the next day (I don't have a more specific time frame).

### Expected behavior
**A banner image saved to the edit page:**
![screen shot 2018-10-31 at 1 57 46 pm](https://user-images.githubusercontent.com/33705514/47818281-f720b380-dd14-11e8-840d-047ec014210a.png)

**Banner image on the collections show page:**
![screen shot 2018-10-31 at 1 56 06 pm](https://user-images.githubusercontent.com/33705514/47818234-d193aa00-dd14-11e8-94bf-c799a9be1f43.png)
  
### Actual behavior
**Error message on collections edit page:**
![screen shot 2018-10-31 at 1 38 31 pm](https://user-images.githubusercontent.com/33705514/47818009-4fa38100-dd14-11e8-9f40-54a85a66afae.png)

**Banner missing on collections show page:**
![screen shot 2018-10-31 at 1 52 50 pm](https://user-images.githubusercontent.com/33705514/47818001-4c0ffa00-dd14-11e8-8ee1-bfc41a172fd8.png)

### Steps to reproduce the behavior
1. Go to the edit page of a collection. Click the branding tab.
2. Upload and save a banner image. 
3. Wait.

**Comment by wickr** [comment]
For the Oregon Sea Grant, I see a file in the collection branding folder:
`911813 Oct 17 14:05 DSC_3407.JPG`

but not the file the HTML is referencing: `https://ir.library.oregonstate.edu/branding/5h73q236r/banner/skinny_banner1.jpg`

**Comment by vantuyls** [comment]
Nurax issue related: https://github.com/curationexperts/nurax/issues/187

@luisgreg99 can you drop a note in that issue indicating that we saw the same issues due to configuration and ask whether thats why we're seeing it on Nurax?

**Comment by luisgreg99** [comment]
Yes, I found out that there is a config for the branding_path used for the banner https://github.com/samvera/hyrax/blob/v2.3.0/lib/hyrax/configuration.rb#L66

Right now it defaults to the current release directory, which gets deleted after the 5th revision.

**Comment by revgum** [comment]
@luisgreg99 @vantuyls our branding image directory is symlinked during deployment to the `shared/public/branding` so the image files persist between deployments.

**Comment by revgum** [comment]
If there are other banners that are missing, we can fetch those. Can someone, please, verify if they are all present now or not? @vantuyls @simholt 

I tested the banner image upload on a new collection and it's working as expected, this ticket should be fully addressed now.

**Comment by simholt** [comment]
@revgum  Some are missing - is it easier for me to reupload them? (would be easier for me)

**Comment by revgum** [comment]
@simholt It's totally up to you.. you can re-upload them or list the collection ID's that are missing the images.

**Comment by simholt** [comment]
All good!
