### ISSUE TITLE
Bottom Review & Approval bar ineffective

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1749]
### Descriptive summary
So there are two Review/Approval bars on item show pages, one at the top, another at the bottom. Clicking the bottom Review/Approval bar is supposed to send the user to the open top bar for action but it does not scroll the screen up all the way up.

I'm not sure if we need Review/Approval at the top and bottom of the screen.

**Options**:
- One functional bar at top.
- One functional bar at bottom.
- Both bars, but clicking on either opens an action window.
- Both bars, but clicking on either send the user to the open action one.

### Steps to reproduce the behavior
1. Go to a [document](https://ir.library.oregonstate.edu/concern/defaults/fn107338m?locale=en), scroll down, click the Review/Approval bar.
2. Scroll all the way up to view the open bar.

**Comment by simholt** [comment]
@straleyb Looks like there's no bottom review bar in Nurax (2.4). I know we are running 2.3 but can you figure out if having one is a glitch on our end?

**Comment by vantuyls** [comment]
stock Hyrax now has no review panel at the bottom of the work showpage. please implement as such.
