### ISSUE TITLE
Make depositor viewable by admin on show pages

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1750]
It would be very helpful if the depositor was a viewable field on show pages for admin.

**Comment by simholt** [comment]
@straleyb Can you deploy this to staging so I can QA it?

**Comment by revgum** [comment]
@straleyb I tested this locally, and wasn't logged in, and it failed `undefined method `admin?' for nil:NilClass` because current_user was nil. This could be fixed with the lonely-operator `current_user&.admin?`
