### ISSUE TITLE
Hide some Collection metadata fields

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1751]
### Descriptive summary

some of the metadata fields on collections are not useful in our context. suppressing them is the best way forward. 
Including:
- [x] keyword
- [x] license
- [x] publisher
- [x] identifier
- [x] resource type

**Comment by vantuyls** [comment]
@straleyb can you update me on the status of this issue? looks liek some of this is done and merged, but not that last check box?

**Comment by lamtu1** [comment]
@straleyb I was wondering on this ticket, the metadata on `nested URL` should it be remove or included to finish the last task on this ticket? if implemented, I see when creating a collection, we do have the `related URL` under the `additional field`. If not, I can go ahead modify the `collection_form.rb` to have the `nested URL` remove.

**Comment by straleyb** [comment]
@lamtu1 I would double check with cara/sarah on what they think for this ticket. Its been so long since its been looked at, double checking the requirements will help with whatever work needs to be done.

**Comment by lamtu1** [comment]
Hi @simholt and @carakey, I was wondering if one of you can double check on this requirement ticket to see if the collection for `nested URL` needed or need to be remove when you get a chance? Thank you

**Comment by simholt** [comment]
@lamtu1 Nested related URLs are not in collections right now, so I think this part of the ticket was to ask for them to be set up. I can write up a new ticket if you like. 

Currently:
<img width="461" alt="Screenshot 2023-10-19 at 8 59 11 AM" src="https://github.com/osulp/Scholars-Archive/assets/33705514/1f58ea11-7132-47a1-ae05-c1b7db651957">

I would like them! I don't use the plain related URL field since it looks ugly and instead do links in the description text box.

**Comment by lamtu1** [comment]
> @lamtu1 Nested related URLs are not in collections right now, so I think this part of the ticket was to ask for them to be set up. I can write up a new ticket if you like.
> 
> Currently: <img alt="Screenshot 2023-10-19 at 8 59 11 AM" width="461" src="https://user-images.githubusercontent.com/33705514/276677975-1f58ea11-7132-47a1-ae05-c1b7db651957.png">
> 
> I would like them! I don't use the plain related URL field since it looks ugly and instead do links in the description text box.

That would be great to have a separate ticket for this and we can link it up to this ticket or mention it.

**Comment by carakey** [comment]
@simholt Does the newer ticket (2539) mean this one can be closed? It's not clear to me what else this one still needs.

**Comment by simholt** [comment]
Yes close away!

**Comment by carakey** [comment]
Remaining item should be resolved within #2539
