### ISSUE TITLE
Enforce check of deprecated ONS terms

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1759]
### Descriptive summary
I cleaned up some old and wrong MAIS degree fields ([example](http://opaquenamespace.org/ns/osuDegreeFields/cnkjcX55)). @wickr deprecated them but they are still showing up in the drop downs. Deprecated terms in ONS should not show up as options.

### Expected behavior
When a term is deprecated in ONS, the system should recognize it and remove it from the list of options so it cannot be used.

### Actual behavior
Deprecated terms show up in drop down.

**Comment by straleyb** [comment]
@wickr If I can get a list of the deprecated terms, It would be easier for me to nail down where the error is coming from and fix it.

**Comment by wickr** [comment]
The DegreeFieldsParser needs to check for the existence of a deprecated value. This will be shown by a value (URI) in the is_replaced_by field. 

Example deprecated term: http://opaquenamespace.org/ns/osuDegreeFields/cnkjcX55
JSON-LD version shows: 
```dc:isReplacedBy": "http://opaquenamespace.org/ns/osuDegreeFields",```

**Comment by wickr** [comment]
I confirmed with Sarah, that at least for Degree Fields, those that have been deprecated are not just 'old' values but should not have been assigned in the first place. Deprecated items can be removed from the degree field list entirely (instead of just marking them 'inactive').

**Comment by simholt** [comment]
QA pass!
