### ISSUE TITLE
Update indexing of nested search fields

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1763]
### Descriptive summary

We want all titles for a work to be indexed in `title_tesim` without any ordering index information. Ensure this continues to be updated on any new edits. This is also where titles for Collections and FileSets are already being indexed.

```
"title_tesim":["Restoring forest health : fire and thinning effects on mixed-conifer forests"],
```

Titles with ordering index can continue to be stored in the `nested_ordered_title_label_ssim` stored field for display and edit form purposes.

```
"nested_ordered_title_label_ssim":["Restoring forest health : fire and thinning effects on mixed-conifer forests$0"],
```

We don't need the ordering information in `nested_ordered_title_label_tesim` as that is tokenized and split for search, so '$0' and '$1' etc. aren't useful.
Also this field can be removed from the 'all fields' search field.

```
"nested_ordered_title_label_tesim":["Restoring forest health : fire and thinning effects on mixed-conifer forests"],
```

When this is merged we'll need to reindex.

### Related work

Related to #1758 adding `title_tesim` back in to the 'all fields' search field.

**Comment by simholt** [comment]
@CGillen Need help/instruction on QA for this one.
