### ISSUE TITLE
Bulk populating of collections - Batch Two

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1770]
More collections are created and ready to be populated. These are smaller collections.

[Spreadsheet with tabs.](https://docs.google.com/spreadsheets/d/18jI5peNDFWUYzhDJvaC2dAKi-0DJFIdeV6V_2ZXMaDo/edit?usp=sharing)

- [x] NAAFE Forum 2015
- [x] NAAFE Forum 2017
- [x] 8th IIFET
- [x] 10th IIFET
- [x] 11th IIFET
- [x] 12th IIFET
- [x] 13th IIFET
- [x] 14th IIFET
- [x] 15th IIFET
- [x] 16th IIFET
- [x] 17th IIFET
- [x] 18th IIFET

AND
- [x] [Dissertations](https://docs.google.com/spreadsheets/d/116FSG6IY0PflRsRIuks96sYlOPqv6IkDdj_vfnPjqpM/edit?usp=sharing)

**Comment by revgum** [comment]
Dissertations are running in the background, they may finish overnight.
