### ISSUE TITLE
Bulk Edits: Articles

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1771]
Bulk edits to clear up in_series metadata from migration.

Batch 1:
https://docs.google.com/spreadsheets/d/1-u1bJRnynAmgr08cHjlMqygEpN09EBACCzLx2SAZCro/edit?usp=sharing

- [x] has_journal
- [x] has_volume
- [x] has_number
- [x] in_series

Batch 2:
https://docs.google.com/spreadsheets/d/1aYloWAeFT_NhTkfY3uokzJNLvIYgnaG4EQie3Bp1k90/edit?usp=sharing

- [x] has_journal
- [x] has_volume
- [x] has_number
- [x] in_series

**Comment by revgum** [comment]
Done
