### ISSUE TITLE
Order in ordered fields not maintained over 10 terms

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1773]
### Descriptive summary
When editing creator fields, I noticed that the order was not saved when there were more than 10 terms listed. 

<img width="266" alt="screen shot 2018-11-30 at 2 48 21 pm" src="https://user-images.githubusercontent.com/33705514/49461274-201ae500-f7a8-11e8-9c05-12dbbe9cf375.png">

<img width="279" alt="screen shot 2018-11-30 at 2 48 44 pm" src="https://user-images.githubusercontent.com/33705514/49395103-7295cc00-f6ea-11e8-8309-37b6c5cb3e18.png">

Ordered fields should not be saved lexigraphically.

### Steps to reproduce the behavior

1. Upload item.
2. Enter 10 terms in an ordered field such as creator.
3. Save item.
4. Order looks good.
5. Edit and add more terms.
6. Order lost.

**Comment by vantuyls** [comment]
can confirm that ordering is lost for 10 or 12 creators but not for 6

**Comment by simholt** [comment]
Looks good!

![screen shot 2018-12-05 at 8 16 02 am](https://user-images.githubusercontent.com/33705514/49527204-3e471a80-f866-11e8-81d0-1e10127ec5cb.png)
