### ISSUE TITLE
Make the remove buttons on edit page uniform

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1777]
### Descriptive summary
Most fields use the Remove text but the nested fields use a trash can button. These should all be the same.
- - -
**Standard fields:**
![remove words](https://user-images.githubusercontent.com/33705514/49479352-88cd8600-f7d7-11e8-931f-c6ca802dfaaf.png)
**Nested fields:**
![remove trash cans](https://user-images.githubusercontent.com/33705514/49479356-8b2fe000-f7d7-11e8-9fa9-77303a18d3f0.png)

- I think the trash can buttons look better. Opinion, @vantuyls?

**Comment by vantuyls** [comment]
remove all text and replace with trash can. always aligned under the Remove header if it exists.

**Comment by straleyb** [comment]
This is going to be extremely tough to get the remove buttons to be the trash cans instead. These buttons are injected using JavaScript which is built in to hyrax. To get those in would be larger system changes to process the es6 and would be a heavy handed approach. Instead, ill replace the trash cans with the remove text instead. Down the road, we can make a decision about if we want to replace the default hyrax based remove buttons.
