### ISSUE TITLE
users should be able to reorder repeated input form fields

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#178]
if a user enters repeatable fields in the wrong order (e.g. wrong author order) they should be able to reorder them in the input form without deleting and re-inputting names

**Comment by wickr** [comment]
I agree with this overall but can we currently guarantee order of repeated elements at all stages?

**Comment by terrellt** [comment]
Oh geez.

**Comment by vantuyls** [comment]
I LOLed Out Loud

**Comment by terrellt** [comment]
There's a bigger decision here: Does the metadata need to contain ordering (a computer can know this person is first author), or does the view just have to display authors in order?

**Comment by vantuyls** [comment]
A couple of considerations (not in order of importance):
1) Automatically building a citation will require that some things (e.g. authors) be in correct order
2) How are things like Subjects ordered in display without there being order? Alphabetically? Is that what we want?
3) Does anyone recall what the Google Scholar people say about author ordering and how it may or may not affect indexing?

**Comment by terrellt** [comment]
1) is the same as a view concern to me.
2) By order of entry.
3) No clue - if I were to guess, probably by order in the DOM?

Better metadata would be ordered RDF for authors - order matters to the profession (right?) and that's what ordered authors would do.

That being said, you don't get anything technical from it that I can think of.

**Comment by vantuyls** [comment]
1) Wha? 
2) If you're ordering by order of entry doesn't that imply that you're keeping the order in the same way we want to keep the order of authors?
3) meh.

Yes, order matters to the profession (both the library people and the researchers themselves). 

The only technical thing i think you might get is better indexing in google scholar, but I could be misremembering the coversation by GS dude at Open Repos.

**Comment by vantuyls** [comment]
"the system needs a whole lot more work before this is do-able" - Ryan Wick
@wickr
