### ISSUE TITLE
Fix predicate for :conference_section

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1781]
### Descriptive summary

The predicate for `conference_section` got changed and needs to be corrected (`...w2id.org...` should be `...w3id.org...`)

Not sure how it got changed, but it was by me when the conference predicates were moved to default metadata: https://github.com/osulp/Scholars-Archive/commit/c7f60452509ca3184cd1111715e67eadfd2d5c91#diff-1e841b2558a016e0f500e5866610cb70R42

Works with the old predicate will not have that data show up if edited and saved or reindexed.

### Expected behavior

`conference_section` predicate is `https://w3id.org/scholarlydata/ontology/conference-ontology.owl#Track`

### Actual behavior
`conference_section` predicate is `https://w2id.org/scholarlydata/ontology/conference-ontology.owl#Track`

### Related work

#1782 - Replace predicate on all works needed

**Comment by straleyb** [comment]
Relates #1862

**Comment by CGillen** [comment]
QA Pass:
https://ir-staging.library.oregonstate.edu/concern/conference_proceedings_or_journals/3x816m79v?locale=en had w2id value and it transfered to w3id no problem
