### ISSUE TITLE
Replace conference_section predicate on all works needed

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1782]
### Descriptive summary

Once #1781 is completed, find all works with the old, wrong predicate for conference_section: `https://w2id.org/scholarlydata/ontology/conference-ontology.owl#Track`

Can't rely on just Solr.

Replace with correct predicate on those works and save.

### Related work

#1781

**Comment by straleyb** [comment]
Relates #1861

**Comment by CGillen** [comment]
Rake task ran, works updated
