### ISSUE TITLE
Bulk Edits: Empty strings

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1797]
### Descriptive summary
Bulk edits to clear up empty strings that create blank facets or otherwise need cleanup.

Some are on the small side but the empty string is in a required field so I can't fix it via the edit page.

These are all on the same spreadsheet -- links to tabs below:

- [x] [conference_name](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=0&range=A1)
- [x] [conference_section](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=1745423512&range=A1)
- [x] [date_accepted](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=149217171&range=A2)
- [x] [date_available](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=1418507572&range=A1)
- [x] [date_copyright](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=1306054180&range=A1)
- [x] [date_issued](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=1351397449&range=A1)
- [x] [date_valid](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=1279548648&range=A1)
- [x] [degree_level](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=352527799&range=A1)
- [x] [degree_name](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=834047024&range=A1)
- [x] [doi](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=412653724&range=A1)
- [x] [graduation_year](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=2139481234&range=A1)
- [x] [has_journal](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=410089659&range=A1)
- [x] [on_behalf_of](https://docs.google.com/spreadsheets/d/1Of6tEZF66TNmWUSLfsEU37XoGEXLNmFEQt8BvVicr2s/edit#gid=1166697407&range=A1)

**Comment by revgum** [comment]
`date_accepted`, `date_available`, and `date_copyright` were run today with copyright due to finish after I leave for the day

**Comment by revgum** [comment]
`on_behalf_of` was started and should finish tonight as well

**Comment by revgum** [comment]
`has_journal` is running.

There are two files left to process, `combined` has `date_issued, date_valid, degree_level, degree_name, and graduation_year` combined (totalling 122 rows), and `doi` has ~2600 rows. Should be able to have these done today.

```
SA Bulk edits_ Empty Strings - combined.csv
SA Bulk edits_ Empty Strings - doi_sim.csv
```

**Comment by revgum** [comment]
`conference_name` and `conference_section` are running this morning

**Comment by revgum** [comment]
`on_behalf_of` (6300 rows) is running through today

**Comment by revgum** [comment]
This was finished in March, closing the ticket.
