### ISSUE TITLE
Geographic coordinates section needs clarification

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1799]
### Descriptive summary
The Geographic coordinates section does not act like other fields. It needs clarification and cleanup.

1. Additional entries for all three formats (bounding boxes, geographic points, location) can be added without filling fields. (Instead of showing the "cannot add another with empty field" note.)
2. Once you've chosen a geographic coordinate type from the drop down menu, that choice disappears from the menu and the type is on the page permanently.
3. Trash can under Remove and separate Remove buttons for each entry is confusing. **Question**: What is the preferred performance here?
- - - 
![geo](https://user-images.githubusercontent.com/33705514/51775982-5855ea00-20ac-11e9-85af-8c9f5e8a904b.png)
- - - 

### Related work
Delete vs trash can buttons: #1777

**Comment by vantuyls** [comment]
per comment on #1777, these should all be trashcan icons. 

also, to answer the above question: the only removal behavior should be for removing an individual element. there should be no behavior for removing an entire block of elements.

**Comment by simholt** [comment]
To clarify:

- [ ] the ❌ Remove text by the bounding boxes should be trash can icons
- [ ] the word REMOVE and existing trashcan icons for the block of location elements should be taken out

<img width="551" alt="Screenshot_11_22_21__9_57_AM" src="https://user-images.githubusercontent.com/33705514/142911823-b99b81bc-1ee9-4a29-88e6-16adff50e05b.png">

**Comment by lamtu1** [comment]
@CGillen @simholt While working on this ticket, I notice that the `Location` section is using the `based_near` to display the section. But it said that we are working in development for refactoring this section out into our own code to fit with `our geo section`. With the original hyrax layout, it is hard to edit the `remove` button in this section until we refactor it out. Was wondering if we can put this on hold for now?

**Comment by simholt** [comment]
@lamtu1 Yes, that makes sense!

**Comment by lamtu1** [comment]
For the `Geographic Coordinates`, the `geo_boxes` should have the implementation done. But for the `location (based_near)`, that's a new ticket we have to come up with to extract out the content to it own form as listed in the comment in the code. And this can be tackle later to change the `remove` button for the location area

**Comment by simholt** [comment]
@lamtu1 looking good! Can you fix the spacing so the text fields don't overlap?

--- 

![Image](https://github.com/user-attachments/assets/9af63a0e-7d2e-4dfa-8757-7f3807dbe0c4)

**Comment by lamtu1** [comment]
> [@lamtu1](https://github.com/lamtu1) looking good! Can you fix the spacing so the text fields don't overlap?

Hi @simholt, I can get this done and fix the overlay on this

**Comment by simholt** [comment]
Looks good!
QA pass --
