### ISSUE TITLE
Creator/Author field should not be auto-filled with logged in user's name

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#180]
Sufia auto-fills creator/author with the logged in user's name. While this made sense for Sufia's use cases, it is less sensical for SA@OSU where mediated deposit means the depositor is usually not the creator/author.

**Comment by vantuyls** [comment]
no longer an issue in Hyrax.

**Comment by zhang4952** [comment]
Closed upon review of issues
