### ISSUE TITLE
Make all form fields same format - corners rounded or not

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1800]
### Descriptive summary
We have a combination of formats - need to choose one and stick with it. 
**Question**: Rounded or square corners?

![make all rounded](https://user-images.githubusercontent.com/33705514/51776390-dd8dce80-20ad-11e9-8fd4-e4dd4218f9f3.png)
- - - 
**NOTE**: Large box format is a Nurax issue:

![nurax round and not round](https://user-images.githubusercontent.com/33705514/51776394-e088bf00-20ad-11e9-8ec6-64afbdcf55f0.png)

**Comment by vantuyls** [comment]
out of box hyrax appears to use rounded edges. let's use those.

**Comment by simholt** [comment]
Looks good, QA passed.

![Screen Shot 2019-11-20 at 2 15 49 PM](https://user-images.githubusercontent.com/33705514/69282953-49db4080-0ba0-11ea-9261-c7615ed04ebb.png)
