### ISSUE TITLE
Abstract field does not render newlines

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1807]
### Descriptive summary

Abstract is a textarea on the edit form, which allows newlines, but on the showpage these are not being rendered. They appear to be saved correctly though.

Test item: https://ir-staging.library.oregonstate.edu/concern/articles/ws859f85j?locale=en
JSON output has `Line 1\r\nLine 2\r\n\r\nLine 4\r\n\r\n\r\nLine 7`

### Expected behavior
Abstract renders newlines as line breaks.

### Actual behavior
Abstract renders on a single line.

### Steps to reproduce the behavior

1. Create work
2. Write abstract, hit Enter for new line(s), add more text
3. View showpage

### Related work

#1634

**Comment by simholt** [comment]
Nice!
![yes](https://user-images.githubusercontent.com/33705514/56929704-3430ed00-6a8f-11e9-8879-443f4ee7daf9.png)
