### ISSUE TITLE
display embargo information even after embargo expiry

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1808]
### Descriptive summary

embargo information is still useful after the embargo has expired. i would like to find a way to display the embargo end date and the reason for the embargo on the metadata record for any item that currently or previously had an embargo.

**Comment by vantuyls** [comment]
mocking up now

**Comment by luisgreg99** [comment]
I just did a reindex_everything on staging. This one is now ready for QA.

**Comment by simholt** [comment]
I am setting up a test document to expire over the weekend.

**Comment by simholt** [comment]
Item was supposed to expire on Sunday but is still embargoed, could not complete QA.
 https://ir-staging.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/w0892b11w

**Comment by simholt** [comment]
We're good!

![Screen Shot 2019-09-03 at 10 20 55 AM](https://user-images.githubusercontent.com/33705514/64194663-89fa1500-ce34-11e9-8ac5-494854460150.png)
