### ISSUE TITLE
Make fields consistent width on edit page

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1810]
### Descriptive summary
Dropdowns, text fields, and text boxes are different widths. Some are fine being short, such as the nested geographic coordinates, but non-nested fields should all be the same width. 

### Expected behavior
Non-nested fields are all the same width. 
**Question**: Should the fields extend no matter how wide the window gets or not?

### Actual behavior
![field length](https://user-images.githubusercontent.com/33705514/52887239-d8132980-312b-11e9-9e65-15cad8a6273d.png)

### Steps to reproduce the behavior
1. Access edit page on SA

### Related work
#1811

**Comment by vantuyls** [comment]
what is best practice for mobile viewing as far as form fields changing size based on screen size? @luisgreg99 @revgum @straleyb @KennaW

**Comment by straleyb** [comment]
@simholt Can you review this and see if staging/production looks fine for the form fields? i wanna verify this is still an issue.

**Comment by simholt** [comment]
@straleyb Yes, it is still an issue. 

This is from staging:
![Screen Shot 2019-11-19 at 11 32 02 AM](https://user-images.githubusercontent.com/33705514/69179336-3b1d5c80-0ac0-11ea-8f19-99b4cbfa2347.png)

**Comment by straleyb** [comment]
Ok I see what is going on here. this is an issue of screen size. On my laptop screen, the fields are fine, but on a larger size screen the form fields only go so far. this is why I wasnt seeing it, because I wasnt testing on a large 1920x1080 screen. Ill make the updates to get them to fill all screen sizes.

**Comment by simholt** [comment]
Still appears to be happening:
![Screen Shot 2019-11-20 at 2 20 38 PM](https://user-images.githubusercontent.com/33705514/69283336-10570500-0ba1-11ea-9fdc-1fd3b047174f.png)
