### ISSUE TITLE
Make helptext wrap on edit page

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1811]
### Descriptive summary
The edit page helptext extends beyond the field and looks bad.

### Expected behavior
Text has a set end point or continues along the field.
**Question**: Should the text extend along the whole field or have a set point where it wraps?

### Actual behavior
![helptext_wrap](https://user-images.githubusercontent.com/33705514/52887376-51ab1780-312c-11e9-8728-654c5c30e960.png)

### Steps to reproduce the behavior
1. Access edit page on SA

### Related work
#1810

**Comment by vantuyls** [comment]
Answer: i'd like the text to be the same width as the form field and wrap as such

**Comment by straleyb** [comment]
This could be fine now that the fields extend the full length of the form.

**Comment by simholt** [comment]
All good, QA passed.

![Screen Shot 2019-11-20 at 1 59 27 PM](https://user-images.githubusercontent.com/33705514/69281904-fec02e00-0b9d-11ea-9011-0d8d51fa2076.png)
