### ISSUE TITLE
versioning a file should update the filename and thumbnail based on new file

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1812]
### Descriptive summary

Currently, creating a new version of a file in Hyrax does not update the filename or thumbnail. We would like SA@OSU to do so. 

### Expected behavior
When a file is versioned, the filename and thumbnail will update based on the new file's characteristics

### Actual behavior
filename and thumbnail remain from the old version of the file, regardless of what file is used as a replacement

**Comment by simholt** [comment]
FYI: Currently, the thumbnail is replaced but not the filename. The filename can be edited manually.

**Comment by simholt** [comment]
Okay, this is a little confusing so hopefully I make sense!

The way things work now, it seems I can change the title of the file on its own **OR** add a new version that also changes the thumbnail. 

When I goto the versioning page and choose a new file with a different name, I get the note “Warning: The title of this fileset has changed to match the above file name. Check the description tab to verify your title”

If I click thru to the description tab, the new file name is shown. I click Save and it changes the filename shown at the bottom of the show page, but does not upload the new file. The previous version and thumbnail are still attached.

If I do not go to the description tab, and instead just click Upload new version, the file and thumbnail change to the new version but the filename does not.

This is item 9z903000p on staging.
<img width="794" alt="Screenshot_2_28_22__4_33_PM" src="https://user-images.githubusercontent.com/33705514/156082494-d30747f2-6b2f-4915-8382-090328c01f19.png">

**Comment by simholt** [comment]
I really like the new warning text & format:

<img width="733" alt="Screen Shot 2022-03-02 at 12 07 53 PM" src="https://user-images.githubusercontent.com/33705514/156442868-4d6853d1-e10f-4153-86b0-1551a7450633.png">

It changed the name of the file but not the file itself or the thumbnail

<img width="667" alt="Screen Shot 2022-03-02 at 12 18 24 PM" src="https://user-images.githubusercontent.com/33705514/156442941-78c1ece5-9215-4d76-9229-07e3b37b51dc.png">
 
I waited a while in case the PDF needed to cycle through but it is still the first version.
You can see the name changes recorded on the fileset page:

<img width="739" alt="Screen Shot 2022-03-02 at 12 21 57 PM" src="https://user-images.githubusercontent.com/33705514/156443359-ce06e5b0-02b2-42e1-a05f-c6e8d72b97ae.png">

But the file versions page shows only the first deposit:

<img width="525" alt="Screen Shot 2022-03-02 at 12 21 48 PM" src="https://user-images.githubusercontent.com/33705514/156443355-2e8b0cec-34cd-4cf2-a028-01dfa6fcf342.png">

Item v118rd75g on staging.

**Comment by simholt** [comment]
Now it seems we are back where things started? It uploaded the new version but there was no title change prompt. I changed the title by going to the fileset edit page
<img width="771" alt="Screen Shot 2022-03-04 at 4 24 50 PM" src="https://user-images.githubusercontent.com/33705514/156859071-9117379e-303c-4997-ad91-8ac1ec97c2fd.png">
.

**Comment by simholt** [comment]
All good here!!  🥳 🥳 🥳 

<img width="376" alt="Screen Shot 2022-03-10 at 6 41 31 AM" src="https://user-images.githubusercontent.com/33705514/157685721-f4a90b4b-3355-45ba-9d92-1c4695a96e42.png">
<img width="338" alt="Screen Shot 2022-03-10 at 6 42 44 AM" src="https://user-images.githubusercontent.com/33705514/157685734-dc50fda3-97b5-44bf-83df-a2601a419d03.png">
