### ISSUE TITLE
Production server monitoring and stability

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1813]
### Descriptive summary

Until we can move SA to a kubernetes infrastructure, we need some improvements to the production system for stability.

- [x] Monitor when `soffice` processes run "too long" and leave zombie processes behind, these should be killed off
- [x] Add log rotation to the tomcat logs to keep from chewing through disk space unnecessarily
- [x] Reduce log level in tomcat to INFO

**Comment by decimalator** [comment]
@DeadCatLady and I will verify whether these got done or not 🤪🤪😎

**Comment by DeadCatLady** [comment]
- [ ]  a script to kill soffice processes
- [ ]  a script to clean tomcat log rotation and something to truncate catalina.out script to clean out all older logs
- [ ]  a script to change from debuging to info

**Comment by DeadCatLady** [comment]
Currently on the correct server, but I'm not sure if the cron job is set up correctly, when its verified, I'll close this issue

**Comment by decimalator** [comment]
The log pruning script has been running happily on staging for awhile now, I've enabled it on prod as well. To verify, we can check that the number of each type of log matches the default 30 day retention.
