### ISSUE TITLE
Reassign correct worktypes

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1824]
### Descriptive summary
Move items to correct worktype:

- [x] [Move to Grad Project/Capstone](https://docs.google.com/spreadsheets/d/1d0gzq3OJop95qJBV0_pHTuvDK9P0KmkBegTi84OFIxI/edit#gid=571990439&range=A1)
- [x] [Move to Default](https://docs.google.com/spreadsheets/d/1d0gzq3OJop95qJBV0_pHTuvDK9P0KmkBegTi84OFIxI/edit#gid=977543458&range=B1)
- [x] [Move to Article](https://docs.google.com/spreadsheets/d/1d0gzq3OJop95qJBV0_pHTuvDK9P0KmkBegTi84OFIxI/edit#gid=740747625&range=A1)

**Comment by wickr** [comment]
All done. There were some odd ones but I think I handled them all. Everything is noted and marked with yellow.
