### ISSUE TITLE
Bulk Edits: Technicals

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1825]
### Descriptive summary

Bulk edits to clean up series fields.

These are all on the same spreadsheet -- links to tabs below:

- [x] [alt_title](https://docs.google.com/spreadsheets/d/1jfUjQEs0o57DIhTSzK6_you15v9ZKrI6ONICx7EV6zE/edit#gid=0&range=A1)
- [x] [in_series](https://docs.google.com/spreadsheets/d/1jfUjQEs0o57DIhTSzK6_you15v9ZKrI6ONICx7EV6zE/edit#gid=298060487&range=A1)
- [x] [subject](https://docs.google.com/spreadsheets/d/1jfUjQEs0o57DIhTSzK6_you15v9ZKrI6ONICx7EV6zE/edit#gid=112750932&range=A1)
- [x] [resource_type](https://docs.google.com/spreadsheets/d/1jfUjQEs0o57DIhTSzK6_you15v9ZKrI6ONICx7EV6zE/edit#gid=226660213&range=A1)

**Comment by luisgreg99** [comment]
Task to update `alt_title` is now running. The logs are looking good.

**Comment by luisgreg99** [comment]
@simholt I found two works that couldn't be found for `alt_title`. I looked at the other fields/tabs and they are listed there too.

id | from | to | property
-- | -- | -- | --
28710691 | * | Report no. 1413 | alt_title
28710666 | * | Report no. 1432 | alt_title

Are the ids supposed to be `028710691` and `028710666`?

**Comment by simholt** [comment]
Yes, that is right -- looks like the zeros got dropped during copy/paste. Good catch!

**Comment by luisgreg99** [comment]
Restarted task for `alt_title` to update the remaining works and those with the correct ids.

**Comment by luisgreg99** [comment]
Bulk edit for `alt_title` finished successfully. Now running task for `in_series`.

**Comment by luisgreg99** [comment]
Task for `in_series` done. Now running `subject`.

**Comment by luisgreg99** [comment]
The `subject` list had an empty row. it stopped at row 557. I'm restarting the task again for `subject` where it left, but now combining it with `resource_type` to let it run for the rest of the day.

**Comment by luisgreg99** [comment]
Now running `subject` (1480 rows remaining) and `resource_type` (1880 rows) in one task.

**Comment by simholt** [comment]
> The `subject` list had an empty row. It stopped at row 557. I'm restarting the task again for `subject` where it left, but now combining it with `resource_type` to let it run for the rest of the day.

Whoops - that's my bad. Looks like I need to do cleanup on my cleanup.

**Comment by luisgreg99** [comment]
Updates for `subject` and ` resource_type` done. @simholt No problem, I think we can close this one unless you find any issues in the updates. I've checked a few of them to confirm that the task completed successfully.

**Comment by simholt** [comment]
[Subject with proper formatting](https://docs.google.com/spreadsheets/d/1jfUjQEs0o57DIhTSzK6_you15v9ZKrI6ONICx7EV6zE/edit#gid=888745622&range=A1)!

**Comment by luisgreg99** [comment]
Now running `subject` once more, but now to replace the URIs previously added with the labels provided in [Subject with proper formatting](https://docs.google.com/spreadsheets/d/1jfUjQEs0o57DIhTSzK6_you15v9ZKrI6ONICx7EV6zE/edit#gid=888745622&range=A1). For this batch, I combined the final CSV with the list with URIs with some modifications (replaced `+` with `-` under `from`) to revert the changes and added the new list at the end to add the labels.

**Comment by luisgreg99** [comment]
Task for `subject` finished successfully.
