### ISSUE TITLE
Bulk Edits: Circulars

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1827]
### Descriptive summary
Bulk edits to clear up series fields.

These are all on one spreadsheet -- links to tabs below:
- [x] [in_series](https://docs.google.com/spreadsheets/d/1A0h8dScRfp-On21--tsZdiKriz4vaawOtPgcE2-qUSE/edit#gid=251701587&range=A1)
- [x] [resource_type](https://docs.google.com/spreadsheets/d/1A0h8dScRfp-On21--tsZdiKriz4vaawOtPgcE2-qUSE/edit#gid=1697276921&range=A1)
- [x] [subject](https://docs.google.com/spreadsheets/d/1A0h8dScRfp-On21--tsZdiKriz4vaawOtPgcE2-qUSE/edit#gid=915878062&range=A1)
- [x] [alt_title](https://docs.google.com/spreadsheets/d/1A0h8dScRfp-On21--tsZdiKriz4vaawOtPgcE2-qUSE/edit#gid=473848487&range=A1)

**Comment by revgum** [comment]
`in_series` running this AM

**Comment by revgum** [comment]
This bulk edit is done
