### ISSUE TITLE
Bulk Edits: PNW + date_issued

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1834]
### Descriptive summary

Cleanup in multiple fields -- including date_issued, which I don't think we've done before. All changes in one tab:

- [x] [PNW + date_issued](https://docs.google.com/spreadsheets/d/1mcgHF4mP1I4nhAHzTqBfCGB4-EO9GuHsoDSmOV0ozAE/edit#gid=1355842832&range=A2)

**Comment by luisgreg99** [comment]
Now running bulk edits PNW + date_issued

**Comment by luisgreg99** [comment]
@simholt I checked a few that update `title`, and they didn't work unfortunately. I just realized `title` is an ordered field, but the other ones are looking good.

**Comment by simholt** [comment]
Oh I forgot about that again! Okay, thanks.

**Comment by luisgreg99** [comment]
The script just finished with the edits. `date_issued` worked well. I checked a few.
