### ISSUE TITLE
Replace native Creator/Author field with new nested Author field

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#184]

**Comment by vantuyls** [comment]
Put the new author field in the place where the old one was?

**Comment by vantuyls** [comment]
the new author field is a required field

**Comment by zhang4952** [comment]
Remove creator will shake the sufia data model and make it difficult to maintain, probably just keep it as it is auto populated as well.

**Comment by zhang4952** [comment]
make creator invisible, optional, and not repopulate
