### ISSUE TITLE
Bulk Edits: Extension docs

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1843]
Cleanup in multiple fields, additions and replacements. All changes in one tab:

- [x] [25 Apr 2019](https://docs.google.com/spreadsheets/d/1nsIT4nA2Ixep5_L5Z9QZb6yNYY1A6te3QVwfYC4kpo4/edit#gid=1285843666&range=A2)

**Comment by straleyb** [comment]
QA complete. closing
