### ISSUE TITLE
Bulk Edits: FRL & Ag Exp

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1851]
Cleanup in multiple fields -- additions and replacements. All changes in one tab:

- [x] [2 May 2019](https://docs.google.com/spreadsheets/d/1LACDOSwORTAFmHPA8EnBDUdTFN80hsF3yP9Pc6zTkpY/edit#gid=811015978&range=A2)

**Comment by revgum** [comment]
Kicked em off, should be done in a couple hours so long as there aren't any hiccups along the way

**Comment by revgum** [comment]
Done!
