### ISSUE TITLE
Bulk Edits: Bulletins & Special Reports

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1868]
Cleanup in multiple fields -- additions and replacements. All changes in one tab:

- [x] [16 May 2019](https://docs.google.com/spreadsheets/d/1FHIoMfa3vt3D0wsFQ1GLAOyISoOrAoWirBQGgqXi68s/edit#gid=538634298&range=A3)

**Comment by luisgreg99** [comment]
Started running task to update Bulletins & Special Reports.

**Comment by luisgreg99** [comment]
The script stopped at row 2624 with id `00000087v` 
![image](https://user-images.githubusercontent.com/3486120/57872226-18805300-77c0-11e9-9290-6c06aeeef45a.png)
@simholt I think you meant `property` to be `in_series` right?

**Comment by simholt** [comment]
Yes, my bad!

**Comment by luisgreg99** [comment]
Replaced `series` with `in_series` under property in the input csv, then restarted the task to update the remaining works. `1665` works remaining.

**Comment by luisgreg99** [comment]
Task completed successfully. @simholt I checked a few for each property and they were updated successfully. I just noticed one issue in the last property `resource_type` when I clicked the facet link in one of the works's show page. It returned 115 items for [research paper](https://ir.library.oregonstate.edu/catalog?f%5Bresource_type_sim%5D%5B%5D=research+paper&locale=en) compared with [Research Paper](https://ir.library.oregonstate.edu/catalog?f%5Bresource_type_sim%5D%5B%5D=Research+Paper&locale=en) that returns 1772. I'm wondering if the `to` column for `resource_type` should have been `Research paper` instead for `research paper`?

**Comment by simholt** [comment]
Yes, it should be Research Paper -- I didn't realize capitalization made a difference.

**Comment by simholt** [comment]
@luisgreg99 Fixed!

**Comment by luisgreg99** [comment]
Nice, thanks! I will export again, then restart the task for those items. There are only 115, so it shouldn't take very long to reset the update.

**Comment by luisgreg99** [comment]
Task finished successfully.
