### ISSUE TITLE
Data remediation for IIFET 2018 collection - items out of workflow

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1879]
### Descriptive summary

-- searched for "Assessment of socio-economic value of the small pelagic fishery in Mafia Island, Tanzania" and there are two records, one without a file.
-- not all the metadata fields listed in the spreadsheet are there, like rights statement, peer reviewed, language.
-- looks like they are coming in without being assigned an admin set. Or at least for that one. Others (https://ir.library.oregonstate.edu/concern/conference_proceedings_or_journals/0v838610t ) are in an admin set but still missing the blue Deposited button
--metadata not showing up on search results. The one I linked above just has resource type.

**Comment by simholt** [comment]
- Searches revealed three duplicate uploads so I deleted them
- Metadata was missing because incorrect terminology used on spreadsheet -- this will be cleared up in this week's bulk edits

**Comment by simholt** [comment]
Details about workflow issues -- this is the case with all in the [IIFET 2018 Seattle collection](https://ir.library.oregonstate.edu/collections/pk02cg65r?locale=en) except the sample ones uploaded individually by a student.

- No blue Deposited button, Relationships under record says Default admin set, URL says Conference Proceedings, do not show up at all on the admin Works page.

Examples:
4q77fx10b
zc77sw29q
0v838610t

**Comment by simholt** [comment]
It would be best if all items out of workflow in SA could be fixed -- there are a lot of migrated Honors College Theses in same situation, making 1189 items altogether:

https://docs.google.com/spreadsheets/d/1VwL9_7B0Q3FImWtk-UZuGV9jFc7rcCRBA1hq71r1URk/edit?usp=sharing
