### ISSUE TITLE
Remove Google Analytics calls from Admin Dashboard views

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1887]
### Descriptive summary

The Admin Dashboard has Google Analytics calls, so each pageview under there is getting tracked. I don't think it matters that `/admin/workflows?locale=en` was visited 33 times in the last week.

Confirm /notifications route/view GA calls are removed too, since it has its own route.

### Expected behavior

Admin Dashboard views do not need to be tracked for Google Analytics

### Actual behavior

Admin Dashboard views are being tracked for Google Analytics

### Steps to reproduce the behavior

1. Visit page in Dashboard
2. Look at Analytics > Realtime > Content view.

**Comment by carakey** [comment]
I visited Staging admin tabs and then viewed the Google Analytics property for SA staging. GA confirmed that 1 user was active. I searched 'admin' in the Pages and Screens tab and got no results. Compare to searching for 'admin' in P&S on GA for prod and getting 6 hits on the `/admin/workflows` line. 

Tentative QA Pass, and then double check after it's in Prod.
