### ISSUE TITLE
Spontaneous embargo reason but no embargo

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1891]
### Descriptive summary
A grad student emailed that she noticed an embargo reason on her deposit even though she had not selected an embargo.

![Screen Shot 2019-06-12 at 12 24 58 PM](https://user-images.githubusercontent.com/33705514/59380072-1fda4400-8d0d-11e9-8fa6-e692ef1b73fe.png)

The deposit is currently in grad school review queue:
f1881s168

I added and then removed an embargo to see if that would override the settings but it did not. The Embargo reason field is not editable by admin.

**Comment by wickr** [comment]
I can confirm the lack of active embargo status, but the reason still being there:
```
irb(main):002:0> item.embargo
=> #<Hydra::AccessControls::Embargo id: "51c417b6-dc33-46f7-81ab-5123d50c7678", visibility_during_embargo: nil, visibility_after_embargo: nil, embargo_release_date: nil, embargo_history: ["An active embargo was deactivated on 2019-06-11.  Its release date was 2020-01-11T00:00:00+00:00.  Visibility during embargo was authenticated and intended visibility after embargo was open"]>
irb(main):003:0> item.embargo_reason
=> "Ongoing Research"
```

**Comment by wickr** [comment]
I manually removed the embargo reason on f1881s168
