### ISSUE TITLE
Bulk Edits: Registrar's Collection+Subcollections

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1897]
Adding items to the Registrar's Collection and three subcollections. I removed the items already in the collections, so there should be no duplication.

- [x] [Registrar Collection adds](https://docs.google.com/spreadsheets/d/1toWWUbOWl2jqJlRFL8Z-uadJqSNp-Do4svbRUhN-34M/edit?usp=sharing)

**Comment by luisgreg99** [comment]
Successfully added works to collection `Registrar's Office` and `General Catalogs`. Now running task to add to collection `sched of classes`.

**Comment by luisgreg99** [comment]
Successfully added works to `sched of classes`, and `Registration Handbooks`.

**Comment by luisgreg99** [comment]
@simholt I finished running the script, and didn't find any issues. I checked a few of them to verify the update.
