### ISSUE TITLE
Items out of workflow

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1902]
### Descriptive summary
Many items in the IIFET 2018 and Honors College collections are out of the workflow. They should be in a workflow.

### Expected behavior
This one was uploaded manually and is fine:
 https://ir.library.oregonstate.edu/concern/conference_proceedings_or_journals/cf95jj220 

### Actual behavior
Out of workflow:
 https://ir.library.oregonstate.edu/concern/conference_proceedings_or_journals/12579z531 

Spreadsheet listing all 1100+ items:
https://docs.google.com/spreadsheets/d/1VwL9_7B0Q3FImWtk-UZuGV9jFc7rcCRBA1hq71r1URk/edit?usp=sharing

**Comment by wickr** [comment]
All items listed in the spreadsheet are now added to the workflow 'One Step Mediated Workflow (default)' with the workflow state 'Deposited'.

**Comment by wickr** [comment]
It wasn't obviously showing any issues in the UI, but all items also needed to be reindexed so the workflow Solr fields were updated.
