### ISSUE TITLE
Segfault on Production, ruby 2.5.2+ needed

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1906]
### Descriptive summary

Per all of the details [here](https://bugs.ruby-lang.org/issues/14634), when using Honeycomb on production there are segfaults causing the server instability.

Need to update SA Production to ruby 2.5.2+;
- [ ] update all references (.ruby-version, docker, deploy.rb, etc)
- [ ] install the target ruby version on production server
- [ ] update deploy.l.o.e application configuration to set rbenv to use the target ruby version

Since this is such a low-level change, it'll require either a manual deployment or a two-step process. I'd recommend;
- update all references 
- install target ruby version on the production server
- deploy SA
- update deploy.l.o.e application configuration to use the new ruby version
- deploy SA (this will deploy the same code as the previous deploy, but this time in the context of the latest ruby version)

**Comment by revgum** [comment]
@straleyb you fixed this I think, close the ticket?

**Comment by straleyb** [comment]
Fixed by #1907
