### ISSUE TITLE
Bulk Edits: 4H & Forest Research

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1909]
Bulk edits - misc alt_title, subject, keywords, in_series, etc. Direct link to relevant tab:

- [x] [4H & Forest Research](https://docs.google.com/spreadsheets/d/1TnAfUIoLZylEX1I3MneludetMgblk47KEEI2-w6IYpc/edit#gid=638059584&range=A2)

**Comment by luisgreg99** [comment]
Started running the task for 4H & Forest Research

**Comment by luisgreg99** [comment]
Restarted the task for `keyword` to clear all values

`*` under `to` didn't work for `keyword` updates. PR https://github.com/osulp/Scholars-Archive/pull/1911 should address this case. Once it's merged, for future reference, example 4 in the wiki [Bulk-Metadata-Modifications](https://github.com/osulp/Scholars-Archive/wiki/Bulk-Metadata-Modifications) should work as expected

**Comment by luisgreg99** [comment]
Task completed successfully to update 4H & Forest Research tab
