### ISSUE TITLE
Alter social media buttons on Work page

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1912]
### Descriptive summary

We currently use Hyrax's social media view. Google+ is no longer active and the button can be removed. This was removed in Hyrax but may be awhile before that gets released and pulled into SA. 
Tumblr can also be removed. 

In OD2, both of these service buttons were removed, and a 'Copy Share Link' button was added. https://github.com/OregonDigital/OD2/blob/master/app/views/hyrax/base/_social_media.html.erb
That can be re-used for SA.

### Expected behavior

Social media sharing buttons for Facebook, Twitter, and Copy Share Link.

### Actual behavior

Social media sharing buttons for Facebook, Twitter, Google+ and Tumblr.

### Related work

 https://github.com/samvera/hyrax/pull/3894

**Comment by mellinma** [comment]
@wickr  can you finish this asap?  It's stopping us from deploying to production (because we just want to do that once).

**Comment by wickr** [comment]
Yeah I'll get it in tomorrow morning. I finalized the CSS alignment today and need to double check what CSS fix I had for the button backgrounds.

**Comment by simholt** [comment]
Okay, the buttons are now filled in but they are too small and/or have corners. Can we get the spacing back the what @wickr had?

Chrome
![Screen Shot 2019-09-10 at 2 08 56 PM](https://user-images.githubusercontent.com/33705514/64650669-98b46f00-d3d4-11e9-9d64-8bcd11d192c6.png)

Firefox
![Screen Shot 2019-09-10 at 2 09 51 PM](https://user-images.githubusercontent.com/33705514/64650725-b08bf300-d3d4-11e9-874a-f8be7867fcfb.png)

Safari
![Screen Shot 2019-09-10 at 2 10 19 PM](https://user-images.githubusercontent.com/33705514/64650746-be417880-d3d4-11e9-902f-9f4e9353f095.png)
