### ISSUE TITLE
Update bulk_ingest_csv Rake task to assign workflow and state

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1917]
### Descriptive summary

The bulk_ingest_csv does not include any steps to put works in a workflow and assign state. Works added with this method will typically not need to go through additional review steps, so can get set to the default workflow and 'Deposited' state (though this can be adjusted).

### Expected behavior

bulk_ingest Rake task should put items in stated workflow and state.

### Actual behavior

Works are not put in a workflow on creation. 'Deposited' badge does now show.

### Steps to reproduce the behavior

1. Run bulk_ingest Rake task
2. Check for 'Deposited' badge not showing

### Related work

#1877

**Comment by shieldsb** [comment]
Complete.
