### ISSUE TITLE
Bulk Edits: 19 Aug 2019

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1918]
This is a large one -- 23K+ changes.

Direct link to relevant tab:
- [x] [SA Bulk Edits 19 Aug 2019](https://docs.google.com/spreadsheets/d/1XCjP1sRnDOGLJDNyxybsr7LyPnC9qHh8BZJdRftAs2o/edit#gid=1005803189&range=A2)

**Comment by luisgreg99** [comment]
@simholt For the first 235 items, you probably want to clear all values under `alt_title` right? Right now there is a bug that prevents clearing all values in a field. PR https://github.com/osulp/Scholars-Archive/pull/1911 will fix the issue, so I'll get this one deployed to master on Monday in prep for the bulk edit.

**Comment by simholt** [comment]
@luisgreg99 Yes, that is correct. Thank you!

**Comment by luisgreg99** [comment]
Started running bulk edit for "SA Bulk Edits 19 Aug 2019"

**Comment by luisgreg99** [comment]
@simholt I've  updated `alt_title` in my copy before exporting and starting the script. With the update now in place, we can now use an empty cell (like it was done in the past) under the `to` column along with `*` under `from` to indicate that we want to clear all values on a property.
![image](https://user-images.githubusercontent.com/3486120/63390172-fe2bb780-c362-11e9-9356-9f90a7b9aac6.png)

**Comment by luisgreg99** [comment]
Started running the 4th small batch (500 items) for "SA_Bulk_Edits_19_Aug_2019_batch4.csv". Batch size of 500 seems to be working well so far (they take about a couple of hours to complete). Will increase the batch size after the next deploy.

**Comment by luisgreg99** [comment]
SA_Bulk_Edits_19_Aug_2019_batch4.csv (500 items processed) finished successfully

**Comment by luisgreg99** [comment]
These batches finished successfully today:
- SA_Bulk_Edits_19_Aug_2019_batch5.csv,
- SA_Bulk_Edits_19_Aug_2019_batch6.csv
- SA_Bulk_Edits_19_Aug_2019_batch7.csv

**Comment by luisgreg99** [comment]
Ran batch `SA_Bulk_Edits_19_Aug_2019_batch8.csv` today, but many failed due to an issue related to empty embargo history values on some works previously migrated from dspace https://github.com/osulp/Scholars-Archive/issues/1962. Made a new list with these issue at `SA_Bulk_Edits_19_Aug_2019_batch8_d.csv`. Will run this batch when https://github.com/osulp/Scholars-Archive/pull/1964 (fixes https://github.com/osulp/Scholars-Archive/issues/1962) gets merged and deployed to production.

**Comment by luisgreg99** [comment]
Completed `SA_Bulk_Edits_19_Aug_2019_batch8_d.csv` today. Bulk edit task finished successfully.

**Comment by luisgreg99** [comment]
Now running task for next batch `SA_Bulk_Edits_19_Aug_2019_batch9.csv` (500 more publisher updates).

**Comment by luisgreg99** [comment]
Completed successfully 3500 more publisher updates:

SA_Bulk_Edits_19_Aug_2019_batch10.csv through SA_Bulk_Edits_19_Aug_2019_batch16.csv

**Comment by luisgreg99** [comment]
Successfully completed 4000 more publisher updates on 10/02/2019:

`SA_Bulk_Edits_19_Aug_2019_batch17.csv` through `SA_Bulk_Edits_19_Aug_2019_batch24.csv`

**Comment by luisgreg99** [comment]
Successfully completed 1500 more published updates today:

`SA_Bulk_Edits_19_Aug_2019_batch25.csv` through `SA_Bulk_Edits_19_Aug_2019_batch27.csv`

**Comment by luisgreg99** [comment]
Successfully completed 2000 more publisher updates on 10/04/2019:

`SA_Bulk_Edits_19_Aug_2019_batch28.csv` through `SA_Bulk_Edits_19_Aug_2019_batch31.csv`

**Comment by luisgreg99** [comment]
Successfully completed 2500 more publisher updates today:

`SA_Bulk_Edits_19_Aug_2019_batch32.csv` through `SA_Bulk_Edits_19_Aug_2019_batch36.csv`

**Comment by luisgreg99** [comment]
Successfully completed 3000 more publisher updates today:

SA_Bulk_Edits_19_Aug_2019_batch37.csv through SA_Bulk_Edits_19_Aug_2019_batch42.csv

**Comment by luisgreg99** [comment]
Successfully completed 2500 more publisher (including degree_name) updates today:

`SA_Bulk_Edits_19_08_19_remaining_batch00.csv` through `SA_Bulk_Edits_19_08_19_remaining_batch04.csv`

**Comment by simholt** [comment]
QA complete @luisgreg99 -- looks perfect!
