### ISSUE TITLE
Revise Ack message 

### ISSUE THREAD

**Issue by shieldsb** [osulp/Scholars-Archive#1977]
### Descriptive summary
Revise Ack message 

### Expected behavior
Message that explains SA outage

**Comment by simholt** [comment]
Please change message to:

> Something isn’t working on our end. Please try again.
> If you encounter this message repeatedly, please let us know what happened via the [contact form](https://ir.library.oregonstate.edu/contact).

Link to contact form: https://ir.library.oregonstate.edu/contact

**Comment by simholt** [comment]
QA passed.
