### ISSUE TITLE
Alpha sort advanced search fields

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1981]
### Descriptive summary

The advanced search page contains multiple fields that users can search against. These fields need to be alpha sorted. Currently they have no logical order.

**Comment by simholt** [comment]
QA passed:

![Screen Shot 2019-11-13 at 11 42 39 AM](https://user-images.githubusercontent.com/33705514/68798136-b7202c00-060a-11ea-93db-539650255e12.png)
