### ISSUE TITLE
Add Metadata as Google Analytics Dimension

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#199]
metadata fields of department, school, and even author should be added to Google Analytics as dimension for report

**Comment by vantuyls** [comment]
I'm not sure we can add these dimensions to GA directly, can we? We'll have that information for the items in the repository and will be able to query based on that metadata for reporting purposes. Is that what you mean?

**Comment by zhang4952** [comment]
It should be discussed in the planning meeting. I want to take full advantage of GA and we should be able to customize dimensions (worst case: Google Tag Manager). So my idea for our new statistics dashboard will be a GA-dependent frontend to generate reports without touching Fedora/Solr at all.

**Comment by vantuyls** [comment]
this is related to statistics reporting.
