### ISSUE TITLE
Honors depositor cannot select appropriate degree level

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1992]
### Descriptive summary
Undergrad Honors student was not allowed to select the Bachelor's degree level and had to pick Master's instead (or Doctorate?).

 https://ir.library.oregonstate.edu/concern/honors_college_theses/9019s8785 

### Expected behavior
Deposit form defaults to Bachelor's.

![Screen Shot 2019-11-13 at 11 45 03 AM](https://user-images.githubusercontent.com/33705514/68798400-357cce00-060b-11ea-8d7c-80a4842f0de2.png)

### Actual behavior
Student is in the correct HCT worktype but Bachelor's is not an option under the degree level drop-down. I can correct this as an admin - the item is currently in the review queue. This happened once before.

**Comment by straleyb** [comment]
@simholt 
The limit has been put in place based on this ticket. 
https://github.com/osulp/Scholars-Archive/issues/1925

This states that ETDs should only be Master's and Doctorate

Honor's College Thesis is, from what I understand, an ETD.

If this is not the case, I can allow Honor's College Thesis to include bachelor's as well.

**Comment by simholt** [comment]
Honor's College Theses are their own thing, not ETDs. They only need Bachelor's default degree levels.
