### ISSUE TITLE
Remove unnecessary metadata fields

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#201]
Remove DOI, ORCID, and Research ID from ingestion form

**Comment by zhang4952** [comment]
need to be reviewed by Steve and Hui

**Comment by vantuyls** [comment]
Refer to the google doc: 
https://docs.google.com/a/oregonstate.edu/spreadsheets/d/1lVOgVtW8_foYj4gdsPOx-xBtF1GACLy4UGPPLKTbjiU/edit?usp=sharing

**Comment by zhang4952** [comment]
check the 'Final Label' column, if 'REMOVED' means the field should be removed
