### ISSUE TITLE
files in a dataset that is not approved should not be available to the public

### ISSUE THREAD

**Issue by luisgreg99** [osulp/Scholars-Archive#2010]
### Descriptive summary
From Clara on slack:

> I would expect the files in a dataset that is not approved to not be available to the public. Is this normal/known/expected? Thanks!

It looks like this behavior is a known issue in current versions of hyrax. There is an open ticket https://github.com/samvera/hyrax/issues/3775 and a pull request https://github.com/samvera/hyrax/pull/3881 that hasn't been released yet that appears to fix the issue.

Options:

- We can make a patch based on https://github.com/samvera/hyrax/pull/3881
- We can tweak the sitemap configuration to list items with `visibility` open and filter by workflow state `workflow_state_name_ssim` to exclude works/files where the work is temporarily unavailable (this option would only affect items in the sitemap, which is currently used for crawlers, but it doesn't resolve visibility in the site).

### Expected behavior
It should exclude files when the parent's workflow state `workflow_state_name_ssim` is set to any of these states `['Changes Required', 'Graduate School Review', 'Pending Review', 'Honors College Review']` (It looks like `Hyrax::Workflow::DeactivateObject` gets triggered when the workflow transitions to these states).

### Actual behavior

FileSets with open visibility end up in Google search results even when the parent work has a restrictive visibility due to the workflow state change.

### Steps to reproduce the behavior

1. Create a work with a file attachment and set workflow state to 'Changes Required'
2. Generate sitemap `rake sitemap:refresh`
3. Inspect localhost:3000/sitemaps/sitemap.xml to see the file set id being listed
 
### Related work
https://github.com/samvera/hyrax/issues/3775

**Comment by simholt** [comment]
Not sure where we are on this ticket!

**Comment by straleyb** [comment]
Fair question. Looks like it might need to be checked out to see if its still bugged or if it's working as expected. This should be looked at by a dev to double check before moving forward to QA.

@CGillen Have any ideas off the top of your head? I know its been like 6 months.

**Comment by CGillen** [comment]
Looks like this is still happening
https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/1n79hd04g?locale=en
https://ir.library.oregonstate.edu/concern/parent/1n79hd04g/file_sets/qz20t186s

**Comment by CGillen** [comment]
Fixed by #2498

**Comment by simholt** [comment]
@CGillen how to QA this?

**Comment by CGillen** [comment]
Ignore the sitemap biz, I can handle that.

1. Create a dataset/work with a fileset attached
2. Attempt to access FileSet page from anonymous user (get redirected)
3. Move to `changes required` state
4. Again attempt to access FileSet page from anonymous user (get redirected). Compare this behavior to production (no redirect & full access to page)
5. Move to `Approved` state
6. Finally, attempt to access FileSet page from anonymous user, page is available

**Comment by simholt** [comment]
1. Done - `cj82k7548`
2. **While logged in**, tried to view fileset (https://ir-staging.library.oregonstate.edu/concern/parent/cj82k7548/file_sets/8s45q892z) by clicking on filename at bottom of page. Was redirected to homepage with message "The item you tried to access is unavailable". Tried to access submissions page but got broken message. Tried to view fileset from anon & got unavailable message.
3. Yep
4. "The item you tried to access is unavailable" received when anon and logged in.
5. Done
6. Can view when anon and logged in.

**Comment by simholt** [comment]
Q: Can we change the text to "The item you tried to access is unavailable because it is in the review process."? @carakey what do you think?

**Comment by carakey** [comment]
@simholt I like it.  It's in keeping with the other restricted item messaging work, #2032 and #2494. Clarity and transparency. 👍

**Comment by CGillen** [comment]
Text changed and fixes should be in

**Comment by CGillen** [comment]
@simholt This should be fixed. Last one to QA before we can deploy and clean up some of those bugs that bug with datasets

**Comment by simholt** [comment]
QA pass -- all good here!
