### ISSUE TITLE
Add js validation on submit for embargo section

### ISSUE THREAD

**Issue by luisgreg99** [osulp/Scholars-Archive#2014]
### Descriptive summary

Only server side validation is currently supported when assigning an embargo to a new work.

### Expected behavior

It would be nice to also validate via js to prevent a form reload (this causes fields like `contributor_committeemember` to get lost) when providing invalid embargo values.

### Actual behavior

When invalid embargo values are provided (missing release date, missing embargo reason, etc), the form validates accordingly, but it forces a form reload, which can cause other fields like `contributor_committeemember` to lose all or partial data entries in the field.

### Steps to reproduce the behavior

1. Create a new work via https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/new?locale=en
2. Fill in the required fields.
3. Fill in test data under `Committee Member`
![image](https://user-images.githubusercontent.com/3486120/71699328-d23e2b00-2d73-11ea-9025-c539645939b2.png)

4. Set embargo values
![image](https://user-images.githubusercontent.com/3486120/71699377-fe59ac00-2d73-11ea-9e9c-46e435e9065d.png)
5. Click Save
6. Validation occurs, but form is reloaded
![image](https://user-images.githubusercontent.com/3486120/71699423-3bbe3980-2d74-11ea-8f8d-834325b5e5b9.png)
7. All the previously entered fields disappear, including `Committee Member`
![image](https://user-images.githubusercontent.com/3486120/71699454-69a37e00-2d74-11ea-80fc-0912547cac0e.png)
8. At this point, the only way to recover the previously entered data, is to navigate to the previous page in the browser via the browser back button.
![image](https://user-images.githubusercontent.com/3486120/71699527-c3a44380-2d74-11ea-89c4-4326c1e65bb3.png)
Everything gets recovered except `Committee Member`, which only gets partially recovered

### Related work

This issue was found when inspecting the logs for a couple of works `d217qw94w`,`rn301749f` that were missing values under `contributor_committee` as mentioned in https://github.com/osulp/Scholars-Archive/issues/2013

**Comment by simholt** [comment]
Okay, looks like a partial fix; the first committee member field is retained now:

Entered three:

![Screen Shot 2020-12-03 at 11 16 57 AM](https://user-images.githubusercontent.com/33705514/101077140-3c99b580-3559-11eb-980a-c2f094cfb330.png)

Followed steps above and submitted w/o an embargo release date, then hit the back button to see that the first line came back but the two fields below were cleared:

![Screen Shot 2020-12-03 at 11 17 10 AM](https://user-images.githubusercontent.com/33705514/101077142-3efc0f80-3559-11eb-8d00-5a24c770c3a8.png)

**Comment by CGillen** [comment]
A partial recovery is all we can manage for multi-value fields once someone navigates away from the form. The important fix is that the form will not submit (and navigate away/reload the page) unless the embargo information is complete.
@simholt were you able to submit without an embargo release date while embargo was selected and/or did your submission cause a form reload and validation failed message?

**Comment by simholt** [comment]
@CGillen That's fine, no problem. 
And yes, it caused a form reload & validation message; I was not able to submit without embargo info. 
I'll move this to QA pass, thanks!
