### ISSUE TITLE
Embargo reason persists even if other visibility selected

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2015]
### Descriptive summary
During deposit: If someone initially chooses embargo and selects an embargo reason, but then changes their mind and **saves** the item Public, OSU, or Private, the embargo reason remains on the record. 

I removed the embargo reason by editing the record, clicking embargo, selecting embargo reason Other but not writing anything in the field, then clicking Public before saving.

### Expected behavior
If a user inputs **any** embargo information during a deposit, including a reason, choosing another type of visibility should clear embargo metadata; it should not show up on the record. (This is different from manually expiring an established embargo.)

### Actual behavior
During the deposit, user thinks they want an embargo and selects an embargo reason. They change their mind and choose Public/OSU/Private and save their work. The work shows as the proper Public/OSU/Private visibility but also has the irrelevant embargo reason.

### Steps to reproduce the behavior
1. Create new work in SA.
2. For visibility, click embargo and select an embargo reason. 
3. Click Public instead.
4. Save

**Comment by shieldsb** [comment]
@simholt What priority level would you like this ticket to have?

**Comment by simholt** [comment]
Good stuff, QA pass---
