### ISSUE TITLE
Location field breaks save/upload

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2016]
### Descriptive summary
Records with info in Geonames location field breaks after attempted upload or, when trying to edit an existing record w/location, fails the save.

### Expected behavior
User enters Geonames location information and is saved fine.

### Actual behavior
Uploading user includes location info and gets broken message.
OR
Editing user cannot save any edits/changes on a record that contains a Geonames field unless the user deletes the location field altogether.

### Steps to reproduce the behavior

1. Add location to test upload and hit save.
2. Broken message.
OR
1. Locate item in SA that already has location field.
2. Edit/add info to a field.
3. Hit save.
4. Broken message.
5. Go back in and remove location.
6. Saves fine.

**Comment by luisgreg99** [comment]
Backtrace from logs:
```
server_1            | I, [2020-01-15T23:27:02.644958 #1044]  INFO -- : Completed 500 Internal Server Error in 6079ms (ActiveRecord: 30.1ms)
server_1            |
server_1            |
server_1            | F, [2020-01-15T23:27:02.651918 #1044] FATAL -- :
server_1            | F, [2020-01-15T23:27:02.652311 #1044] FATAL -- : NoMethodError (undefined method `[]' for nil:NilClass):
server_1            | F, [2020-01-15T23:27:02.652518 #1044] FATAL -- :
server_1            | F, [2020-01-15T23:27:02.652696 #1044] FATAL -- : app/indexers/default_work_indexer.rb:23:in `block (2 levels) in generate_solr_document'
server_1            | app/indexers/default_work_indexer.rb:23:in `each'
server_1            | app/indexers/default_work_indexer.rb:23:in `map'
server_1            | app/indexers/default_work_indexer.rb:23:in `block in generate_solr_document'
```

**Comment by luisgreg99** [comment]
@simholt The fix for this issue is ready for QA testing on staging.

**Comment by simholt** [comment]
@luisgreg99 Okay, no issues with the saving or editing! However, it isn't showing anything except the first name (which is better than when it would go city-county-state- etc all the way out to Earth). But that's another issue. All good!

![Screen Shot 2020-01-22 at 11 01 10 AM](https://user-images.githubusercontent.com/33705514/72924980-c3112400-3d06-11ea-822d-7d00ce99981f.png)

![Screen Shot 2020-01-22 at 10 59 15 AM](https://user-images.githubusercontent.com/33705514/72924990-ca383200-3d06-11ea-8466-3ff831be6824.png)
