### ISSUE TITLE
Port indexing work over from OD2 to bypass long load times.

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#2018]
### Descriptive summary
https://github.com/OregonDigital/OD2/pull/939

This work fixes some of the issues that users were having with long load times.

**Comment by luisgreg99** [comment]
The update for this issue made it to production in the previous deploy (fixed by https://github.com/osulp/Scholars-Archive/pull/2026). I also did a test to double check that the PR/update works as described.
