### ISSUE TITLE
Reassign correct worktypes

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2024]
### Descriptive summary
Move items to appropriate worktype:

- [x] [Move to ETD - 4](https://docs.google.com/spreadsheets/d/1d0gzq3OJop95qJBV0_pHTuvDK9P0KmkBegTi84OFIxI/edit#gid=1939348283&range=A2)
- [x] [Move to Graduate Project - 160+](https://docs.google.com/spreadsheets/d/1d0gzq3OJop95qJBV0_pHTuvDK9P0KmkBegTi84OFIxI/edit#gid=571990439&range=A1)
- [x] [Move to Article - ~650](https://docs.google.com/spreadsheets/d/1d0gzq3OJop95qJBV0_pHTuvDK9P0KmkBegTi84OFIxI/edit#gid=740747625&range=A1)
- [x] [Move to Default - 10+](https://docs.google.com/spreadsheets/d/1d0gzq3OJop95qJBV0_pHTuvDK9P0KmkBegTi84OFIxI/edit#gid=977543458&range=B1)
- [x] [Move to Conference Proceeding - 35+](https://docs.google.com/spreadsheets/d/1d0gzq3OJop95qJBV0_pHTuvDK9P0KmkBegTi84OFIxI/edit#gid=1735930427&range=A2)
- [x] [Move to Honors College Thesis - 7](https://docs.google.com/spreadsheets/d/1d0gzq3OJop95qJBV0_pHTuvDK9P0KmkBegTi84OFIxI/edit#gid=0&range=A2)
- [x] [Move to Undergraduate Thesis - 9](https://docs.google.com/spreadsheets/d/1d0gzq3OJop95qJBV0_pHTuvDK9P0KmkBegTi84OFIxI/edit#gid=766778766&range=A1)

**Comment by wickr** [comment]
All requested changes have been completed.
