### ISSUE TITLE
Clean up the way the attributes are rendered

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#2028]
We need to clean up the way the attributes are rendered. This is partially reliant on #2027 since that would at least get the terms out into normalized lists in the models. 

After that is done, we can see if any of the lists exactly aligns with the way that the attributes are rendered. If they do, then we can iterate over those terms to render the attributes.

We can also create a second list and use that as the "ordered list" when rendering attributes. 

One thing to note is the models differ relatively greatly through out the system. So careful consideration needs to go into that.

**Comment by CGillen** [comment]
Closed by #2481
