### ISSUE TITLE
Bulk Edits: 19 Feb 2020

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2041]
- [x] [Change 622 resource types](https://docs.google.com/spreadsheets/d/1WFdJUz51WHTu_Tqfg9oDd5CFgKOulnWbr3qI2UE7u1k/edit#gid=0&range=A2)

- [x] [Remove/replace 1348 duplicate dates](https://docs.google.com/spreadsheets/d/1H7FFR-1yoErJezK0UtmQAGmIbEeZKisERkQ_QD_2ZNc/edit#gid=2034224029&range=A2)

- [x] [Remove 22 empty strings](https://docs.google.com/spreadsheets/d/1tA86kT4uv-UQFrWbghaIWKN1N7vdkA2-ETPexHe9on4/edit#gid=0&range=A2)

**Comment by straleyb** [comment]
@simholt I ran these. Good for QA to see if the changes were correct. I took a peek and it seemed right based on the sheets.

**Comment by simholt** [comment]
Looks good to me, also -- thanks!
