### ISSUE TITLE
pin solr to 6-slim in docker-compose.yml

### ISSUE THREAD

**Issue by decimalator** [osulp/Scholars-Archive#2051]
### Descriptive summary
The container image for solr is currently solr:alpine in docker-compose.yml. This will pull the latest 8.x slim image. Current solr configs don't work with versions > solr:6-slim

### Related
https://github.com/osulp/Scholars-Archive/issues/2001
https://github.com/osulp/Scholars-Archive/pull/2009

**Comment by luisgreg99** [comment]
QA Pass:

I pulled the update https://github.com/osulp/Scholars-Archive/pull/2108 and it worked well in my machine. It also resolved an issue that I was having in my solr configuration in development environment.
