### ISSUE TITLE
Bulk Edits: 27 Feb 2020

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2058]
- [x] [1548 Language corrections](https://docs.google.com/spreadsheets/d/1t07YJhzGXUK0y2PXZesUC-FXVUYQqIALys5Lk2pHHGA/edit#gid=0&range=A2)

- [x] [Lots of date cleanup -> 20119, may need to be broken into chunks](https://docs.google.com/spreadsheets/d/1lSRsWTj8mxMBnldGsISs3nWKZEhq0tVM9ckTw0awXxQ/edit#gid=1039006030&range=A2)

**Comment by straleyb** [comment]
@simholt I processed the first language corrections. If you wanna take a look at those and QA, they should be fine. Lots of data cleanup will be next.

**Comment by simholt** [comment]
@straleyb All good!

**Comment by simholt** [comment]
@straleyb 
Is this complete?

**Comment by straleyb** [comment]
Yes
