### ISSUE TITLE
Staging Cleanup: administrative_report_or_publications worktype only allows Private visibility

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2075]
### **ONLY HAPPENING ON STAGING**
Items uploaded as administrative_report_or_publications default to Private visibility and don't allow the user to choose another.

![Screen Shot 2020-03-12 at 2 52 06 PM](https://user-images.githubusercontent.com/33705514/76569848-5518eb80-6471-11ea-80f8-43763eb6e596.png)

### Expected behavior
User can choose whatever visibility they want.

### Actual behavior
 https://ir-staging.library.oregonstate.edu/concern/administrative_report_or_publications/rj430463s 

Upload page defaults to Private and the user cannot click on the other bullets.

### Steps to reproduce the behavior

1. Deposit test item in AdminReport worktype on staging.
2. Try to change visibility.

**Comment by straleyb** [comment]
Administrative report had been set to no embargo. This forced all visibility settings to private. This has been remedied by setting it to embargoes of any length and setting to all visibility settings. 

<img width="1301" alt="Screen Shot 2020-05-15 at 12 41 55 PM" src="https://user-images.githubusercontent.com/6424683/82090034-a465dd00-96a9-11ea-8ece-db73ed822662.png">

**Comment by simholt** [comment]
I don't see that this ever went through QA. It is still happening on staging:

![Screen Shot 2020-12-02 at 2 43 28 PM](https://user-images.githubusercontent.com/33705514/100940456-d5bec280-34ac-11eb-86d1-3f4d451c713b.png)

**Comment by CGillen** [comment]
This is an odd one to have come back but it was the same problem. The admin set for Administrative Reports was set to no embargos and only private visibility. Fixed by updated the admin set settings to match production.

**Comment by simholt** [comment]
All the options now available -- QA pass
