### ISSUE TITLE
Encoding Issue with HAML file apostrophe 

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#2078]
### Descriptive summary

![image](https://user-images.githubusercontent.com/6424683/80248794-7bf83f00-8625-11ea-8813-daeede8e7cda.png)

**Comment by mellinma** [comment]
It looks like it was fixed.  but maybe with the rollback it won't be anymore? 

![Screen Shot 2020-07-07 at 11 47 58 AM](https://user-images.githubusercontent.com/11778515/86828185-bdef2980-c047-11ea-86cd-83e76bf1ae33.png)

**Comment by wickr** [comment]
This was fixed directly here: https://github.com/osulp/Scholars-Archive/blob/c635cb3e95e31b0cf7e69b8634d385fa424bd67a/app/assets/html/500.html.haml

and it should be included in deploys going forward.
