### ISSUE TITLE
Staging Cleanup: Purchased e-Resource workflow

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2092]
### Descriptive summary
PURCHASED ER -- Workflow for $ER incorrect. 

### Expected behavior
Deposits to $ER go to Pending Review.

### Actual behavior
Does not go through review process. Deposited item skipped review altogether, went right to published:
https://ir-staging.library.oregonstate.edu/concern/purchased_e_resources/th83kz46f

### Steps to reproduce the behavior

1. On staging, deposit item to Purchased e-Resource worktype.
2. Item goes to published.

**Comment by straleyb** [comment]
<img width="1572" alt="Screen Shot 2020-05-15 at 12 36 37 PM" src="https://user-images.githubusercontent.com/6424683/82089597-c14de080-96a8-11ea-9b1b-ffc06607bcd4.png">

Fixed. Default Admin Set Workflow was wrong on staging. This has been updated and remedied.
