### ISSUE TITLE
Manager gets broken message when trying to update Version of a file

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2124]
### Descriptive summary
Grad School Julie keeps encountering the broken message when she tries to upload a new version of a file. This first happened on 15 July. I have not been able to recreate this problem myself.

![Screen Shot 2020-07-22 at 11 09 22 AM](https://user-images.githubusercontent.com/33705514/88212292-df394380-cc0b-11ea-9d61-e2419ae6696d.png)

### Expected behavior
User navigates to bottom of show page, clicks on Versions, selects a file, and uploads it successfully.

### Actual behavior
User gets broken message when she clicks on Versions on the show page. This happened most recently with item `6q182s91d`

**Comment by luisgreg99** [comment]
Error backtrace from logs for `6q182s91d` when accessing member file set `vq27zv969`
```
1021908:I, [2020-07-22T08:45:44.774822 #22299]  INFO -- : [e664ae44-16ed-4a40-82b8-ae8bc6884a28] method=GET path=/concern/file_sets/vq27zv969/edit format=html controller=Hyrax::FileSetsController action=edit status=500 error='NoMethodError: undefined method `admin_set' for #<FileSet:0x000056248a1afc70>' duration=185.07 view=0.00 db=8.50 params={"locale"=>"en"} time=2020-07-22 08:45:44 -0700
1021909:F, [2020-07-22T08:45:44.776306 #22299] FATAL -- : [e664ae44-16ed-4a40-82b8-ae8bc6884a28]
1021910:F, [2020-07-22T08:45:44.787376 #22299] FATAL -- : [e664ae44-16ed-4a40-82b8-ae8bc6884a28] NoMethodError (undefined method `admin_set' for #<FileSet:0x000056248a1afc70>):
1021911:F, [2020-07-22T08:45:44.787439 #22299] FATAL -- : [e664ae44-16ed-4a40-82b8-ae8bc6884a28]
1021912:F, [2020-07-22T08:45:44.787484 #22299] FATAL -- : [e664ae44-16ed-4a40-82b8-ae8bc6884a28] app/models/ability.rb:29:in `block in custom_permissions'
```
From error backtrace, edit page (for a file set possibly coming from the show page via the versioning_display) is failing at https://github.com/osulp/Scholars-Archive/blob/77cf85d19d1559fbaa87d70debf5397120e87548/app/models/ability.rb#L29 Related to https://github.com/osulp/Scholars-Archive/pull/2107

**Comment by luisgreg99** [comment]
This one is ready for QA. To recreate the error, I had to become a non-admin user and become a manager in a collection like GTD. The existing work for the test also had to be owned by a different user. Editing versions worked if I was already the owner, but it failed with the broken message when the work was owned by someone else.

**Comment by simholt** [comment]
QA pass -- no problems adding a new version to an item Greg uploaded.
