### ISSUE TITLE
Span closing tag displaying at bottom on 'More Facets' modal

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#2128]
### Descriptive summary

Clicking on a 'More' button on a facet pops up the modal interface to show more options. At the bottom by the next/previous navigation, a `</span>` displays by the buttons.

![image](https://user-images.githubusercontent.com/2293544/88699279-fa98c880-d0bb-11ea-8b72-942b15b49aa8.png)

### Expected behavior
`</span>` is not shown to the user.

### Actual behavior
`</span>` is shown to the user.

### Steps to reproduce the behavior

1. Visit search page: https://ir.library.oregonstate.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=
2. Click Degree Field facet to open
3. Click 'more'

**Comment by simholt** [comment]
All good here, QA Pass--
![Screen Shot 2020-12-02 at 2 18 37 PM](https://user-images.githubusercontent.com/33705514/100938299-4c59c100-34a9-11eb-9b00-d3c84a1a63e1.png)
