### ISSUE TITLE
Display private works in the review queue for admin users

### ISSUE THREAD

**Issue by luisgreg99** [osulp/Scholars-Archive#2129]
### Descriptive summary

While doing QA for https://github.com/osulp/Scholars-Archive/issues/1878 on staging, @simholt discovered some inconsistencies in the review queue as an admin user specific to private works.

Private works with status "pending review" for Undergrad Thesis or Project and "published" for Default were not showing up in the queue as an admin user. These were listed in the "All Works" tab, but not in the review queue. For these works to be available in the queue, the admin user had to be added to the Admin Sets as a "manager".

### Expected behavior
Admin users should have access to all works with status "under review" and "published" via the "Review Submissions" tab.

Options:
1. Manually add admin users to every admin set as a "manager" role
2. Patch "Review Submissions" to allow the user to view all works in the queue regardless of the admin set responsibilities
    - proposed patch available in branch [feature/patch-for-admin-users-to-view-all-submissions-under-review](https://github.com/osulp/Scholars-Archive/compare/feature/patch-for-admin-users-to-view-all-submissions-under-review)

### Actual behavior
I posted my observations regarding my tests in https://github.com/osulp/Scholars-Archive/issues/1878#issuecomment-665188905. In summary, the queue filters out private works in the "Review Submissions" table based on the admin set responsibilities regardless of the "admin" user role.

### Steps to reproduce the behavior
Setup: Become an "admin" user, and remove "manager" roles in the Admin Sets for "Default" and "Undergrad Thesis or Project"

For Default work:
1. Start a new "Default" work
2. Set visibility to private
3. Submit work
4. Go to "Review Submissions" tab
5. Private work is not being listed in the "Published" tab

For Undergrad work:
1. Start a new "Undergrad Thesis or Project" work
2. Set visibility to private
3. Submit work
4. Go to "Review Submissions" tab
5. Private work is not being listed in the "Under Review" tab

### Related work

I have an initial attempt to patch "Review Submissions" table to allow admin users to access all works in branch [feature/patch-for-admin-users-to-view-all-submissions-under-review](https://github.com/osulp/Scholars-Archive/compare/feature/patch-for-admin-users-to-view-all-submissions-under-review)

**Comment by lamtu1** [comment]
Fixed by #2434
