### ISSUE TITLE
Label time series graph

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#213]

**Comment by zhang4952** [comment]
Add label to x and y-axis

**Comment by zhang4952** [comment]
_flot_stats in pr#213

**Comment by zhang4952** [comment]
Need to be re-based to latest SA and update the PR

**Comment by vantuyls** [comment]
Can i see a screenshot of what this looks like?

**Comment by zhang4952** [comment]
http://hydra-sa-dev.library.oregonstate.edu/files/gm80hv344/stats

**Comment by vantuyls** [comment]
Need to label these with labels that can be understood by others. Also, the labels need to be centered on the axes

x-axis label: Date
y-axis label: Number of Pageviews or Downloads
