### ISSUE TITLE
Translation missing error with blacklight_range_limit Submit button

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#2137]
### Descriptive summary

Translation error causing blacklight_range_limit on Date facet to not work:

![image](https://user-images.githubusercontent.com/2293544/94474546-a7f29000-0182-11eb-988e-a1b8393526e2.png)

### Expected behavior

Date facet range selection should work the same regardless of locale

### Actual behavior

Date facet range selection is broken locales other than 'en'

### Steps to reproduce the behavior

1. Visit https://ir.library.oregonstate.edu/catalog?locale=es
2. click on Date facet

**Comment by CGillen** [comment]
This does not seem to be an issue anymore:
fr:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/11052958/125696214-233d6a89-5fdc-4387-afaa-baece274b604.png">
it:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/11052958/125696236-c9713fca-54bc-4d08-b285-58f270fcd69e.png">
pt-br:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/11052958/125696278-71df0237-3435-4256-98da-357399a09f0d.png">
zh:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/11052958/125696316-29574c18-6251-4f20-9dc2-4c594a02d812.png">
