### ISSUE TITLE
Translations missing in footer make it unusable

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#2138]
### Descriptive summary

When selecting a locale other than 'en' the footer text strings are missing translations and the whole footer is unusable. 

![image](https://user-images.githubusercontent.com/2293544/94475075-6c0bfa80-0183-11eb-9537-ab73344cd201.png)

A couple of the text strings in the 'es' locale are working.

### Expected behavior

Footer has text strings in all locales, even if they fall back to English, links work

### Actual behavior

Footer has text strings identifying the fields but no useful info

### Steps to reproduce the behavior

1. Visit https://ir.library.oregonstate.edu/?locale=fr
2. Look at footer

**Comment by simholt** [comment]
QA pass
