### ISSUE TITLE
Thumbnail image tiny dupe or black

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2143]
### Descriptive summary
PDF uploads to SA resolve with thumbnail errors. This has mostly happened with batch uploads of $ETDs but occasionally with single deposits. I've experimented with replacing the file, deleting the file and uploading again, and cleaning up/saving the PDF to archival standards. They still upload with the error but the file appears fine after download. This suggests something is wrong with the PDF but I don't know what.

Here are some of the problem deposits:
https://ir.library.oregonstate.edu/concern/purchased_e_resources/ms35tg89n
https://ir.library.oregonstate.edu/concern/purchased_e_resources/r207tw699
https://ir.library.oregonstate.edu/concern/defaults/cz30px94x
https://ir.library.oregonstate.edu/concern/purchased_e_resources/x633f676w
https://ir.library.oregonstate.edu/concern/purchased_e_resources/gb19fd46v
https://ir.library.oregonstate.edu/concern/purchased_e_resources/j6731986q
https://ir.library.oregonstate.edu/concern/purchased_e_resources/p8418v42v
https://ir.library.oregonstate.edu/concern/defaults/r781wh454
https://ir.library.oregonstate.edu/concern/defaults/6d56zx853
****This is most recent and the only one I did not upload myself:****
https://ir.library.oregonstate.edu/concern/defaults/0k225j64c 

ETA another: https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/c247f052w

### Expected behavior
Thumbnail is tiny version of PDF.

### Actual behavior
Thumbnail looks like this:
![Screen Shot 2020-10-09 at 9 18 50 AM](https://user-images.githubusercontent.com/33705514/95607702-f9b3d980-0a10-11eb-8739-5302353099f7.png)

![Screen Shot 2020-10-09 at 9 18 45 AM](https://user-images.githubusercontent.com/33705514/95607714-fc163380-0a10-11eb-8396-e2568a938dce.png)

### Steps to reproduce the behavior
1. Download a PDF from one of the above URLs.
2. Deposit the file.

**Comment by simholt** [comment]
Did a bunch of uploads using items that came up w/weird thumbs on prod, all's well here! QA pass --

**Comment by wickr** [comment]
I re-created derivatives on the FileSets for the works above and the thumbnails all look to be fixed.
