### ISSUE TITLE
Update triplestore-adapter.

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#2147]
### Descriptive summary

Need to update to the newest version of triplestore-adapter. This needs extra testing to make sure all the endpoints are still working properly, specifically for the fetching of CVs in the fetch_graph_worker stuff.

**Comment by CGillen** [comment]
Triplestore adapter is currently set to latest main branch:
https://github.com/osulp/Scholars-Archive/blob/main/Gemfile.lock#L25C1-L27
https://github.com/osulp/Scholars-Archive/blob/main/Gemfile#L69
