### ISSUE TITLE
Staging Cleanup: Article worktype does not allow embargoes

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2157]
### **ONLY HAPPENING ON STAGING**
If uploading to article worktype, system does not allow user to select an embargo. 

![Screen Shot 2020-12-02 at 2 39 19 PM](https://user-images.githubusercontent.com/33705514/100941300-461a1380-34ae-11eb-8b60-6e8c43364e19.png)

### Expected behavior
User can choose whatever visibility they want.

### Actual behavior
Embargo bullet is greyed out and cannot be selected.
https://ir-staging.library.oregonstate.edu/concern/articles/4x51hj180

### Steps to reproduce the behavior

1. Deposit test item in Article worktype on staging.
2. Try to set an embargo.

### Related work

#2075

**Comment by CGillen** [comment]
Same issues as #2075, admin set settings were out-of-sync with production. Updated to match.

**Comment by simholt** [comment]
Embargo available! QA pass--
