### ISSUE TITLE
Get admin stats dashboard working on the staging server

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#216]
The issue that we are having is, we are getting a 503 error when visiting the /admin/stats page. We need to figure out what is causing the faulty request (faulty uri or configuration)

**Comment by zhang4952** [comment]
The problem is caused by staging server points its solr to lib-solr1.library.oregonstate.edu:8985/hydrair-stage-core, so the new solrconfig.xml only updated to localhost but not the actual solr server. Deploy the new config to lib-solr1 and test to make sure it works
