### ISSUE TITLE
Contributor field not updating/indexing

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2163]
### Descriptive summary
When doing name cleanup in the Advisor, Committee Member, etc. fields using the limiter interface, I noticed the same names do not collate properly for Contributor. Contents can be exactly the same, with no spaces or mistakes, and remain on separate lines.

![NoCollate](https://user-images.githubusercontent.com/33705514/102937598-63b01c80-445f-11eb-93c9-fa18cc5c5cb0.png)

It would be a good idea to make sure this is not a problem in any of the other fields.

### Expected behavior
When using the limiter to sort items, there should be only one entry for each term.

### Actual behavior
Same name listed multiple times for Contributor.

### Steps to reproduce the behavior

1. Click **Contributor** in Limit your search.
2. Click **More**
3. Click **A-Z Sort**
4. Click both **Adamus, Paul R.** links, edit each document to have "Adamus, Paul R." as a Contributor and Save.
5. Reload Contributor page and see Adamus, Paul R. is still on two lines.

**Comment by wickr** [comment]
Yeah, the text of the name is the same but the indexed value includes the 'index' of the nested ordered field objects. 

The first link has `%240` after the name
`https://ir.library.oregonstate.edu/catalog?f%5Bnested_ordered_contributor_label_ssim%5D%5B%5D=Adamus%2C+Paul+R.%240&locale=en&q=&search_field=all_fields`
The second facet link has `%242` after the name
`https://ir.library.oregonstate.edu/catalog?f%5Bnested_ordered_contributor_label_ssim%5D%5B%5D=Adamus%2C+Paul+R.%242&locale=en&q=&search_field=all_fields`

`%24` is url encoded for `$` as a separator, followed by the numerical index value. 

This shouldn't be in the facet values at all though, and removing it should cause the names to collapse together as intended.

A quick look at https://github.com/osulp/Scholars-Archive/blob/master/app/models/concerns/scholars_archive/has_solr_labels.rb#31 seems to show that all of the nested ordered fields will have the same indexing behavior. Assuming both the document fields and facet fields are using the same code for indexing, something different will have to be done, to remove the index value from facets.

**Comment by simholt** [comment]
All good -- QA pass

![contrib](https://user-images.githubusercontent.com/33705514/108571318-c76e8e80-72c4-11eb-9552-9e8401329ff6.png)
