### ISSUE TITLE
Set time frame (x-axis) on large time series graph to 3 months - each point representing one day

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#217]

**Comment by luisgreg99** [comment]
@vantuyls: I was able to set the initial time frame on the x-axis to be 3 months (from 3 months ago to yesterday). I have an example
![image](https://cloud.githubusercontent.com/assets/3486120/10917500/ed62f55e-8215-11e5-8596-02be9b87ea3f.png)

**Comment by luisgreg99** [comment]
By default, the intervals on the x-axis is set to be 1 week per tick. Is this the preferred interval?

**Comment by vantuyls** [comment]
It's fine for now.

**Comment by zhang4952** [comment]
Rebase to latest SA and update PR
