### ISSUE TITLE
Deposit skipped review queue

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2181]
### Descriptive summary
Deposit by student to Other/Default worktype went right to deposited status. Did not go into Pending Review queue. Review notifications were not sent out.

https://ir.library.oregonstate.edu/concern/defaults/7m01bt408

### Expected behavior
Items deposited to Other/Default worktype go into Pending Review.

### Actual behavior
Skipped queue, went live on SA.

**Comment by CGillen** [comment]
After combing through logs and the process by which the admin set is chosen when coming to the new work form, I can only conclude this value is being changed by user mistake.

I've taken off my own admin role, and found that depositors can still see the `article` admin set.

I've messed with `admin_set_map.yml` and the associated `admin_set_select_service.rb` to see if the `default` work type isn't properly selecting an admin set, but it is defaulting to `Default Admin Set` as expected. I was able to get a `default` work to default to `Article` admin set by messing withe `admin_set_map.yml` so the mechanism seems to be working correctly.

I also noticed that the two works this happened to recently have been `defaults` that should have been `articles`. I can only guess that the depositors knew they wanted to deposit an article but ended up in default by mistake. Once they got to the relationship tab they saw something that could be changed to article and did so, not knowing what an admin set is.
Locking admin set changes down, per #2166, would fix this flow.
