### ISSUE TITLE
Capitalize all sort option labels for consistency

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#2184]
### Descriptive summary

In the search results sort options dropdown, only the title options are capitalized. Consistency is good, so we should capitalize all the sort options.

### Expected behavior

All options are capitalized.

### Actual behavior

Only Title options are capitalized.

### Steps to reproduce the behavior

1. Do a search
2. Select sort options dropdown to see options

### Related work

Related to #2182

**Comment by simholt** [comment]
Good catch, @wickr! Looks great, QA pass --
