### ISSUE TITLE
Allow admins to view full text OCR on an item's page

### ISSUE THREAD

**Issue by CGillen** [osulp/Scholars-Archive#2193]
### Descriptive summary
As outlined in #1408, admin's would like to be able to see the OCR text as a debug tool. This can be either on the work show page or disabled in the edit form.

**Comment by lamtu1** [comment]
@CGillen I'm currently looking at this ticket hoping to tackle it as my next ticket. I understand what OCR do and we made implementation towards the search result to display this via highlight of the word search. Wondering what kind view does OCR  produce that admin wants to look like for example? Would it be something similar to the suggestion Ryan W made with this link: https://www.not-implemented.de/hocr-proofreader/

**Comment by CGillen** [comment]
In ScholarsArchive's case, we don't need the editor necessarily. I think what we would most like to see is a new tab on the edit form, with either an text edit block or some well formatted display of the full text field. Be careful of some cases where full text is VERY long. That can impact load time significantly. I would rather have a truncated (or better, paginated) version than a form that takes > ~5sec to load

This isn't for editing the OCR, it's just for getting a better understanding of what the system is seeing

**Comment by lamtu1** [comment]
So based on that, below is a step-by-step what I think it will happen based on what you said and feel free to make any suggestions.

`Step #1`: Go to the `edit button` and click on it
<img width="1358" alt="Screenshot 2023-06-08 at 1 45 56 PM" src="https://github.com/osulp/Scholars-Archive/assets/111306182/417d40bb-c21c-4240-b490-548e53deb239">

`Step #2`: Have a tab either in one of those area and if it is an admin, there a link to redirect them to a new page and display full text
<img width="1242" alt="Screenshot 2023-06-08 at 1 46 37 PM" src="https://github.com/osulp/Scholars-Archive/assets/111306182/6947d47b-6d51-4361-8620-1e19c5476b30">

`Step #3`: Display the `full text` in a view we can set up as a text display to display content similar to the picture below
<img width="822" alt="Screenshot 2023-06-08 at 1 48 33 PM" src="https://github.com/osulp/Scholars-Archive/assets/111306182/8da2344f-cb8c-4083-bcae-1b5251f1f321">

**Comment by CGillen** [comment]
I think we'd prefer it to not be a new page, but just a new tab view on the `description` `doi` `files` `relationship` section.
Other than that, looks good

**Comment by lamtu1** [comment]
Fixed by PR #2504

**Comment by CGillen** [comment]
@carakey @simholt Please continue to QA. This was pushed as a necessity to deploy and keep GA4 in place
