### ISSUE TITLE
Add admin/manager-only Documentation field

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2200]
### Descriptive summary
Would like a field visible only to and usable only by admin and managers for documentation purposes. This would be a place to track communication with patrons about any embargo and visibility changes and other situations.

MAP would then need to be updated.

### Expected behavior
- Documentation field visible only to admin and managers to track changes to and info about a record.
- Large text box.
- Admin and managers add any relevant info.
- Edit page: Documentation field shows up last, under **Identifier**
- Show page: Documentation field shows up as second-to-last field, below **Additional Information** and above **Depositor**

### Actual behavior
Any changes to a deposit happen without documentation on the record.

**Comment by CGillen** [comment]
Closed by #2278
