### ISSUE TITLE
Bulk edit: missing date_uploaded_dtsi

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2201]
Substitute `system_create_dtsi` for missing `date_uploaded_dtsi` data from previous bulk ingest.

- [x] [Bulk Edits: Colls missing date_uploaded_dtsi](https://docs.google.com/spreadsheets/d/1PWq0Q7BORdt2FEGLDn_lSN_760pZCllzNJsAzzwqoJQ/edit?usp=sharing) All info on first tab - 180 items

### Related work
#2063
#1874

**Comment by wickr** [comment]
The edit task completed with no errors. Final count was 178 works.

**Comment by wickr** [comment]
The new dates are showing up in the JSON view, I checked a couple since this doesn't appear on the show page.

**Comment by wickr** [comment]
The values were saved, but weren't getting indexed, due to the values being a String and not a DateTime object. I wrote a small script to convert the new values and they look to be indexed correctly now, correct values are in the SolrDocument.

```ruby
irb(main):020:0> w2.date_uploaded
=> Thu, 11 Mar 2021 22:00:23 -0800
irb(main):021:0> w1.date_uploaded
=> "2019-05-31T22:12:57Z"
irb(main):022:0> w1.date_uploaded.class
=> String
irb(main):023:0> w2.date_uploaded.class
=> DateTime
irb(main):024:0> w1.date_uploaded.to_datetime
=> Fri, 31 May 2019 22:12:57 +0000
```

**Comment by simholt** [comment]
QA pass -- all good
