### ISSUE TITLE
Investigate why date_uploaded_dtsi missing from bulk ingest

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2202]
### Descriptive summary
Items for batch ingests linked below are missing `date_uploaded_dtsi` data. This is problematic because it impacts (minimally) the sort by date function.

This needs to be fixed before we can perform further bulk ingests. It appears to be the only missing field.

[Bulk ingest instructions](https://github.com/osulp/Scholars-Archive/wiki/Perform-Bulk-Ingest).

### Related work
#2063
#1874

**Comment by simholt** [comment]
@wickr Here is a [ten-item test batch](https://docs.google.com/spreadsheets/d/1LrIme5OMiQJKGifM2CvmT5NkWYJSpHRruA1AB-aQ9rc/edit?usp=sharing) for QA.

FYI: this has a different visibility (authenticated) than previous bulk ingests. It also has **Related Items** which we've not done before. I wasn't sure which terms to use; I pulled these from the MAP:

- nested_related_items > label
- nested_related_items > related_url

**Comment by CGillen** [comment]
Ingested test batch to staging: https://ir-staging.library.oregonstate.edu/collections/3n203z262?locale=en
Looks like the works & metadata worked. The `date_uploaded_dtsi` was set in solr to the time of ingest:
```
> sd = SolrDocument.find('707957863')
> sd['date_uploaded_dtsi']
=> "2021-05-17T20:14:17Z"
```

@wickr I followed https://github.com/osulp/Scholars-Archive/wiki/Perform-Bulk-Ingest as best I could but file attachments never worked.
And @simholt, some of your fields weren't recognized. `visibility` and `nested_related_items > label/related_url` didn't want to go through (maybe ingest task needs some work) and the collection id obviously changed. Adding `nested_related_items` support is a different issue, but it can be prioritized for this week if you need it
