### ISSUE TITLE
Bulk edits: 3 Mar 2021

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2203]
≈2K changes to complete DOI and language fields.

- [x] [Direct link to relevant tab](https://docs.google.com/spreadsheets/d/1xAyTUrrJEoLxSLPOQyrQGc27142NmChvlZYHHzxGRgU/edit#gid=1647004067) SA Bulk Edits: Need English + DOI

**Comment by wickr** [comment]
All updates are completed. There was one error, on zk51vm38r though it appears as that one has been deleted.

**Comment by simholt** [comment]
QA pass -- not sure about that deleted one.
