### ISSUE TITLE
Initial deposit of file not being recorded

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2208]
### Descriptive summary
Initial deposit of file not being recorded under User Activity. Changes such filenames are being recorded.
***
### Expected behavior
Item deposited before Friday:
![File___LaiChung-Ping2021_pdf___ID__z890s207r___ScholarsArchive_OSU](https://user-images.githubusercontent.com/33705514/110522607-ebeca800-80c5-11eb-9ca2-e08c023f77f2.png)
***
### Actual behavior
Item deposited Monday:
![rose](https://user-images.githubusercontent.com/33705514/110522820-2f471680-80c6-11eb-881b-49a3824a49eb.png)
***
### Steps to reproduce the behavior

1. Deposit a file.
2. Check user activity on file.

**Comment by CGillen** [comment]
Fixed by #2211
