### ISSUE TITLE
Browse Everything cloud files add not working

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2215]
### Descriptive summary
User selects a file to attach but it never closes out so the is user stuck with the pop-up window. 
@wickr was able to make it work by deleting the elements for the Browse Everything modal dialogs w/in the browser.

### Expected behavior
User selects Add cloud files on the Files tab, chooses appropriate files, clicks Submit, then the file is attached.

### Actual behavior
User selects Add cloud files, chooses files, and then is stuck with the window. Attachment does not appear to complete, cancel says it works but doesn't and user has to close window to escape.

### Steps to reproduce the behavior

1. Go to edit on any existing work and click on Files tab.
2. Add cloud files.
3. Choose file.

**Comment by wickr** [comment]
Browse Everything is working but not closing after clicking Submit (or Cancel).
The workaround is to manually delete the elements for the modal and the spinner, which returns control to Hyrax, and then one can submit the new file to attach.

# Select file(s) in Browse Everything dialog modal
# click Submit
# Modal says 100% complete, but does not close
# Use Developer Tools. In Chrome, right-click on dialog modal, click Inspect
# Make sure the dialog is highlighted, look up a few levels for element/code: `<div class="modal-dialog modal-lg">`, right-click on that line and select 'Delete Element'
# After deleting that one, it's probably the next highlighted one, look for `<div tabindex="-1" id="browse-everything" ...`, and right-click on that line and select 'Delete Element'
# That should close both the modal and the spinner, and the selected file can then be submitted as expected

**Comment by simholt** [comment]
Was able to attach test file without getting stuck, is listed on show page. QA pass--
