### ISSUE TITLE
Force academic_affiliation to show up in English

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2216]
### Descriptive summary
Academic affiliation for Linus Pauling Institute shows up in Chinese instead of English. This is a [Wikidata authority](https://www.wikidata.org/wiki/Q3151762).

### Expected behavior
English

### Actual behavior
Chinese

### Steps to reproduce the behavior

1. [View any of these items](https://ir.library.oregonstate.edu/catalog?q=%E9%AE%91%E6%9E%97%E7%A0%94%E7%A9%B6%E9%99%A2&search_field=other_affiliation_label).

**Comment by wickr** [comment]
All works are fixed. 
Found one other label that was English but was the long form of LPISM and wasn't faceting with the others, that's fixed too.

I had to manually edit the RDF graph returned from wikidata and save that to blazegraph. Steps to do that extend the existing ones for force-clearing cached labels and are here: 
https://github.com/osulp/Scholars-Archive/wiki/Update-Fetched-Label-and-Reindex#fixing-problems-with-fetched-labels
