### ISSUE TITLE
Make Related Items label show as plain text

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2221]
### Descriptive summary
The Related Items field links to other resources and information about a deposit. Clicking the label text creates a "Search for this item in SA" while the actual link is accessible by clicking the arrow image. Although the help text explains this, the field would be more functional and less confusing if the label text was not clickable.

### Expected behavior
Label text is plain.

### Actual behavior
User clicks on label text expecting to go to the link and instead does an unwanted search.

![Other_Scholarly_Content___Shaping_the_Public_Good__Women_Making_History_in_the_Pacific_Northwest___ID__02871359d___ScholarsArchive_OSU](https://user-images.githubusercontent.com/33705514/113911498-e9e23b80-978e-11eb-9cc2-2ac63c6dab21.png)

### Steps to reproduce the behavior

1. View any item with Related Items ([example](https://ir.library.oregonstate.edu/concern/defaults/02871359d))
2. Hover and click

**Comment by wickr** [comment]
Related to https://github.com/osulp/Scholars-Archive/issues/1557

**Comment by simholt** [comment]
Link free -- QA pass
<img width="521" alt="Screen Shot 2021-07-19 at 11 34 04 AM" src="https://user-images.githubusercontent.com/33705514/126209749-e0972e10-24c3-4c97-b2dc-ca0138a6d2c0.png">
