### ISSUE TITLE
Change "Featured Researcher" tab text to more general term

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2223]
### Descriptive summary
We need a less-specific term than "Featured Researcher" for the right primary tab on the homepage, something that will support a blurb about a wider variety of topics.

Right now there are four tabs:
![Screen Shot 2021-04-22 at 4 55 28 PM](https://user-images.githubusercontent.com/33705514/115798636-8c074380-a38b-11eb-8d93-1d8b281a414e.png)

First we need to decide what a good term would be. Suggestions?
- ScholarsArchive Spotlight
- [something] Highlight
- Featured Deposits
- [something] Focus
- 👀

**Comment by wickr** [comment]
I think just 'Spotlight' would be good. I don't feel it needs to be two words, but could also do 'Research Spotlight'

**Comment by simholt** [comment]
Okay I talked to others and let's go with "Spotlight" as replacement text!

**Comment by simholt** [comment]
Looks good - QA pass
<img width="387" alt="Screen Shot 2021-07-19 at 10 57 34 AM" src="https://user-images.githubusercontent.com/33705514/126205292-1111e57a-e545-41a6-933f-bb7c81debf97.png">
