### ISSUE TITLE
Unable to add ETDs to appropriate collection

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2224]
### Descriptive summary
Only get broken message when attempting to add ETDs to their collection. I've tried from the Relationships tab on the ingest page and from the collection edit page. This started on or around 22 March 2021. Adding to other collections has been fine, albeit slow at times.

### Expected behavior
ETDs can be added to their [collection](https://ir.library.oregonstate.edu/collections/j3860c90v?locale=en).

### Actual behavior
The Graduate Theses and Dissertations collection can be selected and added from the Relationships tab but it fails upon save and you get the broken message.

### Steps to reproduce the behavior
1. Choose a [recently uploaded ETD](https://ir.library.oregonstate.edu/catalog?f%5Bresource_type_sim%5D%5B%5D=Masters+Thesis&locale=en&q=&search_field=all_fields)
2. Try to add it to the Graduate Theses and Dissertations collection

**Comment by CGillen** [comment]
This looks like it's because the GTD collection has grown too large and our resource management (PumaWorkerKiller and Monit) are set too aggressive for this workflow. I've upped the memory limit a bit which should take effect next production deploy.
I'll come back to this ticket once we deploy and see how it's going

**Comment by CGillen** [comment]
Looks like the same problem. I bumped the memory limit again (6.5GB => 8.5GB). We'll see what happens next deploy.
This should be completely solved once we're in the cluster though

**Comment by simholt** [comment]
FYI: I just checked and this is still an issue.

**Comment by CGillen** [comment]
This has been a combination of fixes. Clusterization centralized our application monitoring and resource management, allowing Rails to balloon enough to handle indexing our huge collections. Removing `PumaWorkerKiller` gem and upping `Puma`'s worker timeout allowed the worker long enough to respond back. I doubled that time out to 2 minutes, but it is easily configurable higher if necessary:
https://github.com/osulp/Scholars-Archive/pull/2335/files#diff-24409379bdb75ad446bb4e2c18fd4cced1a263b99a3ff96fc3777d8fd8faeab9R17

**Comment by simholt** [comment]
Added a handful to the collection, times ranged between 3.5-4.5 minutes. 
A batch add to the collection from the [Works page](https://ir.library.oregonstate.edu/dashboard/works?f%5Badmin_set_sim%5D%5B%5D=Graduate+Thesis+or+Dissertation&f%5Bsuppressed_bsi%5D%5B%5D=false&locale=en&page=2) broke.
It will take a while to backfill all the ETDs to the collection; I might make a spreadsheet instead.

**Comment by decimalator** [comment]
increasing Puma worker timeouts will prevent the worker from exiting before backend stuff completes. there may be other timeouts we're hitting, like Faraday for individual requests to SOLR, Fedora, etc.

https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts#faraday

(Also includes timeout configurations for other Ruby gems)
