### ISSUE TITLE
Bulk edits: 28 Apr 2021

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2226]
About 10K changes for description field.
[
Direct link to relevant tab](https://docs.google.com/spreadsheets/d/1YsXDiHir6EDPBxzzeGsI3UkA4zwuYm9tvSP05QY4bxU/edit#gid=205714637&range=A1): SA Bulk Edits: description - Batch 1

**Comment by wickr** [comment]
Update task completed. The several I checked all look good.
