### ISSUE TITLE
Bulk Ingest: Press

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2237]
### Descriptive summary
[Bulk ingest of 73 Press titles.](https://docs.google.com/spreadsheets/d/1fyeqd7CBbMNwX3lfORopLy7BgzDWQAV_pZXtMsoNPZs/edit#gid=233835545&range=A1)

### Related work
#2063
#1874

**Comment by wickr** [comment]
73 titles ingested successfully on 6/4 and 6/5.
Derivatives look good (nothing by default for ePubs).
Nested Related Items content exists on the works, but is not appearing on show page.

**Comment by simholt** [comment]
Thanks @wickr -- I'll go thru and check things out.

**Comment by simholt** [comment]
Overall, good, with all items with correct visibility and in collection.
Few problems fixed after opening item to re-save:
- Related Items visible on Edit page but not show page. Clicked to add new line and saved, reindexed fine.
- Abstract and Creator not showing up on results page.
![Screen Shot 2021-06-16 at 3 26 46 PM](https://user-images.githubusercontent.com/33705514/122302661-45c7ef80-ceb7-11eb-94e7-d3e423ea4900.png)
