### ISSUE TITLE
Enable Authenticated visibility on bulk ingests

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2249]
### Descriptive summary
We need to support submission for items that use Authenticated (OSU-only) visibility. The code needs to be changed and reference notes left in the wiki.

[Test ingest](https://docs.google.com/spreadsheets/d/1LrIme5OMiQJKGifM2CvmT5NkWYJSpHRruA1AB-aQ9rc/edit#gid=0&range=A2)

### Actual behavior
Currently can only upload with public/open visibility.

### Related
#2202

**Comment by CGillen** [comment]
Wiki updated: https://github.com/osulp/Scholars-Archive/wiki/Perform-Bulk-Ingest#spreadsheet-details
Includes optional `visibility` column, allowed values, and mentions `Public` as default value.
