### ISSUE TITLE
Bulk edits: 18 May 2021

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2252]
About 5K changes for description and peer reviewed fields.

Direct link to relevant tab: [SA Bulk Edits: description_batch2](https://docs.google.com/spreadsheets/d/1GGHr_tiTr3mji-gC43Tqyi-ZOZ4joZoS3eLEHBgHrxA/edit#gid=205714637&range=A2)

**Comment by wickr** [comment]
Started this about an hour ago.

**Comment by wickr** [comment]
The update task completed. Spot checks look good.

**Comment by simholt** [comment]
QA pass, all good here.
