### ISSUE TITLE
Items listed in review queue despite being approved + edits no show

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2262]
### Descriptive summary

Have two submissions that still show in the review queue even though they have been approved. Also, corrections don't appear on the show page even though you can see them when you click through to the edit page. One is an ETD (listed as being in Graduate School Review) and the other is in the default worktype (Pending Review). They have had days to correct and are still stuck.

https://ir.library.oregonstate.edu/concern/defaults/6w924k50m
https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/9c67wv53b

### Expected behavior
Items disappear from the review queue after they are approved. Edits show up on the show page shortly after being saved.

### Actual behavior
Two items are lingering on the review page and the corrections are not listed on the show page even though they are visible when you view the edit page.

### Steps to reproduce the behavior

1. View either of the links above. Both are listed as Deposited on the show page but are listed in Review in the queue.
2. Make and edit and wait for it to show up.

**Comment by simholt** [comment]
It looks like the item in the default worktype has cycled through; it no longer shows up on the review queue. The ETD is still listed as being in Graduate School Review.

**Comment by simholt** [comment]
The student contacted me about not being able to view the submission. I was able to edit and save the submission this morning and it is no longer in the queue. Not sure what happened but it looks like everything is okay now.

**Comment by straleyb** [comment]
Closing since the two works don't show up in the review queue anymore.
