### ISSUE TITLE
Bulk edits: 14 July 2021

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2276]
About 1300 changes for series and subject fields.

Direct link to relevant tab: [Kiln Conferences](https://docs.google.com/spreadsheets/d/1bEV1zWRNOBtbIemF22nlRPbzVAo1HZcKXmvHyDWAZZU/edit#gid=1697507573&range=A1)

**Comment by wickr** [comment]
All edits are completed.

About midway through I realized the http URIs should have been the text labels, since SA doesn't natively pull the labels (outside of the form autocomplete). So I stopped and updated the CSV, removing the URIs and replacing with the matching labels.

**Comment by simholt** [comment]
QA pass!
