### ISSUE TITLE
Build view to assign embargo on generic file

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#230]
On the edit page (when generating a new asset, it creates it initially then takes you to the edit page)

**Comment by straleyb** [comment]
Lastly, add the necessary view pieces (embargo date picker and after embargo visibility to the ingest form) to allow a user to customize embargo visibility.

**Comment by luisgreg99** [comment]
@vantuyls Here's an updated version of the embargo view: 
![image](https://cloud.githubusercontent.com/assets/3486120/11005197/590987f2-8471-11e5-825b-989f44c15d0d.png)
