### ISSUE TITLE
Spam from contact form

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2306]
### Descriptive summary
We're getting a lot of spam from the [contact form](https://ir.library.oregonstate.edu/contact?locale=en). 

### Expected behavior
Some spam.

### Actual behavior
Too much spam (like 20 a day).

**Comment by CGillen** [comment]
https://cisomag.eccouncil.org/google-recaptcha-bypass-vulnerability/
😬 Yikes! Google defeats itself on it's own captcha service. reCaptcha is basically useless for more sophisticated bots. We should try a honeypot and see if that adds any additional detection: https://github.com/markets/invisible_captcha

**Comment by simholt** [comment]
Captcha has disappeared!
https://ir.library.oregonstate.edu/contact

**Comment by simholt** [comment]
I'm getting less spam overall (the test below went thru) so that is good!

<img width="517" alt="Screen Shot 2022-02-23 at 1 33 30 PM" src="https://user-images.githubusercontent.com/33705514/155412275-0a964721-1d7c-4cc4-82f2-582e7e3620ce.png">
