### ISSUE TITLE
Batch uploads not working

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2315]
### Descriptive summary
All necessary fields completed, files load, etc. but goes directly to broken message after hitting submit button.

**Comment by decimalator** [comment]
looks like a routing error?

https://ui.honeycomb.io/osulp/datasets/scholars-prod/result/r8rmyXPwuQ5/trace/krS6dEhZtRU?span=7928dc3b7da44906

**Comment by simholt** [comment]
@CGillen 
So I don't have any pre-problem emails but the notifications in my SA include the subject heading and text:

<img width="658" alt="Screen Shot 2022-03-09 at 10 13 17 AM" src="https://user-images.githubusercontent.com/33705514/157504826-6a1e82b3-84de-41fb-810e-49ae5850654c.png">

Expected emails for batch submissions:
**Passing batch create** for admin/managers (I don't think this goes to the depositor)
**Deposit needs review** to admin/managers
**Thank you for your deposit to ScholarsArchive@OSU** to depositor

Actual emails:
The notifications show up in SA but are not sent out via email.

**Emails for non-batch submissions are fine**

**Comment by CGillen** [comment]
```
SCHOLARSARCHIVE_SMTP_HOST
SCHOLARSARCHIVE_SMTP_PORT
SCHOLARSARCHIVE_SMTP_ENABLED
```
Env Vars were not set for `workers` on staging or production. Values are set and I got emails off of staging

**Comment by simholt** [comment]
I rec'd the expected emails: passing batch create and deposit needs review. BUT the individual thank you emails were the dataset ones. (From tix #2324) 

--- 
<img width="679" alt="Screen Shot 2022-03-10 at 7 11 12 AM" src="https://user-images.githubusercontent.com/33705514/157691605-eb8277f1-b1ab-4c19-b452-4faa972aba5e.png">

The message below should be the default thank you response:

---
<img width="688" alt="Screen Shot 2022-03-10 at 7 09 41 AM" src="https://user-images.githubusercontent.com/33705514/157691290-32afd29f-6e89-45da-8006-9047bb2fa90e.png">
