### ISSUE TITLE
Upgrade Solr from 6.6.6 to the latest 8.x

### ISSUE THREAD

**Issue by CGillen** [osulp/Scholars-Archive#2319]
### Descriptive summary
```
next local WC can we look at upgrading SOLR from 6.x to 8.x? Under heavy load, the SOLR nodes tend to crash. solr-2 died about 65 minutes ago and has been resyncing with the cluster leader. It's stable under normal load, but reindexes are pushing SOLR 6.x past what it can reliably handle

not to mention when it happens the leader grabs tons of RAM, solr-0 has 31GB of RAM active atm :exploding_head:
```
Solr 6 is causing cluster instability and resource hogging. @rordway believes an upgrade to solr8 should help smooth out heavy solr loads

### Expected behavior
Solr 8.x in development and cluster

### Actual behavior
Solr 6.x in development and cluster

### Steps to reproduce the behavior
Start reindex-by-chunk job in B8S
See Solr nodes fall over
See Solr leader grab tons of RAM

**Comment by simholt** [comment]
We are still on 6?

**Comment by decimalator** [comment]
still on SOLR 6.6.6. OD2 has been running on 8.x since very early development. it started with 6.6.6 but upgraded to 8.x.

**Comment by decimalator** [comment]
Completed
