### ISSUE TITLE
Cleanup from Jan migration 

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2320]
- [ ] 8k71np40p — is missing files 
- [x] bg257n90h — can be deleted
- [x] r781wp633 — can be deleted

The two to be deleted are ghosts - they show up in the review queue but do not exist and I cannot delete them from my end. (They were previously deleted items and **should** be deleted!)

**Comment by CGillen** [comment]
@simholt If I re-attach the files for `8k71np40p` what user should I attach them with? You? Me? Andrew?

**Comment by CGillen** [comment]
Attaching as myself.
That should be everything in this ticket. Hopefully #2322 catches everything else
