### ISSUE TITLE
Transferred items disappear from Works page

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2350]
### Descriptive summary
After a transfer is accepted, the transferred item no longer shows up on the [Works](https://ir-staging.library.oregonstate.edu/dashboard/my/works?locale=en) page, not under All Works for Admin or the new user's Your Works. This is a barrier for users who want to easily view the item. It does show up if you search for it on the Works page or a regular search.

### Expected behavior
After a transfer is accepted, the item should show up on the Your Works tab for the person who accepted the transfer. It should be listed on the All Works tab for Admin. It should not be listed on the original owner's Your Works.

### Actual behavior
The item is not listed on the works page under any tabs.

### Steps to reproduce the behavior

1. Do a transfer request + acceptance.
2. Check the Works page.

### Related work
#2321

**Comment by CGillen** [comment]
Turned out to be a sorting issue that pushed works off the page 🤣
