### ISSUE TITLE
Update fixity checking service

### ISSUE THREAD

**Issue by CGillen** [osulp/Scholars-Archive#2373]
### Descriptive summary

SA is using a version of auditing/fixity checking that doesn't seem to be in Hyrax anymore:
https://github.com/osulp/Scholars-Archive/blob/master/lib/tasks/fixity_check.rake#L5

We should use the newest documented format:
https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#fixity-checking

This is so @rordway can implement a cron job to run on SA for fixity checking. Part of our Core Trust work

### Expected behavior
Fixity checking runs with more recent `Hyrax::RepositoryFixityCheckService`.

### Actual behavior
Fixity checking runs with `Hyrax::RepositoryAuditService`, which I don't see anymore

### Steps to reproduce the behavior
`rake scholars_archive:fixity`

**Comment by lamtu1** [comment]
Fixed by PR #2416 & #2417
