### ISSUE TITLE
Files not attaching to submissions

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2378]
### Descriptive summary
Files are not showing up for deposits, only a record without a file. This happened to two students on Friday. I got a PDF from one of the students to add the file today and it does not show up. Also created a new submissions to test -- the file uploads but never attaches.

1j92gg16j
3j333941j
Test item: wm117x251

### Expected behavior
Files are uploaded and show up.

### Actual behavior
Files upload but not saved/attached to record.

### Steps to reproduce the behavior
1. Create new work.
2. Attach file.
3. File doesn't stick.

**Comment by CGillen** [comment]
Workers had failed overnight; No indicator as to why. Workers restarted and seem to be running fine (for now).
