### ISSUE TITLE
Docker image optimizations

### ISSUE THREAD

**Issue by decimalator** [osulp/Scholars-Archive#2380]
### Descriptive summary

Our Docker images are pretty massive. The Surfliner team has shared some of their optimizations. We should spend some time using the same techniques in our containers.

Smaller images will help improve build and upload times, lower storage use across the cluster and make container boot times much faster.

https://gitlab.com/surfliner/surfliner/-/blob/comet-docker/comet/Dockerfile

**Comment by CGillen** [comment]
QA is testing/using most of the site and seeing if anything breaks. Ingests, edits, derivatives, metadata, fileset metadata, admin dashboard, almost all of it. This removed some packages that looked useless, but who knows what could have been used where
