### ISSUE TITLE
Batch uploads - uploads but no edit

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2381]
### Descriptive summary
Batch uploads break when you deposit ~~more than two items at a time. Upload 3+~~ ➡️ the items appear to process normally, but the **Contributor** field has an empty string and clicking edit goes to a blank screen. It doesn't appear to matter if the **Contributor** field is filled or not.

Example items:
0r967b775
c534fx23q
t722hj01z
bc386s298

![Screen Shot 2022-05-03 at 9 13 15 AM](https://user-images.githubusercontent.com/33705514/166492839-b447d459-ba2b-4dc8-8a3f-2ce3dc579273.png)
--- 
### Expected behavior
Batch uploads allow more than one item at a time.

### Actual behavior
No luck!

### Steps to reproduce the behavior

1. Click [Batch upload](https://ir.library.oregonstate.edu/batch_uploads/new?locale=en&payload_concern=TechnicalReport)
2. Deposit 3+ works.
3. After they process, click Edit button.

**Comment by CGillen** [comment]
@simholt Not sure what could have changed, but is this still happening? I'm not seeing it locally or on staging.
1. Batch upload 3+ different files
2. Set all to `Technical Report`

3a. Fill required metadata & leave contributor empty
4a. Open created work, see no contributor field
5a. edit created work, contributor not filled & form working

3b. Fill required metadata & fill contributor
4b. Open created work, see filled contributor field
5b. Edit created work, contributor filled & form working

**Comment by simholt** [comment]
@CGillen Just did a test batch on prod and it was fine ... weird glitchy thing that has somehow resolved? Closing this, thanks for checking it out.
