### ISSUE TITLE
[Notifications] When i find an item in SA@OSU I want to be able to send a notification to the author/owner of the item

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#240]
e.g. to ask for a copy of the article. 

Like an "Email the Author" button...

**Comment by revgum** [comment]
File may not be visible, so allow user to request access to the bits.

**Comment by straleyb** [comment]
Assuming PCDM is in.

**Comment by vantuyls** [comment]
current functionality does not allow this as an option. Specifically, and especially with Hyrax 2.1, the default behavior of Hyrax is that private content will not be discoverable to most users, making the concept of a button to request access moot.
