### ISSUE TITLE
Time stamp for comments

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2403]
### Descriptive summary
Timestamps would add valuable context to comments in the Review and Approval pane.

### Expected behavior
Posted comments include date and time (HH:MM) so it's easier to follow up on lingering and problematic submissions that require changes.

### Actual behavior
It's not obvious when comments by users or admin were left. Users have to go to the notifications page to get a general idea.

**Comment by simholt** [comment]
@lamtu1  The date and time formatting is perfect! I like the italics.
BUT -- the spacing for multiple comments looks like it could get confusing (what comment when). Can we remove the spacing between the date/time and comment so it is obvious which ones go together -- more like what is currently on prod.

Staging right now:
<img width="288" alt="Screen Shot 2022-11-07 at 9 59 03 AM" src="https://user-images.githubusercontent.com/33705514/200381731-24a5922b-d048-4e61-a474-c9dd373f14b4.png">

Currently on prod:
<img width="285" alt="Screen Shot 2022-11-07 at 9 56 36 AM" src="https://user-images.githubusercontent.com/33705514/200381622-e7521228-f30e-4710-93ff-90a92a965134.png">

**Comment by lamtu1** [comment]
@simholt Yes, I will try to make the spacing fit the comment under the datetime so it would not be difficult to identify which comment belong to which one.

**Comment by lamtu1** [comment]
@simholt, I have given two different way for spacing between comments, would any of them looks good?

Option 1: Not adding margin bottom to the spacing between comment
<img width="556" alt="Screenshot 2022-11-07 at 10 20 31 AM" src="https://user-images.githubusercontent.com/111306182/200387835-daa12c49-6a63-43e8-9468-314c2a01e75a.png">


Option 2: Adding  20px margin bottom to the spacing between comment
<img width="566" alt="Screenshot 2022-11-07 at 10 36 13 AM" src="https://user-images.githubusercontent.com/111306182/200388309-a9a7bf6c-9b16-4b3a-ab1b-99319107dc1b.png">

**Comment by simholt** [comment]
Let's go with Option 2!

**Comment by lamtu1** [comment]
Sarah passed this
