### ISSUE TITLE
Add CoreTrustSeal logo to ScholarsArchive

### ISSUE THREAD

**Issue by carakey** [osulp/Scholars-Archive#2407]
### Descriptive summary

ScholarsArchive@OSU has been certified as a Trustworthy Data Repository by the CoreTrustSeal Standards and Certification Board until 22 Sep 2025. We need to add their logo to the site. 

Their instructions:
> 
> Please place the CoreTrustSeal logo on your repository website with the link to the public version of your application. ( Link: https://www.coretrustseal.org/wp-content/uploads/2022/09/20220922-ScholarsArchive@OSU_final.pdf )
> 
> The CoreTrustSeal logo can be downloaded here: https://drive.google.com/drive/folders/1UpXrzQ5dAfobCVwFKtgDC_uS0NT1yeX-

**Comment by carakey** [comment]
Presenting a few options from other repositories for consideration:

* Logo in footer: https://ladsweb.modaps.eosdis.nasa.gov ; https://podaac.jpl.nasa.gov ; https://rda.ucar.edu ; many others
* Logo in header: https://conservancy.umn.edu/drum
* Logo with CTS blurb in About pages: https://daac.ornl.gov/about/
* Logo with CTS blurb on front page body: https://scholarsmine.mst.edu ; https://merritt.cdlib.org

**Comment by simholt** [comment]
I'm for logo in footer (bottom right corner?) and logo+blurb on the About page.

**Comment by carakey** [comment]
The CTS working group all concur with Sarah's preference for (1) the logo in the footer, bottom right corner, linking to our application; and (2) the blurb on the About page. 

(1) can proceed at any time. I will follow up with specifics for (2).

**Comment by simholt** [comment]
QA pass for the footer + associated PDF. 
<img width="423" alt="Screen Shot 2022-11-07 at 10 02 40 AM" src="https://user-images.githubusercontent.com/33705514/200382631-6c1489e5-be57-4376-8471-fea39555d017.png">

@carakey You/we can populate the About page [here](https://ir-staging.library.oregonstate.edu/pages/edit?locale=en).
