### ISSUE TITLE
Add summary report to fixity check job

### ISSUE THREAD

**Issue by CGillen** [osulp/Scholars-Archive#2421]
### Descriptive summary

With #2373 fixed, fixity checks are running again. Now we need a way to report out to Cara & Sarah how many passed/failed. By default Hyrax sends out an email to the depositor for every file set that fails. That can be a lot of spam and it goes to the users, not us.

Before the job runs, we should ensure that no emails can go out (possibly be an env var, though I don't know of a case where we might want them to go out).

After the job runs, we should query `ChecksumAuditLog` for some information and send it to `scholarsarchive@oregonstate.edu`.

### Expected behavior
The `scholars_archive:fixity` rake task includes the following:

- [ ] Prevent emails for the fixity checks
- [ ] Enables a final email after all checks are ran
- [ ] Sends an email to `scholarsarchive@oregonstate.edu` with the following information
  - [ ] Start time
  - [ ] End time
  - [ ] Count of File Sets checked
  - [ ] Count of File Sets passed
  - [ ] Count of File Sets failed
  - [ ] IDs of File Sets failed

These stats should only be from `ChecksumAuditLog` that were created by the latest run. Easiest would be to do `where` queries against the start time.

### Actual behavior
Fixity checks are ran and `ChecksumeAuditLog` entries are created in the DB, no reports

### Steps to reproduce the behavior
`rake scholars_archive:fixity`

### Related work
#2373 
#2414

**Comment by lamtu1** [comment]
Fixed by PR #2430

**Comment by carakey** [comment]
Sarah and I have not been receiving these emails, either at scholarsarchive@oregonstate.edu or at our individual emails.

**Comment by lamtu1** [comment]
@carakey when running the fixity check job, at the end, it never send out the email?

**Comment by lamtu1** [comment]
@carakey or @simholt Can you guys check to see if `scholarsarchive@oregonstate.edu` received a test email in regards of fixity? thank you

**Comment by simholt** [comment]
@lamtu1 Yes, it went through!

**Comment by lamtu1** [comment]
@carakey @simholt Look like the original code of the mailer is working as expected with that test email. I wonder how long do we want to have the fixity run to do a daily check on the FileSets? like once a month or couple weeks?

**Comment by carakey** [comment]
@lamtu1 -- @CGillen said it's set up to run the automatic check on the 15th every month, which is good with me.

**Comment by carakey** [comment]
> @carakey Did the SA email never receive the report once we run it back in May?

@lamtu1 Correct, the SA email did not receive the report in May. 

If I'm understanding, the fixity checks have been running monthly since roughly last summer, and the test yesterday was the first email report I've seen.

**Comment by lamtu1** [comment]
Ah I see, I will take a look into this problem and update you on it

**Comment by lamtu1** [comment]
@carakey @simholt I'm going to do a manual run of the rake task on staging to see if the email will get send out, and will deduce from there on to find out the problem.

**Comment by carakey** [comment]
These emails have been getting delivered to the SA email since June, and they have the expected info.
