### ISSUE TITLE
Add job status log message to end of fixity check job

### ISSUE THREAD

**Issue by CGillen** [osulp/Scholars-Archive#2426]
### Descriptive summary
>can we get a last log line that says it's all done? we get a bunch of "Performing" and "Performed" and all the debug logging but nothing to indicate it finished successfully, other than the status of the Job - Ryan O

After the fixity check job completes we should add a log message indicating we have finished
`All fixity checks complete`

Bonus points if you can expand on #2421 and add the summary data

### Expected behavior
Log message at the end of fixity check job

### Actual behavior
All log messages are only related to performing/performed and no notice of finishing

### Steps to reproduce the behavior
Run fixity check job
Check last log message

### Related work
#2421

**Comment by lamtu1** [comment]
Fixed by PR #2430
