### ISSUE TITLE
[Geo] When i enter a URI for geonames the labels should be fetched

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#243]
Depends on #301

**Comment by mickeroo** [comment]
Depends on #144

**Comment by revgum** [comment]
Could be a good starting point for implementing into SA: https://github.com/OregonDigital/oregondigital/blob/d82d944d55dd087d2670b3f065725ef0e5ddc4ce/lib/oregon_digital/controlled_vocabularies/geographic.rb
