### ISSUE TITLE
Fetch English label(s) for Wikidata URI(s)

### ISSUE THREAD

**Issue by carakey** [osulp/Scholars-Archive#2492]
### Descriptive summary

We got a report that a non-English label "Laynus Polinq İnstitutu" is currently appearing for the Linus Pauling Institute Wikidata entity in the Non-Academic Affiliation field. This URI `http://www.wikidata.org/entity/Q3151762` appears in 23 works, and all are showing the non-English label.
 
Broadly, make sure we are fetching the English language label by default for Wikidata entities, though I'm not seeing any other instances of Wikidata URIs with non-English labels at this time.

### Expected behavior

The URI `http://www.wikidata.org/entity/Q3151762` appears with the label "Linus Pauling Institute" when a user is viewing an SA page in English. English terms appear as the default for Wikidata URIs. 

### Actual behavior

The URI `http://www.wikidata.org/entity/Q3151762` appears with the label "Laynus Polinq İnstitutu" on 23 SA works. This is listed as the Azerbaijani label on the Wikidata entity page. 

I think I'm only seeing two other Wikidata URIs in SA and both are appearing as English: 
[Pacific Marine Energy Center](http://www.wikidata.org/entity/Q7060130) and [Oregon State University Cascades Campus](http://www.wikidata.org/entity/Q7101371) 

### Steps to reproduce the behavior

1. Search for URI or label (in quotes) "http://www.wikidata.org/entity/Q3151762" or "Laynus Polinq İnstitutu" 
2. Click on Non-Academic Affiliation filter and note non-English label
3. View any work in results list and note non-English label in Non-Academic Affiliation field

Also, the depositor reported selecting the English label on the drop down, but getting the other version after saving.

### Related work

Link to related tickets or prior related work here.

**Comment by simholt** [comment]
### Related work

 #2216

**Comment by carakey** [comment]
QA pass - details:
Created a test work https://ir-staging.library.oregonstate.edu/concern/articles/pk02c995f?locale=en with the Linus Pauling Institute and other two Wikidata URIs mentioned above. All labels appear in English. There is another work on staging that has the same Pauling URI that shows in Azerbaijani, so I expect those will need to be re-fetched after the fix goes in.
