### ISSUE TITLE
Add download statistics option to contact form

### ISSUE THREAD

**Issue by carakey** [osulp/Scholars-Archive#2509]
### Descriptive summary

We need an option for "Requesting download statistics" included in the "Issue Type" drop-down on the [contact form](https://ir.library.oregonstate.edu/contact). Until we restore the Analytics view or have a better option, the [User Guide](https://guides.library.oregonstate.edu/c.php?g=708682&p=5729323) is pointing to the Contact Form asking users to request download stats from us directly. 

### Related work

https://github.com/osulp/Scholars-Archive/pull/2508

**Comment by lamtu1** [comment]
Fixed by PR #2510
