### ISSUE TITLE
Restrict Degree Level drop-down list options

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2522]
### Descriptive summary

To encourage accuracy and make the deposit process earlier, limit the degree level drop-downs to the only correct choices for specific worktypes. ➡️ This is based off a previous ticket (#1925); I'm not sure what happened since it doesn't appear to be functioning. I have added more details to this ticket.

### Expected behavior

Worktype: Graduate theses or dissertations
Degree Level:

- Doctoral
- Master’s
- Other

Worktype: Graduate Projects
Degree Level:

- Certificate
- Doctoral
- Master’s
- Other

Worktype: Undergrad Thesis/Projects
Degree Level:

- Bachelor’s
- Other

Worktype: Honors College Thesis
Degree Level:

- Bachelor’s
- Other
**This one is already auto-select Bachelor's -- I would like Other added.**

### Actual behavior
Students select from long list and make mistakes.

### Related work

#1925

**Comment by lamtu1** [comment]
@simholt I was wondering, do you want the `Undergrad Thesis/Projects` and others to select a degree automatically when creating a new work like the one in `Honor` or just filter it out and leave the `Honor` to be the only one selected?

**Comment by simholt** [comment]
@lamtu1 It would be appropriate only for `Undergrad Thesis/Projects` to auto-select `Bachelor’s` since `Graduate theses or dissertations` and `Graduate Projects` have too many options; depends on student being in a masters or doctoral program.

(If it is easier to have none of them select than all, that's fine.)

**Comment by lamtu1** [comment]
The one for the `Undergrad Thesis/Projects` is doable and I can just leave the other as blank but filter out to only have those options only.

**Comment by simholt** [comment]
`Undergrad Thesis/Projects` and `Honors College Thesis` both look good!

`Graduate theses or dissertations` and `Graduate Projects` -- I think this is fine for now. I noticed that if the user chooses the Degree Name _before_ the Degree Level, they are able to select and save a mismatch. 

<img width="296" alt="Screenshot 2023-09-15 at 9 58 51 AM" src="https://github.com/osulp/Scholars-Archive/assets/33705514/090e0897-74c8-47a6-b4c8-3538d21a641a">

Keeping in mind we're at the end of the sprint and perfect is the enemy of the good -- future work in this area can introduce validation, etc. but this will help reduce mistakes. @carakey, what do you think?

**Comment by carakey** [comment]
@simholt I agree - I expect most depositors will just go top to bottom, so this will prevent a majority of errors. Let's move forward with what we have, and make a new ticket for the validation piece.
