### ISSUE TITLE
Fileset links to works in review are redirecting to SA homepage

### ISSUE THREAD

**Issue by carakey** [osulp/Scholars-Archive#2524]
### Descriptive summary

Our grad school reviewer, Sean, reported this bug. While reviewing GTDs, when he scrolls down to the "Items" section near the bottom of the work page to access a file, the links take him to the SA homepage instead of the file.

This behavior was seen by Sean on at least two unrelated works. I was not able to reproduce the behavior (with an admin account). The "Download PDF" link at the top opens the file as expected.

<img width="1025" alt="image" src="https://github.com/osulp/Scholars-Archive/assets/17655103/f4f8fde4-4373-450e-be2a-fe28e616895e">

### Expected behavior

The links under Items > Title take a user to the fileset landing page (provided the user's role matches up with the fileset's visibility setting). 

### Actual behavior

The link under Items > Title take a user to the SA homepage.

### Steps to reproduce the behavior

Unable to reproduce from an admin account. 

### Related work

This is new behavior after the latest push to production. Seems possibly related to #2010.

**Comment by lamtu1** [comment]
@carakey @simholt I also tried to reproduce this on all platform `local`, `staging`, and `production`. I am not seeing anything wrong with it, all link seems to link to the `file sets` view page totally fine. I don't know if that is a weird glitch we have but I would say we can put this in backlog. And if this problem occur again, we have a ticket to go back to. If not, we can close it and open a new one when the problem occur again. But right now I'm not seeing the problem to the linking of the file sets.

**Comment by shieldsb** [comment]
@simholt Is Sean still experiencing this issue?

**Comment by simholt** [comment]
Nope I think we can close!
