### ISSUE TITLE
Some other_affiliations not on show page or limiters

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2532]
### Descriptive summary
Newly assigned `other_affiliations` based on LC URIs are not displaying on show pages or under the Non-Academic Other limiter. ONS and Wikidata ones are fine. LC servers can be very busy, but this has been happening a lot and I can't find any pattern; it is us or them?

### Expected behavior
When a user selects a Non-Academic Other, it should be listed after the save on the show page and be collated with others under limiters.

### Actual behavior
`other_affiliations` with LC URIs don't show up, although they can be viewed if you go in to edit or if you pull the id with Solr. 
Example: https://ir.library.oregonstate.edu/concern/defaults/3r075360h has Hatfield listed as Non-Academic Other (LC URI: http://id.loc.gov/authorities/names/n84131837) but it is not on the show page.

I removed a Non-Academic Other from a work where it was shown correctly, then went in and added it again, and it did not show up.

Some other LC authorities:
http://id.loc.gov/authorities/names/n79115395
http://id.loc.gov/authorities/names/n79100852
http://id.loc.gov/authorities/names/n80126175

**Comment by simholt** [comment]
### Steps to reproduce the behavior

1. Go into existing work and select Hatfield as a Non-Academic Other
2. Save
3. See Hatfield is not on show page
4. (Clean up and delete your addition!)

**Comment by simholt** [comment]
I can add those URIs now but they are not resolving to the correct text on the show page:

**EDIT PAGE:**
![Screenshot 2023-11-07 at 3 32 56 PM](https://github.com/osulp/Scholars-Archive/assets/33705514/a6fcfb9c-2360-4fb1-82ad-e34fdbaae8a9)


**SHOW PAGE:** 
![Screenshot 2023-11-07 at 3 32 47 PM](https://github.com/osulp/Scholars-Archive/assets/33705514/dcf2b960-72b0-44d3-9377-104ed6a334e9)

**Comment by lamtu1** [comment]
@simholt Would you like the show page to display the naming convention like in the `edit` form rather just a URL link? or would you want the naming convention to show up with the hyperlink to their specific affiliation?

**Comment by simholt** [comment]
Cannot test until staging is sorted.

**Comment by simholt** [comment]
So there are words showing up instead of URIs, but they are not the LC authorities. Example:`qv33rw93b`

<img width="378" alt="Screenshot 2024-01-08 at 4 15 33 PM" src="https://github.com/osulp/Scholars-Archive/assets/33705514/31ce068f-8407-4eeb-afa1-119201063b4f">

We use basic names in the dropdown to help users, but the show page needs to reference the official LC authorities:

URI: http://id.loc.gov/authorities/names/n79100852
LC Authority: Oregon State University. Sea Grant College Program
SA basic dropdown: Oregon Sea Grant

**Comment by simholt** [comment]
Not seeing any affiliations now, LC URIs or otherwise.

**Comment by lamtu1** [comment]
Hi @simholt, was this work just got created or was it already created before the updated code got added in?

**Comment by simholt** [comment]
That work was just created but they aren't showing on earlier ones, either.
