### ISSUE TITLE
STAGING: error messages on save new works (article and default) + skipping workflow (default)

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2545]
### Descriptive summary
Error messages when saving article and default new work (oops can't find that page). Can reload and view page, but the default ones skip the review queue (articles don't have to review). Sometime also changes itself to a private visibility.

### Expected behavior
Ability to upload.

### Steps to reproduce the behavior
Add new article or default item to staging.

### Related work

 #2287

**Comment by simholt** [comment]
✅ Deposits saved okay for article and default.
Default upload has the Pending Review button on the show page - `2r36tx73z` - but the review queue is empty.

**Comment by CGillen** [comment]
Is the review queue still empty for you?
<img width="1182" alt="image" src="https://github.com/osulp/Scholars-Archive/assets/11052958/f32ea03f-45e1-47c8-9d72-5674bb9feb27">
I have `Testing error messages on save new works + skipping workflow #2545` (2r36tx73z) in my view

**Comment by simholt** [comment]
It is populated!

**Comment by simholt** [comment]
Aaaaaand we are back to the review queue not being populated.

**Comment by CGillen** [comment]
I'm marking my place here while I switch off to another issue.

I'm pretty sure this is related to an already reported Hyrax issue: https://github.com/samvera/hyrax/issues/6001
We could clean up sipity entities (workflow tracking BS) that point to deleted works, but this will likely crop back up when we delete works that are still in review.

**Comment by CGillen** [comment]
Cleaned up Sipity Entities on staging and pushed fix. lets see how this works

**Comment by simholt** [comment]
Okay --
There **are** items in the Review Submissions page but none of mine (new/old) show up, even when I re-save them. They have the correct Pending Review buttons. When I sort My Works for those in review, the correct ones show up. They do not show up on the Review Submissions page.

**Comment by CGillen** [comment]
@simholt I think the review queue is now sorted oldest to newest. I can find `2r36tx73z` in the review queue at the very end. I'll get working on that

**Comment by CGillen** [comment]
😞 So... fedora just needed a restart.
Upside deposits work again 😄😭

**Comment by simholt** [comment]
Alright -- able to submit new works, with the proper ones going to the review queue and articles going straight to published. QA pass

**Comment by CGillen** [comment]
Fixed through console shenanigans
