### ISSUE TITLE
Fixity reports failing

### ISSUE THREAD

**Issue by CGillen** [osulp/Scholars-Archive#2551]
### Descriptive summary

Fixity checks run 8pm every 15th. They've been running but failing out on the phantom filesets from #2530. This is preventing the report from finishing and being sent out.

I think we're going to have to figure out how to fully remove these filesets for fixity to finish and give us a report.

### Expected behavior
Fixity checks finish & delivers a report

### Actual behavior
Fixity checks fail on phantom FileSets and error out, causing no fixity report to be produced

### Steps to reproduce the behavior
Run `rake scholars_archive:fixity` on production and wait.... wait a long time. Or just review last fixity check cronjob run through logs

### Related work
#2530

**Comment by carakey** [comment]
If this is pushed to production before the next scheduled run, Monday the 15th, then we can confirm whether receive the report and give it a resounding QA pass at that point.

**Comment by carakey** [comment]
I assume this is expected as I don't think it made it to production before the 15th, but just noting that the fixity report did not go out for a scheduled January 15 check.

**Comment by carakey** [comment]
It's still not clear whether this fix is in production, but again noting that no fixity report was received for a scheduled February 15 check.

**Comment by CGillen** [comment]
Code is on production, fixity will run tonight
