### ISSUE TITLE
Embargoes not expiring - staging and prod

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2556]
### Descriptive summary
Cara noticed the embargoes on sample items listed in #2032 had not expired as they should. Not sure if this is a config issue with the new version?

I checked prod just because and there are unexpired embargoes starting 6 Jan 2024 until 10 Jan 2024 (today). Scroll to bottom of embargo management page to see: https://ir.library.oregonstate.edu/embargoes

Q: How often is the rake task running?

I created a test article that should expire tomorrow: https://ir-staging.library.oregonstate.edu/concern/articles/t722h901h

### Expected behavior
System releases embargoed items on a daily basis.

### Actual behavior
Release appears to have stopped.

### Related work
#2356

**Comment by straleyb** [comment]
@simholt Are you ok with closing this now that the cron job is running again?

**Comment by simholt** [comment]
yes!
