### ISSUE TITLE
Search bar is spilling over the page boundaries

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#256]

**Comment by zhang4952** [comment]
Not responsive

**Comment by mickeroo** [comment]
It looks like the size of that field was set to 650px on line 34 in this commit, which stops it from being responsive: https://github.com/osulp/Scholars-Archive/commit/9449b8612d1d9463fc3738c61094db3cb706dd6b 

If it was added to address issues in the ingest form, maybe the solution would be to have a more specific selector for just the .input-group on the ingest form.
