### ISSUE TITLE
Dataset worktype needs Documentation field

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2566]
### Descriptive summary
An admin/manager-view-only documentation field was added to all models except datasets in 2021. It is a place to track communication with patrons about any embargo and visibility changes and other situations. We need this field in datasets, also.

### Expected behavior

- Documentation field visible only to admin and managers to track changes to and info about a record.
- Large text box.
- Admin and managers add any relevant info.
- Edit page: Documentation field shows up last, under Identifier
- Show page: Documentation field shows up as second-to-last field, below Additional Information and above Depositor

### Actual behavior
Any changes to a deposit happen without documentation on the record.

### Related work
#2200

**Comment by lamtu1** [comment]
Hi @simholt, I am currently working on the ticket and reading the requirement, I saw that when in edit mode, you wanted to be `Documentation field shows up last, under Identifier`. But there is no `Identifier` field in the Dataset. Below I put it under as `Additional Field after the Description area`. And was wondering if this was good area to put it in Dataset form?

<img width="1102" alt="Screenshot 2024-03-14 at 2 51 28 PM" src="https://github.com/osulp/Scholars-Archive/assets/111306182/5a5cb371-0807-47df-b26d-54cc9122a998">

**Comment by simholt** [comment]
Ach, yeah no identifier field there -- 
Yes, just put it as the very last field!

**Comment by simholt** [comment]
QA pass - shows for Admin only all good!

**Comment by CGillen** [comment]
Fixed & Deployed
