### ISSUE TITLE
Fixity email report fields aren't pulling correct data

### ISSUE THREAD

**Issue by carakey** [osulp/Scholars-Archive#2568]
### Descriptive summary

Look into how the fixity checker is counting and reporting passing / failing files in its data fields. The last report had a discrepancy where it says zero files failed, but gives 14 IDs of failed files.

### Expected behavior

Counts of passing and failing files are reported accurately in the fixity report email.

### Actual behavior

The following is the fixity report emailed on on Feb 17, 2024:

> Fixity Report
> Hi there, below are the report on the Fixity Job that ran and the results after it has finished running:
> 
> Start Time: 2024-02-16 15:48:47 -0800
> End Time: 2024-02-17 01:03:08 -0800
> No. of Files [CHECKED]: 157268
> No. of Files [PASSED]: 157268
> No. of Files [FAILED]: 0
> List of all Failed Files [IDs]:
> 
> [kp78gg577](https://github.com/concern/file_sets/kp78gg577) 
> [dj52wc82j](https://github.com/concern/file_sets/dj52wc82j) 
> [41687r184](https://github.com/concern/file_sets/41687r184) 
> [br86bb654](https://github.com/concern/file_sets/br86bb654) 
> [qn59qb39p](https://github.com/concern/file_sets/qn59qb39p) 
> [8c97kx72p](https://github.com/concern/file_sets/8c97kx72p) 
> [1z40m1672](https://github.com/concern/file_sets/1z40m1672) 
> [qv33s449d](https://github.com/concern/file_sets/qv33s449d) 
> [pc289r65p](https://github.com/concern/file_sets/pc289r65p) 
> [jm214w89m](https://github.com/concern/file_sets/jm214w89m) 
> [v979v971k](https://github.com/concern/file_sets/v979v971k) 
> [vh53x358h](https://github.com/concern/file_sets/vh53x358h) 
> [9p290h89n](https://github.com/concern/file_sets/9p290h89n) 
> [hx11xp80b](https://github.com/concern/file_sets/hx11xp80b) 
> 
> - Scholars Archive Support
> 
> Email Date & Time: February 17, 2024 - 1:03 AM

I'm reading this as "100% of files passed. Zero files failed. These 14 files failed." If the last thing is true, then the first two things are not. 

### Steps to reproduce the behavior

Fixity report emails are saved in ScholarsArchive email archive.

### Related work

#2551 ; #2421

**Comment by carakey** [comment]
I don't have a way to QA without seeing the monthly email report.

**Comment by lamtu1** [comment]
Hi @carakey , since it is already April, we can wait till the next report run this month to check it and make more revision after it.

**Comment by CGillen** [comment]
Code is on production, fixity will run tonight

**Comment by carakey** [comment]
We got the fixity report last night and the field mismatch is still the same. The passed/failed counts are still off. Unless the changes didn't make it to production, this should get moved back to ready for the next local WC.

> Fixity Report
> 
> Hi there, below are the report on the Fixity Job that ran and the results after it has finished running:
> Start Time: 2024-04-15 13:00:11 -0700
> End Time: 2024-04-15 18:53:08 -0700
> No. of Files [CHECKED]: 157607
> No. of Files [PASSED]: 157607
> No. of Files [FAILED]: 0
> List of all Failed Files [IDs]:
> [kp78gg577](https://github.com/concern/file_sets/kp78gg577) 
> [dj52wc82j](https://github.com/concern/file_sets/dj52wc82j) 
> [br86bb654](https://github.com/concern/file_sets/br86bb654) 
> [qn59qb39p](https://github.com/concern/file_sets/qn59qb39p) 
> [8c97kx72p](https://github.com/concern/file_sets/8c97kx72p) 
> [1z40m1672](https://github.com/concern/file_sets/1z40m1672) 
> [qv33s449d](https://github.com/concern/file_sets/qv33s449d) 
> [pc289r65p](https://github.com/concern/file_sets/pc289r65p) 
> [jm214w89m](https://github.com/concern/file_sets/jm214w89m) 
> [v979v971k](https://github.com/concern/file_sets/v979v971k) 
> [vh53x358h](https://github.com/concern/file_sets/vh53x358h) 
> [hx11xp80b](https://github.com/concern/file_sets/hx11xp80b)
> 
> - Scholars Archive Support
> Email Date & Time: April 15, 2024 - 6:53 PM

**Comment by carakey** [comment]
June fixity report still has this issue. Most failures have been resolved, but still one failed file ID and "No. of Files [Failed]: 0".

> Fixity Report
> Hi there, below are the report on the Fixity Job that ran and the results after it has finished running:
> Start Time: 2024-06-15 13:00:09 -0700
> End Time: 2024-06-15 19:42:31 -0700
> No. of Files [CHECKED]: 158856
> No. of Files [PASSED]: 158856
> No. of Files [FAILED]: 0
> List of all Failed Files [IDs]:
> [kp78gg577](https://github.com/concern/file_sets/kp78gg577)
> -Scholars Archive Support
> Email Date & Time: June 15, 2024 - 7:42 PM

**Comment by carakey** [comment]
I'm not sure how we can QA this except to go ahead and push to Production and wait for the next report to come in.

**Comment by lamtu1** [comment]
That should be fine @carakey, we can wait until it is push to production and wait for the next time it run to check it out.

**Comment by carakey** [comment]
A minor issue has resurfaced with this. (We hadn't had any fixity failures reported since this ticket was closed two years ago! :tada: ... until last month.) The July fixity report shows: 

> Start Time: 2026-07-15 13:00:11 -0700
End Time: 2026-07-15 22:00:21 -0700
No. of Files [CHECKED]: 167152
**No. of Files [PASSED]: 167152**
No. of Files [FAILED]: 1
List of all Failed Files [IDs]:
[n009wb437](render:///concern/file_sets/n009wb437)
Scholars Archive Support
Email Date & Time: July 15, 2026 - 10:00 PM

It looks like the `No. of Files [PASSED]:` line is meaningless. If 1 of the 167152 `CHECKED` files did fail, then `PASSED` files should be 167151. 

FYI the same file failed in June and is ticketed over here #2904.

**Comment by lamtu1** [comment]
`QA`: This can be tested only once push through to `prod`
