### ISSUE TITLE
Embargo not expire on staging or prod running 3.6

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2584]
### Descriptive summary
Test item on staging `c534fp16v` did not expire as it was supposed to over the weekend.
I checked items on prod -- `gm80j408b` was supposed to expire today (2024-04-15) but did not. 

### Expected behavior
Both were to expire to public.

### Actual behavior
Still under embargo.

### Related work

Link to related tickets or prior related work here.
#2556

**Comment by CGillen** [comment]
@simholt

Do these two file sets actually exist on anything?
[ShawGrahamR2021.pdf](https://ir.library.oregonstate.edu/embargoes/9p290h89n/edit?locale=en)
[DunkleGabrielleR2021.pdf](https://ir.library.oregonstate.edu/embargoes/41687r184/edit?locale=en)

They're the last two on the Expired Active Embargo tab. If they don't they need deleted in Solr and things should clear up

**Comment by CGillen** [comment]
Also, I don't think staging has a running embargo expiry job. I think they just haven't been expiring. Nothings been expiring since 2021 & I can't find a cronjob where prod has them or anywhere else

**Comment by simholt** [comment]
Both those works are public already (at least one was expired manually early as per student request). 
`hq37vw750`
`bk128k119`

**Comment by CGillen** [comment]
Cool, so they're from filesets that don't exist anymore. I'm gonna delete those solr documents and re-run the expiry job

**Comment by CGillen** [comment]
I'm not sure if the definition of expired embargo changed from v2.9.5 to v3.6.0, but it looks like an `active` embargo includes the embargo release date, so works won't release their embargo until the next day

**Comment by simholt** [comment]
@CGillen okay - that's probably been my misunderstanding. Good to know!
