### ISSUE TITLE
Files still private after items set to public

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2586]
### Descriptive summary
It appears that some items that were under embargo expired to Private instead of Public. When I change the visibility to Public and click save, I am prompted to confirm access:

> 
> Apply changes to contents?
> You have changed the access level on work GraduateThesisOrDissertation: b8515x06n, making it accessible to other users or groups to view or edit.
> Would you like change all of the files within the work to have the same access users, groups and visibility as well?

I say yes but the files remain Private, even after hours have gone by.

### Expected behavior
Files change to requested visibility within a few minutes.

### Actual behavior
They remain at previous status.
Examples: 
`1z40m221n`
`pr76fb61s`

**Comment by CGillen** [comment]
Nvm, none of that worked....

**Comment by CGillen** [comment]
QA Pass. Applying new visibility passed through to fileset
