### ISSUE TITLE
OSU Branding

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#26]

**Comment by terrellt** [comment]
@vantuyls What do you have in mind for this? Do you need graphic design student time?

**Comment by vantuyls** [comment]
At this point I don’t think so. Looking at scholar sphere (as an example) I think we just need to adjust coloring, get a background image, and insert the logo. Mike sent me the website for the university guidance on web design.

**Comment by vantuyls** [comment]
http://oregonstate.edu/brand/web-and-interactive-media

**Comment by terrellt** [comment]
If you come to the lab we can work on some CSS.

**Comment by vantuyls** [comment]
okay.

**Comment by vantuyls** [comment]
Still want to add: terms of use, about page, help page, set up contact form, and maybe a couple of other things.

**Comment by wickr** [comment]
I think it'd be better to have separate tickets for those things.

**Comment by terrellt** [comment]
+1. Can you make them?

**Comment by vantuyls** [comment]
moving this to done. i added individual items for the remainder of branding.
