### ISSUE TITLE
OAI-PMH endpoint errors 

### ISSUE THREAD

**Issue by carakey** [osulp/Scholars-Archive#2600]
### Descriptive summary

An admin with the CORE indexing service let me know that they were not able to harvest SA@OSU contents:

> The OAI-PMH endpoint we use is https://ir.library.oregonstate.edu/catalog/oai. Our system could not start indexing of content of your repository because ListRecords section of the OAI-PMH endpoint (https://ir.library.oregonstate.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc) is not accessible.

I confirmed that the [endpoint](https://ir.library.oregonstate.edu/catalog/oai) comes up, and that the `Identify`, `ListSets`, and `ListMetadataFormats` verbs produce correct results, but I get a 500 error on `ListRecords` and `ListIdentifiers`. 

Additional information / possible clues:

- The latter two have that `&metadataPrefix=oai_dc` argument and the others do not. 
- Our OAI configuration was updated semi-recently.

### Expected behavior

External harvesting services can use our OAI-PMH endpoint to include SA@OSU records in their indexes, promoting discovery and use of OSU works.

### Actual behavior

SA@OSU records cannot be harvested.

### Steps to reproduce the behavior

Either try the OAI-PMH call directly at https://ir.library.oregonstate.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc

Or go to the endpoint at https://ir.library.oregonstate.edu/catalog/oai and click "ListRecords".

### Related work

#2548 
#2559

**Comment by wickr** [comment]
The error looks to be coming from one of the overrides we did to remove `Collection` from the list of models included for the solr query in https://github.com/osulp/Scholars-Archive/blob/main/config/initializers/hacks/blacklightoaiprovider_solrdocumentwrapper_hack.rb

```ruby
[9e23c89991f0d58e52da989b3917e94d] Solr parameters: {"facet.field"=>["academic_affiliation_label_ssim", "contributor_advisor_sfacet", "graduation_year_sim", "contributor_committeemember_sim", "con │
│ [9e23c89991f0d58e52da989b3917e94d] Solr parameters: {"facet.field"=>["academic_affiliation_label_ssim", "contributor_advisor_sfacet", "graduation_year_sim", "contributor_committeemember_sim", "con │
│ [9e23c89991f0d58e52da989b3917e94d] Completed 500 Internal Server Error in 269ms (ActiveRecord: 5.5ms)                                                                                                │
│ [9e23c89991f0d58e52da989b3917e94d]                                                                                                                                                                   │
│ [9e23c89991f0d58e52da989b3917e94d] FrozenError (can't modify frozen String: "{!terms f=has_model_ssim}Article,GraduateThesisOrDissertation,GraduateProject,UndergraduateThesisOrProject,EescPublicat │
│ [9e23c89991f0d58e52da989b3917e94d]                                                                                                                                                                   │
│ [9e23c89991f0d58e52da989b3917e94d] config/initializers/hacks/blacklightoaiprovider_solrdocumentwrapper_hack.rb:10:in `sub!'                                                                          │
│ [9e23c89991f0d58e52da989b3917e94d] config/initializers/hacks/blacklightoaiprovider_solrdocumentwrapper_hack.rb:10:in `block in conditions'                                                           │
│ [9e23c89991f0d58e52da989b3917e94d] config/initializers/hacks/blacklightoaiprovider_solrdocumentwrapper_hack.rb:9:in `each'                                                                           │
│ [9e23c89991f0d58e52da989b3917e94d] config/initializers/hacks/blacklightoaiprovider_solrdocumentwrapper_hack.rb:9:in `conditions'
```

Either an update to this file or is needed or another approach to change the models included.

**Comment by carakey** [comment]
Is this change live on Staging? I tried QA at https://ir-staging.library.oregonstate.edu/catalog/oai, and I still get an error on `ListRecords` and `ListIdentifiers` as in the original comment.

**Comment by lamtu1** [comment]
Hi @carakey, it is live on staging, but if it is still failing meaning it is still breaking in the code, and will go look into it again.

**Comment by carakey** [comment]
QA: No change from my previous comment. Still errors on `ListRecords` and `ListIdentifiers` at https://ir-staging.library.oregonstate.edu/catalog/oai.

**Comment by lamtu1** [comment]
@carakey I am currently checking it out and something is failing on Rancher pods which is not pushing the update through and working on trying to fix it.

**Comment by carakey** [comment]
QA pass!
