### ISSUE TITLE
Clearer messaging and routing for editing works under review

### ISSUE THREAD

**Issue by carakey** [osulp/Scholars-Archive#2612]
### Descriptive summary

We're getting a lot of emails from student depositors trying to make requested changes to their works during review. The current system behavior is confusing when they try to access their work without being logged in first. This can be helped with improvements to the email message text, the system warning message text, and an option to route to a login and then through to the work, similar to #2494. 

### Current behavior

If changes are requested for a work during review, the depositor gets an email like this:  

> **You have a new message: Your deposit requires changes** 
>  
> Your deposit {WORK TITLE} ([{WORK PID}]({link})) requires additional changes before your deposit can be accepted into ScholarsArchive@OSU. {REVIEWER_ONID} left you a comment: '  
> {REVIEWER COMMENT TEXT}  
>  '  
> Visit [https://ir.library.oregonstate.edu/](https://ir.library.oregonstate.edu/) and go to your inbox for more info.

If they click the link to the work but aren't logged in, they get something like the following:

![Screenshot 2024-06-12 at 10 01 32](https://github.com/osulp/Scholars-Archive/assets/17655103/7b3a1c98-8657-47d5-895f-c5f90ac877e2)

At this point they often send a 'please help' email. 

### Expected behavior

(changes are in bold)

1. Update text to the email message to indicate that they need to log in: "Your deposit {WORK TITLE} ([{WORK PID}]({link})) requires additional changes before **it ~your deposit~** can be accepted **~into ScholarsArchive@OSU~**. **You need to be logged in to ScholarsArchive@OSU to access and make changes to your deposit.** {REVIEWER_ONID} left you a comment:" (etc.) 
2. Update text to the system message to indicate that they need to log in: "The work is not **~currently~** available because it has not **~yet~** completed the approval process. **If you are the owner of this work, [log in](link) to make changes.**"
3. If possible, use the routing logic from #2494 to redirect them to the work after logging in (if they are the owner!)

### Related work

#2494

**Comment by carakey** [comment]
QA:
1. Email messaging -- looks good!
2. System warning message: I see the updated text with instructions to log in. Please remove the crossed out words from above (currently; yet). There is no login link in the system message.
3. Redirect: There is no login option so no redirect happening.

**Comment by straleyb** [comment]
@carakey This should be good for QA again. It is redirecting to the homepage with the login link, then gets you to login afterwords. When you login as the owner it takes you to your work.

**Comment by carakey** [comment]
QA: It works! 
We'd like to see minor tweaks to the warning message: 

1. "The work is not currently available..." <-- remove "currently"
2. "If you are the owner of this work, [Click here](link)..." <-- lowercase click  

Then we should be good to go.

**Comment by carakey** [comment]
QA - looks good!
