### ISSUE TITLE
Cannot add existing collection as subcollection

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2629]
### Descriptive summary
Because of a name change, I'm trying to add **Undergraduate Research, Scholarship, and the Arts (URSA)** as a subcollection to the **Office of Undergraduate Research (OUR)** collection. I keep getting error messages. I tried with other colls and those didn't work either.

### Expected behavior
Can add collections as subcollections to existing collections.

### Actual behavior
<img width="834" alt="Screenshot 2024-07-09 at 10 20 46 AM" src="https://github.com/osulp/Scholars-Archive/assets/33705514/641b8eea-79f1-4a68-9952-4c6d96844d91">

### Steps to reproduce the behavior

1. From a collections dashboard view (?), [example](https://ir.library.oregonstate.edu/dashboard/collections/j96028497), click Add a subcollection.
2. Choose a dropdown from the menu.
3. Get error message.

**Comment by simholt** [comment]
A populated dropdown appeared (that's new!) and I selected a collection but nothing happened. I clicked the Add a subcollection button multiple times and eventually an error message appeared. Tried multiple times.



![Image](https://github.com/user-attachments/assets/4d770172-99fe-45d7-9798-7ebda1009a0e)



![Image](https://github.com/user-attachments/assets/2921e1db-1414-4b30-bbac-7fe19b54d790)

**Comment by straleyb** [comment]
So when you click the button to add a subcollection to a collection, it has no feedback (out of the box functionality from Hyrax). If you just click the button once and then give it a minute or two, it actually is processing in the background. This can most definitely be enhanced user experience wise. 



![Image](https://github.com/user-attachments/assets/a0f01180-5e7e-42bf-a14f-2f871982f02e)

This GIF is a minute long so its a tough one. But I added Cara's Collection to A Nice Collection

**Comment by simholt** [comment]
I clicked to add a subcollection and let it run for seven minutes and nothing changed (screenshot below). The box did not disappear as in the gif above.

![Image](https://github.com/user-attachments/assets/877deb14-cb7d-43a5-b520-a1ee4ad86011)

I clicked around and the window disappeared and the subcollection had been added. I tried with another subcollection addition but didn't wait as long and it also was added.

Can we have it so the Add a subcollection button greys out and it closes when the task is done?

**Comment by straleyb** [comment]
@simholt This should be ready for QA now.

Note: It'll disable the button and close the popup window. You'll still have to refresh the page to see the update, but there is an alert that pops up saying that the action is being processed in the background.

**Comment by simholt** [comment]
Great! QA pass ---

**Comment by simholt** [comment]
@straleyb  Did this get pushed to production? It isn't working for me.

**Comment by straleyb** [comment]
@simholt I think it did. On production, when I go to a collection page and click the add subcollection button, I get this view. Are you able to have the dropdown on the popup window to choose the subcollection?
 
<img width="1137" alt="Screenshot 2024-08-05 at 12 25 33 PM" src="https://github.com/user-attachments/assets/13a29770-7cd5-4f19-9d0b-29e13e4c0a4f">

**Comment by simholt** [comment]
Yes, that shows, but I choose one and nothing happens. I did not get the same alert about processing in the background like I did on staging. Tried a few times, waited 5+ minutes.

**Comment by straleyb** [comment]
I think I have to recompile the javascript. I think I did it on staging but not after the production deploy. Let me run that and ill ping here when it is complete.

**Comment by straleyb** [comment]
Alright give it another go @simholt

**Comment by simholt** [comment]
Okay -- I logged in and the first collection I was trying to add showed up correctly as a subcollection.
I tried another (adding Library Undergraduate Research Awards as a subcollection to the University Libraries collection) and while the working-in-background popup showed, the subcollection was not added.

**Comment by simholt** [comment]
Okay -- looks like I need to give this process more time! It works!
