### ISSUE TITLE
Cannot add items to collection from Works page

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2630]
### Descriptive summary
On the [Works](https://ir.library.oregonstate.edu/dashboard/works?locale=en) page --
Trying to add items to collections but the system says I don't have access to existing collections (despite having created them).

### Expected behavior
Can add items to collections from Works page (this is the fastest way to put items in a collection).

### Actual behavior
<img width="824" alt="Screenshot 2024-07-09 at 10 31 19 AM" src="https://github.com/osulp/Scholars-Archive/assets/33705514/cf1b2637-e8c5-42b9-b6c3-1e8b08bb7053">

### Steps to reproduce the behavior

1. View Works page.
2. Select items.
3. Click Add to collection.
4. Get error message.

### Related work
Maybe #2594?

**Comment by straleyb** [comment]
@simholt I tried to reproduce this error. 
I went to a work that I owned on staging.
I clicked the checkbox next to the work which brought up the button list thats hidden unless a checkbox is checked. 
I clicked the button that said add to collection
I found a collection, one that I didn't even own
I clicked the save button and it added that work to the collection.

Here is a video I took of the process. Does this look like the same workflow you went through? If so, could you test this out on staging. It COULD be something that is fixed but maybe not pushed to production. Or it has to be some sort of permissions issue (albeit you are an admin both on staging and production.)



![Image](https://github.com/osulp/Scholars-Archive/assets/6424683/69a2c729-9c59-47f6-924f-1bfc672de6b9)

**Comment by simholt** [comment]
@straleyb I can add works I **own** to any collection, but not other people's works. 
However, unlike prod, on staging I was able to select a collection -- but it always timed out.

**Comment by straleyb** [comment]
Im getting that error for items that aren't on the first page. The plot thickens!

**Comment by straleyb** [comment]
![Image](https://github.com/osulp/Scholars-Archive/assets/6424683/822cb388-36ed-4c89-bbff-21024cfb743c)

**Comment by simholt** [comment]
What happens when you try on prod?
https://ir.library.oregonstate.edu/dashboard/works?locale=en
From the All Works tab, search for URSA.
Scroll down and select like 5 items in URSA collection.
Click Add to Collection and type in OUR.

**Comment by straleyb** [comment]
On production Im getting the no permissions error on ANY works that I try and add to a collection EXCEPT for the first 2 pages. The first two pages bring up the correct popup with the search bar that I can find a collection to add it to.

Anything not on the first two pages gives me the permission error.

**Comment by carakey** [comment]
@straleyb Yeah, can confirm on staging, first page works fine for me but later pages fail.

**Comment by straleyb** [comment]
On the first two pages of the All Works tab I can also select multiple. So it seems like any work not on those first few pages is having a weird permissions thing. This is an oddly enigmatic situation. Im gonna keep digging. I can pull up the works and solr documents on production to see if there is any difference in ownership or permissions with them.

**Comment by straleyb** [comment]
Ill also see what the popup window is checking to display that error and that should help get closer to the root of the problem. Thanks for the patience and digging to understand the problem more.

**Comment by simholt** [comment]
@straleyb is "oddly enigmatic" a technical term?

**Comment by straleyb** [comment]
Its the technical term for WTF!

**Comment by straleyb** [comment]
Once this gets QA'd we can get it out on production as well. The deploy that just happened does not include this fix.

**Comment by simholt** [comment]
Now the dropdown cannot find any collections???


![Image](https://github.com/user-attachments/assets/3cda9a03-b74d-4ef5-81e3-391ddaa9d5c0)

**Comment by simholt** [comment]
Hmm, looks like that collection does not exist?! But it was showing up on the works page. Hold on here---

**Comment by simholt** [comment]
Note: Tried adding an item to a collection from the edit page's relationship tab and that doesn't work anymore.

![Image](https://github.com/user-attachments/assets/252a2dc7-58df-4f65-8c5e-58920fda7fc0)

**Comment by straleyb** [comment]
I am seeing this as well and am investigating.

**Comment by simholt** [comment]
@straleyb  Soooo, I keep getting 504s but they are eventually showing up in the proper collections. Is that a weird staging thing or ?

**Comment by straleyb** [comment]
It could be just a staging thing, but thats probably because of the amount of memory/cpu we have allocated. How many works are you trying to add?

**Comment by simholt** [comment]
4

**Comment by straleyb** [comment]
Thats about where I hit the Gateway timeout too. Its a timeout due to how long it takes to add the works to the collection. More memory/cpus will raise this upper limit, but there will most certainly be some upper limit on production too. We can't really know for sure what that upper limit is unless we allocate more memory on staging.

From what I can see, production has double the amount of memory allocated, so we should be able to handle more. How much more remains to be seen. 

With that being said, it doesn't crash the server, so it still adds them, we just get the gateway timeout because its trying to move the user to the next step and just cant because of the holdup.

If we were able to fire off that process without having to route the user it would alleviate the gateway timeout, but that will be some heavy reworks of how Hyrax is dealing with this process.

**Comment by simholt** [comment]
QA pass!
