### ISSUE TITLE
Dataset record edits do not save

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2650]
### Descriptive summary
`2r36v416r` -- can make edits but they do not save. Screen instead reloads with red boxes; see screenshot below. 

### Expected behavior
Can edit record.

### Actual behavior
<img width="707" alt="Screenshot 2024-08-06 at 9 58 42 AM" src="https://github.com/user-attachments/assets/e5b97c81-2e19-446e-b7ce-18d0d63eca74">

**Comment by straleyb** [comment]
When editing, it autofills the DOI with some value. The form is coming back saying that the DOI is invalid. The error message isn't helpful at all with this. Ill work on refining that error while figuring out why the DOI is "wrong"

**Comment by straleyb** [comment]
https://ir-staging.library.oregonstate.edu/concern/datasets/xd07gt05g?locale=en Record for testing. When edited, go to the DOI section and change 10.70029/xd07gt05g to /xd07gt05g which emulates the DOI of the work that wasn't working.



![Image](https://github.com/user-attachments/assets/38ee0b02-4dd9-4060-90d2-b50a800282d1)

**Comment by simholt** [comment]
QA pass -- save was allowed, all good here
