### ISSUE TITLE
Geonames location not resolving on show page

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2658]
### Descriptive summary
You can add Geonames locations to a record and it saves fine (and shows up in limiters) but it doesn't appear on the show page. They were showing sporadically before the upgrade but now they don't show up at all.

### Expected behavior
Geonames location info listed on show page.

### Actual behavior
It's associated with the work but you can't see it unless you view the edit page.
Example: https://ir.library.oregonstate.edu/concern/defaults/qf85nk58b

### Steps to reproduce the behavior

1. Add something to a location field - like this one: `gt54kw13k` Save.
2. View the record -- nothing there. 
3. Click edit button and oh look the field is filled out.
4. Please remove your change!

**Comment by lamtu1** [comment]
Hi @simholt, I just checkout the link you mention in this ticket, below is the screenshot on my end of what I see and it is displaying the `location` correctly.

![Image](https://github.com/user-attachments/assets/272d591b-70af-48d4-8713-7b8d92ec5d24)

And I also did a test on my `local` env, when I first created the work, it didn't appear and waited for couple minutes until it process and refresh the page, and the `location` appear for me (another screenshot below) and was wondering if it is not showing still for you on your end?

![Image](https://github.com/user-attachments/assets/8a8be0d1-897d-4a1b-8805-ce7892e6ecc0)

**Comment by simholt** [comment]
[qf85nk58b](https://ir.library.oregonstate.edu/concern/defaults/qf85nk58b) That one shows for me now! I don't know what changed?

However, all the others I checked that have locations -- [like all these](https://ir.library.oregonstate.edu/catalog?f[based_near_label_sim][]=Klamath+Basin%2C+%2C+United+States%2C+(Area)&locale=en&q=&search_field=all_fields) -- the location is not showing up.
I tried re-saving it & waiting a while, deleting the location then re-entering, and still nothing.

**Comment by lamtu1** [comment]
Hmm I see it too, I will have to dive deep into it and see what I can do

**Comment by lamtu1** [comment]
`UPDATE:` Discover that the `geoname location` is using `sidekiq worker` to perform solr indexing which it will take a couple minutes (roughly 1-2 min) to be index and the display will show up after waiting a couple minutes and refresh the page to see the change.

**Comment by simholt** [comment]
@lamtu1 Q: So it sounds like we will need a reindex for locations to show up on existing records?



![Image](https://github.com/user-attachments/assets/c462a530-854f-4901-97ed-c327a6592889)



A couple things:
1. Can we make it so any extra comma/space combos don't show up? Should be just one comma and one space between terms. AND get rid of the comma at the end.
2. We do not want the info in parenthesis showing.



Related:
#1694

**Comment by lamtu1** [comment]
Hi @simholt, do you want these areas on SA to be change as well and have it follow the format you wanted on the show page? or just the show page itself only?

![Image](https://github.com/user-attachments/assets/29319fcc-0f21-42a3-ad05-d117bc02516c)
![Image](https://github.com/user-attachments/assets/cbddf769-fc38-4888-827d-453701316511)

**Comment by simholt** [comment]
@lamtu1  Yes, they all should have the same structure.
