### ISSUE TITLE
The Reordering of the Fields (depositor form)

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2660]
### Descriptive summary
Improve user experience by showing the fields they are most likely to need in an order that makes sense. Move other fields to below-the-fold or admin-only as needed.

### Expected behavior
Describe items with lots of correctly-completed fields!

### Actual behavior
Users overwhelmed and/or confused; Sarah does lots of cleanup.

---

**TWO PARTS** 

_New Order_
[See linked doc](https://docs.google.com/document/d/1yA3MibXkyWZhbYBVmB_oWenGpneSJTmn-QDIdI_AzFY/edit) for new field listings by Primary, Secondary, and Admin.

_New Functions_
Listed at bottom of above linked doc.

[Spreadsheet view - first tab here.](https://docs.google.com/spreadsheets/d/1_ghORnq2xa22qbrl8pbg02vd7DjQVle1Io9YLrXNqGo/edit?gid=1739641615#gid=1739641615)

**Comment by carakey** [comment]
@straleyb, Following up from standup: The "Date" and "Location" in the spreadsheet are meant to be the date section and location/geo section as they currently exist.

**Comment by straleyb** [comment]
Primary Terms (Top of the fold terms)

![Image](https://github.com/user-attachments/assets/ce6f7731-9e53-4fd4-b4ae-fc17a8300f00)



![Image](https://github.com/user-attachments/assets/714c7975-4167-463b-8949-29e016a0f628)



![Image](https://github.com/user-attachments/assets/5772a327-e750-49e6-b731-6f10c5f9c849)



![Image](https://github.com/user-attachments/assets/b3dce737-7112-4c6a-aa75-2205365414fd)

Additional Terms (Bottom of the fold terms)



![Image](https://github.com/user-attachments/assets/8125e1f3-6de3-427a-8787-0c66f8b457cc)



![Image](https://github.com/user-attachments/assets/68508f71-3640-4a88-a5d4-3d964ab4da64)



![Image](https://github.com/user-attachments/assets/38f4aca0-5cd3-4273-a9ed-719e9e609f09)



![Image](https://github.com/user-attachments/assets/647ef489-377e-4ac0-9ddc-bb95aacc17de)



![Image](https://github.com/user-attachments/assets/55921d97-db46-4d0f-9ac9-4cd9dd282344)

@carakey @simholt Here is a spot check for the Article work type. Its got the admin terms in there at the bottom. This is mostly a quick spot check to see if things look good so far while im wiggling things around. Lemme know if anything looks out of order or isnt required properly.

**Comment by carakey** [comment]
@straleyb Assuming the dupes are just from screenshot overlap, I don't see anything missing or out of place and required fields look good. Nice work!

**Comment by straleyb** [comment]
Yeah I left the dupes in to help track where in the form you were.

**Comment by straleyb** [comment]
@carakey @simholt This should be ready for QA now. I did some spot checking. Plus I got the alternative_title toggling for admin just under title.

**Comment by carakey** [comment]
I got some screenshots on staging from both admin and non-admin accounts for QA. I haven't had time to go through them yet but they're saved in the SA Google Drive, in case Sarah gets to it before me. https://drive.google.com/drive/u/0/folders/10ybup4UpLvdlrGbl7xi68dycgueWHhQA

**Comment by carakey** [comment]
Overall these are looking great, but I did pick up a few things on my review. 
 
- _All worktypes_ have file_format as admin only but should be all users (in Secondary, between Language and File_Extent).
- _Tech Reports_ should have (but don't): at the bottom of Primary, contributor_advisor, degree_level, degree_name, and degree_field.
- _Conference Proceedings or Journal_ should NOT have (but do): at the bottom of Primary, contributor_advisor, degree_level, degree_name, and degree_field.
- _Purchased e-Resources_ - Required fields other than title are not showing as required (creator, resource_type, rights_statement).
- _Purchased e-Resources_ - the label for digitization_spec shows as "Igitization spec" (should be "Digitization Specifications".
- _GTD, GP, HCT, UTP_ at the top of Secondary, bibliographic_citation is admin only but should be all users.
- _GTD, GP, HCT, UTP_ -- I think this was an omission in the spec -- there are fields in Secondary for conference_name and conference_section but not conference_location; that should be added (between conference_section and location); @simholt verify?

**Comment by straleyb** [comment]
Checklist for myself:

- [ ] Tech Reports have contrib, degree * 3
- [ ] Conference should not have contrib degree * 3
- [ ] PERs required fields are creator, title resource_type, rights_statement
- [ ] PERs label for digitization spec fixed
- [ ] ETDs have bibliographic_citation for all users

**Comment by simholt** [comment]
@straleyb I like the checklist - thanks!
I went through everything w/admin view and the only thing missing was `conference_location` for GTDs, GradProf, HCT, and UGT (because I didn't include them on the form). I added them; all secondary terms after `conference section` and before `geo_location`. Brandon, I'm going to ping you to take away my admin status so I can test the user view.

**Comment by simholt** [comment]
USER VIEW QA PASS
**SO NICE** not to see the `alt_title` field on the student thesis forms!!! 
ADMIN VIEW QA PASS
All good on the `conference_location` noted above.
IT'S BEAUTIFUL.
