### ISSUE TITLE
Deprecate other_affiliation authorities

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2692]
### Descriptive summary
Out-of-date `other_affiliation` authorities are showing up and confusing users.
https://github.com/osulp/Scholars-Archive/blob/main/config/authorities/other_affiliation.yml
Changing their status to `false` doesn't seem to impact visibility -- is something being missed? To be honest, I'm not sure if a deploy happened since they were changed or not.

### Expected behavior
Items with `false` status do not show for users. Namely **Graduate School** and **Undergraduate Research, Scholarship, and the Arts (URSA)**.

### Actual behavior
Items with `true` and `false` are listed for users.

**Comment by lamtu1** [comment]
@simholt From what I see that both `local & staging` of SA shows that both of those items are listed as `false` and it is not shwoing up on the form in those area from those two staging. Then I discover the last deploy image was release around `Sept 18` and Brandon did have a PR merge in around `Sept 25` to update the active affiliation. So this could be an update thing we need to do to the image to make `prod` up to date with it that new PR merge in and hopefully it fixes it.
