### ISSUE TITLE
Fix edit_batch_spec

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#270]
Currently, for some reason, when running the edit_batch_spec (the full spec, this does not happen when you run each spec separately) it causes marmotta or something that fetches the label to not work. The fix is reseting your computer currently, however this is highly inconvenient. This does not effect anything in the actual application and wont on the prod server because the specs are never run on the prod server. This does, however, need to be fixed asap.

**Comment by zhang4952** [comment]
After run the spec, Marmotta stop pulling URI with AbstractHttpProvider, so it sounds like several spaces to look at:
1. the html related spec in edit_batch_spec such as have_selector and etc
2. running Marmotta in tomcat
3. gem conflict (?)

**Comment by revgum** [comment]
Closed upon review of issues
