### ISSUE TITLE
[Analytics] Configure Google Analytics to track all traffic

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#274]
We need to ensure that both bitstream and other things

**Comment by wickr** [comment]
Is this any different than #118 and #125  ?

**Comment by revgum** [comment]
feature/GoogleAnalyticsServerSide branch: This branch has a functional server-side Google Analytics posting both an Event and a Pageview for direct link file downloads.. this seems like a decent starting point. You gotta ‘bundle install’ the new gem, and set config/initializers/sufia.rb to a legit GA tracking code to test

**Comment by zhang4952** [comment]
branch restored at: https://github.com/osulp/Scholars-Archive/commit/5ecc239da1ae04574959a45377fde0bc4f96504c

**Comment by zhang4952** [comment]
Solution from UCSD is to get the direct-link downloads from parsing web logs, not to deal with Hydra codes. It could be a feasible approach because we will include ES statistics to GA anyway, should we update GA cache for this purpose?

**Comment by wickr** [comment]
Parsing web logs is not a good approach for us since we've moved away from them almost completely with Google Analytics.

**Comment by vantuyls** [comment]
closing this in deference to #309
