### ISSUE TITLE
[Visibility] Need visibility setting for Private but metadata is still visible in repository

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#278]
Use case: My content (the actual bitstreams) should be embargoed and hidden completely from view, but the metadata record for the item should still appear in the repository.

**Comment by vantuyls** [comment]
This is likely dealt with by PCDM which allows visibility settings to be different at the Work and File level

**Comment by vantuyls** [comment]
This is accomplished by setting the visibility on the file while different visibility on the work.

**Comment by revgum** [comment]
Closed upon review of issues
