### ISSUE TITLE
[Extraction] Extract Featured Researcher Delete into sufia after sufia 7 launch

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#284]
We are extending the functionality of content blocks to be able to delete featured researchers. We would like to work it into sufia, however, sufia is undergoing lots of changes and is unstable. We can add it to our project now, but after the sufia 7 launch, we should extract it into sufia. 

https://github.com/projecthydra/sufia/blob/master/app/controllers/content_blocks_controller.rb

**Comment by vantuyls** [comment]
for hyrax to fix
