### ISSUE TITLE
[Bug] Ingest form Datepickers second rendering lose date logic

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#295]

**Comment by revgum** [comment]
The second time you click to view a pre-existing datepicker, the cycling forward to the next month inadvertently sticks you back into the 1900s. The logic of rendering datepickers needs to only render each date picker once, but be smart enough to make properly unique datepicker id's for each new dynamically added INPUT on the form

**Comment by straleyb** [comment]
closed upon review of issues
