### ISSUE TITLE
[Geo] Nested attributes for geographic geonames

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#301]
Relates to #300 and #144

**Comment by revgum** [comment]
Save and store the geoname URI in the backend. Fetching the label and storing a cache of the label will be handled on another ticket.

**Comment by vantuyls** [comment]
@luisgreg99 what is the status of this? shoudl it stay open? what milestone?

**Comment by revgum** [comment]
fixed and closed by Greg in SA - Hyrax2.x enhancements
