### ISSUE TITLE
itemtype attribute in Tag show fields partial should be https://schema.org/keywords

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#305]
https://github.com/osulp/Scholars-Archive/blob/master/app/views/records/show_fields/_tag.html.erb

itemtype value should be `https://schema.org/keywords`

**Comment by straleyb** [comment]
Tag is not in use as the description for the "keyword" attribute. It has been transitioned over to keyword now. On the _keywords page, there is no itemtype attribute in the html. Do we want to add the itemtype to the html or is it necessary? 

Link to the _keywords page: https://github.com/projecthydra-labs/hyrax/blob/master/app/views/records/show_fields/_keyword.html.erb

Adding it in would be straight forward and simple.

**Comment by wickr** [comment]
Thanks for checking Brandon. I don't think this is something to add for our local customizations, but adding the itemtype to Hyrax would probably be a quick ticket/PR if someone wants to do it. I'll close this on our end.

**Comment by straleyb** [comment]
https://github.com/projecthydra-labs/hyrax/issues/808 Hyrax ticket
