### ISSUE TITLE
"Share With" does not appear to be persisting the association

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#311]
Edit permissions on content, but sharing with another user doesn't appear to work.. related to #244

**Comment by vantuyls** [comment]
Related to #244

**Comment by vantuyls** [comment]
also: related to #244 and also #244

**Comment by vantuyls** [comment]
see also: #244

**Comment by revgum** [comment]
The association works, you have to click the "+" associated with the person/permission selected. The person/permission is added to the table at the bottom of the page. Click the "Save" button the persist the changes. 

Closing issue, since the association is working.

**Comment by straleyb** [comment]
closed upon review of issues
