### ISSUE TITLE
Logout does not seem to fully logout

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#315]
Clicking Logout seems to remove the local cookie, but leaving the window open maintains the server side session. Clicking Login, logs in the previously logged in user.

**Comment by vantuyls** [comment]
This may have been a choice we made.  We wanted to be able to log out of SA@OSU but stay at SA@OSU. This should be revisited, but at milestone 3-ish.

**Comment by vantuyls** [comment]
Still an issue in Hyrax. Is this something we should worry about now or push off? @revgum @straleyb @wickr @zhang4952 @luisgreg99

**Comment by revgum** [comment]
Verified not longer an issue
