### ISSUE TITLE
BatchController#update is not setting "Share With" user

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#318]
While ingesting a file, setting "Share With" a specific user does not get persisted.

**Comment by vantuyls** [comment]
Is this fixed in S7?

**Comment by straleyb** [comment]
So I think the item does get shared properly, but if you create a new work, fill out the metadata, upload a file, add someone in the shared tab, hit save, then go to update that work and check the shared users, you cant tell that it was shared with someone. So it seems more investigation needs to be done here.

**Comment by vantuyls** [comment]
Closed upon review of issues: April 11, 2017
