### ISSUE TITLE
config/config.yml not loading ERB

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#319]
prevents us from injecting ENV variables into configurations

**Comment by straleyb** [comment]
closed upon review of issues

**Comment by straleyb** [comment]
closed upon review of issues

**Comment by straleyb** [comment]
closed upon review of issues

**Comment by straleyb** [comment]
closed upon review of issues

**Comment by vantuyls** [comment]
Closed upon review of issues: April 11, 2017
