### ISSUE TITLE
[Notification] Styling for email to author and depositor on successful deposit

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#334]
When an object is loaded and characterized, the author and depositor receive an email notification. The current styling for that email should be reviewed and modified (if necessary).

**Comment by mwillihooper** [comment]
@vantuyls - do you have a copy of the current message or ideas of where to find it? I looked through my email archive and couldn't a deposit confirmation message.

**Comment by vantuyls** [comment]
I do not. @zhang4952 do you have any idea how to find out what the current email notification to users looks like in DSpace (e.g. when they deposit something). 

That said, i think we're in a positing to create something new that makes sense for new SA.

**Comment by mwillihooper** [comment]
Okay, here are some potential, very generic responses to different situations. I'm not sure of the systems capacities--is it possible for the metadata or at least a unique identifier to be part of the email? I'm also wondering if we need separate emails for when an item is under review and after it has been characterized--wouldn't one immediately follow the other? Could that just be one email? (below)

**Initial deposit confirmation:** Subject: Your upload to ScholarsArchive was successful. 
Body: Thank you for submitting your work to ScholarsArchive@OSU. The upload was successful, and your submission is now under review. You will receive another email when the submission has been approved and is live. Please email ScholarsArchive@oregonstate.edu with any questions or concerns.
