### ISSUE TITLE
Clicking search throws a Mysql2::Error: Incorrect string value: '\xE2\x9C\x93

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#335]
When on the home page and clicking go in the search box when the search was empty, it throws a mysql, incorrect search error. It seems to be inputing a string that looks quite interesting but definitely not what we need.

**Comment by vantuyls** [comment]
Is this still a bug in S7?

**Comment by straleyb** [comment]
Mysql2::Error: Incorrect string value: '\xE2\x9C\x93"\x0Ac, yep

**Comment by revgum** [comment]
This is due to the utf8=checkmark on the URL, we should scrub or eliminate this.

**Comment by straleyb** [comment]
closed upon review of issues
