### ISSUE TITLE
Discuss restarting redis and workers upon app reload.

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#337]
After an app gets deployed, it could be possible to get it to force restart redis and resque-pool to make sure all services are running fresh.

**Comment by revgum** [comment]
Resque-pool will restart when the 'god' service restarts it. Outstanding question is, do we need to have redis restart as well? 

This is also related to #338.. 

Note: god.conf is the script that would need updated to handle restarting redis

**Comment by vantuyls** [comment]
SIDEKICKQUE

**Comment by revgum** [comment]
Related to monit.d restart configurations

**Comment by vantuyls** [comment]
@straleyb @revgum still an issue? if so, add milestone.

**Comment by straleyb** [comment]
Not an issue for k8s
