### ISSUE TITLE
[Licensing] - License type should be a facet for browsing/search/reporting

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#339]
As a user, i want to narrow down my search results by the license type - only look at, for example, CC-BY licensed items.

**Comment by straleyb** [comment]
This ticket is related to #525. When we figure out the list of what we want indexed and searchable by defualt, it should allow those things to be faceted as well.

**Comment by vantuyls** [comment]
taken care of in the MAP
