### ISSUE TITLE
[S7 Functionality Fix] Fix thumbnail linking issue

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#340]
Currently on lib-sastage1 (ir-staging.l.o.e) thumbnails are being generated, but arent being linked up properly. Its giving a 404 error based on the downloads controller not finding anything.

**Comment by revgum** [comment]
Short term fix, sufia bug fix is in place: 
https://github.com/projecthydra/sufia/issues/1928#issuecomment-215127267

**Comment by vantuyls** [comment]
Closed upon review of issues: April 11, 2017
