### ISSUE TITLE
Configure system emails to be sent for Contact Form

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#341]
This most likely has to do with some configuration in config/initializers/sufia.rb or has to do with the mailer that sufia uses. 

@vantuyls We'll need to know what email to send these contact emails to.

**Comment by vantuyls** [comment]
contact emails should go to me for now.

**Comment by vantuyls** [comment]
Emails from contact form should go to scholarsarchive@oregonstate.edu
