### ISSUE TITLE
Disallow License to be multi-valued.

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#342]
Implement new FormMetadataService for SA which functions similar to Hyrax

**Comment by wickr** [comment]
This is in Sufia 7.1 milestone, was requested we push upstream if we get it working. https://github.com/projecthydra/sufia/issues/1287

**Comment by vantuyls** [comment]
@wickr - yes we should push this one up

**Comment by vantuyls** [comment]
i think this might be fixed in S7

**Comment by straleyb** [comment]
In Hyrax, currently you can only have one rights statement. However you can have multiple licenses, I dont know what the use case is for multiple licenses on one work, but we could work on removing the multi-value indicator on the license field as well.

![screen shot 2017-04-18 at 10 49 24 am](https://cloud.githubusercontent.com/assets/6424683/25145067/e03d507e-2424-11e7-80ed-e72a9d9901c2.png)

**Comment by wickr** [comment]
Right now that seems to be defined in https://github.com/projecthydra-labs/hyrax/blob/aaee5c43ab0adc01dbdf8ee21d0affe692c6b8c0/app/services/hyrax/form_metadata_service.rb

instead of basicMetadata with a `multiple: false`

**Comment by straleyb** [comment]
@wickr Should we allow multiple Licenses?

**Comment by wickr** [comment]
@straleyb No, only 1 license allowed.

**Comment by straleyb** [comment]
The next question is should we push this into Hyrax as well?

**Comment by vantuyls** [comment]
@straleyb no.

**Comment by wickr** [comment]
Current Hyrax issue: samvera/hyrax#105
