### ISSUE TITLE
[Question] Should we allow someone to sign up and add a profile picture?

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#346]
This is related to #345. Should we allow users, on the sign up page, to add a user profile picture there, or have them add their profile picture afterwords?

**Comment by vantuyls** [comment]
what?

**Comment by straleyb** [comment]
@vantuyls This has to do with the profile pictures. It would make sense, if we have profile pictures, that during the sign up process (when they are signing up to use the service), to allow them to add a profile picture so they aren't just stuck with the default, or in this case a small white square.

**Comment by vantuyls** [comment]
This is super duper duper low priority

**Comment by vantuyls** [comment]
Closed upon review of issues: April 11, 2017
