### ISSUE TITLE
Make better HTML error messages

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#350]
Currently for most errors, you are presented with a very simple 404 page. We could have better error handling to tell you that an item doesn't exist in the database instead of saying page not found. That is slightly misleading.

**Comment by vantuyls** [comment]
Would be helpful to know what types of errors we want special messages for.

I've also contacted @KennaW to ask if OSULP or OSU have HTML error pages we can use/leverage

**Comment by vantuyls** [comment]
Text

404: Oops! Looks like we can't find the page you asked for. Head back [home](http://ir.library.oregonstate.edu) and search again!

500: Ack! Looks like ScholarsArchive@OSU has been temporarily severed from the internet. Try again later and let us know on the Contact Form how you wound up here.


????
