### ISSUE TITLE
[S6 -> S7 port] Add support for RDF

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#363]
We need to port these RDF feature from existing SA@OSU on top of Sufia7 to support linked data in SA@OSU:
- TriplepoweredResource
- Solr atomic update 
- Support libraries for Marmotta

**Comment by zhang4952** [comment]
It address the same issue as #361 with a few more details. Marmotta or Blazegraph is open for discussion.

**Comment by straleyb** [comment]
Duplicate ticket so we closed it.
