### ISSUE TITLE
[Ingest Form] - Need to be able to format Abstract fields with rich text (indentations, bullet lists, paragraphs, etc.)

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#364]

**Comment by vantuyls** [comment]
This functionality might already exist in sufia. Check on that.

**Comment by wickr** [comment]
Most metadata standards that I've seen don't allow rich or mixed content in the abstract field, it can only be plain text. 

We could possibly enable this for the app, and then for any type export or harvest type functions, strip out the formatting. But I'm not sure if the formatting should be stored as HTML, Markdown or something else.

**Comment by wickr** [comment]
Possibly related: https://github.com/projecthydra/sufia/issues/2473

**Comment by vantuyls** [comment]
closing this issue. it should be dealt with at the Hyrax level.
