### ISSUE TITLE
[Ingest Form] - Dates - need to add date field for weird dates

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#365]
Such as combined months (e.g. Sept-Oct 2016)

**Comment by wickr** [comment]
This doesn't need to be a separate field does it? 

We're looking at the EDTF format ( https://www.loc.gov/standards/datetime/ ) for Oregon Digital, it's definitely worth a look for SA. Along with https://github.com/inukshuk/edtf-ruby

**Comment by vantuyls** [comment]
@luisgreg99 are our date fields now able to deal with this?
