### ISSUE TITLE
[S6 -> S7 port] Add date properties to metadata fields

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#369]
Relates to #365. We need to make sure that the date properties are added to the system. We don't want to add them to the form as it would normally be generated. Instead what we want to do is add one date field and have a selector with other date type fields that we could add dynamically depending on what is needed. So for this ticket we need to make sure that the date properties exist in the system as well as dont show up in the ingest form.

- [ ] Date properties added to system
- [ ] Date properties dont show up on ingest or edit forms.

**Comment by revgum** [comment]
DatetimePicker UI - make the fields able to accept typed values (not just the UI)
