### ISSUE TITLE
[S6 -> S7 port] Metadata for Geographic location

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#372]
We have 3 types of geographic locations. We have a point, a bounding box and a geonames uri. These pieces of metadata need to be added to the system with the proper URI's. These will be used much like the date fields by being selected from a select drop down.

**Comment by luisgreg99** [comment]
Working branch: https://github.com/osulp/Scholars-Archive/tree/feature/GeoLocProperties 
Related to https://github.com/osulp/Scholars-Archive/issues/373
