### ISSUE TITLE
Create GA account owned by OSULP

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#388]
The GA account currently in use for SA is owned by a personal account (zhang4952), OSULP should create an GA account for SA (as it for other production systems). It is related to #344

**Comment by mickeroo** [comment]
We should discuss whether we want to transfer the existing code from SA over or establish a new one.

**Comment by zhang4952** [comment]
CDSS will discuss how to handle over the GA between DSpace and the coming Hydra in production

**Comment by decimalator** [comment]
There is already an OSULP account for GA. There is already a property for SA setup, we just need to change the GA metadata to point to the correct GA

**Comment by vantuyls** [comment]
is this closed? @zhang4952 @decimalator @mickeroo

**Comment by zhang4952** [comment]
Not yet. The questions to answer: do we need to create a GA property for Sufia in addition to DSpace, when we will start to use that new property in staging

**Comment by vantuyls** [comment]
@zhang4952 create a new property for Hyrax SA@OSU

**Comment by zhang4952** [comment]
Ryan O add a property for the ir-staging server:
Property-ID: UA-35760875-19
Property name: SA@OSU Hyrax

**Comment by zhang4952** [comment]
Done.
