### ISSUE TITLE
[S6 -> S7] Start test variety of SOLR and Fedora

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#391]
Before running the specs, shutdown and restart new instances of SOLR and Fedora with appropriate URLs and SOLR core names. (see config/solr.yml, config/fedora.yml, config/blacklight.yml)

Also god.conf on sandbox server has a demonstration command for killing and restarting SOLR, could be used and applied to Fedora.

**Comment by mickeroo** [comment]
@revgum do we need to figure this out sooner rather than later?

**Comment by vantuyls** [comment]
Closed upon review of issues: April 11, 2017
