### ISSUE TITLE
[Licensing] - License drop-down should also show abbreviated names

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#398]
Where the license drop-down now shows the entire verbose name (e.g. Attribution 3.0 United States) we also want it to show the abbreviation (e.g. Attribution 3.0 United States - CC-BY)

**Comment by revgum** [comment]
Update the yml file with descriptions

**Comment by wickr** [comment]
Maybe suggest this for Hyrax.

**Comment by vantuyls** [comment]
fixed by another issue.
