### ISSUE TITLE
[Licensing] - License drop-downs should offer CC4.0 licenses

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#401]
Stil need to retain CC3.0 licenses on content that was originally assigned those licenses.

**Comment by vantuyls** [comment]
From Hydra General Slack Channel - June 23, 2016

vantuyls [2:13 PM]  
Is there a particular reason for choosing to assign Creative Commons 3.0 licenses instead of 4.0 in Sufia (or Curation Concerns, or wherever else)? I'm wondering if i'm missing something important or if this is just a community norm.

Mike Giarlo [2:25 PM]  
I'm guessing we chose it before CC 4.0 came out

vantuyls [2:26 PM]  
not very forward thinking of you, Mike

[2:26]  
sheesh

Mike Giarlo [2:26 PM]  
I believe we now have tooling to add new licenses to that list and mark old ones as "inactive"

[2:26]  
where "inactive" means that, e.g., CC 3.0 licenses would no longer be selectable in new works but are displayable in old works.

vantuyls [2:27 PM]  
ah, good. thanks.

**Comment by vantuyls** [comment]
Continued the next day:
Carolyn [3:53 AM]  
@awead: @jcoyne: That was written so long ago.  It definitely did not fix a bug with full text that was found recently...

hackmaster.a [5:55 AM]  
mjgiarlo: would be interested to see a pointer to documentation or code re: marking licenses inactive.
1

narogers [6:40 AM]  
@hackmaster.a: You're back! :balloon: :balloon:

hackmaster.a [6:58 AM]  
narogers: Hi!

jcoyne [8:54 AM]  
@hackmaster.a: @grosscol wrote that stuff. you should ask him.

new messages
Colin Gross [9:21 AM]  
What now?

Mike Giarlo [9:35 AM]  
@hackmaster.a: I'm not sure it's well documented. here's the commit that brought that change in: https://github.com/projecthydra/curation_concerns/commit/2e60b6d954c60cf25236ad22f31177f18d33a54d
1

[9:35]  
@hackmaster.a: basically, you can set `active` to `true` or `false` for each entry in `config/authorities/rights.yml`

[9:35]  
true entries are selectable, false entries are not.

hackmaster.a [9:36 AM]  
interesting. thanks!

Mike Giarlo [9:37 AM]  
we could also do the same for resource types if we wish by making a small tweak to https://github.com/projecthydra/curation_concerns/blob/master/app/services/resource_types_service.rb

**Comment by straleyb** [comment]
These statements to not exist in hyrax however it seems to be easily configurable to make this a thing. Do we want to close this ticket and add in a ticket that says something along the lines of "Add CC 4.0 to licenses yaml". @vantuyls 

Here is the page where the configuration lives https://github.com/projecthydra-labs/hyrax/blob/master/lib/generators/hyrax/templates/config/authorities/licenses.yml

**Comment by wickr** [comment]
I think this ticket is fine for adding them to SA. This may be another thing that could be pushed up to Hyrax, I looked and didn't see an open issue for CC 4.0.

**Comment by straleyb** [comment]
Yeah, that makes sense why we would want to push it up to hyrax. Ill open a ticket as a question and see if anyone says anything.

**Comment by vantuyls** [comment]
One thing i'd like to keep in mind is that we have CC3 licenses applied to content we will be migrating, but will want CC4 licenses for new content. So we need to be able to allow CC3 and CC4 licenses BUT only allow CC4 licenses to be selected for new content.

**Comment by straleyb** [comment]
https://github.com/projecthydra-labs/hyrax/issues/810 Hyrax ticket.

**Comment by vantuyls** [comment]
issue on hyrax.
