### ISSUE TITLE
Provide page title value for Work and File Analytics pages, to match text in h2

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#452]
Currently the page title for http://ir-staging.library.oregonstate.edu/files/8623hx72q/stats  is "File Stat // Sufia". "File Stat" should probably match "File Analytics" that is in the h2.

Because we don't provide a page_title value, I think Curation Concerns is just using a default page value from the controller name: https://github.com/projecthydra/curation_concerns/blob/71f0b9d8b210a7833eefdf333bfeb8859e255c56/app/helpers/curation_concerns/title_helper.rb#L18

**Comment by zhang4952** [comment]
I think this issue has been solved with the new Hyrax, as shown with this sample: http://ir-staging.library.oregonstate.edu/files/v405s938k/stats. @wickr ?

**Comment by zhang4952** [comment]
Correction, page title as shown with this sample: http://ir-staging.library.oregonstate.edu/files/v405s938k/stats, is still 'File Stats // Hyrax'. But I also see that same pattern used for many other views, such as http://ir-staging.library.oregonstate.edu/concern/parent/t722h8817/file_sets/v405s938k, the page title is 'Show File Set // Hyrax'. I suspect it is by default from curation_concerns, should we customize all the views?
