### ISSUE TITLE
File Analytics page does not display filename or other title in h1

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#453]
Currently nothing is displayed in the main h1 header on the page. http://ir-staging.library.oregonstate.edu/files/8623hx72q/stats

**Comment by zhang4952** [comment]
This is screenshot with filename displayed for file stats page.
<img width="1135" alt="screen shot 2017-05-03 at 3 25 09 pm" src="https://cloud.githubusercontent.com/assets/609011/25677703/018db538-3015-11e7-89b0-0539b594ca75.png">

**Comment by wickr** [comment]
I'm not sure where that screenshot came from. Viewing the files stats page for that doc I do not see the title. http://ir-staging.library.oregonstate.edu/files/0c483j36g/stats

![image](https://cloud.githubusercontent.com/assets/2293544/25679119/04dfa53e-3001-11e7-929e-d9f317c9dccd.png)

**Comment by zhang4952** [comment]
@wickr : that is after I made change to stats view, will push that branch in a minute
