### ISSUE TITLE
[Ingest Form] When adding a Geographic Coordinates > Locations, clicking 'Add another Geonames...' clears out any value in form field

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#454]
When a value is in the form field for "Geonames.org Link or ID" clicking "Add another Geonames Link or ID" does not add another field, instead it clears out any value already in the field.

**Comment by vantuyls** [comment]
still relevant? if so, add milestone. @wickr

**Comment by wickr** [comment]
This was redone and is no longer happening.
