### ISSUE TITLE
[Ingest Form] Geographic Coordinates fields button to add another field has labels like 'LabelLatitudeLongitudeLabelLatitudeLongitude' instead of 'Geographic Point'

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#456]
The form button to add another field is combining the form field labels, not the label from the group.

**Comment by vantuyls** [comment]
still relevant? if so, add milestone. @wickr

**Comment by wickr** [comment]
This was redone and is no longer happening.
