### ISSUE TITLE
On Record Show page, triple powered properties should not show alt or variant labels.

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#458]
Only the first label, probably prefLabel, should be shown for a field value.

http://ir-staging.library.oregonstate.edu/concern/generic_works/41687h45k

Creator: 
Oregon State University. Water Resources Research Institute
Corvallis (Or.). Oregon Water Resources Research Institute
Corvallis (Or.). Water Resources Research Institute
Oregon State University. Oregon Water Resources Research Institute
Oregon Water Resources Research Institute
Oregon. Oregon Water Resources Research Institute
Oregon. State University, Corvallis. Water Resources Research Institute.
Oregon. Water Resources Research Institute
Water Resources Research Institute (Oregon State University)

**Comment by vantuyls** [comment]
still relevant? if so, add milestone. @wickr

**Comment by wickr** [comment]
This was redone and is no longer happening.
