### ISSUE TITLE
Verify Geonames lookup API is functional and labels showing

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#459]
No labels appear to be fetched:
http://ir-staging.library.oregonstate.edu/concern/generic_works/41687h45k

Does the Geonames API username need to be configured on the staging server?

**Comment by revgum** [comment]
Check Geonames configuration on the `initializers/hyrax.rb`

**Comment by vantuyls** [comment]
@straleyb is this done? if yes, please close.

**Comment by vantuyls** [comment]
@straleyb and @luisgreg99 do you think this can be closed?
