### ISSUE TITLE
Geonames labels should have more information added about parent features (county, state, country, etc.) to disambiguate

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#461]
This is how it was constructed in Oregon Digital 1: 
https://github.com/OregonDigital/oregondigital/blob/d82d944d55dd087d2670b3f065725ef0e5ddc4ce/lib/oregon_digital/controlled_vocabularies/geographic.rb

where both `.fetch` and `.rdf_label` are modified. The first goes and fetches info from the parent location URI, and then that gets appended to the label to give more information. This was doable due to ActiveTriples, not sure how this fits in with either the geonames-wrapper gem or triplepoweredproperties.

**Comment by vantuyls** [comment]
still relevant? if so, add milestone. @wickr

**Comment by wickr** [comment]
Questioning Authority gem now does most of this when setting the label: https://github.com/samvera/questioning_authority/blob/master/lib/qa/authorities/geonames.rb#L8

If we desire to change this we can make a separate ticket.
