### ISSUE TITLE
Logout of account redirect back to SA@OSU homepage

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#47]

**Comment by vantuyls** [comment]
current redirect is to the ONID login page

**Comment by terrellt** [comment]
Only way to do this is if logout just logs you out of SA, not out of CAS.

**Comment by vantuyls** [comment]
My perspective is that it would be better to be redirected back to SA homepage but still logged into CAS. Is that doable? The logout direct to the ONID page is yucky.

**Comment by mickeroo** [comment]
So the desired action is to not log out of CAS but destroy the session logging you out of SA
