### ISSUE TITLE
Migration path for DSpace to Sufia

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#478]
EPIC issue contains all related github issues

**Comment by vantuyls** [comment]
@zhang4952 could you fill out some more elements of the Epic? I only see one issue.

**Comment by zhang4952** [comment]
TODOs for ingesting DSpace bags to Sufia:
1. export a DSpace collection in bags
2. create a list of DSpace collections and communities
3. create a CV for collections in opaquenamespace
4. finalize metadata crosswalk of DSpace to Sufia
5. finalize collection facet (UI issue, a collection facet with more than 400 elements is not helpful)
they are pre-requisite for the actual development of the rails programs that will parse the bags, look for collection/item relationship, and ingest contents into Fedora4/Sufia.

**Comment by vantuyls** [comment]
This is now DSpace2Hydra
