### ISSUE TITLE
Update Footer

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#48]
Change copyright statement, leave link to Hydra/Sufia, remove Penn State image note

**Comment by vantuyls** [comment]
copy copyright currently on SA@OSU: http://ir.library.oregonstate.edu/xmlui/

**Comment by vantuyls** [comment]
add link to OSU homepage and to OSULP homepage a la scholarsphere.psu.edu

**Comment by straleyb** [comment]
https://scholarsphere.psu.edu/files/5712mq285#.VUuWstNVikp
http://ir.library.oregonstate.edu/xmlui/

Just for my reference. OSU | OSULP | DISCLAIMER | ACCESSIBILITY
