### ISSUE TITLE
Academic year field

### ISSUE THREAD

**Issue by luisgreg99** [osulp/Scholars-Archive#499]
Since we may know the academic year periods (start/end dates) in advance from the 5-year calendar provided by the registrar https://oregonstate.edu/registrar/pdf/osu-5-year-calendar-summer-first.pdf we could calculate it given the ingested date or dissertation date provided by the user.

We could have a setting in the admin section where we could input the start/end dates ranges from the current 5-year calendar, then have a logic in the system that would determine the academic year. This data could then be stored in a field or just be displayed on the fly in the item show page.

**Comment by luisgreg99** [comment]
refers to https://github.com/osulp/sa-content/issues/25

**Comment by vantuyls** [comment]
We've removed the need for this field - this has been reflected in the MAP
