### ISSUE TITLE
[Analytics] Migrate DSpace usage statistics

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#503]
This is the epic ticket containing activities of migrating usage statistics in Elastic Search index to Google Analytics.

**Comment by zhang4952** [comment]
Atmire's response regarding to integrating elastic search: 
After initial research into support for importing external statistics data into Google Analytics, it is evident that importing your existing Elastic Search statistics data into GA is not a feasible option.

We will need to hack a solution by ourselves.

**Comment by zhang4952** [comment]
Export ES statistics by item in CSV Using the help doc: https://docs.google.com/a/oregonstate.edu/document/d/1s0agek-HexwIibeW8VgQIALQFR77-ns-RW8Ltn-jVeo/edit?usp=sharing.

**Comment by zhang4952** [comment]
1. The dump of elasticsearch: lib-saapp1: /data0/hydra/shared/tmp/elasticsearch_export.
2. Provide legacy statistics: 
- not integrate with the graphics on the Analytics page
- however, SA want to provide a download function that include GA and legacy statistics
3. Parsing legacy statistics:
- for each handle (parent work in SA), create a csv with three columns: date, total downloads, total views

**Comment by zhang4952** [comment]
Elasticsearch contains no record between 2014-08-01 and 2014-12-31 (but other periods are fine). I will try to find out what is the cause of it. @revgum

**Comment by vantuyls** [comment]
statistics moved and added to local database.
