### ISSUE TITLE
_form_permission_under_embargo failed to render

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#508]
Create a work, in embargo, then try to edit it. The default partial is not provided by Hyrax.

**Comment by vantuyls** [comment]
@revgum still an issue? i dont' fully understand the nature of the problem. 

Is it that you can't see all of the visibility options after it is set to embargo? I also noted that the mention of the Embargo Management Page in the visibility box, and it's a broken link...

**Comment by revgum** [comment]
captured and fixed recently by Greg
