### ISSUE TITLE
Default role for registered users

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#511]
Establish a "Role" for registered users, tie this role to appropriate AdminSets for deposit/manager/viewer roles. 

Maybe a default registered user role would allow for "Self Deposit" items. 

Do we create a role for users who would deposit ETDs, Articles, and other items? If so, we have to manage associating the user after they register with SA to the appropriate "Groups".

**Comment by vantuyls** [comment]
Default registered user role should follow the "default workflow". In our case, that default workflow is one step mediation.

**Comment by zhang4952** [comment]
Another use case: for graduate students submitting ETDs, they should be added as the 'depositor' role to ETD admin set. That means the registration process will check CAS and check whether the user is a graduate student.
