### ISSUE TITLE
show the 'canonical'/citable URI alongside the descriptive metadata

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#520]
URLs get all junked up with stuff, we want the clean URI in the descriptive metadata on the show page for each item.

**Comment by wickr** [comment]
Can you expand on this? Which fields? Show Labels and URIs? Or is this making sure a straight URL doesn't get mangled?

**Comment by vantuyls** [comment]
yep. 

This is the URL: http://ir-staging.library.oregonstate.edu/concern/default_works/hx11xf25t?locale=en

But we want URI: http://ir-staging.library.oregonstate.edu/concern/default_works/hx11xf25t

people usually have a hard time parsing URLs for the useful bits, so if we put the URI in the metadata, it'll help.

**Comment by wickr** [comment]
Ok, would a better description be to show the 'canonical'/citable URI alongside the descriptive metadata? I don't think it needs to be inserted into the metadata. If it's needed for OAI or other retrieval/export it can be added automatically. (OD inserts the 'view URL' into an OAI record response).
