### ISSUE TITLE
Export from elasticsearch

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#522]
We can let @atmire to export the usage statistics from elastic search, but we should agree on the format of the export:
- two spreadsheets: one for pageview and one for download
- columns: item_id, bitstream_id, every month since SA@OSU is in production
- rows: monthly download/pageview for each item/bitstream

The granularity of time (monthly, weekly, or daily) has significant impact of spreadsheet size, and have to take in consideration. Comments?

**Comment by zhang4952** [comment]
@revgum @vantuyls @wickr @straleyb @luisgreg99 @mwillihooper

**Comment by zhang4952** [comment]
Atmire responses with more questions about the export, let's record our conversation and try to get the most from it:
1.) what format/structure of the text file should be? (we assume csv?)

2.) how should additional fields with multiple values be stored? ( as a csv column value with "||" delimiting the additional multiple values?)

3.) is it sufficient to reference items by owningItem (internal item id) or would it be necessary to map to the items handle identifier? (The latter will be more difficult, doing so will require us to implement the solution in java using the DSpace API)

4.) do you eventually want to attach these files to the existing Items in DSpace as bitstreams or just maintain them is a separate directory? (Doing so will require us to implement the solution in java using the DSpace API)

5.) does the script need to update existing files with new data via repeated calls? or will you be running one single dump?

**Comment by zhang4952** [comment]
Atmire provide a solution that I think is working for us, and I will make sure atmire has the information at item G. It will take most of our credits (64 out of 81) and seems like can meet our migration schedule.

A.) use psycopg2 PyGreSQL to access postgres and retrieve the item handle. If possible we will cache these in memory to speed up processing. You will need to install one of these from pip on your system

B.) We will add any available data in the json output to the csv, other than the handle identified in (1), we cannot translate any other information to other formats.

C.) The script will work with other versions of DSpace earlier than DSpace 6, which changes from "int" to "uuid" for internal identifiers.

D.) We will add support to provide a community, collection or item handle (it will be looked up in the DSpace database and the Elasticsearch query tuned to only return those results.

E.) The script will work on incremental subsets of the statistics only in that the existing script lets you parameterize timeframes. Care will need to be taken not to run the script such that it overwrites or appends new statistics to an existing set of files.

F.) The script will export results to separate csv files in a configured directory (one csv file for each item)

G.) We will need access to your ElasticSearch service via http and a dump of your postgres database to develop and test the work against.

We estimate this work will take 16 hours of developer time (64 credits) to develop, test locally on our systems and provide instruction for execution on your system.

**Comment by vantuyls** [comment]
@zhang4952 have you been updating this ticket or is this being reported in another ticket?

**Comment by zhang4952** [comment]
Export elasticsearch statistics in CSV for 60,637 DSpace items to lib-saapp1: /data0/hydra/shared/tmp/elasticsearch_export
