### ISSUE TITLE
Hyrax::BasicMetadata indexing consideration

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#525]
None of the fields in Hyrax::BasicMetadata are indexed/searchable by default, we need to consider which of those we want indexed and override them in our app.

https://github.com/projecthydra-labs/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb

I'm imagining `resource_type` and `creator` at least, what do @vantuyls  and @wickr think?

**Comment by straleyb** [comment]
This ticket is related to #339. When we get a list of things that we want indexed and searchable by default, then we should be able to close out both these tickets at the same time.

**Comment by vantuyls** [comment]
are these the only metadata fields that are indexable, or can we also include other fields that are not in basic_metadata.rb?

**Comment by vantuyls** [comment]
What are these fields?
property :label, predicate: ActiveFedora::RDF::Fcrepo::Model.downloadFilename, multiple: false
property :description, predicate: ::RDF::Vocab::DC11.description
property :based_near, predicate: ::RDF::Vocab::FOAF.based_near
property :source, predicate: ::RDF::Vocab::DC.source

**Comment by revgum** [comment]
https://docs.google.com/spreadsheets/d/1koKjV7bjn7v4r5a3gsowEimljHiAwbwuOgjHe7FEtuw/edit?ts=58f7857e#gid=0

**Comment by wickr** [comment]
No we can index whatever we want.

:label is filename
:description is description
:based_near is Location
:source is Source and can be a related or derived-from resource

Of these I would do:
Indexed: label, description, source, based_near
Faceted: based_near

**Comment by zhang4952** [comment]
related to #532

**Comment by vantuyls** [comment]
I'd like to close this issue given the work done over the past month on the MAP. @revgum @zhang4952 @straleyb @wickr @luisgreg99
