### ISSUE TITLE
What is the maximum filesize for upload

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#528]
heard from some folks at UW that the hyrax uploader has a 200MB max filesize. Is this true? Can we up that to 5GB or something in that ballpark?

**Comment by revgum** [comment]
Hyrax default max file size for the uploader.js is currently 500mb: https://github.com/projecthydra-labs/hyrax/blob/1e504c200fd9c39120f514ac33cd42cd843de9fa/app/assets/javascripts/hyrax/uploader.js#L32

I've set Nginx to allow for 4gb or 10min whichever comes first right now. I've tested with a 260mb(ish) file and it took just about 6min from my laptop to the server using dspace2hydra. 

We should chat more and do some testing.

**Comment by revgum** [comment]
Also to consider, this taxes the memory of the web server as the uploaded file is cached in memory by nginx before handing it off to the application to process. We probably don't expect to have huge files frequently uploaded, but it's something to keep in mind.

**Comment by vantuyls** [comment]
yeah. i'd like to find a good balance point. i suspect it is around 5 gb and that this upload size wont happen very often. above that, we'd push the depositor to torrent (or ipfs/dat).

**Comment by revgum** [comment]
My test of 500mb file upload using the web UI timed out (> 10min) .. I'm thinking we should aim for something like 1gb for the max using the web UI. Lets table this and do some testing..

**Comment by wickr** [comment]
We can always bypass the web uploader past a certain size, and add the files to Fedora through the console or something. 1-5GB seems like a lot in the browser. 

Avalon folks and the Browse Everything plugin have addressed this some: https://github.com/projecthydra/browse-everything  though I don't see explicit mention of file sizes/limits in the README.

**Comment by vantuyls** [comment]
closed but referenced by MS3 tix: #817
