### ISSUE TITLE
How do we want to save URI's for linked data?

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#539]
For example, when we use Questioning Authority to find a label in the form, it saves the label as a string but doesn't save the URI. We could save the URI on the work as well as SOLR at the same time, or simply index it in SOLR or only in Fedora?

Basically where would we want to store this data, if anywhere? 

If we index it in SOLR, we can search either the label or the URI which seems handy in some cases.

**Comment by vantuyls** [comment]
Decision for URI enabled fields:
*Store URI and Label as separate properties
*URI is not facetable but IS serchable
*Label is facetable and searchable

**Comment by vantuyls** [comment]
want to be able to search Alt Labels, too

**Comment by wickr** [comment]
Clarifying what Steve said:
* store URI in Fedora on record
* store URI and label in Solr  (label is fetched on save if not already in triplestore)
* URI is not facetable but IS searchable
* Label is facetable and searchable

searching alt labels is a bigger project regarding enhancements that I think needs a lot more attention: where/how they're searched, term weighting, how they're displayed, etc.
