### ISSUE TITLE
Which fields do we want hooked up to Linked Data.

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#540]
Currently we can implement subject, quite easily as a Linked Data Field (RDF Enabled field) What is the list of fields, we would like to hook up as well and where do we want those fields querying.

In example, subject searches LOC for subject headings.
Or Location searches Geonames.

**Comment by wickr** [comment]
These will be listed in the Vocabularies column of the Metadata Application Profile.
