### ISSUE TITLE
Make Degree Name and Degree Level local authorities

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#543]
Are there any fields we would like to use any local authorities for? Or do we have to implement this for CVM data? I dont believe CVM has a sparql endpoint but I could be wrong.

**Comment by wickr** [comment]
By 'local authorities' here do you mean the list of values is stored in Hyrax like the rights statements?  I don't know of any field we'd use that for.

CVM has SPARQL through Blazegraph, yes.

**Comment by vantuyls** [comment]
@straleyb @wickr status? milestone?

**Comment by wickr** [comment]
Per the MAP, we've decided to make Degree Level and Degree Name local authorities.

**Comment by wickr** [comment]
Making this Milestone 1 since on Ingest any values should validate and match the local authority.
