### ISSUE TITLE
Enhance JavaScript for QA for a better user experience.

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#544]
Like maybe adding an in progress spinner that lets you know its searching. 

Also an error or alert suggesting it didnt or it didnt find anything.

**Comment by revgum** [comment]
We should write some modular JS that adds/extends this functionality to the fields that get the `autocomplete` functionality. It would make it somewhat easier to create a PR for this to the community (rather than overriding the existing autocomplete JS)

**Comment by straleyb** [comment]
This would be something to think about getting into hyrax.
