### ISSUE TITLE
If we save URI's, should we be able to toggle between the uri and the label

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#545]
Switchy Button

**Comment by revgum** [comment]
I'd say the uris and alt labels should be microdata and probably just small light grey text just beneath the label itself. I'm thinking fewer clicky buttons for the sake of seeing additional information.. OTOH, if there are a ton of altLabels, maybe the small light grey div can expand/collapse itself in a `:hover` event.

**Comment by wickr** [comment]
The URI is the main/only piece of data being saved. And the label is not actually saved, at least on the work/record. So I think the URI should go in the form field. If we want to show the label underneath or to the side to help verify, that could work. On Oregon Digital's edit form, once a field with a URI is saved, it is disabled and on subsequent views changed to show the Label only.

I still think altLabels can be held off on for now, but maybe they're essential to workflow. I don't think they're worth showing under every field that has them.

**Comment by vantuyls** [comment]
@wickr @straleyb @revgum status? milestone?
