### ISSUE TITLE
build all workflows for SA@OSU

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#549]

**Comment by vantuyls** [comment]
Comments on this workflow would be useful. This is a two step review workflow for graduate theses and dissertations (GTDs). States include: deposited, gs_review, osulp_review, 

{
    "workflows": [
        {
            "name": "gtd_workflow",
            "label": "Graduate Thesis and Dissertation Workflow",
            "description": "Workflow for Graduate Theses and Dissertations. Review includes the Graduate School and OSULP Cataloging.",
            "actions": [
                {
                    "name": "deposit",
                    "from_states": [],
                    "transition_to": "gs_review",
                    "notifications": [
                        {
                            "notification_type": "email",
                            "name": "Hyrax::Workflow::PendingReviewNotification",
                            "to": ["approving"]
                        }
                    ],
                    "methods": [
                        "Hyrax::Workflow::DeactivateObject"
                    ]
                }, {
                    "name": "request_changes",
                    "from_states": [{"names": ["deposited", "gs_review", "osulp_review"], "roles": ["approving"]}],
                    "transition_to": "changes_required",
                    "notifications": [
                        {
                            "notification_type": "email",
                            "name": "Hyrax::Workflow::ChangesRequiredNotification",
                            "to": ["approving"]
                        }
                    ],
                    "methods": [
                        "Hyrax::Workflow::DeactivateObject"
                    ]
                }, {
                    "name": "approve",
                    "from_states": [{"names": ["osulp_review"], "roles": ["approving"]}],
                    "transition_to": "deposited",
                    "notifications": [
                        {
                            "notification_type": "email",
                            "name": "Hyrax::Workflow::DepositedNotification",
                            "to": ["approving"]
                        }
                    ],
                    "methods": [
                        "Hyrax::Workflow::ActivateObject"
                    ]
                }, {
                    "name": "request_review",
                    "from_states": [{"names": ["changes_required"], "roles": ["depositing"]}],
                    "transition_to": "pending_review",
                    "notifications": [
                        {
                            "notification_type": "email",
                            "name": "Hyrax::Workflow::PendingReviewNotification",
                            "to": ["approving"]
                        }
                    ]
                }, {
                    "name": "comment_only",
                    "from_states": [
                        { "names": ["changes_required"], "roles": ["depositing"] },
                        { "names": ["pending_review", gs_review", "osulp_review", "deposited"], "roles": ["approving"]}
                    ]
                }
            ]
        }
    ]
}

**Comment by revgum** [comment]
Fixed the JSON:
```
{
  "workflows": [{
    "name": "gtd_workflow",
    "label": "Graduate Thesis and Dissertation Workflow",
    "description": "Workflow for Graduate Theses and Dissertations. Review includes the Graduate School and OSULP Cataloging.",
    "actions": [{
      "name": "deposit",
      "from_states": [],
      "transition_to": "gs_review",
      "notifications": [{
        "notification_type": "email",
        "name": "Hyrax::Workflow::PendingReviewNotification",
        "to": ["approving"]
      }],
      "methods": [
        "Hyrax::Workflow::DeactivateObject"
      ]
    }, {
      "name": "request_changes",
      "from_states": [{
        "names": ["deposited", "gs_review", "osulp_review"],
        "roles": ["approving"]
      }],
      "transition_to": "changes_required",
      "notifications": [{
        "notification_type": "email",
        "name": "Hyrax::Workflow::ChangesRequiredNotification",
        "to": ["approving"]
      }],
      "methods": [
        "Hyrax::Workflow::DeactivateObject"
      ]
    }, {
      "name": "approve",
      "from_states": [{
        "names": ["osulp_review"],
        "roles": ["approving"]
      }],
      "transition_to": "deposited",
      "notifications": [{
        "notification_type": "email",
        "name": "Hyrax::Workflow::DepositedNotification",
        "to": ["approving"]
      }],
      "methods": [
        "Hyrax::Workflow::ActivateObject"
      ]
    }, {
      "name": "request_review",
      "from_states": [{
        "names": ["changes_required"],
        "roles": ["depositing"]
      }],
      "transition_to": "pending_review",
      "notifications": [{
        "notification_type": "email",
        "name": "Hyrax::Workflow::PendingReviewNotification",
        "to": ["approving"]
      }]
    }, {
      "name": "comment_only",
      "from_states": [{
          "names": ["changes_required"],
          "roles": ["depositing"]
        },
        {
          "names": ["pending_review", "gs_review", "osulp_review", "deposited"],
          "roles": ["approving"]
        }
      ]
    }]
  }]
}
```

**Comment by revgum** [comment]
Need roles for `osulp_review` and `gs_review` and then to sort out the `request_review` state to transition to a state that is reflected/handled within the `approve` state.

**Comment by vantuyls** [comment]
[sa_gtd_workflow.txt](https://github.com/osulp/Scholars-Archive/files/968736/sa_gtd_workflow.txt)
[sa_datasets_workflow.txt](https://github.com/osulp/Scholars-Archive/files/968735/sa_datasets_workflow.txt)
[sa_stakeholder_workflow.txt](https://github.com/osulp/Scholars-Archive/files/968733/sa_stakeholder_workflow.txt)
[sa_noreview_workflow.txt](https://github.com/osulp/Scholars-Archive/files/968737/sa_noreview_workflow.txt)
[sa_default_workflow.txt](https://github.com/osulp/Scholars-Archive/files/968734/sa_default_workflow.txt)
