### ISSUE TITLE
Add DC Abstract to DefaultMetadata

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#558]
We're changing Description to Abstract. 

Need to add dct:abstract to DefaultMetadata. Property name is :abstract, faceted no, searchable yes, indexed yes

Label is Abstract or Summary. 

MAP: https://docs.google.com/spreadsheets/d/1koKjV7bjn7v4r5a3gsowEimljHiAwbwuOgjHe7FEtuw/edit?usp=sharing

**Comment by vantuyls** [comment]
@straleyb FYI
