### ISSUE TITLE
Add architecture for allowing SA to get RDF from sources that dont respond to RDF::Graph.load

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#566]
For example, Geonames links do not work with RDF::Graph.load. Instead, what we have to do is allow geonames to return its "RDF" and take it and build a graph ourselves. Then we can send that graph over to the triplestore adapter's store method and we can cache it ourselves. 

- [ ] Change triple_powered_properties to a hash which contains the CV endpoint.
- [ ] Create new object which has ScholarsArchive::TriplePoweredProperties::Triplestore as a base
- [ ] Object responds to fetch and overrides triple_powered_properties
- [ ] App checks if provided URI that doesnt work with Graph.load is in triplestore or not.
- [ ] Fetches RDF and builds/returns graph
- [ ] Graph gets saved into triplestore

**Comment by revgum** [comment]
no longer needed with triplestore-adapter update to use rdf/rdf-xml for fetching geonames
