### ISSUE TITLE
Translate MAP to Default Metadata

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#572]
Take contents from the MAP:
https://docs.google.com/spreadsheets/d/1koKjV7bjn7v4r5a3gsowEimljHiAwbwuOgjHe7FEtuw/edit#gid=0

and put it into the Default Metadata, indexers, and presenters. For:
- [x] ETD
- [x] Default
- [x] EESC
- [x] Article

**Comment by straleyb** [comment]
Relates to #576
