### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#58]
as an administrator i want to be able to load a new version of an item to SA@OSU while tracking the provenance of the item.

**Comment by vantuyls** [comment]
Version control exists in Hyrax, but need to check to see if it does what we want it to do.

**Comment by straleyb** [comment]
We checked to see if Versioning worked in Hyrax. Short answer, it doesn't. 

Long Answer: From what I can tell, It looks like there is an argument error, 
`wrong number of arguments (1 for 2)` in the file_actor in ingest_file.

https://github.com/projecthydra-labs/hyrax/blob/master/app/actors/hyrax/actors/file_actor.rb#L23

The faulty call is coming from here

https://github.com/projecthydra-labs/hyrax/blob/master/app/actors/hyrax/actors/file_set_actor.rb#L89

**Comment by straleyb** [comment]
Reevaluate the work on this Friday April 21st, 2017
