### ISSUE TITLE
Add CrossRef FundRef funders as Questioning Authority source

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#586]
For the type-ahead source for the Funding Body field, QA should search CrossRef's FundRef funders list.

Here is CrossRef's search widget with type-ahead: http://search.crossref.org/funding
and code: https://github.com/Crossref/fundref-widget

That appears to be hitting search.crossref.org
Example of full list with tokenized labels: http://search.crossref.org/funders?

The field should store the URI: http://dx.doi.org/10.13039/100000003

**Comment by vantuyls** [comment]
@simholt i recall you checked on this and it looked like fundref was available for use and populated enough to be useful. is that correct?

**Comment by simholt** [comment]
@vantuyls Yep. It isn't perfect but getting better every day.

**LOOKINTO FUNDER REGISTRY (no more fundref)**

- https://www.crossref.org/services/funder-registry/
- Currently (Jan 2018) have almost 16,000 funders listed.
- Is updated monthly.
- Search: https://search.crossref.org/funding
- API: https://github.com/CrossRef/rest-api-doc
- Funder Registry: https://github.com/CrossRef/open-funder-registry
- CSV of registry: https://doi.crossref.org/funderNames?mode=list
- More tech stuff: https://support.crossref.org/hc/en-us/sections/203055563-Funding-data

Review from Jan 2015
https://scholarlykitchen.sspnet.org/2015/01/28/what-has-fundref-done-for-me-lately/

Did a scattershot search using some OSU papers --

Not included: 
Washington Blueberry Commission
Washington State Commission for Pesticide Registration
Northwest Agricultural Research Foundation 
University of Tennessee, Knoxville 
USDA Forest Service (USDA, yes; Forest Service, yes)
Rocky Mountain Research Station's Great Basin Native Plant Project
Malheur County Education Service District 
Northwest Potato Research Consortium 

WoS fundings listings aren’t always accurate. Some have weird numbers/letters in places.

**Comment by geekscruff** [comment]
In case you weren't aware: https://github.com/samvera/questioning_authority/blob/master/lib/qa/authorities/crossref.rb

**Comment by carakey** [comment]
This is no longer viable. Fundref / Funder Registry has been merged with ROR and will be phased out. We should look into ROR to support Funding Body instead - will ticket separately.
