### ISSUE TITLE
consider a more conservative result list view

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#594]
the list view in the hyrax results page shows too much information and the thumbnail is a bit too big. this makes the results list hard to read because you are only seeing one or two items on the page. if blacklight has a different gallery view that is more conservative, maybe we coudl use that?

This also might be something to consider asking to be implemented in hyrax.

**Comment by wickr** [comment]
I think limiting words in description in #592  and reducing the fields shown to what is in the MAP under 'Search Results Fields' will help a lot. Reducing the thumbnail size can be done in CSS.

**Comment by revgum** [comment]
This CSS rule can be included to resize the image causing the view to look better:

`.document .list-thumbnail {
    width: 15%;
}`

**Comment by vantuyls** [comment]
Title font size to  to 24px

h2.modal-title
