### ISSUE TITLE
Figure out why Google Scholar metadata not being included in output

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#597]
In an Item page, there's a section in the source `<head>` that says "Google Scholar metadata" but nothing is output.

Hyrax has a template for Google Scholar and Twitter metadata, need to figure out why this isn't displaying anything. https://github.com/projecthydra-labs/hyrax/blob/a3245fb01b39bb40600cadb4743cba5e2f976c0d/app/views/shared/_citations.html.erb

Issue in Hyrax: https://github.com/projecthydra-labs/hyrax/issues/109

**Comment by vantuyls** [comment]
this has been resolved by hyrax#109. double check that we're seeing these tags as expected.
