### ISSUE TITLE
Duplicate Academic Units with overlapping date ranges

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#627]
Here are some situations that I found where we have two URIs that have overlapping dates and with the same Label. I think each of these needs to have one term deleted and its date merged with the other:
```
http://opaquenamespace.org/ns/osuAcademicUnits/anFD3WEN & http://opaquenamespace.org/ns/osuAcademicUnits/t55uBUrB

http://opaquenamespace.org/ns/osuAcademicUnits/AOTNK61a & http://opaquenamespace.org/ns/osuAcademicUnits/ML4lsV6u

http://opaquenamespace.org/ns/osuAcademicUnits/SiEOLn7 & http://opaquenamespace.org/ns/osuAcademicUnits/TALPtSDu

http://opaquenamespace.org/ns/osuAcademicUnits/ea6nw3Q4 & http://opaquenamespace.org/ns/osuAcademicUnits/jUkDpZiw
```

**Comment by vantuyls** [comment]
These are departments with different parents units. For example, Agricultural Education has both the parent units Agriculture and Education. It is unclear from the source data whether there were actually two departments in these cases or a single department with two parent units, so respecting the source data, we need the two different departments.

Lumber manufacture is just a straight up duplicate, though. Dedupe, please.

**Comment by wickr** [comment]
For Lumber Manufacture, I checked, and http://opaquenamespace.org/ns/osuAcademicUnits/SiEOLn7 was used in SA, so I removed http://opaquenamespace.org/ns/osuAcademicUnits/TALPtSDu.

It's all cleared away on opaquenamespace.org. So it should update in SA accordingly.
