### ISSUE TITLE
UI for Location Needs Fixed

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#633]
Location element on the UI is behaving badly. 
![screen shot 2017-06-12 at 10 42 23 am](https://user-images.githubusercontent.com/9534576/27047166-ec860170-4f5b-11e7-8792-ed9721695fd6.png)

- [x] need to extend the fields so they match length of other fields
- [x] search box needs to be same size as other fields
- [x] need an empty field under location by default

**Comment by revgum** [comment]
Also, failing to persist on the backend when the metadata is changed to properly use it as a controlled property:
```
self.controlled_properties = [:based_near]

property :based_near, predicate: ::RDF::Vocab::FOAF.based_near, class_name: Hyrax::ControlledVocabularies::Location do |index|
  index.as :stored_searchable, :facetable
end

accepts_nested_attributes_for :based_near, :allow_destroy => true, :reject_if => proc { |a| a[:id].blank? }
```

UI Error:
```
Location
#<Hyrax::ControlledVocabularies::Location:0x007f8c42b50650> is not a URL
```
