### ISSUE TITLE
Fix Ordering of Metadata on show page and Ingest page.

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#656]
Via https://docs.google.com/spreadsheets/d/1MOMoLH_vfVDLNHri-yDDfFKOUo4dnomUfp9ntaXzX3E/edit#gid=0 which shows the ordering of the metadata

**Comment by straleyb** [comment]
Done for Default Models. Needs to be done with the metadata for etd, oer, and article

**Comment by straleyb** [comment]
References #642

**Comment by luisgreg99** [comment]
- [ ] Default
- [ ] Article
- [ ] ETD
- [ ] OER
