### ISSUE TITLE
Users without emails can't edit profile

### ISSUE THREAD

**Issue by terrellt** [osulp/Scholars-Archive#66]

**Comment by straleyb** [comment]
@terrellt So I was thinking we could add a before filter on the catalog controller that checks the presence of a valid current session and also checks to see if the current session's user has a valid email (Any email really). If there is an invalid email, then we redirect to a form, where we allow them to input an email, so they can edit their profile. Thoughts?

This could either be an underlying issue with cas, cas_authenticatable, or sufia, but we can mitigate it for all people without an email.
