### ISSUE TITLE
TriplePoweredProperties not fetching labels properly

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#704]
When the other_affiliation is pointing at id.loc.gov, we are not fetching labels.

I believe the functionality in the TriplePoweredProperties needs to be more intelligent in finding the `prefLabel` before `label`, and so on. 

![screen shot 2017-07-05 at 3 20 45 pm](https://user-images.githubusercontent.com/32885/27887499-e8a48d28-6195-11e7-947b-12a91cb2589c.png)

**Comment by revgum** [comment]
Maybe just add the label predicates here: https://github.com/osulp/Scholars-Archive/blob/master/lib/scholars_archive/triple_powered_properties/triplestore.rb#L26

**Comment by wickr** [comment]
We can call the `default_labels` from ActiveTriples: https://github.com/ActiveTriples/ActiveTriples/blob/dd3e55c24bc7d08676ae3156c811f517939f7f90/lib/active_triples/rdf_source.rb#L558
