### ISSUE TITLE
Academic Affiliation & Other Affiliation label facet duplicates

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#706]
Facets by TriplePoweredProperty related labels are showing as duplicates. This makes sense, because the `Music` Academic Unit is found in multiple URIs (because of date ranges likely) but leaves for a confusing experience. 

![screen shot 2017-07-06 at 7 42 11 am](https://user-images.githubusercontent.com/32885/27916798-0880dc80-621f-11e7-8392-7ee182655e00.png)

**Comment by wickr** [comment]
One way to approach this would be to create a new ControlledVocabularies class for AcademicAffiliation, and then override `rdf.label` to append the date ranges at the end.

Similar to https://github.com/samvera/hyrax/blob/master/app/controlled_vocabularies/hyrax/controlled_vocabularies/location.rb
