### ISSUE TITLE
Notification Emails specific to types of events

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#708]
Automatic notification emails should be specific to the following types of notification events:

- [ ] Deposit Received (to depositor)
- [ ] Deposit Accepted (live in the system; to depositor)
- [ ] Request Changes (to depositor)
- [ ] Request Review (to reviewer role)

**Comment by luisgreg99** [comment]
It looks like the message body for an email notification is currently defined in the Notification object itself in hyrax: 

ChangesRequiredNotification:
https://github.com/samvera/hyrax/blob/master/app/services/hyrax/workflow/changes_required_notification.rb#L11

DepositedNotification:
https://github.com/samvera/hyrax/blob/master/app/services/hyrax/workflow/deposited_notification.rb#L11

PendingReviewNotification
https://github.com/samvera/hyrax/blob/master/app/services/hyrax/workflow/pending_review_notification.rb#L11

**Comment by vantuyls** [comment]
I'll peek at these Monday. Need to generate notification text for the important ones there.

**Comment by vantuyls** [comment]
submission emails should include some indication of the mediation process the item will be going through.
