### ISSUE TITLE
[METADATA] Check if metadata values mapped to dce:description

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#714]
We set up Abstract and Additional Information (`dct:description`) but still have `dce:description` defined in default_metadata, and values may have been mapped there: https://github.com/osulp/dspace2hydra/blob/b4604f06288829711e57a50f79deedad588aaf5b/config/graduate_thesis_or_dissertation.yml#L247

Should query Solr to check for any existing values. There doesn't appear to be a presenter set up for this.

If no,
remove property from default_metadata
change dspace2hydra mapping to use `additional_information` to be safe

If yes,
add `dce:description` to MAP
possibly plan for a later change

**Comment by straleyb** [comment]
Additional_information and description are being mapped differently and contain separate information. There will be a discussion with steve about whether this is ok or if things need to be changed.
