### ISSUE TITLE
bibo:peerReviewed doesn't exist, look again at BIBO ontology

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#716]
`http://purl.org/ontology/bibo/peerReviewed` which is mapped in default metadata doesn't actually exist. 

There is a `http://purl.org/ontology/bibo/status/peerReviewed` and it's counterpart `http://purl.org/ontology/bibo/status/nonPeerReviewed` but they're term values for I think the bibo:DocumentStatus property.

The ontology is here: https://github.com/structureddynamics/Bibliographic-Ontology-BIBO/blob/master/bibo.owl

**Comment by wickr** [comment]
@vantuyls @simholt 

Option A:
Change predicate to http://dbpedia.org/ontology/isPeerReviewed in DefaultMetadata and all items with this predicate
The values for that are of range xsd:boolean (one of 'true', 'false', 1, 0) so I think we're ok there, even though our TRUE/FALSE are capitalized

Option B:
Change predicate to http://purl.org/ontology/bibo/status in DefaultMetadata and all items with this predicate
Change PeerReviewed property values (TRUE/FALSE) to
* http://purl.org/ontology/bibo/status/peerReviewed
* http://purl.org/ontology/bibo/status/nonPeerReviewed

This would allow other Statuses defined by BIBO ('draft', 'forthcoming', 'legal', 'published', 'rejected, 'unpublished' have URIs) and any others we would want to define. The existing Peer Reviewed facet could be configured to stay as it is now, or it could be merged in to a bigger 'Document Status' one that has Peer Reviewed and Non Peer Reviewed along with the other values.

**Comment by wickr** [comment]
Steve said go with Option A.

**Comment by vantuyls** [comment]
@wickr please also update the MAP when you finalize this.

**Comment by vantuyls** [comment]
@simholt @wickr if this is properly reflected on the MAP, please close this issue.

**Comment by revgum** [comment]
The current thinking is that I run a job to change the predicate in Fedora in conjunction with a code update so the application knows about the property/predicate change, and our “QA” service is aware of the metadata value. The new values should be lowercase `true` and `false`. 

The solution to this ticket will need to be coordinated and planned to run the Fedora update immediately after the code is pushed to production.

**Comment by carakey** [comment]
We are changing the predicate to `http://dbpedia.org/ontology/isPeerReviewed` (as in Option A, with agreement as documented in this ticket in Jan 2018). The new predicate should have xsd:boolean conformant values `true` or `false`.

Aspects of this change include:

- [ ] Change predicate for existing items from `http://purl.org/ontology/bibo/peerReviewed` to `http://dbpedia.org/ontology/isPeerReviewed`
- [ ] Update code with new predicate
- [ ] Change values for existing items from `TRUE`/`FALSE` to `true`/`false`
- [ ] Update controlled vocabulary to use lowercase values: https://github.com/osulp/Scholars-Archive/blob/master/config/authorities/peerreviewed.yml
- [ ] Update MAP

**Comment by revgum** [comment]
Production update process;

- [ ] Tunnel to the SOLR server and query all of the works (~44k) with `peerreviewed` set : http://localhost:8983/solr/hydra-prod/select?fl=id,%20peerreviewed_tesim&indent=on&q=peerreviewed_sim:*&rows=60000&wt=csv
- [ ] Rake task to iterate through each work; deleting the statement with the old predicate from the graph, setting the `peerreviewed` to lowercase value, save the work (updates Fedora and index)

**Comment by carakey** [comment]
**QA TL;DR:** QA Pass for new instances of the Peer Reviewed statement / field. However QA fail for updates to existing Peer Reviewed statements.

- - - - - -

QA in Staging based on criteria in 4/30/19 comment above:

- **Criteria:** Change predicate for existing items from http://purl.org/ontology/bibo/peerReviewed to http://dbpedia.org/ontology/isPeerReviewed
     - Found an existing item [v692t643n](https://ir-staging.library.oregonstate.edu/concern/defaults/v692t643n?locale=en) with `Peer Reviewed = Yes`
     - Downloaded the NT and examined with Sublime Text. The file has the statement: `<https://ir-staging.library.oregonstate.edu/concern/defaults/v692t643n> <http://purl.org/ontology/bibo/peerReviewed> "TRUE" .` 
     - **QA fail.** The existing item still has the old bibo predicate. 
     
- **Criteria:** Change values for existing items from TRUE/FALSE to true/false
     - **QA fail.** See above; the existing item still has the old allcaps "TRUE" value.

- **Criteria:** Update code with new predicate
    - Found an existing test work of mine with no Peer Reviewed value [pk02c995f](https://ir-staging.library.oregonstate.edu/concern/articles/pk02c995f?locale=en)
    - Edited metadata to add `Peer Reviewed = Yes` & saved changes
    - Downloaded the NT and examined with Sublime Text. The file has the statement: `<https://ir-staging.library.oregonstate.edu/concern/articles/pk02c995f> <http://dbpedia.org/ontology/isPeerReviewed> "true" .`
    - **QA pass** A new entry in the Peer Reviewed field uses the new dbpedia predicate.

- **Criteria:** Update controlled vocabulary to use lowercase values: https://github.com/osulp/Scholars-Archive/blob/master/config/authorities/peerreviewed.yml
    - **QA pass** See above; a new entry in the Peer Reviewed field uses the lowercase "true" value.

- ~Update MAP~ (for @carakey to do when the others are done)

**Comment by lamtu1** [comment]
Hi @carakey, have you run the rake task that is include in this PR, `:update_peer_review_data`? This file will update it all the old `peerreview` to the new predicate and change the value as well.

**Comment by carakey** [comment]
Hi @lamtu1, running rake tasks is not a thing I do. I don't have back end access and I wouldn't know how to run one if I did.

**Comment by lamtu1** [comment]
Hi @carakey, I will ask either Brandon and Corey about running on staging to test and see if we could do it.

**Comment by carakey** [comment]
QA Round 2 -- fail. A statement with the new `dbpedia` predicate was added, but the old `bibo` statement was not removed.

- - - - - 

QA detail: 

* Found another existing item [cr56n115b](https://ir-staging.library.oregonstate.edu/concern/articles/cr56n115b?locale=en) with `Peer Reviewed = Yes`
* Downloaded the NT ([here](https://ir-staging.library.oregonstate.edu/concern/articles/cr56n115b.nt)) and examined with Sublime Text. **The file has both the old and new statements:**

```
(line 26) <https://ir-staging.library.oregonstate.edu/concern/articles/cr56n115b> <http://purl.org/ontology/bibo/peerReviewed> "TRUE" .
(line 41) 
<https://ir-staging.library.oregonstate.edu/concern/articles/cr56n115b> <http://dbpedia.org/ontology/isPeerReviewed> "true" .
```

Staging has 3 total files with pre-existing Peer Reviewed values: 

* [cr56n115b](https://ir-staging.library.oregonstate.edu/concern/articles/cr56n115b?locale=en) 
* [v692t643n](https://ir-staging.library.oregonstate.edu/concern/defaults/v692t643n?locale=en) 
* [vt150j424](https://ir-staging.library.oregonstate.edu/concern/articles/vt150j424?locale=en)

...Plus one that I added in QA round 1: 

* [pk02c995f](https://ir-staging.library.oregonstate.edu/concern/articles/pk02c995f?locale=en)

Looking further into this, I checked the NT files for all 4 in this round. All 3 pre-existing ones now have both statements. The post-update one only has the `dbpedia` statement.

**Comment by carakey** [comment]
After @lamtu1 reran the script, all 4 staging works in the previous comment have only the `dbpedia` statement with lowercase "true" values. 

QA pass. 

BUT double check after the first run on Prod to make sure the old statements are removed.

**Comment by carakey** [comment]
I changed the predicate in the MAP.

**Comment by lamtu1** [comment]
Hi @carakey, I don't think it update fully during the reindex because for updating it, we need to run a rake task that actually update them. I will need to talk with Corey to see if everything on production side is all good with reindexing and I will run that rake task to update it.

**Comment by carakey** [comment]
@lamtu1  It looks like this needs to be run again to swap predicates on existing items.

So, I don't have any way to explicitly search works with the old `bibo` predicate, as far as I know. However, SOLR is indicating none of the Honors College Thesis have a Peer Reviewed value, when this type is expected to have it. Sure enough checking NT files for HCT works they do still have the `bibo` predicate.

__For tracking purposes going forward:__

As of now, using Browse All, I'm seeing, out of 80,667 works:

- 35,921 with Peer Reviewed = No
- 8,173 with Peer Reviewed = Yes
- Leaving 36,573 with no Peer Reviewed value.

**Comment by lamtu1** [comment]
`UDPATE:` I think all the works has been updated to the new predicate after doing an individual ran of each works. Below is the screenshot of all the works with `peer review` value in it. Even though we have 80,667 works, since the field is optional, not all works will have it this field, but after running it couple times. It should be fully updated.

![Image](https://github.com/user-attachments/assets/3c4173ca-9cd2-48c3-a514-87a5282cd27f)

**Comment by carakey** [comment]
@lamtu1 Any idea why the yeses would be lower today than what you reported yesterday? 9,533 < 9,554.

You're correct that not every item will include this field. So while this still feels lower than I expect, I can't prove it without manual spot checking of items that don't have a value. I wish we had captured the counts before this ran - lessons learned for next time. 

@simholt how do these numbers look to you? 

SOLR results by model, with vs without a Peer Reviewed value:

- AdministrativeReportOrPublication - 3578 with / 4276 without
- Article - 5760 with / 3777 without
- ConferenceProceedingsOrJournal - 5341 with / 1192 without
- Dataset - 88 with / 367 without
- Default - 4096 with / 4976 without
- EescPublication - 47 with / 325 without
- GraduateProject - 1794 with / 10 without
- GraduateThesisOrDissertation - 28197 with / 3755 without
- HonorsCollegeThesis - 2299 with / 0 without 
- OpenEducationalResource - 454 with / 733 without
- PurchasedEResource - 1167 with / 49 without
- TechnicalReport - 3630 with / 2742 without
- UndergraduateThesisOrProject - 1111 with / 827 without

**Comment by lamtu1** [comment]
> [@lamtu1](https://github.com/lamtu1) Any idea why the yeses would be lower today than what you reported yesterday? 9,533 < 9,554.

Hi @simholt this is something I have no idea why it would have done that, but when running each individual works, I notice `AdministrativeReportOrPublication` or `Article` end up updating some values, but couple find a blank with no value in it, but I can rerun with just those two and see if there was a weird thing that happen, but I can look into the code and ask if this something normal or funky.

**Comment by simholt** [comment]
AFAICT, thse numbers are fine. The one that changed is probably my doing -- this is a regular field I correct.

**Comment by carakey** [comment]
I'm not sure I'm following @lamtu1 's last comment but if the numbers look okay to Sarah then I'm okay to QA pass.
