### ISSUE TITLE
[ONS Related] the Degree Field drop down list should include only the degree fields that have been granted in the past 5 years

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#717]

**Comment by straleyb** [comment]
@vantuyls Do you know where I could find a list of these? Or maybe a place where I could figure out which ones have been used in the past 5 years?

**Comment by wickr** [comment]
Once the Degrees are in opaquenamespace.org, we'll look at the date field value, if it ends in `open` then it's still active and can be used on the filtered degree list.

**Comment by revgum** [comment]
When rendering the "create" page, filter the list based on the date field value expressed above. `object.new_record? == true`: filter the list
`object.new_record? != true`: don't filter the list, this allows "old" works to have full access to all of the select options.

**Comment by straleyb** [comment]
Blocked by needing the Degree names in ONS
