### ISSUE TITLE
Degree Field drop down list should update every year to represent the most recent 5 years of degree fields

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#718]

**Comment by simholt** [comment]
Sarah will add more info.

**Comment by simholt** [comment]
I'm not 100% sure what Steve had in mind but this feature is built into ONS in that they expire after five years -- and then have to be manually renewed. (Expire from view for the User; Admin will always view all Degree Fields except for deprecated ones.) This could use some finessing but that would be on the ONS end, which is part of a larger issue.
Closing!
