### ISSUE TITLE
Error Missing host to link to when sending emails with Mailboxer

### ISSUE THREAD

**Issue by luisgreg99** [osulp/Scholars-Archive#728]
When creating a new work, we get `Error Missing host to link to` 
 when `Mailboxer::MessageMailer#send_email` is processed. It looks like Mailboxer attempts to build the email message based on values originally defined in a Notification object (from Workflows).

After inspecting the logs, Mailboxer appears to fail when rendering the new_message_email view  due to a missing host in one of the links being defined in this view:
``` 
Rendered .../bundle/ruby/2.2.0/gems/mailboxer-0.15.1/app/views/mailboxer/message_mailer/new_message_email.html.erb (4.3ms)
Completed 500 Internal Server Error in 1882ms (ActiveRecord: 53.7ms)
ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
17:       Visit <%= link_to root_url, root_url %> and go to your inbox for more info.
```

**Comment by revgum** [comment]
Probably need to set the host in an initializer, section 2.7 has details: http://guides.rubyonrails.org/action_mailer_basics.html
