### ISSUE TITLE
Handle the situation when an old migrated item is missing required fields

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#733]
The scenario is such that an old item might not have had appropriate metadata to include a currently required field on the form. When the item is being edited, you are forced to make a selection without knowledge of what value to update. For instance:

http://lib-saapp1.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/hx11xg030/edit?locale=en

Considering our mapping during migration to be "{DegreeName} in {DegreeField}", we migrated only the applicable degree name because the original metadata didn't include the " in {DegreeField}" details: original metadata: `Master of Science (M.S.)`

**Comment by luisgreg99** [comment]
We decided that admin users can manage these special cases. The expectation is that admin users should have access to all the drop-down options available.
