### ISSUE TITLE
Manage harvesting for SA@OSU 

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#751]
Who is harvesting our content and how will this be managed after we migrate to Hyrax?

need to be concerned about:
- [ ] methods of harvest available (OAI-PMH, whatever)
- [ ] how they will handle non-Handle URIs

**Comment by wickr** [comment]
Some Scholarsphere notes: https://github.com/psu-stewardship/scholarsphere/wiki/Upload-to-SHARE-Notify-(Not-working-due-to-share-API-change-no-need-to-test)

**Comment by wickr** [comment]
Some notes from Rick at Notre Dame: http://www.share-research.org/2015/11/ricks-metatips-share-metadata-is-stitching-together-the-research-life-cycle/

**Comment by zhang4952** [comment]
For MS2: we could focus on SHARE harvesting based on ND's Share-notification gem: https://github.com/samvera-labs/share_notify, And the code that does the uploading to SHARE is here: https://github.com/ndlib/curate_nd/blob/master/script/push-to-share.rb. The OAI-PMH gem development, if we think it is necessary, could be MS3.

**Comment by zhang4952** [comment]
Include these issues:
#806 
#808 
#809

**Comment by vantuyls** [comment]
@zhang4952 @wickr status of this issue?

**Comment by zhang4952** [comment]
@wickr 's solution has been deployed to production: https://ir.library.oregonstate.edu/catalog/oai?verb=ListSets. Two known harvesters notified #806
