### ISSUE TITLE
[After Launch] Update Directory of Open Access Repositories (OpenDOAR) listing

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#752]
http://www.opendoar.org/find.php?rID=108&format=full

**Comment by simholt** [comment]
I put in a request for updates, waiting to hear back.

**Comment by simholt** [comment]
They corrected some things but not others. I wrote back again and they corrected everything except the record count:

> All record counts in OpenDOAR are now provided by CORE.
Please contact CORE (www.core.ac.uk) directly with regards to your record count.
