### ISSUE TITLE
CachingService intelligence

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#774]
https://github.com/osulp/Scholars-Archive/blob/master/app/services/scholars_archive/caching_service.rb

- [x] Perform HTTP OPTIONS on the URI, grab the ETag from the headers of the response
- [x] If the response ETag is different than what was previously cached (or it didn't exist to begin with), then cache the ETag and perform HTTP GET to fetch and cache the content
- [x] If the response ETag is the same as what was previously cached, then serve the content that was cached previously
- [x] Set the expires_in to something quite long, such as a year, so that the automatic cache clearing doesn't happen (because presumably the ETag will change as updates happen to the URI endpoint)

`Rails.cache.write` and `Rails.cache.read` would be better to use instead of `.fetch`
http://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-write

**Comment by vantuyls** [comment]
@revgum @straleyb this looks complete. can we close?

**Comment by revgum** [comment]
already covered in previous updates
