### ISSUE TITLE
auto generate bibliographic citation

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#775]
How challenging would it be to concatenate existing data from the metadata into a bibliographic citation in the form:

<authors, comma separated>. (<copyright year>). <title>. <journal title>, <volume>, <issue>.
<publisher>. <DOI>.

**Comment by wickr** [comment]
Citation code already exists but isn't currently exposed, there's presenters that this view calls, but this view isn't currently displayed:
https://github.com/samvera/hyrax/blob/master/app/views/hyrax/citations/work.html.erb

**Comment by wickr** [comment]
It might need some set up:
```
Citation formatting suggestions | requires configuration: enable config.citations in Hyrax initializer, then run rails g hyrax:citation_config
```
from 
https://github.com/samvera/hyrax/wiki/Feature-matrix

**Comment by vantuyls** [comment]
closing to collapse all citation issues onto #818
