### ISSUE TITLE
Format should be removed or suppressed for users

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#783]
isn't this dealt with in the file characterization process?

**Comment by wickr** [comment]
So it's facetable. The data in file characterization is not actionable, it's just a blob of text.

**Comment by vantuyls** [comment]
grr

**Comment by straleyb** [comment]
Is this resolved? @vantuyls

**Comment by vantuyls** [comment]
i'm concerned about the potential mismatch between the file characterization and a manually entered file format. I wonder, too, if format is a useful facet at all. We have Resource Type already which covers broad categories of types and may actually be more useful than format.

**Comment by vantuyls** [comment]
format is mapped from DSpace in Dspace2Hydra. 

Solution: suppress format on all forms but allow admins to see it.
