### ISSUE TITLE
Source is an element in the metadata form but does not appear in the MAP, Do we need to keep source as a metadata element?

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#784]
Should be removed if it's not something we need.

**Comment by wickr** [comment]
This came over from Hyrax's basic_metadata. We could have data in this from DSpace, but I don't see it currently mapped anywhere in dspace2hydra.

**Comment by vantuyls** [comment]
creating issue to remove Source from input forms
