### ISSUE TITLE
Metadata resolution for LCSH terms

### ISSUE THREAD

**Issue by mickeroo** [osulp/Scholars-Archive#8]
As an administrator I want LCSH headings to autocomplete for the subject field on the ingest form so that I don't have to manually find the URIs.

**Comment by terrellt** [comment]
There should be a way to search LCSH for good terms and provide contextual data about each term - IE description.

**Comment by terrellt** [comment]
This searching should happen after a person enters a plain string into the search box.

**Comment by revgum** [comment]
Closed upon review of issues
