### ISSUE TITLE
Notify OAI harvested with new SA@OSU address

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#806]
Keep SHARE harvesting with SA@OSU in Hyrax with ND's Share-notification gem: https://github.com/samvera-labs/share_notify, And the code that does the uploading to SHARE is here: https://github.com/ndlib/curate_nd/blob/master/script/push-to-share.rb.

related to #751

**Comment by zhang4952** [comment]
We can start with ND's two step approaches:
- Export metadata in SA@OSU as CSV, like: https://github.com/ndlib/curate_nd/blob/dltp-670/script/make-share-from-solr.rb
- Push to SHARE, like: https://github.com/ndlib/curate_nd/blob/dltp-670/script/push-to-share.rb

**Comment by vantuyls** [comment]
@zhang4952 what is the status of this issue?

**Comment by zhang4952** [comment]
Notify COS contact with the new OAI uri of SA@OSU: https://ir.library.oregonstate.edu/catalog/oai?verb=Identify and https://ir.library.oregonstate.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc, and let them test.

**Comment by zhang4952** [comment]
Notify base.ub@uni-bielefeld.de.

**Comment by zhang4952** [comment]
Both contacts acknowledges that then receive the new SA OAI addresses.
