### ISSUE TITLE
Support OAI 

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#809]
These collections are harvested by other digital libraries in DSpace with OAI-PMH, make sure the harvesting not broken after migrated to Hyrax:
 BASE
 Western Waters

related to #751

**Comment by vantuyls** [comment]
The list of clients for our data from a meeting the last week of july include:
- [ ] SHARE
- [ ] BASE
- [ ] Western Waters
- [ ] Metaarchive

**Comment by vantuyls** [comment]
By "make sure the relationship is not broken" you mean that we need to ensure that our content can be represented in those aggregators?

**Comment by zhang4952** [comment]
OAI documentation and code from OD:
https://github.com/OregonDigital/oregondigital/tree/master/lib/oregon_digital/oai
https://github.com/OregonDigital/oregondigital/wiki/OAI-Documentation

**Comment by zhang4952** [comment]
Update from BASE:
thanks for your message. We index the OAI interface, that's correct. If
there's a change in the URL to the OAI interface just leave us a message
at base.ub@uni-bielefeld.de.

Concerning handle URLs: We index the metadata of the records delivered
via OAI. We are updating all sources about twice a month. If you change
something in the record's metadate, we will update these information in
our index, if the record is marked as updated via OAI. We also
re-harvest and re-index a source completely from time to time.
