### ISSUE TITLE
Ingest form Hover Boxes need to have human readable information so users can understand what they should enter in the field

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#81]
Some fields in the ingest form do not have descriptive information in the hover box under the ? icon (see: dcType). Also would like the field titles to be helpful (e.g. what is dcType for?).

**Comment by vantuyls** [comment]
Maura should be able to provide content/context for the ingest form fields.

**Comment by straleyb** [comment]
Pretty much everything in the "additional fields" section needs attention. 

Dc type, date, spacial, temporal, abstract, table of contents, format, bibliographiccitation, provenance, isreferencedby, relation, iscitedby, isidenticalto, ispartof, isversionof, doi, hdl, orcid, rid. We need specifics on what these fields "mean" or ways to describe what they are to users.

**Comment by mlv611** [comment]
Type refers to the type of item such as article or dataset.  It should be a drop down list.  Date with no qualifier would refer to publication date.  Spacial refers to geographic location @vantuyls will know how it is used in data sets.  Temporal refers to time.  Again @vantuyls will know how it is used in datasets.  Abstract and table of contents are self-explanatory.  Bibliographic citation is the citation for the dataset itself ( or article, whatever the item is we are describing).  Provenance is the history of the item.  Is referenced by refers to articles or other items in the repository that refer to the item.  For example, in Oregon Digital, the Herbarium plant samples have articles in the collection that refer to that species.  Relation refers to a related resource.  Is cited by is used when the data is cited in articles and the bibliographic citation for that resource would be used.  Is identical to is for identical resources.  @vantuyls do we have identical resources in the repository?  Is part of refers to if the data is part of a bigger data project.  isversionof is used for articles to cite another version of the article.  @vantuyls same for data?  DOI is the identifier of the dataset.  hdl is the handle from dSpace.  orcid is the researcher id and rid is the relative id and is administrative metadata - not descriptive.

**Comment by vantuyls** [comment]
@mlv611 - thanks for this input. From the perspective of setting the pop ups in the ingest form (the stuff that lives under the little question marks in the ingest fields) - could you provide actual text that would help a user understand what these fields are for and what they should put in them? For instance, I don't think "Temporal refers to time" is useful for a user. 

That said, looking through the ingest form - i'm not entirely clear why some of these fields are in the form. I know that these represent the metadata we *currently* have in DSpace metadata, but that seems very different to the fields we need for a form and how those fields read to a user.

**Comment by mlv611** [comment]
The input form began long before I began editing it, but it is my understanding that if a field is in the input form, it is because at some point a user did need to enter it.  I didn't realize you needed text for the hover boxes, you should be more specific.  I thought I was answering a programmer's question.  When you decide what fields will remain, I will write the text for you.

**Comment by vantuyls** [comment]
Any updates here?

**Comment by vantuyls** [comment]
We've agreed on text for these hover boxes.

**Comment by vantuyls** [comment]
Agreed on text for these forms in Issue 135
