### ISSUE TITLE
Test filesize upload limit and determine process for too large files

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#817]
Using the web UI, there will be a practical upload limit on filesize. We need to determine what that is and how we want to deal with upload larger than this. 

See also: #528

**Comment by vantuyls** [comment]
@simholt do your recent conversations with @zhang4952 clarify this?

**Comment by simholt** [comment]
@vantuyls
 
Yes. 
I don't want to be responsible for giant files but I'm fine with large using this method.
