### ISSUE TITLE
Set up and configure auto generation of bibliographic citations

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#818]
Hyrax has the ability to generate MLA/APA/Chicago citations automatically for items, but it needs to be set up and surfaced.

**Comment by simholt** [comment]
So it looks like the only date field it pulls from is date_created. We primarily use date_issued; can we switch to that?

Test doc:
 https://ir-staging.library.oregonstate.edu/concern/articles/t148fh339

**Comment by simholt** [comment]
All good here -- pass QA.
