### ISSUE TITLE
Batch export of metadata records

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#837]
Batch export of metadata records from Hyrax for MA preservation and push contents to OSF SHARE repository, fields should include:
- selected descriptive metadata (title, creator and etc)
- adminset, Fedora resource URI
- Fileset URI where binaries located (for creating Bags)

**Comment by vantuyls** [comment]
@zhang4952 @wickr what is the status of this issue?

**Comment by zhang4952** [comment]
This is irrelevant now because SA@OSU support OAI, although it could be an useful feature probably for MS3.

**Comment by wickr** [comment]
I disagree that this is irrelevant, as not all descriptive metadata is exposed by OAI. URIs are not included. And if this is for preservation at all, it should include system and technical metadata (admin sets, etc.). Moving this to MS3

**Comment by vantuyls** [comment]
@zhang4952 @wickr status update on this issue, please?

**Comment by zhang4952** [comment]
This function is an improvement to Hyrax out of box. I think we can include it for the discussion of the next sprint.

**Comment by zhang4952** [comment]
related to #1726

**Comment by mellinma** [comment]
@zhang4952  Can this ticket be closed because the MA ingest happened?

**Comment by zhang4952** [comment]
We do not need OAI-PMH for MA export anymore, it is in BagIT now. OSF Share has been updated with new url after migration to Hyrax: https://share.osf.io/discover?sources[]=ScholarsArchive%40OSU.

**Comment by shieldsb** [comment]
Notch8 work will address - check after their work is complete.

**Comment by zhang4952** [comment]
This can be closed: we used BagIT for MA preservation and the metadata is extracted from Fedora and saved in the BagIT manifest.
