### ISSUE TITLE
Rake task update for generating proper uris

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#841]
https://github.com/osulp/Scholars-Archive/blob/master/lib/tasks/handle_dump.rake#L7

Use the `human_readable_type_tesim` value to translate from the work for use uris, export the handle

Goal: `${replaces_tesim},/concern/${translated_work_type}/${id}`

An example translated work type for `Graduate Thesis Or Dissertation` would be `gradate_thesis_or_dissertations` .. a simple approach would be to store these mappings in a simple table/configuration.

**Comment by revgum** [comment]
may not be necessary any longer with the handle redirect controller implemented in #873

**Comment by vantuyls** [comment]
@revgum can you check for sure on this one and, if not necessary, close?

**Comment by revgum** [comment]
no longer valid
