### ISSUE TITLE
Change banner image

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#844]
need a non-stock banner image for SA@OSU 

@vantuyls will find one and put it here

**Comment by vantuyls** [comment]
![library at dusk 0766 web](https://user-images.githubusercontent.com/9534576/29585848-6f102b16-873d-11e7-915f-0f1fa92cb29a.jpg)

**Comment by vantuyls** [comment]
lemme know if that needs cropped. maybe include a screenshot in a comment here.

**Comment by revgum** [comment]
given the way the image is applied with CSS, we would see the top maybe 10% of this image..so you'd want to crop it down to probably just above the sunshine IMO

**Comment by revgum** [comment]
![screen shot 2017-08-22 at 1 37 39 pm](https://user-images.githubusercontent.com/32885/29586319-21e50a6c-873f-11e7-9fb8-2167381ca41b.png)

**Comment by revgum** [comment]
![screen shot 2017-08-22 at 1 39 36 pm](https://user-images.githubusercontent.com/32885/29586391-6d33daf2-873f-11e7-8dbd-329799be308a.png)

**Comment by vantuyls** [comment]
![library at dusk_kmp6073 web](https://user-images.githubusercontent.com/9534576/29586398-751eca10-873f-11e7-9168-a2132b6836eb.jpg)

**Comment by revgum** [comment]
![screen shot 2017-08-22 at 1 41 41 pm](https://user-images.githubusercontent.com/32885/29586475-abec481a-873f-11e7-990a-afcec3dd7218.png)

**Comment by revgum** [comment]
![screen shot 2017-08-22 at 1 43 28 pm](https://user-images.githubusercontent.com/32885/29586559-eedf417c-873f-11e7-987d-5d3e67056927.png)
