### ISSUE TITLE
Handle Redirect Controller and Workflow

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#862]
- [ ] On ir.l.o.e, redirect traffic to handle traffic to SA on a handle controller
- [ ] The handle controller derives the original handle uri and searches SOLR for this url (ie. http://hdl.handle.net/1957/89921)  
  - [ ] If a work is found, redirect user to `#show` to that work
  - [ ] If a work is not found, show a stylish 404 error and notify SA administration of the problem

**Comment by wickr** [comment]
Original ticket: https://github.com/osulp/Scholars-Archive/issues/595
