### ISSUE TITLE
Fix CSS in embargo

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#868]

**Comment by straleyb** [comment]
![screen shot 2017-08-24 at 4 19 04 pm](https://user-images.githubusercontent.com/6424683/29693010-02f5a666-88e8-11e7-9da9-13647c4a789f.png)

**Comment by revgum** [comment]
Is `yyyy-mm-dd` necessary? IMO it would be nicer set as the `placeholder="yyyy-mm-dd"` on the input field html attribute.

**Comment by vantuyls** [comment]
agree with @revgum - that yyyy-mm-dd would be better suited as the help text in the box.
