### ISSUE TITLE
Add email notification when ScholarsArchive::HandleErrorLoggingService logs an error

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#881]
It would be useful to notify an administrator via `ENV['SCHOLARSARCHIVE_ADMIN_EMAIL']` when one of these errors gets logged. That way we dont have to try to keep checking in on the log files to see when these errors are being logged.

**Comment by vantuyls** [comment]
not sure we still need this. @revgum @zhang4952 can either of you see when the last time we had one of these errors on SA Hyrax?

**Comment by straleyb** [comment]
Closing. If we run into this again, we can address
