### ISSUE TITLE
[Ryan Ordway] Rewrite traffic going from ir.l.o.e to lib-saapp1.l.o.e

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#882]
After the migration is complete and we are ready to make the switchover, Ryan Ordway will have to go in and change traffic routing to ir.l.o.e to rewrite to lib-saapp1.l.o.e. This will work towards the completion of the migration from DSpace to Hyrax. All URI's should be respected.

**Comment by wickr** [comment]
This is completed.
