### ISSUE TITLE
need contextual information on showpage about parent items

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#887]
when a work has a parent work, the child work's showpage should have some contextual information pointing to that parent work. 

any recollection as to why we haven't done that?

**Comment by straleyb** [comment]
This feature is also broken in hyrax. I created a ticket, https://github.com/samvera/hyrax/issues/2960 in hyrax detailing this issue. This work would be best done in hyrax if we decide to work on it. Otherwise we can wait for it to be fixed eventually. It works in sufia but not in hyrax or nurax.

**Comment by simholt** [comment]
Nice!

![screen shot 2018-05-15 at 2 42 32 pm](https://user-images.githubusercontent.com/33705514/40085108-413d0fa0-584e-11e8-8d65-940c232c5c09.png)

![screen shot 2018-05-15 at 2 42 26 pm](https://user-images.githubusercontent.com/33705514/40085107-41246f72-584e-11e8-8cb0-9f7de396748a.png)

**Comment by vantuyls** [comment]
omg i'm hyperventilating about this.

**Comment by straleyb** [comment]
qa done and deployed to production
