### ISSUE TITLE
Allow for multiple facets on a single facet field [Advanced Search]

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#888]
currently, when faceting on a field, one can only use a single facet per metadata field. often, though, we want to use multiple facets for a single field (e.g. i want to see all of the items by Steve AND Hui).

**Comment by wickr** [comment]
https://github.com/projectblacklight/blacklight_advanced_search  provides this.

http://oregondigital.org/advanced?action=index&controller=catalog  (facets on the right have checkboxes for multiple select).

**Comment by wickr** [comment]
Starting with these as Search Fields: Title, Creator, Advisor

**Comment by vantuyls** [comment]
so, is there a reason to not enable this for all facets at this point? those that obviously don't make sense (date, because of the slider is an example) we wouldn't...
