### ISSUE TITLE
Should we expose :description in the ingest form and show page for Default metadata?

### ISSUE THREAD

**Issue by luisgreg99** [osulp/Scholars-Archive#899]
After going over the ordering of the metadata for Article, I noticed that we have `:description` (`RDF::Vocab::DC11.description`) listed in the default model, but it was not being exposed neither in the form nor the show page. 

See: https://github.com/osulp/Scholars-Archive/blob/master/app/models/concerns/scholars_archive/default_metadata.rb#L67-L69

However, I found that we have `:additional_information` (`RDF::Vocab::DC.description`) being exposed and shared a similar predicate.

See: https://github.com/osulp/Scholars-Archive/blob/master/app/models/concerns/scholars_archive/default_metadata.rb#L17-L19

After looking in dspace2hydra, it looks like we are mapping `peerreviewnotes` and `provenance` to `:additional_information` and defaulting to `:description`.

- `:additional_information`: https://github.com/osulp/dspace2hydra/blob/master/config/default.yml#L201-L212 
- `:description`: https://github.com/osulp/dspace2hydra/blob/master/config/default.yml#L170-L172.

**Comment by wickr** [comment]
Related #714 
There are definitely values in dce:description, as Greg noted above. They display at the top of the show page, right under "Citeable URL", and are not currently on the form.
