### ISSUE TITLE
create FAQ for Rights Statements and Licenses

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#903]
- [x] FAQ for Rights Statements
- [x] FAQ for CC 4.0 Licenses
- [x] identify rightstatements and licenses that may be confusing/irrelevant

**Comment by vantuyls** [comment]
@boockm any estimate as to when this will be ready?

**Comment by boockm** [comment]
Latest version: https://docs.google.com/document/d/15u9v-NcK2dDMiriTDon-MfVk3b_PuLbGneJiPsi9SVo/edit. 

See what you think. I admit that I am not comfortable requiring authors to assign Rights Statements, especially if/when the author has already applied a CC license.

**Comment by vantuyls** [comment]
can you say more about why your not comfortable requiring rightsstatement?

**Comment by boockm** [comment]
I'm okay with it if we choose to reduce the options. If an author chooses a CC license and then is presented with Rights options that don't correlate is where I have an issue. I think the field is mostly useful for staff making rights determinations for objects that are being digitized.

**Comment by simholt** [comment]
Worked with Mike to rejigger the FAQ, posted to the SA User Guide, all good.
