### ISSUE TITLE
Notification upon upload should be more helpful

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#910]
currently, when one uploads content to the repository, the message:

"Your files are being processed by ScholarsArchive@OSU in the background. The metadata and access controls you specified..."

Better text would read:

"ScholarsArchive@OSU has received your upload. Your file is currently being processed. Thank you for your deposit."

**Comment by simholt** [comment]
@straleyb Hmmm.

![screen shot 2018-04-20 at 12 58 37 pm](https://user-images.githubusercontent.com/33705514/39071127-c07204c8-449a-11e8-80a5-2c216d28427b.png)

**Comment by simholt** [comment]
Excellent.

![screen shot 2018-04-23 at 10 38 21 am](https://user-images.githubusercontent.com/33705514/39143343-893cbc38-46e2-11e8-88a5-8df347a78222.png)
