### ISSUE TITLE
Automatic Embargo Lifting

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#93]
Embargos set by administrators should be automatically removed on a given end-date.

**Comment by terrellt** [comment]
We should talk to the Hydra community about current implementations.

**Comment by terrellt** [comment]
@vantuyls There's ongoing discussion with the rights metadata group on recommendations for predicates and practices regarding Embargos. Do we want to wait for that work?

Asking the hydra-tech list about current implementations would still be good though. @luisramg do you want to handle that?

**Comment by terrellt** [comment]
Bah, waffle doesn't autocorrect usernames - @luisgreg99

**Comment by luisgreg99** [comment]
@terrell sure I can take a look

**Comment by vantuyls** [comment]
do you have a link to the conversation? any idea about the timeline for that work?

**Comment by terrellt** [comment]
@vantuyls https://wiki.duraspace.org/display/hydra/Rights+Subgroup+2015-06-03 Notes from the last call.

**Comment by terrellt** [comment]
One Sufia implementation with embargos: https://github.com/ualbertalib/HydraNorth/commit/49d109962a3ca6ac532254ccdf1b2df369dd6c93

**Comment by vantuyls** [comment]
Embargos should apply to metadata and file
