### ISSUE TITLE
ERROR fetch_cached_graph not found in triplestore

### ISSUE THREAD

**Issue by luisgreg99** [osulp/Scholars-Archive#938]
From error logs:
```
2017-09-26T17:42:57.439Z 2198 TID-ow8r7tpd0 ResolrizeJob JID-30b2eeaf6e01b03e6b9c8dd2 INFO: start
[INFO] fetch_cached_graph(http://opaquenamespace.org/ns/osuAcademicUnits/ikL2Q5ZX) not found in triplestore cache (http://127.0.0.1:8080/blazegraph/namespace/staging/sparql)
ERROR [line 1] Expected subject (found: "Not a valid (absolute) URI: Computer Science")
Computer Science failed to fetch from triplestore with error: Expected subject (found: "Not a valid (absolute) URI: Computer Science")
Oregon State University failed to fetch from triplestore with error: Statement #<RDF::Statement:0x3fe068880b34(nil nil nil .)> is incomplete
```
It looks liks it's coming from old content in `academic_affiliation`

**Comment by revgum** [comment]
lets extend the rake task to handle these, i'll query the json from solr

**Comment by luisgreg99** [comment]
I looked more into this issue, and found that labels that were being fetched for `academic_affiliation` were being completed successfully, but the labels for `degree_fields` were not (this particular issue is described in this ticket: https://github.com/osulp/Scholars-Archive/issues/929). The fix for this issue is addressed here: https://github.com/osulp/Scholars-Archive/pull/939
