### ISSUE TITLE
Create the Bags export script for Hyrax/Fedora

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#963]
Write a script:
1. find all the items by adminset in Solr index
2. for each item, search Fedora and get its UID
3. export Fedora UID in Bag using the fedora-import-export util

**Comment by zhang4952** [comment]
Done

**Comment by zhang4952** [comment]
The Bags export script should be converted into a rake, test, and merged into SA. I will try to get it done by Dec.7

**Comment by zhang4952** [comment]
1. Create a list of works to export with Solr query: by dspace_collection and model
2. Export Bags of works (including children works) given the list

Sample ETD: https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/mk61rn60q?locale=en

**Comment by zhang4952** [comment]
Solr query for work ids of ETDs:
`select?fl=id&indent=on&q=dspace_collection_tesim:"Electronic%20Theses%20and%20Dissertations"&rows=30000&wt=json`

**Comment by zhang4952** [comment]
The export script will:
1. read the list of work ids
2. get work object
  work = ActivwFedora::Base.find('work_id')
3. find whether the work is a parent or child
  if work.member_ids.nil? && work.has_model == "FileSet" 
    call step 4 
  else
    foreach work.member_ids |m|
       traverse until m is a FileSet #a parent work will have three levels: parent, child, and FileSet while a child work has two levels of child, FileSet
    end
  end  
4. call fedora-import-export to export Bags for FileSet
  system ("command") #`java -jar fcrepo-import-export-0.1.0.jar --mode export --resource http://localhost:8080/fcrepo/rest/prod/6m/31/1v/09/6m311v09q --dir exports/4 --binaries --bag-profile default --bag-config metadata.yml`

**Comment by wickr** [comment]
At some point, which has probably passed, we will not be able to keep using `dspace_collection_tesim:` as a query parameter for all items, and need to query AdminSets or similar for groups of items.

**Comment by vantuyls** [comment]
@zhang4952 what is the status of this issue?

**Comment by zhang4952** [comment]
I will close this issue but have to create a new issue.
The Bag export script is ready and has been used to generate ETD BAGs. However, a recent test with MetaArchive revealed that it requires 'flat' Bags like this one: http://metaarchive-staging.lib.calpoly.edu/bd-ms190_bag001_split/bd-ms190_bag001_1/. The current Bag script uses fedora-import-export.jar and produces a Bag with 'deep' hierarchy without meaningful bag-info and manifest that MA crawler needs.
