### ISSUE TITLE
Create script(?) to pull EESC publications into the EESC admin set

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#965]
EESC publications were migrated to technical reports mistakenly. We'll want to put these back into the EESC admin set/work type.

**Comment by zhang4952** [comment]
- [ ] create a list of work ids of EESC collections from dspace_collection

- [ ] get fileset ids of the works

- [ ] set admin_set_id to 'j9602060k' for works and filesets

**Comment by zhang4952** [comment]
Done, 8214 works assigned to EESC Publication
