### ISSUE TITLE
Article request button

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#979]
More publishers require that articles in IRs be embargoed for 12-36 months. A "request this article from the author" button would circumvent this, enabling immediate access to content. https://wiki.duraspace.org/display/DSPACE/RequestCopy

**Comment by vantuyls** [comment]
since we have a local policy about publisher embargoes and functionality in Hyrax 2.1 makes private content undiscoverable, the concept of an article request button is moot. Let's take this up again if we see an uptick in requests for embargoed content. cc: @simholt
