### ISSUE TITLE
allow non admin users to only see currrent degree fields (last 5 years)

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#984]

**Comment by luisgreg99** [comment]
@vantuyls @wickr I tested out this feature/filter locally and I can confirm that the form is already listing current degree fields (last five years) in the form, so it's working as expected. I think we can close this ticket unless we want a feature for admin users to impersonate a student (non admin) and be able to see the filtered list. Is this what you are looking for @vantuyls ?
 
For now, the only way for admin users to see this list is by removing themselves from the `users` list in the admin role (becoming a non-admin temporarily) via the console as follows:
 ```
admin_role = Role.find_by_name('admin')
admin_users = admin_role.users.to_a
admin_role.users = admin_users.delete_if { |u| u = User.find_by_email("useremail-here@oregonstate.edu") }
```
And to become an admin again:
```
admin_role = Role.find_by_name('admin')
admin_role.users << User.find_by_email("useremail-here@oregonstate.edu")
```
