### ISSUE TITLE
Background jobs failing generating PDF derivatives

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#989]
We think these things work together imagemagick_ver: ‘7.0.7’, openjpg_ver: ‘2.1.0’, libtiff_ver: ‘4.0.5’, libpng_ver: ‘1.6.28’, gs_ver: ‘9.19’

Mark Bussey suggests that we install and build these versions on the server, they've spent a lot of time to try and identify the best combination of packages.

**Comment by vantuyls** [comment]
@revgum any idea if this issue is resolved?

**Comment by vantuyls** [comment]
ping @revgum

**Comment by revgum** [comment]
I believe these issues were more related to the PDF's that were being migrated versus current PDF's being ingested. I've tested this a number of times and haven't had problems with the derivative generation for PDFs. We're using ImageMagick 6.7.2, gs 8.70, libpng 1.2.49, libtiff 3.9.4.
